package com.sosinvitalii.database.truthOrDare

/// Правда или действие на английском языке языке
object EnglishTruthOrDare {
    fun fetch(type: Type): List<String> {
        return if (type == Type.TRUTH) {
            truth
        } else {
            dare
        }
    }

    private val truth = listOf(
        "What's the funniest or weirdest habit you have?",
        "What's the biggest fear you have and why?",
        "What's the funniest or most embarrassing adventure you've ever had?",
        "What's the stupidest thing you've ever done?",
        "What secret piece of hardware have you always did you want to try or correct yourself?",
        "What is the strangest dream you've ever had? Tell me about him.",
        "What's the biggest lie you've ever told? Why did you do it?",
        "What is the most awkward situation that happened to you because of your romantic interest?",
        "What is the funniest nickname or nickname ever given to you?",
        "What is the strangest object you have ever found in your bag or pocket?",
        "What is the funniest or strangest event that happened to you in public?",
        "What is the funniest or strangest phobia you have?",
        "What is the most awkward situation that happened to you during a date?",
        "What is the stupidest quarrel or misunderstanding you had with someone from friends or relatives?",
        "What is the strangest or unusual gift you have ever received and from whom?",
        "What is the funniest or strangest did you have a delusion as a child?",
        "What is the strangest or most eccentric tradition your family has?",
        "What is the most awkward moment you've ever experienced at work or at school?",
        "What is the wildest or most dangerous experiment you've ever conducted?",
        "What is the most ridiculous or funny costume you've ever worn on Halloween or to a theme party?",
        "What's the most embarrassing or weird thing you've ever done to attract attention to yourself?",
        "What's the biggest lie you've ever heard from your friend?",
        "What's the most ridiculous or ridiculous fear you have about which are you having a hard time telling?",
        "What's the stupidest or funniest rhyme you've ever composed?",
        "What's the most embarrassing or funny situation that happened to you during a sports event or workout?",
        "What's the strangest or most unusual eating habit you have?",
        "What's the stupidest or funniest message you've ever sent by mistake?",
        "What is the most embarrassing or funny mistake during public speaking or speaking in front of the class?",
        "What is the strangest or unusual thing you've ever found in your bed?",
        "What is the most ridiculous or funny gift you've ever given someone?",
        "What's the most ridiculous or funny thing that happened to you on the beach or in the pool?",
        "What's the stupidest or funniest nickname you've ever had or one of your friends?",
        "What's the strangest or most unusual phobia you have?",
        "What's the most embarrassing or did a funny situation happen to you because of your favorite singer/actor/athlete?",
        "What is the most ridiculous or funny joke you've ever done with friends or family?",
        "What is the strangest or most unusual place where you've ever fallen asleep or fallen asleep?",
        "What is the most awkward or did a funny situation happen to you on a date?",
        "What is the stupidest or funniest myth or fairy tale you ever believed as a child?",
        "What is the strangest or most unusual phrase you've ever heard in a dream?",
        "What is the most ridiculous or funny frame you've ever shot in a photo or video?",
        "What is the most Is your best friend's tradition weird or eccentric?",
        "What's the most embarrassing or funny compliment you've ever heard?",
        "What's the stupidest or funniest childhood story you've ever heard about yourself?",
        "What's the most awkward or funny situation that happened to you at a wedding or other celebration?",
        "What's the stupidest or funniest belief you've ever heard from someone?",
        "What's the most embarrassing or funny adventure you've had on a trip?",
        "What's the strangest or most unusual habit your brother or sister has?",
        "What's the most ridiculous or funny way you've tried fall asleep?",
        "What is the stupidest or funniest childhood story of your friend?",
        "What is the most awkward or funny situation that happened to you at a dance or music event?",
        "What is the strangest or most unusual tradition of your neighbors or family friends?",
        "What's the funniest or stupidest nickname you've ever had or any of your friends?",
        "What's the most awkward or funny situation that happened to you because of an awkward acquaintance or performance?",
        "What's the stupidest or funniest behavior you had while sleeping?",
        "What is the most ridiculous or funny moment you had while taking a photo or video?",
        "What is the strangest or unusual food combination that you have ever tried and it actually turned out to be delicious?",
        "What's the most embarrassing or funny moment you've ever experienced at work or at school?",
        "What's the stupidest or funniest name you've ever had for a group on social media or in a game?",
        "What's the most ridiculous or funny costume you've ever worn to a carnival or on masquerade?",
        "What is the strangest or funniest noticeable place on your body you have?",
        "What is the most awkward or funny situation that happened to you because of a misunderstanding or translation of a word or phrase?",
        "What is the strangest or unusual phrase that you have ever heard from your home an animal?",
        "What is the stupidest or funniest childhood story of your brother or sister?",
        "What is the most ridiculous or funny object you have ever found in your bag or backpack?",
        "What is the strangest or unusual phobia of one of your friends?",
        "What is the most awkward or funny the situation happened to you at a party or club?",
        "What is the stupidest or funniest statement you have ever heard from someone?",
        "What is the most embarrassing or funny adventure you had on public transport?",
        "What is the strangest or unusual tradition of your parents or grandparents?",
        "What's the most awkward or funny moment you've ever experienced while flirting or dating someone?",
        "What's the stupidest or funniest myth or legend you've ever heard?",
        "What's the most awkward or funny situation that happened to you in class or at a lecture?",
        "What's the strangest or most unusual thing you've ever had in your pocket or bag?",
        "What's the stupidest or funniest behavior you've had in public that no one knows about?",
        "What's the most embarrassing or funny situation that happened to you because of an awkward or inappropriate comment?",
        "What is the strangest or most unusual object you have ever found on the street or in the park?",
        "What is the stupidest or funniest sign or belief you have?",
        "What is the most awkward or funny situation that happened to you at a wedding or on another holiday?",
        "What is the stupidest or funniest have you ever sent a message by mistake in a group chat or social networks?",
        "What is the strangest or most unusual habit of one of your relatives?",
        "What is the most ridiculous or funny moment you had during sports or physical education?",
        "What's the stupidest or funniest nickname you've ever had or one of your neighbors?",
        "What's the most embarrassing or funny situation happened to you because of an awkward or incorrect greeting?",
        "What's the stupidest or funniest behavior you've had at a holiday or public event?",
        "What's the stupidest or funniest place you've ever slept in?",
        "What's the most awkward or funny situation that happened to you at a wedding ceremony or other formal event?",
        "What's the strangest or most unusual acquaintance you had with someone?",
        "What is the stupidest or funniest story from your sibling's childhood?",
        "What is the most ridiculous or funny comment you've ever heard from your pet?",
        "What is the strangest or most unusual thing you've ever found on the street or in the park?",
        "What is the most awkward or funny situation that happened to you because of an awkward or inappropriate joke?",
        "What was the stupidest or funniest behavior you had on stage or in front of an audience?",
        "What was the most awkward or funny situation that happened to you at a graduation party or other special event?",
        "What is the stupidest or funniest statement you have ever heard from your teacher or teacher?",
        "What is the most awkward or funny situation that happened to you because of an awkward or incorrect use of a word or phrase?",
        "What is the strangest or most unusual object you have ever found on a walk or trip?",
        "What is the stupidest or funniest sign or belief of one of your friends?",
        "What is the most awkward or funny situation that happened to you because of an awkward or inappropriate message in social networks or messenger?",
        "What's the stupidest or funniest behavior you've had at a public event or festival?",
        "What's the strangest or most unusual habit one of your neighbors has?",
        "What's the most awkward or funny moment you've had at a family meeting or parent-teacher meeting at school?",
        "What's the stupidest or a funny story from your best friend's childhood?",
        "What is the most awkward or funny acquaintance you had with someone from famous people?",
        "What is the strangest or unusual thing you have ever found on the beach or in the pool?",
        "What is the most embarrassing or funny situation that happened to you because of a misunderstanding or translation in a foreign language?",
        "What was the stupidest or funniest behavior you had during a culinary experiment or cooking?",
        "What is the most embarrassing or funny situation that happened to you at a Christmas party or New Year's holiday?",
        "What is the stupidest or funniest statement you've ever heard from your brother or sister?",
        "What is the most awkward or funny situation that happened to you because of an awkward or inappropriate dance?",
        "What's the strangest or most unusual item you've ever found in your refrigerator or kitchen?",
        "What's the stupidest or funniest sign or belief your grandparents have?",
        "What's the most awkward or funny situation that happened to you during a photo shoot or video recording?",
        "What's the stupidest or funniest did you have funny behavior while visiting a museum or art gallery?",
        "What is the most awkward or funny situation that happened to you at a birthday party or a friend's holiday?",
        "What is the strangest or most unusual habit of your teacher or teacher?",
        "What is the most awkward or funny moment you had during an excursion or a trip?",
        "What is the stupidest or funniest childhood story of your neighbor or friend?",
        "What is the most awkward or funny situation that happened to you during karaoke or a music contest?",
        "What is the stupidest or funniest have you ever heard a statement from your colleague or classmate?",
        "What is the most awkward or funny acquaintance you had with someone on the street or in a public place?",
        "What is the strangest or most unusual tradition of your friends from another country?",
        "What is the stupidest or funniest childhood story of your parent or relative?",
        "What is the most awkward or funny situation that happened to you on a date or in a restaurant?",
        "What is the stupidest or funniest behavior you had at a corporate party or business event?",
        "What is the most awkward or funny did a funny situation happen to you at a festival or concert?",
        "What is the strangest or most unusual habit of one of your friends on the Internet?",
        "What was the most awkward or funny moment you had during a picnic or outdoors?",
        "What is the most awkward or funny situation that happened to you while walking or traveling in nature?",
        "What is the strangest or unusual habit of one of your colleagues or classmates?",
        "What is the most awkward or funny situation that happened to you while visiting an amusement park or entertainment center?",
        "What is the most awkward or funny situation that happened to you at a wedding or other celebration?",
        "What is the most awkward or funny situation that happened to you at a sports event or training?",
        "What is the strangest or most unusual habit of one of your neighbors or family friends?",
        "What is the most ridiculous or funny moment you had at work or at school?",
        "What is the strangest or most unusual thing you have ever found in your refrigerator or kitchen?",
        "What is the most awkward or funny situation that happened to you at a Christmas party or on a New Year's holiday?",
        "what is the strangest or most unusual tradition of your friends from another country?",
        "What is the most awkward or funny situation that happened to you while walking or traveling in nature?",
        "What is the strangest or most unusual habit of your neighbor or family friend?",
        "What is the most awkward or funny situation that happened to you at a birthday party or at a friend's party?",
        "What is the most awkward or funny situation that happened to you at a wedding or other holiday?",
        "What is the most awkward or funny situation that happened to you at a Christmas party or New Year's holiday?",
        "When was the last time you cried with laughter, and what caused it?",
        "What is the funniest meme or video you've ever seen on the Internet?",
        "What is the most embarrassing or funny situation that happened to you while traveling abroad?",
        "What is the funniest noise or sound you've ever heard and couldn't stop laughing?",
        "What is the most awkward or funny moment you had while communicating with a pet?",
        "What is the strangest or unusual animal you would like to have as a pet?",
        "What is the most awkward or did a funny situation happen to you at a public performance or in front of the camera?",
        "What is the stupidest or funniest dream you've ever had and can you describe it?",
        "What is the strangest or most unusual hobby or hobby you had or one of your friends?",
        "What is the most awkward or funny situation that happened to you at a public event where you found yourself in an uncomfortable outfit?",
        "What is the strangest or most unusual thing that you have ever seen at a fair or bazaar?",
        "What is the most awkward or funny moment you had during sports or physical education?",
        "What's the funniest or weirdest chance encounter you've had with a stranger?",
        "What's the stupidest or funniest misconception you've ever had as a child?",
        "What's the most embarrassing or funny situation that happened to you while using technology or electronics?",
        "What's the funniest or most ridiculous moment you've had on a date or while flirting?",
        "What's the strangest or most unusual dish you've ever tasted and what was your reaction to it?",
        "What's the funniest or most unexpected thing you've ever had in the rain?",
        "What is the most awkward or funny situation that happened to you because of an awkward or inappropriate gift?",
        "What is the strangest or unusual item you have ever found in your bag or pocket?",
        "What is the most funny or ridiculous situation that happened to you in class or during a lecture?",
        "What's the stupidest or funniest statement you've ever heard from your parent or grandparents?",
        "What's the most awkward or funny situation that happened to you because of an awkward or unsuccessful flirtation?",
        "What's the strangest or most unusual thing you've ever had in your backyard or in yard?",
        "What is the stupidest or funniest childhood story of your boyfriend or girlfriend?",
        "What is the most awkward or funny situation that happened to you on a morning jog or exercise?",
        "What is the funniest or most ridiculous moment you had while taking a photo or video?",
        "What's the stupidest or funniest statement you've ever heard from your neighbor or classmate?",
        "What's the most awkward or funny situation that happened to you because of an awkward or inappropriate comment?",
        "What's the funniest or most ridiculous thing you've ever had happen at a wedding or other special event?",
        "What was the most awkward or funny situation that happened to you at a party or at a club?",
        "What was the funniest or most ridiculous moment you had while visiting an amusement park or entertainment center?",
        "What is the funniest or most ridiculous situation that happened to you while shopping or shopping?",
        "What is the strangest or most unusual nickname you have ever had or one of your friends?",
        "What is the most awkward or funny situation that happened to you at work or at school because of ridiculous or funny incident?",
        "What is the funniest or most ridiculous moment you had while visiting a museum or art gallery?",
        "What is the strangest or most unusual habit of one of your neighbors or colleagues?",
        "What's the funniest or most ridiculous thing you've ever had while traveling on public transport?",
        "What's the most embarrassing or funny situation that happened to you at a graduation party or other special event?",
        "What's the funniest or most ridiculous moment you had while using social media?",
        "what is the strangest or most unusual phobia you or any of your friends have?",
        "What is the funniest or most ridiculous moment you had while visiting an amusement park or amusement park?",
        "What is the most awkward or funny situation that happened to you on the beach or on a holiday?",
        "What is the strangest or most unusual hobby or hobby you had or one of your friends?",
        "What is the most funny or ridiculous situation that happened to you at a photo shoot or when shooting a video?",
        "What was the stupidest or funniest remark you had in a movie or at a theater performance?",
        "What was the most awkward or funny situation that happened to you during a romantic date?",
        "What is the strangest or most unusual thing that ever happened to you while visiting a park or garden?",
        "What was the funniest or most ridiculous moment you had at a holiday or at a family gathering?",
        "What was the most awkward or funny situation that happened to you at a wedding ceremony or at another formal event?",
        "What was the most awkward or funny situation that happened to you at a graduation party or at another solemn event?",
        "What is the funniest or most ridiculous situation that happened to you at a wedding or other solemn event?",
        "What is the funniest or most ridiculous moment you had during sports or physical education?",
        "What is the most awkward or funny situation that happened to you at a public performance or in front of the camera?",
        "What is the strangest or unusual thing that ever happened to you on a morning jog or exercise?",
        "What is the most awkward or funny situation that happened to you because of an awkward or inappropriate gift?",
        "What's the funniest or most ridiculous thing you've ever had at a Christmas party or a New Year's holiday?",
        "What's the funniest or most ridiculous moment you've had on a date or in a restaurant?",
        "What is the stupidest or funniest sign or belief of someone you know?",
        "What is the most awkward or funny situation that happened to you during a trip on public transport?",
        "What is the funniest or most ridiculous situation that happened to you at a birthday party or a friend's holiday?",
        "What was the funniest or most ridiculous moment you had while using technology or electronics?",
        "What was the most awkward or funny situation that happened to you at a wedding or other festive event?",
        "What is the funniest or most ridiculous situation that happened to you at a festival or concert?",
        "What was the most awkward moment you had on a date or during a flirtation?",
        "What is the funniest or strangest situation that happened to you at a public event or party?",
        "What is the funniest or most ridiculous moment you had were you at a family lunch or dinner?",
        "What is the most awkward or funny situation that happened to you at a sports competition or training?",
        "What is the stupidest or funniest phrase you've ever said to an exciting situation?",
        "What's the funniest or most ridiculous moment you've had while using social networks or instant messengers?",
        "What's the strangest or most unusual thing you've ever found in your car or bus?",
        "What's the most ridiculous or funny moment you've had on a date or while flirting?",
        "What is the funniest or most ridiculous situation that happened to you on the beach or on vacation?",
        "What is the funniest or most ridiculous moment you had during a family gathering or meeting?",
        "What is the stupidest or funniest childhood story of your relative or brother/sister?",
        "What is the most awkward or funny situation that happened to you in physical education or sports?",
        "What is the strangest or unusual habit of your friend or girlfriend?",
        "What is the most ridiculous or funny moment you had while visiting a museum or art gallery?",
        "What is the most funny or ridiculous situation did it happen to you at a social event or party?",
        "What is the stupidest or funniest phrase you have ever uttered in front of a large audience?",
        "What is the funniest or most ridiculous moment you had at work or at school?",
        "What is the strangest or most unusual habit of your neighbor or colleague?",
        "What is the most embarrassing or funny situation that happened to you at a public speech or in front of the camera?",
        "What is the strangest or most unusual thing that ever happened to you at a Christmas party or New Year's holiday?",
        "What is the most did an awkward or funny situation happen to you on a public transport trip?",
        "What is the strangest or most unusual thing that has ever happened to you at a wedding or other holiday?",
        "What is the most ridiculous or funny moment you had while using social media?",
        "What is the stupidest or funniest phrase you have ever heard from your teacher or teacher?",
        "What is the strangest or most unusual dream you had as a child?",
        "What is the funniest or most ridiculous dream have you ever seen?",
        "What is the strangest or most unusual adventure you would like to experience?",
        "What is the most awkward or funny situation that happened to you because of a ridiculous or incorrect understanding of something?",
        "What is the funniest or strangest incident you experienced on the street or in a public place?",
        "What is the most awkward or funny situation that happened to you at a holiday or at a family gathering?",
        "What is the strangest or most unusual thing that ever happened to you while traveling?",
        "What is the most ridiculous or funny moment you had at a photo shoot or when shooting a video?",
        "What is the most funny or ridiculous situation happened to you at work or at school because of a ridiculous or funny incident?",
        "What is the most embarrassing situation you've ever been in when someone confused you with someone else?",
        "What is the strangest thing you've ever seen in someone else's house?",
        "What is the funniest or most unusual reason for canceling or postponing an event that you were going to go to?",
        "What is the strangest or most unusual name you've ever seen at a restaurant or cafe?",
        "What is the most awkward or funny moment you've seen on the street or in a public place?",
        "What is the most did a stupid or funny situation happen to you when you were trying to learn a new skill or hobby?",
        "What is the strangest or most unusual tradition you have ever seen in another country or culture?",
        "What is the most ridiculous or funny situation that happened to you in a store or supermarket?",
        "What is the strangest or most unusual creature you have seen in nature or in a zoo?",
        "What is the funniest or most ridiculous advertisement or advertisement you have ever seen?",
        "What is the most embarrassing situation that happened to you on public transport?",
        "What is the strangest or most unusual object you have ever seen on the street?",
        "What is the funniest or most ridiculous situation that happened to you while watching a movie or TV series?",
        "What is the strangest or most unusual hobby have you ever noticed with your friends?",
        "What is the stupidest or funniest sign or belief have you heard from someone?",
        "What is the most awkward or funny situation that happened to you during a trip to a restaurant or cafe?",
        "What is the strangest or most unusual thing you have ever found on the beach or at sea?",
        "What is the funniest or most ridiculous moment you had at a wedding or other special event?",
        "What is the stupidest or funniest story from your childhood that you heard from your sibling?",
        "What is the most awkward or funny situation that happened to you at a photo shoot or when shooting a video?",
        "What's the most embarrassing or funny thing that happened to you because of the truth in the past?",
        "What's the scariest truth you've ever heard from someone?",
        "What's the funniest secret you've ever hidden from friends or family?",
        "What's the most unpleasant truth about you was told to someone else, and how did you cope with it?",
        "What is the biggest confession or secret you would be willing to reveal in the game 'Truth or Action'?",
        "What truth have you always wanted to find out from someone, but could not find the courage to ask this question?",
        "What was the most embarrassing truth ever revealed in the game 'Truth or Action' and how did it affect the relationship in the group?",
        "What was the biggest lie told in the game 'Truth or Action' and what were the consequences?",
        "What was the bravest truth you ever expressed in the game 'Truth or Action' and how did it affect the relationship in the group?",
        "What is the most secret information you ever learned from someone in the game 'Truth or Action', and how did you use this information?",
        "What truth or secret information revealed in the game 'Truth or Action' caused you the strongest emotional reaction?",
        "What was the most difficult truth you had to tell in the game 'Truth or Action' and how did you cope with it?",
        "What was the most embarrassing task 'Action' you had to perform in the game?",
        "What is the most audacious or provocative truth you've ever heard from someone in the game 'Truth or Action'?",
        "What truth have you always wanted to hear from a certain person, but never asked this question?",
        "What truth would you like to learn about yourself from other players in the game 'Truth or Action'?",
        "What is the most daring or extreme challenge 'Action' you had to perform in the game?",
        "What is the most interesting or unusual question 'Truth' have you asked other players in the game?",
        "What truth or action causes you the most anxiety or anxiety before the game?",
        "What was the most memorable moment you had in the game 'Truth or Action'?",
        "What truth would you like to hear from someone in the game, but you are afraid that they will hide it?",
        "What is the funniest or strangest truth you heard about yourself the last time you played Truth or Action?",
        "What action were you always ready to perform in the game, but never got the opportunity?",
        "What truth about yourself did you tell the last time you played 'Truth or action', and why?",
        "Which truth that you told in the game turned out to be the most surprising or unexpected for other players?",
        "Which truth do you consider the most difficult for yourself to tell in the game 'Truth or Action'?",
        "Which is the most funny or strange was the 'Action' task given to you in the game?",
        "What truth about yourself would you never tell in the game, even if you had to?",
        "What truth about yourself were you ready to tell in the game, but never got the chance?",
        "What truth would you like to hear from someone in the game to better understand him or her?",
        "What truth about your personal life were you ready to tell in the game, but eventually changed your mind?",
        "What action were you ready to perform in the game 'Truth or Action', but then got scared or considered it too risky?",
        "What truth would you like to hear from your best friend or best friend in the game 'Truth or Action'?",
        "What truth about your romantic feelings would you like to hear from someone with whom you play 'Truth or Action'?",
        "What truth about your secret hobbies or interests were you ready to tell in the game?",
        "What is the most shocking or unpleasant truth was revealed about you in the game 'Truth or action'?",
        "What action do you consider the most daring or extreme that was performed by someone else in the game?",
        "What truth about yourself would you like to hear from your parents in the game 'Truth or Action'?",
        "What is the most intimate or personal truth you were ready to tell your partner or partner in the game?",
        "What truth about your friends or loved ones would you like to hear from them in the game 'Truth or Action', but are afraid to ask?",
        "What truth about yourself were you ready to tell in the game, but did you change your mind at the last moment because of fears or fear?",
        "What truth about your past actions or mistakes would you like to hear from someone in the game?",
        "What action would you like someone to perform in the game to prove their loyalty or courage?",
        "What truth about your secret desires or dreams were you ready to tell in the game?",
        "What truth about your real identity would you like to hear from other players in the game 'Truth or Action'?",
        "What is the funniest or strangest task 'Action' have you ever given other players in the game?",
        "What truth about yourself do you think is the most amazing or unusual, and are you ready to tell it in the game?",
        "What truth about your fears or phobias were you ready to tell in the game?",
        "What truth about your family relationships or dynamics with relatives would you like to hear from other players in the game?",
        "What truth about your previous relationships or romantic relationships would you like to hear from someone in the game 'Truth or Action'?",
        "What truth about your secret skills or talents would you like to reveal in the game 'Truth or Action'?",
        "What truth about your material desires or ambitions were you ready to tell in the game?",
        "What action would you like someone to do in the game to show their love or friendship?",
        "What truth about your funniest or embarrassing moments in life were you ready to tell in the game?",
        "What truth about your inner struggles or emotional problems would you like to hear from other players in the game?",
        "What is the most provocative or embarrassing truth you have ever heard from someone in the game 'Truth or Action'?",
        "What truth about your moral or ethical beliefs would you like to hear from other players in the game?",
        "What truth about your big risks or adventures were you ready to tell in the game?",
        "What truth about your past friendships or relationship breakups would you like to hear from other players in the game?",
        "What truth about your most unusual or strange habits were you ready to tell in the game 'Truth or Action'?",
        "What truth about your most vague or mysterious moments in life were you ready to reveal in the game 'Truth or Action'?",
        "What truth about your strongest or weakest sides would you like to hear from other players in the game?",
        "What truth about your wildest or unusual fantasies were you ready to tell in the game?",
        "What action would you like to do in the game to show your generosity or compassion?",
        "What truth about your most vague or mysterious dreams were you ready to reveal in the game?",
        "What truth about your funniest or strangest habits were you ready to tell in the game?",
        "What truth about your deepest or secret fears were you ready to tell in the game?",
        "What truth were you ready to tell about your most embarrassing or embarrassing romantic moments in the game?",
        "What truth about your most exciting or touching moments in life were you ready to reveal in the game?",
        "What truth about your strangest or most eccentric desires were you ready to tell in the game 'Truth or Action'?",
        "What truth about your most vague or mysterious meetings with strangers were you ready to tell in the game 'Truth or Action'?",
        "What truth about your most unforgettable or memorable were you ready to reveal your travels in the game?",
        "What truth about your most dramatic or emotional experiences were you ready to tell in the game?",
        "What action would you like someone to do in the game to show their courage or determination?",
        "What truth about your most unusual or strange dreams were you ready to tell in the game?",
        "What truth about your most poignant or inspiring moments in life were you ready to reveal in
                "What truth about your funniest or unusual dog pranks were you ready to tell in the game?",
        "What truth about your most disturbing or frightening nightmares were you ready to tell in the game?",
        "What truth about your most mysterious or incomprehensible thoughts were you ready to reveal in the game?",
        "What truth about your most original or extravagant fashion experiments were you ready to tell in the game 'Truth or Action'?",
        "What truth about your funniest or funniest situations at work were you ready tell in the game 'Truth or action'?",
        "What truth about your most awkward or funny moments in communication with the opposite sex were you ready to reveal in the game?",
        "What truth about your most strange or unusual daily rituals were you ready to tell in the game?",
        "Which action would you consider the most romantic or mysterious that was performed by someone else in the game 'Truth or Action'?",
        "What truth about your most vague or mysterious hobbies were you ready to reveal in the game?",
        "What truth about your most ridiculous or funny role-playing games were you are you ready to tell in the game?",
        "What truth about your funniest or strangest eating habits were you ready to reveal in the game?",
        "What truth about your most awkward or funny attempts to sing or dance were you ready to tell in the game?",
        "What truth about your most vague or mysterious cases of losing or finding things were you ready to reveal in the game?",
        "What truth about your most unusual or strange situations at public events were you ready to tell in the game?",
        "What is the most awkward moment in the game 'Truth or Action' have you ever experienced?",
        "What is the funniest truth you heard from another player during the game?",
        "What is the strangest challenge 'Action' did you do it in the game?",
        "Tell me about the most unpleasant truth that you had to say in the game 'Truth or Action'.",
        "What is the most secret information you revealed about yourself in the game 'Truth or Action'?",
        "What is the boldest question 'Truth' did you ask another player and what was his answer?",
        "What truth did you always want to hear from a certain player in the game, but he never said?",
        "Tell me about the most extreme 'Action' challenge that you saw in the game.",
        "What is the most provocative truth you heard from another player and how did it affect the atmosphere of the game?",
        "What truth about yourself did you tell in the game that caused surprise or shock to other players?",
        "What is the most personal and emotional truth you told in the game 'Truth or Action' and how did it affect you?",
        "What is the most embarrassing truth you had to hear about yourself from other players in the game?",
        "What is the challenge of 'Action' did you refuse to perform in the game and why?",
        "What is the funniest or funniest truth about yourself you heard from another player in the game?",
        "What truth about your secret fears or phobias were you ready to tell in the game?",
        "What truth about your hidden talents or skills did you reveal in the game 'Truth or action'?",
        "What is the most embarrassing or strange truth about yourself that you told in a game that surprised other players?",
        "What is the most challenging or daring challenge 'Action' have you seen or performed in the game?",
        "What truth about your family relationships or dynamics were you ready to reveal in the game 'Truth or Action'?",
        "What truth about your most unusual or strange habits did you tell in the game and how it was perceived by other players?",
        "What is the most terrible did you hear the truth about yourself in the game 'Truth or Action' and how did you cope with it?",
        "What is the funniest or funniest task 'Action' was given to you in the game?",
        "What truth about your romantic feelings were you ready to tell in the game?",
        "What is the most unpleasant truth about yourself you told in the game that caused discontent or irritation among other players?",
        "What is the most bold or risky question 'Truth' did you ask another player and what was his answer?",
        "What truth about your secret desires or dreams did you reveal in the game?",
        "What truth about your past mistakes or awkward situations were you ready to tell in the game?",
        "What is the funniest or strangest truth about yourself revealed in the game 'Truth or Action' and how did it affect the mood of the game?",
        "What truth about your previous relationships or romantic relationships would you like to hear from other players in the game?",
        "What truth about your strangest or eccentric habits were you ready to tell in the game?",
        "tell me about the most awkward moment associated with your answer to the question 'Truth' in the game 'Truth or Action'.",
        "What is the funniest truth you heard from another player when he answered the question 'Truth'?",
        "What is the strangest action you had to perform in the game 'Truth or Action' and how did it affect you?",
        "What is the most secret information about yourself that you revealed when answering the question 'Truth' in the game?",
        "What truth about another player have you always wanted to hear, but never asked this question?",
        "Tell us about the most extreme 'Action' challenge that you have seen or performed in the game.",
        "What truth about your previous romantic relationships would you like to hear from other players in the game?",
        "What was the most personal and emotional truth you told in the game 'Truth or Action' and how did it affect you and other players?",
        "What was the most embarrassing truth you had to hear about yourself from other players in the game and how did you cope with it?",
        "What action did you refuse to perform in the game 'Truth or Action' and why?",
        "Tell us about the funniest or funniest truth that you heard about yourself from other players in the game.",
        "What truth about your secret fears or phobias were you ready to tell in the game Truth or Action' and how did it affect the atmosphere of the game?",
        "What truth about your hidden talents or skills did you reveal in the game 'Truth or Action' and how did it affect other players?",
        "What is the most embarrassing or strange truth about yourself did you tell in the game that caused surprise or shock to other players?",
        "What is the most challenging or bold challenge 'Action' have you seen or performed in the game and how did it affect the atmosphere of the game?",
        "What truth about your family relationships or dynamics were you ready to reveal in the game 'Truth or Action' and how did it affect other players?",
        "What truth about your most unusual or strange habits did you tell in the game and how did it affect the atmosphere of the game?",
        "Tell us about the funniest case when you experienced awkwardness or embarrassment.",
        "Perform your best imitation of an animal.",
        "Tell me about the strangest dream you've ever seen.",
        "Show your dancing skills without music.",
        "Tell me about your worst date or romantic experience.",
        "Call a random person from your contact list and sing 'Happy Birthday' or 'Happy New Year'.",
        "Tell me about the strangest thing you've ever hidden under the bed or in the closet.",
        "Come up with and perform a rap song about any player in the room.",
        "Show your juggling skills with any objects that are in the room.",
        "Tell me about the strangest case when you were caught off guard.",
        "Call your best friend or friend and ask what they think of you without telling your name.",
        "Show your funniest face and ask other players to take a picture of it.",
        "Tell me about your strangest fear or phobias.",
        "Call the restaurant and order pizza with the strangest and most ridiculous additives.",
        "Tell us about the most embarrassing case when you stumbled or fell.",
        "Come up and perform an original dance for 30 seconds.",
        "Tell us about your funniest or funniest journey.",
        "Call your parents and tell them you won a million dollars, but it's a joke.",
        "Tell them about the strangest or most unusual gift you've ever received.",
        "Make up another player with your eyes closed.",
        "Tell them about the most embarrassing or funny case when you I was caught doing something forbidden.",
        "Try to eat a lemon whole without facial expression.",
        "Tell me about the strangest or most unusual place where you ever fell asleep or woke up.",
        "Invent and perform a short poetic song about the person to your right.",
        "Try to repeat by heart the maximum number of numbers of the number 'Pi'.",
        "Come up with and perform a mini-sketch in which you play all the players in the room.",
        "Tell us about the strangest or funniest chance encounter that has ever happened to you.",
        "Try to make a wheel on your hands or feet and hold it as long as possible.",
        "Tell us about the most embarrassing situation associated with sending a message or letter by mistake to the wrong person.",
        "Come up with and perform a funny monologue on the topic 'How to conquer the world'.",
        "Tell me about the strangest or funniest phrase you've ever heard from a random passerby.",
        "Show your skills of imitating a celebrity or a famous character.",
        "Tell us about the most unusual or eccentric hobby that you are fond of.",
        "Call a random number and try to persuade the interlocutor to talk about your favorite pets.",
        "Tell us about the funniest or strangest comic situation in which you find yourself.",
        "Come up with and perform a funny monologue about your favorite food supplement.",
        "Tell us about the most embarrassing or funny case when you were 'caught in the act' at school or at work.",
        "Try to play a mini-scene in which you play yourself and other players play your relatives.",
        "Tell us about the strangest or funniest phobia that you have ever heard from another person.",
        "Come up with and perform a funny song about your favorite food or drink.",
        "Tell us about the funniest or strangest story related to a misinterpretation or incorrect pronunciation of a word or phrase.",
        "Try to repeat a famous magic trick and surprise other players with your illusionistic skills.",
        "Tell us about the most awkward or funny case when you got confused during a public speech or presentation.",
        "Come up with and perform a comedic monologue about how you cope with everyday life problems.",
        "Tell us about the most a strange or funny adventure that you experienced while traveling.",
        "Come up with and perform a funny dance to the song that is playing now.",
        "Tell us about the most awkward or funny situation related to the use of new technologies or gadgets.",
        "Try to play the role of a popular character from a movie or literature and continue the dialogue with other players.",
        "Tell us about the strangest or funniest case when you got into an awkward situation because of your misunderstanding or interpretations.",
        "Come up with and perform a funny scenario for an improvisational performance about life on another planet.",
        "Tell us about the funniest or funniest story related to your pet or pet.",
        "Try to play a mini-scene in which you are a superhero with your unique superpower.",
        "Tell us about the most embarrassing or funny case when you made a misunderstanding or interpretation of a famous proverb or saying.",
        "Come up and perform a funny dance to any song that other players choose.",
        "Tell us about the strangest or funniest case when you got into a funny situation because of your misunderstanding or misinterpretation of cultural differences.",
        "Come up with and perform a comic scene in which you play a musical performer who is experiencing technical problems on stage.",
        "Tell us about the most embarrassing or funny case when you experienced an epic failure in performing a simple task or skill.",
        "Try to play the role of a famous historical or literary character and answer the questions of others players, using their style and manner of speech.",
        "Tell us about the strangest or funniest situation when you accidentally found yourself in the wrong place or among the wrong company.",
        "Come up with and perform a funny improvisation in which you play the role of a scientist trying to explain the simplest things in a complex language.",
        "Tell us about the funniest or funniest story related to your childhood ideas about the world or scientific misconceptions.",
        "Try to play the role of a famous comedian or comedic character and read a joke or anecdote for other players.",
        "Tell us about the most embarrassing or funny case when you made an inappropriate remark or joke in an inappropriate situation.",
        "Come up and perform a funny song about your favorite fruit or vegetable.",
        "Tell us about the strangest or funniest case when you got lost or got into a funny situation in an unfamiliar place.",
        "Come up and perform a mini-performance based on a randomly selected phrase or sentence.",
        "Tell us about the most awkward or a funny case when you tried to impress someone and it suddenly didn't work.",
        "Try to play the role of a news anchor and conduct a fictional report about an event that just happened in the room.",
        "Tell us about the strangest or funniest situation when you got into a serious discussion about a frivolous topic.",
        "Come up with and perform a funny monologue about your favorite toy from childhood.",
        "Tell us about the funniest or funniest story related to your attempts to cook something delicious or experiment with food.",
        "Try to play a mini-scene in which you are a jumping kangaroo.",
        "Tell us about the most awkward or funny case when you got into a funny situation because of your lack of sleep or sleepy adventures.",
        "Come up with and perform a funny dance on the theme of 'Life in the Wild West'.",
        "Tell us about the strangest or funniest mistake you made when using technology or electronics.",
        "Come up with and perform a comic scene in which you play an awkward superhero with ridiculous abilities.",
        "Tell us about the most embarrassing or funny case when you forgot something obvious or made an obvious ",
        "Try to play the role of a famous fantastic character and read your favorite quote or phrase of this character.",
        "Tell us about the strangest or funniest situation when you got into an awkward or unusual situation in public.",
        "Come up with and perform a funny monologue about how you are trying to solve the riddle of the universe.",
        "Tell us about the funniest or funniest story related to your attempts to master a new hobby or hobby.",
        "Try to play a mini-scene in which you are a policeman stopping funny crimes.",
        "Tell us about the most embarrassing or funny case when you tried to do something epic and turned out to be a funny failure.",
        "Come up with and perform a funny dance to any children's song.",
        "Tell us about the strangest or funniest situation when you accidentally witnessed the strange or ridiculous behavior of other people.",
        "Invent and perform a comic scene in which you play a forgetful professor.",
        "Tell us about the most awkward or funny case when you tried to use slang or jargon and did it awkwardly or incorrectly.",
        "Try to play the role of a famous fairy-tale character and imagine yourself at a fairy-tale ball.",
        "Tell us about the strangest or funniest situation when you were caught doing something awkward or strange.",
        "Come up with and perform a funny monologue about how you are trying to learn a new language or dialect.",
        "Tell us about the funniest or funniest story related to your attempts to do something creative or artistic.",
        "Try to play a mini-scene in which you are a superhero with an unusual and ridiculous superpower.",
        "Tell us about the most awkward or funny case when you got confused in an ordinary and simple task or situation.",
        "Come up with and perform a funny dance to any rock song.",
        "Tell us about the strangest or funniest mistake you made when using social networks or the Internet.",
        "Come up with and perform a comic scene in which you play the role of a clumsy superhero saving the world from banal problems.",
        "Tell us about the most awkward or funny case when you tried to impress someone and it turned out funny or unexpected.",
        "Try to play the role of a famous writer and read your fictional short story or poem.",
        "Tell us about the strangest or funniest situation when you accidentally found yourself in the wrong place or met the wrong person.",
        "Come up with and perform a funny monologue about how you are trying to learn a new skill or skill",
        "Tell us about the funniest or funniest story related to your attempts to learn to play a musical instrument.",
        "Try to play a mini-scene in which you are a funny and awkward tourist traveling to an unfamiliar country.",
        "Tell us about the most embarrassing or funny case when you experienced forgetfulness or confusion during an important event or meeting.",
        "Come up and perform a funny dance to any song from a cartoon or a children's movie.",
        "Tell us about the strangest or funniest situation when you got into a funny or ridiculous misunderstanding due to a misunderstanding of language or cultural differences.",
        "Come up and perform a comic scene in which you play a role the hero of a fantastic saga who faces absurd problems.",
        "Tell us about the most awkward or funny case when you made an unexpected and ridiculous gesture or movement.",
        "Try to play the role of a famous historical or literary character and ask other players a riddle or puzzle.",
        "Tell us about the strangest or funniest situation when you got into a funny or awkward situation at work or at school.",
        "Come up with and perform a funny monologue about how you are trying to learn a new sports skill or exercise.",
        "Tell us about the funniest or funniest story related to your attempts to use a new technology or device.",

    )

    private val dare = listOf(
        "Tell the funniest story you know.",
        "Play a song on an imaginary guitar.",
        "Ask a random passerby for an autograph.",
        "Call your best friend and sing 'Happy Birthday' to him.",
        "Show your funniest dance.",
        "Call a random number and ask for pizza.",
        "Call someone from the contact list on your phone and sing him the song 'Happy Birthday'.",
        "Get a piercing with a button on your shirt.",
        "Play the role of a popular cartoon a character.",
        "Close your eyes and let others draw something on you with a marker.",
        "Dance in the center of the room to the music.",
        "Tell a joke that will make everyone laugh.",
        "Show your best imitation of an animal.",
        "Play a theatrical scene with another player.",
        "Call the pizzeria and ask which pizza is the most popular.",
        "Show your best magic trick.",
        "Knock on the next door and introduce yourself as a vacuum cleaner salesman.",
        "Find something in the refrigerator and eat it without using your hands.",
        "Play the role of your favorite superhero.",
        "Call your parents and ask them where they met for the first time.",
        "Turn your T-shirt inside out and wear it for 10 minutes.",
        "Take a selfie with the strangest facial expression.",
        "Call the local store and ask if they sell penguins.",
        "Show your best magic illusion.",
        "Play the role of a zombie and try to scare other players.",
        "Call your ex-partner and tell him that you still love him/her.",
        "Dance in the rain (use a bucket of water).",
        "Do gymnastics outside in front of the window.",
        "Call a random number and ask where you can buy a flying forging.",
        "Call someone from your contact list and ask him/her to go on a date.",
        "Show your best accent and try to speak another language.",
        "Play the role of a mad scientist.",
        "Call a restaurant and ask if they have a menu for unicorns.",
        "Find someone on the street who looks like you and take a picture together.",
        "Play the role of a popular celebrity.",
        "Call your boss and tell him that you won the lottery and quit.",
        "Assemble a pyramid of plastic cups on the floor and then break it by falling on top of it.",
        "Show your weirdest dance move.",
        "Call a local store and ask if they sell dinosaurs.",
        "Turn your socks inside out and wear them for 10 minutes.",
        "Take a selfie where you make a stupid grimace and send it to your best friend.",
        "Show your best karate kick.",
        "Play the role of a wild animal.",
        "Call a random number and ask for coffee.",
        "Call someone from your contact list and ask him/her to show your funniest dance.",
        "Come up with a new dance and show it to everyone.",
        "Tell the scariest story you know.",
        "Show your best imitation of a celebrity.",
        "Play a theatrical skit using funny voices.",
        "Call a local store and ask if they sell rainbows in cans.",
        "Call a random number and ask where the end of the rainbow is.",
        "Show your most passionate hobby.",
        "Play the role of a fantastic creature.",
        "Call your teacher and tell him that you want to go back to school.",
        "Dance on one leg for 1 minute.",
        "Take a photo with a stranger who will make a strange facial expression.",
        "Call the store and ask if they sell temporary tattoos for old people.",
        "Show your best magic illusion using items from the room.",
        "Play the role of a mad professor.",
        "Call your boss and tell him that you forgot your passphrase.",
        "Try to fold your tongue in the most difficult way.",
        "Make the highest possible loud sound with your mouth.",
        "Call the local zoo and ask if they have vultures.",
        "Call a random number and ask them to bring you ice cream.",
        "Call someone from your contact list and ask him/her to make a cuckoo sound.",
        "Put your best magic trick using objects from the room.",
        "Call your boss and tell him you want to take a year off.",
        "Assemble a pyramid of plastic bottles on the floor and then break it by falling on top of it.",
        "Show your strangest animal sound.",
        "Play the role of an evil wizard.",
        "Call a local store and ask if they sell temporary tattoos for children.",
        "Flip Take your T-shirt and wear it inside out for 10 minutes.",
        "Take a selfie where you make the strangest facial expression and send it to your ex-partner.",
        "Show your best karate kick without using your hands.",
        "Play the role of a funny clown.",
        "Call a random number and ask where you can buy a magic wand.",
        "Call someone from your contact list and ask him/her to sing you the song 'Happy Birthday'.",
        "Play the role of your favorite cartoon character.",
        "Show your best imitation of a celebrity using only gestures.",
        "Call a local store and ask if they sell invisible glasses.",
        "Call a random number and ask where you can find the end of the rainbow.",
        "Show your weirdest hobby using items from the room.",
        "Play the role of a robot and try to imitate their movements.",
        "Call your boss and tell him that you want to take an extra month off.",
        "Dance on the street to music and ask random passers-by to join.",
        "Take a photo with a stranger who will make a funny facial expression.",
        "Call the store and ask if they sell invisible dragons.",
        "Call a random number and ask them to bring you a pie.",
        "Call someone from your contact list and ask him/her to show your best magic trick.",
        "Put your best imitation of an animal using only sounds.",
        "Call your boss and tell him that you want to take unpaid leave for six months.",
        "Assemble a pyramid of books on the floor and then break it by falling on top of it.",
        "Show your strangest stretching.",
        "Play the role of a mad scientist using only gestures.",
        "Call a local store and ask if they sell temporary tattoos for the elderly.",
        "Call a random number and ask where you can buy a magic carpet.",
        "Show your best imitation of a celebrity using only sounds.",
        "Play the role of a mad professor using only gestures.",
        "Call your boss and tell him that you forgot your prepaid bill.",
        "Try to make the longest and loudest 'Meow' or 'Woof' without using a microphone.",
        "Tell the funniest story of your life.",
        "Show your best vocal performance, perform a song of your choice.",
        "Call a random number and ask for advice on a haircut.",
        "Try to draw a portrait of another player without lifting the pencil from the paper.",
        "Call the store and ask where you can buy a unicorn.",
        "Play the role of a famous politician or leader.",
        "Call a random number and ask for the song 'Birthday' in the reverse language.",
        "Call someone from your contact list and ask what secret talents he/she has.",
        "Tell the most terrible story that happened to you personally.",
        "Dance to your favorite song and ask the other players to join.",
        "Call the restaurant and ask if they have a menu for dinosaurs.",
        "Find someone on the street who will agree to do a dance battle with you.",
        "Play the role of a famous athlete and demonstrate your skills.",
        "Call your nearest neighbor and ask if you can borrow a cup of sugar from him/her.",
        "Put your best imitation of the sound of thunder.",
        "Call a local store and ask if they sell aliens.",
        "Call a random number and ask them to bring you a bouquet of flowers.",
        "Call someone from your contact list and ask him/her to tell the funniest dream they've ever had.",
        "Tell me a story about the strangest journey you've been on/participated in.",
        "Dance in the image of your favorite cartoon character and ask the other players to guess who it is.",
        "Play the role of a famous movie hero and imagine a scene from the movie.",
        "Call a random number and ask for pizza with an unusual combination of ingredients.",
        "Tell the scariest story you've heard /heard.",
        "Put on your best imitation of the beast sound.",
        "Call a local store and ask if they sell magic wands.",
        "Call a random number and ask them to bring you a bouquet of sweets.",
        "Call your nearest neighbor and ask him to wrestle in a coat.",
        "Play the role of a famous artist and draw a portrait of another player.",
        "Put your best imitation of the sound of a car engine.",
        "Call the store and ask if they sell anti-gravity boots.",
        "Find someone on the street who will agree to become your model for a photo shoot.",
        "Play the role of a famous singer and perform your version of a popular song.",
        "Call your boss and tell him what you want to take day off.",
        "Tell the funniest story that you have heard/ heard from the lips of your parents.",
        "Dance in the image of your favorite superhero and ask the other players to guess who it is.",
        "Call a random number and ask them to deliver you a pot of gold.",
        "Call someone from your contact list and ask him/her what they really think about you.",
        "Tell the strangest story from your school life.",
        "Try to draw a portrait of another player with your eyes closed.",
        "Call a local store and ask if they sell a flying carpet carpet.",
        "Call your nearest neighbor and ask him to lend you a superhero costume.",
        "Play the role of a famous athlete and demonstrate your skills in physical exercises.",
        "Put on your best imitation of the sound of a police car siren.",
        "Call the store and ask if they sell amulets against evil spirits.",
        "Call a random number and ask them to bring you a book with the author's signature.",
        "Call someone from your contact list and ask him/her what is the strangest dish he/she has ever had tried/tried.",
        "Tell the scariest story you've heard/heard from your friends.",
        "Put on your best imitation of the sound of loud music.",
        "Call the local store and ask if they sell magic hats.",
        "Find someone on the street who will agree to do an acrobatic trick with you.",
        "Play the role of a famous actor and repeat his/her famous line.",
        "Call your boss and tell him that you want to take time off to go to the moon.",
        "Tell the funniest story you've heard from your grandparents.",
        "Dance in the image of your favorite singer and ask the other players to guess who it is.",
        "Call a random number and ask to deliver you a pot of candy.",
        "Call someone from your contact list and ask him/her what fairy tale he/she told/told before going to bed as a child.",
        "Tell the strangest story from your student life.",
        "Try to draw a portrait of another player using only the nose.",
        "Call a random number and ask for a rap song 'Happy Birthday'.",
        "Call a local store and ask if they sell temporary tattoos for robots.",
        "Call your nearest neighbor and ask to go to heaven together, look for signs of life in extraterrestrial galaxies.",
        "Play the role of a famous cosmonaut and tell us about your fictional flight to the moon.",
        "Put your best imitation of the sound of car brakes.",
        "Call the store and ask if they sell invisible paints.",
        "Call a random number and ask them to bring you the crown of the king/queen.",
        "Call someone from your contact list and ask him/her what is the strangest place he/she has ever visited.",
        "Tell the scariest story you have heard/heard about paranormal phenomena.",
        "Put on your best imitation of the sound of a meteorite falling.",
        "Call a local store and ask if they sell magic wands for cats.",
        "Find someone on the street who will agree to do a dance with you on the street.",
        "Play the role of a famous writer and tell us about your fictional book.",
        "Call your boss and tell him that you want to take time off to explore the Atlantic Ocean on a submarine.",
        "Tell the funniest story you've heard/heard from your relatives.",
        "Dance in the image of your favorite musical instrument and ask the other players to guess what kind of instrument it is177. Call a random number and ask them to play the tune 'Twinkle Twinkle Little Star' on the piano.",
        "Call your local store and ask if they sell floor mats for dancing on the ceiling.",
        "Call your nearest neighbor and ask him to help you create a secret secret operations agency.",
        "Play the role of a famous explorer and tell us about your imaginary journey into the jungle.",
        "Put on your best imitation of the sound of a spaceship.",
        "Call the store and ask if they sell books with the ability to predict the future.",
        "Call a random number and ask them to bring you a surprise pie.",
        "Call someone from your contact list and ask him/her which country he/she would visit if he/she could fly.",
        "Tell the scariest story you've heard/heard about ghosts.",
        "Put your best imitation of the sound of fireworks.",
        "Call a local store and ask if they sell magic writing pens.",
        "Find someone on the street who will agree to make a friendly jumping photo with you.",
        "Play the role of a famous cook and offer your fictional recipe for exotic dishes.",
        "Call your boss and tell him that you want to take time off to explore the underwater world among dolphins.",
        "Tell the funniest story that you have heard/heard from your teachers.",
        "Dance in the image of your favorite musical genre and ask the other players to guess what genre it is.",
        "Call a random number and ask them to sing 'Pinocchio' in opera style.",
        "Call the local store and ask if they sell invisible socks.",
        "Call your nearest neighbor and ask to look at the clouds together, look for the shapes of different animals.",
        "Play the role of a famous director and tell us about your imaginary movie that you want to make.",
        "Put on your best imitation of the sound of a roaring lion.",
        "Call the store and ask if they sell magic bars that make invisible.",
        "Call a random number and ask them to bring you helium balloons.",
        "Call someone from your contact list and ask him/her what superpower he/she possessed/possessed if he/she could choose.",
        "Tell the strangest story about adventures with wild animals that you have heard/heard.",
        "Try to draw a portrait of another player using only teeth.",
        "Call a random number and ask them to sing the song 'Favorite City' in French.",
        "Call a local store and ask if they sell real dragons.",
        "Call your nearest neighbor and ask him to take part in a competition to build the tallest tower of maps.",
        "Play the role of a famous archaeologist and tell about your fictional discovery of an ancient artifact.",
        "Put on your best imitation of the sound of a steam locomotive.",
        "Call your boss and tell him that you want to take a day off to go in search of the lost city.",
        "Tell the funniest story you've heard/heard about animals.",
        "Dance in the image of your favorite musical instrument and ask the other players to guess what kind of instrument it is.",
        "Call a random number and ask them to sing the song 'Volare' in Italian.",
        "Call local shop and ask if they sell magic wands for unicorns.",
        "Call your nearest neighbor and ask him to help you organize a secret party.",
        "Play the role of a famous journalist and conduct an interview with another player.",
        "Put your best imitation of the sound of a stone falling into the water.",
        "Call the store and ask if they sell space helmets for cats.",
        "Call a random number and ask them to bring you a heart-shaped balloon.",
        "Call someone from your contact list and ask him/her which book he/she considers the most inspiring.",
        "Tell the scariest story you've heard/heard about the lost cities.",
        "Put on your best imitation of the sound of a bird with an unusual voice.",
        "Call a local store and ask if they sell magic board games.",
        "Find someone on the street who will agree to take a selfie with you in the image of a celebrity.",
        "Play the role of a famous astronaut and tell about your imaginary flight to Mars.",
        "Put your best imitation of the sound of a meteorite rain.",
        "Call your boss and tell him that you want to take a day off to explore the depths of the ocean on an underwater motorcycle.",
        "Tell the funniest story you've heard/heard about school adventures.",
        "Call a random number and ask them to sing the song 'Despacito' in Spanish.",
        "Tell your strangest phobia.",
        "Open your phone and call a random number.",
        "Eat a spoonful of mustard.",
        "Pretend to be an animal and play a scene from their life.",
        "Take a selfie with a stranger on the street.",
        "Call your ex-boyfriend or girlfriend and ask why they broke up with you.",
        "Show your funniest dance performance.",
        "Show your funniest photo on social networks.",
        "Eat a piece of lemon without violence.",
        "Call your mom and ask if she found you on the doorstep of her house when you were a child.",
        "Subscribe to a random person on Instagram and send them a welcome message.",
        "Hold your nose and try to say your name.",
        "Show how you jump on one leg around the room.",
        "Take a picture of yourself making a grimace and make it your avatar in chats for a week.",
        "Put the song on speakerphone and sing it out loud.",
        "Call a random person in the phone book and congratulate him on his Birthday.",
        "Show your funniest body movement.",
        "Record a video in which you play the role of your favorite cartoon character.",
        "Put the eyeball on your forehead and try to eat it without using your hands.",
        "Call the restaurant and ask why your pizza delivery is taking so long to arrive.",
        "Tell us the funniest dream you've ever had.",
        "Eat a teaspoon of salt without drinking water.",
        "Call a friend and tell him that you just saw his ex with another guy.",
        "Play the role of a popular character from the movie.",
        "Tell a friend to come and join you in the game.",
        "Try to lick your elbow.",
        "Call the taxi service and ask them to take you to the next city.",
        "Show us your funniest reaction to fright.",
        "Tell us about your strangest sexual experience.",
        "Try to do the splits right now.",
        "Call a relative and ask how old they are.",
        "Show us your funniest face.",
        "Eat a slice of onion without wrinkling your face.",
        "Call the nearest pizzeria and ask for a pizza recipe.",
        "Tell me the strangest habit you have.",
        "Come up with a new word and give it a definition.",
        "Show us your craziest jumping move.",
        "Pour a spoonful of ketchup into your palm and lick it.",
        "Call a random number and ask if it is possible to visit them for the night.",
        "Show us your funniest yoga pose.",
        "Show us your funniest animal incarnation.",
        "Take a selfie with a neighbor.",
        "Eat a piece of onion without crying.",
        "Call a friend and ask what he is doing now.",
        "Show your funniest reaction to anger.",
        "Play the role of your favorite actor.",
        "Call the store and ask if they have live unicorns.",
        "Tell us the strangest dream you've ever seen.",
        "Eat a spoonful of mustard and then drink a glass of water.",
        "Call the nearest pet store and ask how much a tiger costs.",
        "Show us your funniest eyebrow movement.",
        "Play a scene from your favorite movie.",
        "Show your funniest imitation of a famous person.",
        "Call a random person and ask what their Wi-Fi password is.",
        "Make a trip around the world around the room without taking your feet off the ground.",
        "Come up with a new dance and perform it in front of the whole group.",
        "Tell me the funniest case from your school life.",
        "Give someone in the group a back massage for 5 minutes.",
        "Eat a whole onion without chewing.",
        "Call the restaurant and ask them to reserve a table for you and your fictional celebrity.",
        "Show your funniest sound spectacular message.",
        "Put on your favorite song and perform a dance for the whole group.",
        "Tell the funniest story related to you and your pet.",
        "Come up with a funny word and create a new dance for him.",
        "Show us your craziest funny shoulder movement.",
        "Call a random person and ask him to tell you a joke.",
        "Show your funniest facial expressions.",
        "Call a local store and ask how much it costs to buy all their products from them.",
        "Tell us the strangest fantasy you've ever seen.",
        "Show your funniest singing.",
        "Eat a punch of mustard, ketchup, tabasco sauce and lemon.",
        "Call a random person and ask him when the last time he washed his hands.",
        "Show us your craziest tongue movement.",
        "Play a scene from your favorite cartoon.",
        "Show your funniest pretend laugh.",
        "Call the nearest zoo and ask if they have local unicorns.",
        "Come up with your own joke and tell it to the whole group.",
        "Show us your craziest belly dance move.",
        "Pour yourself a glass of water on your head without taking off your clothes.",
        "Call a friend and ask what his temperature is now.",
        "Show your funniest imitation of nature sounds.",
        "Play the role of your favorite comedian.",
        "Tell the strangest story from your family life.",
        "Show us your funniest foot movement.",
        "Call the nearest store and ask if they have flying carpets for sale.",
        "Come up with a new song and perform it in front of the whole group.",
        "Show your craziest pretense of sadness.",
        "Play the role of your favorite character from the book.",
        "Call a random person and ask him where the 'border of madness' is.",
        "Show us your funniest ear movement.",
        "Play the role of your favorite athlete.",
        "Call a local store and ask if they sell invisible colored pencils.",
        "Call your nearest neighbor and ask them to join you in creating your own secret language.",
        "Play the role of a famous magician and show your best magic trick.",
        "Tell the strangest story from your childhood.",
        "Show us your craziest pretense of fear.",
        "Call a random person and ask tell him what the weather will be tomorrow.",
        "Come up with a new acrostic from the name of one of the participants and show it to the whole group.",
        "Show your funniest finger movement.",
        "Play the role of your favorite character from the game.",
        "Call the nearest store and ask if they have magic wands for sale.",
        "Tell the funniest story related to you and your friends.",
        "Show your craziest imitation of the sounds of transport.",
        "Play a scene from your favorite play.",
        "Show your funniest pretence of surprise.",
        "Call the nearest restaurant and ask if they have magic drinks on the menu.",
        "Come up with a funny story based on the last text message you received.",
        "Show us your craziest booty move.",
        "Eat a tablespoon of salt without drinking.",
        "Call a friend and ask how much money he has left in his bank account.",
        "Show your funniest imitation of animal sounds.",
        "Tell the strangest fairy tale you've ever heard.",
        "Show your funniest lip movement.",
        "Call the nearest store and ask if they have starships for sale.",
        "Come up with a new dance production and show it to the whole group.",
        "Show your craziest pretence of sadness.",
        "Call a random person and ask him when was the last time he laughed to tears.",
        "Show us your funniest finger movement.",
        "Play a scene from your favorite comedy show.",
        "Show your craziest pretence of surprise.",
        "Call the nearest zoo and ask if they have exotic animals like dragons.",
        "Tell the funniest joke you've ever heard.",
        "Show your the funniest imitation of weather sounds.",
        "Eat a tablespoon of sugar without drinking.",
        "Call a friend and ask if he has a supply of magic dust.",
        "Show your craziest movement with your eyes.",
        "Play the role of your favorite writer.",
        "Show your funniest pretence of fear.",
        "Call the nearest pizzeria and ask if they have a pizza with magic ingredients.",
        "Come up with a funny story based on the last movie you watched.",
        "Show us your craziest shoulder movement.",
        "Play the role of your favorite musical artist.",
        "Call a random person and ask him what his plans for the evening are today.",
        "Show your funniest pretence of joy.",
        "Play a scene from your favorite detective series.",
        "Show your craziest nose movement.",
        "Call the nearest store and ask if they have magic books for sale.",
        "Tell me the strangest story you've heard from your parents or grandparents.",
        "Show your funniest pretense of surprise.",
        "Call a random person and ask him how he spends his day off.",
        "Come up with a new dance and invite all the participants of the game to join you.",
        "Show your craziest throat movement.",
        "Play the role of your favorite villain from the movie.",
        "Call the nearest zoo and ask if they have magical animals.",
        "Tell the funniest joke that you came up with yourself.",
        "Show your funniest imitation of sounds transport.",
        "Play a scene from your favorite comedy play.",
        "Show your craziest pretence of fear.",
        "Call the nearest store and ask if they have magic pencils for sale.",
        "Come up with a funny story based on the last dream you saw.",
        "Show us your craziest heel movement.",
        "Eat a tablespoon of sour cream without drinking water.",
        "Call a friend and ask what his mood is today.",
        "Show your funniest pretense of sadness.",
        "Play the role of your favorite fantasy character.",
        "Show your funniest eyebrow movement.",
        "Call the nearest store and ask if they have magic mirrors for sale.",
        "Tell the funniest story related to your pets.",
        "Show your craziest imitation of the sounds of nature.",
        "Play the role of your favorite movie hero.",
        "Call a random person and ask him how he imagines the perfect day.",
        "Show us your funniest hip movement.",
        "Play a scene from your favorite musical.",
        "Show your craziest pretence of joy.",
        "Call the nearest pizzeria and ask if they have pizza with magic ingredients.",
        "Come up with a funny story based on the last adventure you experienced.",
        "Show your funniest imitation of rain sounds.",
        "Eat a tablespoon of mayonnaise without drinking water.",
        "Call a friend and ask what he wants to order for lunch.",
        "Show your craziest tongue movement.",
        "Play the role of your favorite historical character.",
        "Show your funniest pretence of fear.",
        "Call the nearest store and ask if they have magic lanterns for sale.",
        "Tell the funniest joke you've heard from your friends.",
        "Play the role of your favorite comic book character.",
        "Call a random person and ask him what he considers the most important thing in life.",
        "Play a scene from your favorite romantic comedy.",
        "Call the nearest store and ask if they have magic tents for sale.",
        "Tell the funniest story you've ever experienced while traveling.",
        "Show your craziest imitation of the sounds of the city.",
        "Play the role of your favorite character from the book.",
        "Call a random person and ask him how he would describe you in three words.",
        "Come up with a new dance and show it to the whole group.",
        "Show your craziest toe movement.",
        "Play the role of your favorite cartoon character.",
        "Call the nearest store and ask if they have magic wands for sale.",
        "Tell the funniest joke you heard at the last party.",
        "Show your funniest imitation of the sounds of nature during a thunderstorm.",
        "Play a scene from your favorite horror movie.",
        "Call the nearest store and ask if they have magic books for sale.",
        "Tell the funniest story related to your neighbors.",
        "Show your craziest imitation of rain sounds.",
        "Call a random person and ask him how he spends his weekend.",
        "Show us your funniest finger movement.",
        "Play a scene from your favorite comedy series.",
        "Call the nearest store and ask if they have magic mirrors for sale.",
        "Tell us the funniest joke you've ever heard from your teacher.",
        "Show your funniest imitation of animal sounds during the rain.",
        "Play the role of your favorite fantasy hero.",
        "Call a random person and ask him how he imagines the perfect vacation.",
        "Show us your craziest tongue movement.",
        "Play a scene from your favorite detective movie.",
        "Call the nearest store and ask if they have magic lanterns for sale.",
        "Tell the funniest story related to your school friends.",
        "Show your craziest imitation of the sounds of the city at night.",
        "Call a random person and ask him what he thinks about space aliens.",
        "Show us your funniest shoulder movement.",
        "Call the nearest store and ask if they have magic tents for sale.",
        "Tell the funniest story you've heard from your parents.",
        "Show your funniest imitation of the sounds of nature during dawn.",
        "Play the role of your favorite historical hero.",
        "Call a random person and ask him how he celebrates his birthday.",
        "Play a scene from your favorite drama movie.",
        "Call the nearest store and ask if they have magic pencils for sale.",
        "Tell the funniest story related to your neighbors.",
        "Show your craziest imitation of the sounds of nature during sunset.",
        "Play the role of your favorite movie actor.",
        "Call a random person and ask him which movie he thinks is the funniest.",
        "Play a scene from your favorite fantasy series.",
        "Tell the funniest joke you've heard from your coach.",
        "Show your funniest imitation of animal sounds during sunset.",
        "Call a random person and ask him what his plans for the weekend are.",
        "Play a scene from your favorite comedy musical.",
        "Tell the funniest story related to your childhood friends.",
        "Show your craziest imitation of the sounds of the city in the early morning.",
        "Play the role of your favorite music composer.",
        "Play a scene from your favorite documentary.",
        "Show your funniest pretence of joy.",
        "Tell the funniest story you've heard from your older brother or sister.",
        "Show your funniest imitation of the sounds of nature during the wind.",
        "Call a random person and ask him what he thinks about paranormal phenomena.",
        "Play a scene from your favorite thriller.",
        "Show us your craziest toe movement.",
        "Call a random person and ask him which movie he thinks is the most terrible.",
        "Show us your craziest imitation of the sounds of nature during dawn.",
        "Call a random person and ask him what he thinks about the existence of parallel worlds.",
        "Play a scene from your favorite fantasy book.",
        "Tell the funniest story you've heard from your trainer.",
        "Show your funniest imitation of animal sounds during dawn.",
        "Play the role of your favorite comic book hero.",
        "Call a random person and ask him which movie he thinks is the most touching.",
        "Play a scene from your favorite musical performance.",
        "Tell the funniest story you've heard from your older brother or sister.",
        "Show your funniest imitation of the sounds of nature during sunset.",
        "Call a random person and ask him what he thinks about mysterious phenomena.",
        "Tell me the funniest story you've heard from your friend.",
        "Call a random person and ask him what he thinks about ghostly phenomena.",
        "Tell the funniest story you've heard from your teacher.",
        "Call a random person and ask him what he thinks about life on other planets.",
        "Show me the funniest imitation of animal sounds during a thunderstorm.",
        "Call a random person and ask him what he thinks about supernatural phenomena.",
        "Show us your craziest finger movement.",
        "Play a scene from your favorite dramatic performance.",
        "Call a random person and ask him which movie he thinks is the most entertaining.",
        "Call a random person and ask him what he thinks about time loops.",
        "Play the role of your favorite hero from a fantasy novel.",
        "Call a random person and ask him what he thinks about the possibility of time travel.",
        "Tell the funniest story you've heard from your friend.",
        "Call a random person and ask him what he thinks about the existence of parallel universes.",
        "Call a random person and ask him what he thinks about the possibility of the existence of ghosts.",
        "Call a random person and ask him what he thinks about magical creatures.",
        "Play a scene from your favorite science fiction movie.",
        "Tell the funniest story you've heard from your parents.",
        "Transform into your favorite cartoon character and play a short scene.",
        "Call a random to a person and ask him what he thinks about the existence of ghosts.",
        "Show us your best imitation of a famous actor or actress.",
        "Show your funniest head movement.",
        "Call the nearest store and ask if they have magic hats for sale.",
        "Tell the funniest joke you've heard from your brother or sister.",
        "Show us your craziest imitation of nature sounds during the night.",
        "Call a random person and ask him which movie he thinks is the funniest.",
        "Show us your craziest belly movement.",
        "Replay a scene from your favorite romantic movie.",
        "Show your funniest pretence of anger.",
        "Tell the funniest story related to your work colleagues.",
        "Show your craziest imitation of animal sounds during the full moon.",
        "Call a random person and ask him which movie he thinks is the most romantic.",
        "Show your craziest pretense of embarrassment.",
        "Call the nearest store and ask if they have magic carpets for sale.",
        "Tell the funniest story related to your relatives.",
        "Show your funniest imitation of the sounds of nature during the full moon.",

    )
}