package com.sosinvitalii.database.congratulations

/// Поздравление с юбилеем
object AnniversariesCongratulations {
    fun fetch(language: Language): List<String> {
        return when (language) {
            Language.EN -> english
            Language.IT -> italian
            Language.RU -> russian
            Language.ES -> spanish
            Language.DE -> german
        }
    }

    private val english = listOf(
        "Congratulations on your jubilee! May this day be filled with joy, happiness, and a festive atmosphere! Wishing you good health, love, and the fulfillment of all your dreams!",
        "Happy jubilee! May every day be filled with joy, achievements, and satisfaction with life! May success accompany you in everything you do!",
        "Congratulations on this wonderful jubilee! Wishing you strong health, happiness, inspiration, and new bright experiences! May your life be filled with joy and prosperity!",
        "Happy jubilee! May this jubilee mark a new beginning filled with new opportunities and achievements! Wishing you happiness, luck, and success in all your endeavors!",
        "Congratulations on this significant jubilee! May every moment of your life be filled with joy, laughter, and well-being! May the years bring only the brightest and unforgettable moments!",
        "Happy jubilee! Wishing you that this jubilee becomes a new page in your life, filled with happiness, satisfaction, and love! May every day bring only joy and the fulfillment of dreams!",
        "Congratulations on this beautiful jubilee! Wishing you robust health, longevity, and a feeling of complete happiness! May there always be room for joy and love in your life!",
        "Happy jubilee! May this day become a new beginning filled with vibrant events, impressions, and happy moments! Wishing you success, prosperity, and the fulfillment of all your desires!",
        "Congratulations on your jubilee! Wishing you to maintain a bright life energy, joy, and optimism for many years ahead! May your entire journey be crowned with success and well-being!",
        "Congratulations on your anniversary! I wish you to maintain a bright life energy, joy, and optimism for many years to come! May your entire journey be crowned with success and well-being!",
        "Congratulations on your anniversary! This special day is a great opportunity to celebrate all your achievements and the challenges you've overcome. I wish you further success and unforgettable moments in life.",
        "Happy anniversary! May this day become a milestone in your life, reflecting all the wonderful moments, accomplishments, and happy memories.",
        "Congratulations on your anniversary! I wish you prosperity, good health, inspiration, and further joyful journeys through life.",
        "Happy anniversary! It's a special moment to look back and take pride in your path. I wish you happiness, love, and new amazing adventures.",
        "Congratulations on your anniversary! May this day mark the beginning of new opportunities, the fulfillment of cherished desires, and the continuation of your boldest dreams.",
        "Happy anniversary! I wish you wisdom, happiness, and well-being at every step of your future journey.",
        "Congratulations on your anniversary! May this day be filled with joy, laughter, and warm memories of the years lived.",
        "Happy anniversary! I wish you further success, well-being, and the fulfillment of all the desires you set for yourself.",
        "Congratulations on your anniversary! May every following day of your life be filled with happiness, smiles, and pleasant surprises.",
        "Happy anniversary! May you preserve a youthful spirit, remain active, and enjoy every moment of your life's journey.",
        "Congratulations on your anniversary! May this day become a new beginning full of opportunities and achievements.",
        "Happy anniversary! I wish you to continue leading your life with confidence, savoring each moment, and relentlessly striving for new heights.",
        "Congratulations on your anniversary! May every day of your life be filled with joy, love, and happiness. You deserve the very best!",
        "Happy anniversary! I wish you to preserve the invaluable experience and wisdom you've accumulated over all these years and enjoy each new day.",
        "Congratulations on your anniversary! May every moment of your life be filled with vibrant colors and unforgettable impressions.",
        "Happy anniversary! I wish you happy moments, well-being, and reaching new heights in your life.",
        "Congratulations on your anniversary! May every step of your future path be filled with joy, success, and gratitude for everything you have already achieved.",
        "Happy anniversary! I wish you to keep the fire in your eyes and youth in your heart, so that each day is filled with new opportunities and pleasant surprises.",
        "Congratulations on your anniversary! May every day of your life be filled with joy, smiles, and the warmth of loving hearts.",
        "Happy anniversary! I wish you to continue overcoming life's obstacles with confidence and enjoy the beautiful moments it brings.",
        "Congratulations on your anniversary! May this day be the beginning of a new chapter in your life, filled with health, joy, and the fulfillment of all your dreams.",
        "Happy anniversary! I wish you unwavering optimism, enthusiasm, and the ability to find joy in the little things that make life beautiful.",
        "Congratulations on your anniversary! May every day of your life be filled with laughter, friendly support, and harmony in your heart.",
        "Happy anniversary! I wish you to maintain the brightness of your soul, the youthfulness of your spirit, and enjoy all the blessings life can offer.",
        "Congratulations on your anniversary! May every day of your life be filled with happiness, achievements, and great victories.",
        "Happy anniversary! I wish you to keep a fresh perspective on life, genuine joy, and inspiration every day.",
        "Congratulations on your anniversary! May your path be strewn with flowers of joy, filled with melodies of happiness, and illuminated by the light of success.",
        "Happy anniversary! I wish you to maintain your life energy, brilliant mind, and the ability to see beauty all around you.",
        "Congratulations on your anniversary! May your heart be filled with love, your mind with wisdom, and your life with unforgettable adventures.",
        "Happy anniversary! I wish you to continue sharing your life wisdom, finding joy in the little things, and being a source of inspiration for others.",
        "Happy anniversary! May this day mark the beginning of a new chapter in your life when you share wisdom and tell stories that begin with the words 'When I was young...'",
        "Congratulations on your anniversary! I wish that every new day of your life is as beautiful as your memories of these days.",
        "Happy anniversary! Don't worry about getting older - you're just becoming a classic. And as you know, classics are always in style!",
        "Congratulations on your anniversary! I wish you such an active life that you look younger than your passport, and such a healthy life that your doctor is surprised every time you visit.",
        "Happy anniversary! May each new year of your age bring you not only wisdom but also superpowers to handle any life situation!",
        "Congratulations on your anniversary! I wish you as much energy as a 20-year-old and as much experience as an 80-year-old - and may they never overlap!",
        "Happy anniversary! Congratulations on reaching an age when you start looking at young people and saying, 'Oh, how adorable, but they're so young!'",
        "Congratulations on your anniversary! Now that you've reached this age, you have every right to complain about loud music and explain how everything was better in your time when you were young and downright hilarious!",
        "Happy anniversary! I wish you enough energy to wake up in the morning without coffee, enough money to buy yourself gifts, and enough friends to help you spend them!",
        "Congratulations on your anniversary! Now you have a wonderful reason to officially declare that 'life begins after 50' and start collecting discounts on everything - from movie tickets to museum visits!",
        "Happy anniversary! May your age become your secret weapon - you can show your pension card to grab attention or skip a line, and everyone will consider you worthy of respect and admiration!",
        "Congratulations on your anniversary! I wish you not to grow old, but instead, become brighter, more attractive, and funnier with each passing year - be the jubilee star of your own comedy series!",
        "Happy anniversary! Congratulations on this wonderful moment when you can say officially, 'I know what the world was like before the internet!'",
        "Congratulations on your anniversary! I wish you to have enough energy not only to cope with daytime naps but also to start your own rock band!",
        "Happy anniversary! Now that you've reached this age, you officially have the right to wear socks with sandals and have conversations with houseplants - it's your privilege!",
        "Congratulations on your anniversary! I wish you always have the keys to your home but occasionally forget why you entered a room to keep the intrigue in your life!",
        "Happy anniversary! May your jubilee cake be so big that you'll have to invite all the neighbors to help you eat it - share happiness and calories!",
        "Congratulations on your anniversary! I wish you so much enthusiasm and life optimism that you always forget what seriousness and adulthood mean!",
        "Happy anniversary! Congratulations on reaching an age where you can call yourself 'vintage' instead of 'old.' You're like a precious, aromatic vintage wine - getting better with each year!",
        "Congratulations on your anniversary! I wish you to maintain enough energy to participate in all the competitions at the summer house and win each one of them!",
        "Happy anniversary! Now you can officially stop using a bad memory as an excuse. Just say that you're going to become a celebrity and you don't need to remember ordinary things!",
        "Congratulations on your anniversary! I wish you to be so healthy that your doctor gets disappointed every time you visit and misses you when you're not there!",
        "Happy anniversary! May your jubilee be so bright and memorable that you'll remember it even through reading glasses!",
        "Congratulations on your anniversary! I wish you enough enthusiasm and courage to pursue all your dreams and enough humor to laugh at yourself when things don't go as planned!"
    )

    private val italian = listOf(
        "Congratulazioni per il tuo giubileo! Che questo giorno sia pieno di gioia, felicità e un'atmosfera festosa! Ti auguro buona salute, amore e il raggiungimento di tutti i tuoi sogni!",
        "Buon giubileo! Che ogni giorno sia pieno di gioia, successi e soddisfazione nella vita! Che il successo ti accompagni in tutto ciò che fai!",
        "Congratulazioni per questo meraviglioso giubileo! Ti auguro una salute robusta, felicità, ispirazione e nuove esperienze luminose! Che la tua vita sia piena di gioia e prosperità!",
        "Buon giubileo! Che questo giubileo segni un nuovo inizio pieno di nuove opportunità e successi! Ti auguro felicità, fortuna e successo in tutti i tuoi sforzi!",
        "Congratulazioni per questo significativo giubileo! Che ogni momento della tua vita sia pieno di gioia, risate e benessere! Che gli anni portino solo momenti più luminosi e indimenticabili!",
        "Buon giubileo! Ti auguro che questo giubileo diventi una nuova pagina nella tua vita, piena di felicità, soddisfazione e amore! Che ogni giorno porti solo gioia e il raggiungimento dei sogni!",
        "Congratulazioni per questo bellissimo giubileo! Ti auguro una robusta salute, longevità e la sensazione di completa felicità! Che ci sia sempre spazio per la gioia e l'amore nella tua vita!",
        "Buon giubileo! Che questo giorno diventi un nuovo inizio pieno di eventi vibranti, impressioni e momenti felici! Ti auguro successo, prosperità e il raggiungimento di tutti i tuoi desideri!",
        "Congratulazioni per il tuo giubileo! Ti auguro di mantenere una brillante energia vitale, gioia e ottimismo per molti anni a venire! Che tutto il tuo percorso sia coronato da successo e benessere!",
        "Congratulazioni per il tuo anniversario! Ti auguro di mantenere una brillante energia vitale, gioia e ottimismo per molti anni a venire! Che tutto il tuo cammino sia coronato dal successo e dalla prosperità!",
        "Congratulazioni per il tuo anniversario! Questo giorno speciale è un'ottima opportunità per celebrare tutti i tuoi successi e le sfide affrontate. Ti auguro ulteriori successi e momenti indimenticabili nella vita.",
        "Buon anniversario! Che questo giorno diventi una pietra miliare nella tua vita, riflettendo tutti i meravigliosi momenti, le realizzazioni e i ricordi felici.",
        "Congratulazioni per il tuo anniversario! Ti auguro prosperità, salute, ispirazione e ulteriori viaggi gioiosi nella vita.",
        "Buon anniversario! È un momento speciale in cui puoi guardare indietro e essere orgoglioso del tuo percorso. Ti auguro felicità, amore e nuove avventure straordinarie.",
        "Congratulazioni per il tuo anniversario! Che questo giorno segni l'inizio di nuove opportunità, la realizzazione dei tuoi desideri più cari e la continuazione dei tuoi sogni più audaci.",
        "Buon anniversario! Ti auguro saggezza, felicità e benessere ad ogni passo del tuo futuro cammino.",
        "Congratulazioni per il tuo anniversario! Che questo giorno sia pieno di gioia, risate e caldi ricordi degli anni trascorsi.",
        "Buon anniversario! Ti auguro ulteriori successi, benessere e il conseguimento di tutti i desideri che ti poni.",
        "Congratulazioni per il tuo anniversario! Che ogni giorno successivo della tua vita sia pieno di gioia, sorrisi e piacevoli sorprese.",
        "Buon anniversario! Ti auguro di mantenere lo spirito giovane, rimanere attivo e goderti ogni momento del tuo percorso di vita.",
        "Congratulazioni per il tuo anniversario! Che questo giorno segni un nuovo inizio, pieno di opportunità e realizzazioni.",
        "Buon anniversario! Ti auguro di continuare a condurre la tua vita con fiducia, goderti ogni istante e perseguire incansabilmente nuove vette.",
        "Congratulazioni per il tuo anniversario! Che ogni giorno della tua vita sia pieno di gioia, amore e felicità. Meriti il meglio!",
        "Buon anniversario! Ti auguro di preservare l'esperienza preziosa e la saggezza che hai accumulato in tutti questi anni e goderti ogni nuovo giorno.",
        "Congratulazioni per il tuo anniversario! Che ogni istante della tua vita sia pieno di colori vivaci e impressioni indimenticabili.",
        "Buon anniversario! Ti auguro momenti felici, benessere e il raggiungimento di nuove vette nella tua vita.",
        "Congratulazioni per il tuo anniversario! Che ogni passo del tuo futuro cammino sia pieno di gioia, successi e gratitudine per tutto ciò che hai già raggiunto.",
        "Congratulazioni per il tuo anniversario! Che ogni giorno della tua vita sia riempito di gioia, sorrisi e il calore dei cuori affettuosi.",
        "Buon anniversario! Ti auguro di continuare a superare le sfide della vita con fiducia e goderti i meravigliosi momenti che essa porta.",
        "Congratulazioni per il tuo anniversario! Che questo giorno segni l'inizio di un nuovo capitolo nella tua vita, ricco di salute, felicità e il raggiungimento di tutti i tuoi sogni.",
        "Buon anniversario! Ti auguro un ottimismo costante, entusiasmo e la capacità di gioire delle piccole cose che rendono la vita meravigliosa.",
        "Congratulazioni per il tuo anniversario! Che ogni giorno della tua vita sia riempito di risate, sostegno amichevole e armonia nel cuore.",
        "Buon anniversario! Ti auguro di preservare la vivacità dell'anima, la giovinezza dello spirito e goderti tutti i beni che la vita può offrirti.",
        "Congratulazioni per il tuo anniversario! Che ogni giorno della tua vita sia pieno di felicità, realizzazioni e grandi vittorie.",
        "Buon anniversario! Ti auguro di mantenere uno sguardo fresco sulla vita, gioia sincera e ispirazione ogni giorno.",
        "Congratulazioni per il tuo anniversario! Che il tuo cammino sia costellato di fiori di gioia, melodie di felicità e illuminato dalla luce del successo.",
        "Auguri per il tuo anniversario! Ti auguro di conservare la tua energia vitale, una mente brillante e la capacità di vedere la bellezza intorno a te.",
        "Auguri per il tuo anniversario! Che il tuo cuore sia pieno d'amore, la tua mente di saggezza e la tua vita di avventure indimenticabili.",
        "Auguri per il tuo anniversario! Ti auguro di continuare a condividere la tua saggezza di vita, gioire delle piccole gioie e essere una fonte di ispirazione per gli altri.",
        "Auguri per il tuo anniversario! Che questo giorno segni l'inizio di un nuovo capitolo della tua vita, in cui condividerai saggezza e racconterai storie che iniziano con le parole: 'Quando ero giovane...'",
        "Auguri per il tuo anniversario! Ti auguro che ogni nuovo giorno della tua vita sia bello come i ricordi di questi giorni.",
        "Auguri per il tuo anniversario! Non preoccuparti di invecchiare, stai solo diventando un classico. E come si sa, il classico è sempre di moda!",
        "Auguri per il tuo anniversario! Ti auguro una vita così attiva che sembrerai più giovane della tua età anagrafica e una vita così sana che il tuo medico si stupirà ogni volta che vai a una visita.",
        "Auguri per il tuo anniversario! Che ogni nuovo anno della tua età ti porti non solo saggezza, ma anche superpoteri per affrontare qualsiasi situazione della vita!",
        "Auguri per il tuo anniversario! Ti auguro di avere tanta energia quanto un ventenne e tanta esperienza quanto un ottantenne, e che non si incrocino mai!",
        "Auguri per il tuo anniversario! Congratulazioni per aver raggiunto un'età in cui guardi i giovani e dici: 'Oh, che cari ragazzi, ma quanto sono giovani!'",
        "Auguri per il tuo anniversario! Ora che hai raggiunto questa età, hai il diritto di lamentarti della musica alta e spiegare che tutto era migliore ai tuoi tempi, quando eri giovane e immediatamente divertente!",
        "Auguri per il tuo anniversario! Ti auguro abbastanza energia per svegliarti al mattino senza l'aiuto del caffè, abbastanza soldi per comprarti regali e abbastanza amici per aiutarti a spenderli!",
        "Auguri per il tuo anniversario! Ora hai un'ottima scusa per dichiarare ufficialmente che 'la vita inizia dopo i 50' e iniziare a ottenere sconti su tutto, dai biglietti del cinema alle visite ai musei!",
        "Auguri per il tuo anniversario! Che la tua età diventi la tua arma segreta: puoi mostrare la tua tessera di pensionato per attirare l'attenzione o saltare la fila, e tutti ti considereranno degno di rispetto e onore!",
        "Auguri per il tuo anniversario! Ti auguro di non invecchiare, ma diventare sempre più luminoso, attraente e divertente ogni anno - sii la star del tuo proprio show comico!",
        "Auguri per il tuo anniversario! Congratulazioni per questo meraviglioso momento in cuipuoi dire ufficialmente: 'So com'era il mondo senza internet!'",
        "Auguri per il tuo anniversario! Ti auguro di avere così tanta energia da non solo gestire un sonnellino pomeridiano, ma anche formare la tua band rock!",
        "Auguri per il tuo anniversario! Ora che hai raggiunto questa età, hai ufficialmente il diritto di indossare calze con i sandali e parlare con le piante di casa - è un tuo privilegio!",
        "Auguri per il tuo anniversario! Ti auguro di avere sempre le chiavi di casa, ma di dimenticare occasionalmente perché sei entrato in una stanza, per mantenere il mistero nella tua vita!",
        "Auguri per il tuo anniversario! Che la tua torta di compleanno sia così grande da dover invitare tutti i vicini per aiutarti a mangiarla - condividi la felicità e le calorie!",
        "Auguri per il tuo anniversario! Ti auguro tanto entusiasmo e ottimismo per la vita, al punto da dimenticare sempre cosa significhi essere seri e adulti!",
        "Auguri per il tuo anniversario! Congratulazioni per aver raggiunto un'età in cui puoi definirti 'vintage' anziché 'vecchio'. Sei come un pregiato vino invecchiato, migliore di anno in anno!",
        "Auguri per il tuo anniversario! Ti auguro di conservare così tanta energia da poter partecipare a tutte le gare al tuo giardino e vincerne tutte!",
        "Auguri per il tuo anniversario! Ora puoi ufficialmente rinunciare all'uso di una memoria cattiva come scusa. Basta dire che stai per diventare una celebrità e non hai bisogno di ricordare le cose comuni!",
        "Auguri per il tuo anniversario! Ti auguro di essere così sano che il tuo medico sarà deluso ogni volta che vai per una visita e sentirà la tua mancanza!",
        "Auguri per il tuo anniversario! Che il tuo anniversario sia così vivido e memorabile che lo ricorderai anche attraverso gli occhiali da lettura!",
        "Auguri per il tuo anniversario! Ti auguro tanto entusiasmo e coraggio per realizzare tutti i tuoi sogni e tanto senso dell'umorismo da ridere di te stesso quando le cose non vanno come previsto!"
    )

    private val russian = listOf(
        "Поздравляю с юбилеем! Пусть этот день будет наполнен радостью, счастьем и праздничным настроением! Желаю здоровья, любви и исполнения всех мечтаний!",
        "С юбилеем! Желаю, чтобы каждый день был наполнен радостью, достижениями и удовлетворением от жизни! Пусть успех сопутствует во всем, что вы делаете!",
        "Поздравляю с замечательным юбилеем! Желаю вам крепкого здоровья, счастья, вдохновения и новых ярких впечатлений! Пусть ваша жизнь будет полна радости и благополучия!",
        "С юбилеем! Пусть этот юбилей станет новым началом, наполненным новыми возможностями и достижениями! Желаю счастья, удачи и благополучия во всех делах!",
        "Поздравляю с знаменательным юбилеем! Желаю, чтобы каждый момент вашей жизни был наполнен радостью, смехом и благополучием! Пусть годы приносят только самые яркие и незабываемые моменты!",
        "С юбилеем! Желаю, чтобы этот юбилей стал новой страницей в вашей жизни, полной счастья, удовлетворения и любви! Пусть каждый день приносит только радость и исполнение мечтаний!",
        "Поздравляю с прекрасным юбилеем! Желаю крепкого здоровья, долголетия и ощущения полного счастья! Пусть в вашей жизни всегда будет место для радости и любви!",
        "С юбилеем! Пусть этот день станет новым началом, наполненным яркими событиями, впечатлениями и счастливыми моментами! Желаю успехов, процветания и сбывания всех желаний!",
        "Поздравляю с юбилеем! Желаю вам сохранить яркую жизненную энергию, радость и оптимизм на долгие годы вперед! Пусть весь ваш путь будет увенчан успехом и благополучием!",
        "Поздравляю с юбилеем! Этот особый день — отличная возможность отметить все достижения и пройденные испытания. Желаю вам дальнейших успехов и незабываемых моментов в жизни",
        "С юбилеем! Пусть этот день станет вехой в вашей жизни, отражая все великолепные моменты, достижения и счастливые воспоминания",
        "Поздравляю с юбилеем! Желаю вам благополучия, здоровья, вдохновения и дальнейших радостных путешествий по жизни",
        "С юбилеем! Это особый момент, когда можно оглянуться назад и гордиться своим пути. Желаю вам счастья, любви и новых удивительных приключений",
        "Поздравляю с юбилеем! Пусть этот день станет началом новых возможностей, исполнения заветных желаний и продолжения ваших самых смелых мечтаний",
        "С юбилеем! Желаю вам мудрости, счастья и благополучия на каждом шагу вашего дальнейшего пути",
        "Поздравляю с юбилеем! Пусть этот день будет наполнен радостью, смехом и теплыми воспоминаниями о прожитых годах",
        "С юбилеем! Желаю вам дальнейших успехов, благополучия и исполнения всех желаний, которые вы себе задаете",
        "Поздравляю с юбилеем! Пусть каждый следующий день вашей жизни будет наполнен радостью, улыбками и приятными сюрпризами",
        "С юбилеем! Желаю вам сохранить молодой дух, оставаться активными и наслаждаться каждым моментом вашего жизненного пути",
        "Поздравляю с юбилеем! Пусть этот день станет новым началом, полным возможностей и достижений",
        "С юбилеем! Желаю вам продолжать вести свою жизнь с уверенностью, наслаждаться каждым мгновением и неутомимо стремиться к новым вершинам",
        "Поздравляю с юбилеем! Пусть каждый день вашей жизни будет наполнен радостью, любовью и счастьем. Вы заслужили самое лучшее!",
        "С юбилеем! Желаю вам сохранять бесценный опыт и мудрость, которые накопили за все эти годы, и наслаждаться каждым новым днем",
        "Поздравляю с юбилеем! Пусть каждый мгновенье вашей жизни будет наполнено яркими красками и незабываемыми впечатлениями",
        "С юбилеем! Желаю вам счастливых мгновений, благополучия и достижения новых вершин в вашей жизни",
        "Поздравляю с юбилеем! Пусть каждый шаг вашего дальнейшего пути будет наполнен радостью, успехами и благодарностью за все, что вы уже достигли",
        "С юбилеем! Желаю вам сохранять огонь в глазах и молодость в сердце, чтобы каждый день был наполнен новыми возможностями и приятными сюрпризами",
        "Поздравляю с юбилеем! Пусть каждый день вашей жизни будет наполнен радостью, улыбками и теплом любящих сердец",
        "С юбилеем! Желаю вам продолжать преодолевать жизненные преграды с уверенностью и наслаждаться прекрасными моментами, которые она приносит",
        "Поздравляю с юбилеем! Пусть этот день будет началом новой главы в вашей жизни, наполненной здоровьем, радостью и исполнением всех мечт",
        "С юбилеем! Желаю вам неизменного оптимизма, энтузиазма и способности радоваться мелочам, которые делают жизнь прекрасной",
        "Поздравляю с юбилеем! Пусть каждый день вашей жизни будет наполнен смехом, дружеской поддержкой и гармонией в сердце",
        "С юбилеем! Желаю вам сохранять яркость души, молодость духа и наслаждаться всеми благами, которые жизнь может предложить",
        "Поздравляю с юбилеем! Пусть каждый день вашей жизни будет наполнен счастьем, достижениями и великими победами",
        "С юбилеем! Желаю вам сохранять свежий взгляд на жизнь, искреннюю радость и вдохновение каждый день",
        "Поздравляю с юбилеем! Пусть ваш путь будет усыпан цветами радости, исполнен мелодий счастья и озарен светом успеха",
        "С юбилеем! Желаю вам сохранять свою жизненную энергию, блестящий ум и способность видеть прекрасное вокруг себя",
        "Поздравляю с юбилеем! Пусть ваше сердце будет наполнено любовью, ваш ум - мудростью, а ваша жизнь - незабываемыми приключениями",
        "С юбилеем! Желаю вам продолжать делиться своей жизненной мудростью, радоваться малым радостям и быть источником вдохновения для других",
        "С юбилеем! Пусть этот день станет началом нового раздела в вашей жизни, когда вы будете делиться мудростью и рассказывать истории, которые начинаются со слов: (Когда я был молодым...)",
        "Поздравляю с юбилеем! Желаю вам, чтобы каждый новый день вашей жизни был так же прекрасен, как ваша память об этих днях",
        "С юбилеем! Не волнуйтесь, что вы стареете - вы просто становитесь классиком. И, как известно, классика всегда в тренде!",
        "Поздравляю с юбилеем! Желаю вам такую активную жизнь, что вы будете выглядеть моложе своего паспорта, и такую здоровую жизнь, что ваш врач будет удивлен каждый раз, когда вы приходите на прием",
        "С юбилеем! Пусть каждый новый год вашего возраста приносит вам не только мудрость, но и суперспособности, чтобы справиться с любыми жизненными ситуациями!",
        "Поздравляю с юбилеем! Желаю вам столько энергии, сколько у 20-летнего, и столько опыта, сколько у 80-летнего - и пусть они никогда не пересекаются!",
        "С юбилеем! Поздравляю с достижением такого возраста, когда вы начинаете смотреть на молодежь и говорить: 'Ах, какие милые детишки, но какие же они молоды!'",
        "Поздравляю с юбилеем! Теперь, когда вы достигли такого возраста, вы имеете полное право жаловаться на громкую музыку и объяснять, что все было лучше в ваше время, когда вы были молодыми и непосредственно смешными!",
        "С юбилеем! Желаю вам столько энергии, чтобы просыпаться утром без помощи кофе, столько денег, чтобы покупать подарки себе и столько друзей, чтобы помогать вам их потратить!",
        "Поздравляю с юбилеем! Теперь у вас есть прекрасный повод заявить официально, что 'жизнь начинается после 50', и начать собирать скидку на все - начиная от билетов в кино до посещения музеев!",
        "С юбилеем! Пусть ваш возраст станет вашим секретным оружием - вы можете показывать свою пенсионную карточку, чтобы получить внимание или пропустить очередь, и каждый будет считать вас достойным уважения и почтения!",
        "Поздравляю с юбилеем! Желаю вам не стареть, а наоборот, становиться все более и более ярким, привлекательным и смешным с каждым годом - будьте юбилейной звездой в своей собственной комедийной серии!",
        "С юбилеем! Поздравляю с этим замечательным моментом, когда вы можете сказать: 'Я знаю, каким был мир без интернета!'",
        "Поздравляю с юбилеем! Желаю вам иметь столько энергии, чтобы не только справиться с дневным сном, но и организовать собственную рок-группу!",
        "С юбилеем! Теперь, когда вы достигли этого возраста, вы официально имеете право носить носки в сандалиях и разговаривать с домашними растениями - это ваша привилегия!",
        "Поздравляю с юбилеем! Желаю вам всегда иметь ключи от дома, но иногда забывать, зачем вы пришли в комнату, чтобы поддерживать интригу в вашей жизни!",
        "С юбилеем! Пусть ваш юбилейный торт будет такой большой, что вам придется пригласить всех соседей, чтобы помочь его съесть - делитесь счастьем и калориями!",
        "Поздравляю с юбилеем! Желаю вам столько энтузиазма и жизненного оптимизма, чтобы вы всегда забывали, что такое серьезность и взрослость!",
        "С юбилеем! Поздравляю с достижением возраста, когда вы можете называть себя 'винтажным', а не 'старым'. Вы как дорогой ароматный винтаж — с каждым годом только лучше!",
        "Поздравляю с юбилеем! Желаю вам сохранять столько энергии, чтобы вы могли поучаствовать во всех конкурсах на даче и выигрывать в каждом из них!",
        "С юбилеем! Теперь вы можете официально отказаться от использования плохой памяти в качестве оправдания. Просто говорите, что вы собираетесь стать знаменитостью и вам не нужно помнить обычные вещи!",
        "Поздравляю с юбилеем! Желаю вам быть таким здоровым, что ваш врач будет разочаровываться каждый раз, когда вы приходите на прием, и скучать без вас!",
        "С юбилеем! Пусть ваш юбилей будет столь ярким и запоминающимся, что вы будете вспоминать его даже через очки для чтения!",
        "Поздравляю с юбилеем! Желаю вам столько энтузиазма и смелости, чтобы исполнять все свои мечты, и столько юмора, чтобы смеяться над собой, когда что-то не получается!",
        "С праздником юбилея! Пусть каждый день нового года твоей жизни будет наполнен радостью, любовью и благополучием.",
        "Желаю великолепного юбилея, наполненного счастьем и успехами! Пусть этот день станет новым началом прекрасных приключений и незабываемых моментов.",
        "Поздравляю с юбилеем! Пусть каждый прожитый год приносит с собой новые возможности, исполнение мечт и бесконечные радости.",
        "Сегодня особый день – твой юбилей! Желаю, чтобы он был наполнен смехом, улыбками и добрыми эмоциями. Пусть сопровождают тебя только радость и удача!",
        "Поздравляем с юбилеем! Это особый момент в вашей жизни, наполненный праздником и радостью. Желаем вам благополучия, здоровья и новых ярких впечатлений!",
        "С днем юбилея! Пусть этот юбилей станет новой страницей в вашей жизни, наполненной счастьем, успехами и вдохновением. Пусть каждый день будет особенным!",
        "Сердечно поздравляем с юбилеем! Это замечательный повод отметить вашу уникальность и достижения. Пусть ваше будущее будет ещё ярче, а счастье ограждает вас от всех невзгод!",
        "Поздравляем с юбилеем! Это время для воспоминаний, благодарности и радости. Пусть все ваши мечты сбываются, а жизнь радует каждым мгновением!",
        "С наступлением юбилея хочется пожелать вам счастья, любви и гармонии. Пусть ваш путь будет усыпан цветами успеха, а каждый день будет наполнен улыбками и удивительными событиями!",
        "Поздравляем с юбилеем! Это время, когда можно оглянуться на пройденный путь и гордиться своими достижениями. Желаем вам новых целей, вдохновения и бесконечного оптимизма!",
        "С днем юбилея! Пусть ваше сердце будет наполнено радостью, а каждый день приносит вам улыбки и счастливые моменты. Желаем ярких эмоций и осуществления всех мечт!",
        "Поздравляем с юбилеем! Ваша жизнь наполнена мудростью и опытом, и каждый год только добавляет к вашей неповторимой личности. Пусть этот юбилей станет новым началом ваших самых счастливых лет!",
        "С наступлением юбилея хочется пожелать вам неиссякаемой энергии и вдохновения. Пусть ваше сердце будет полно радости, а ваш дом наполнен счастливыми моментами!",
        "Поздравляем с юбилеем! Ваша жизнь – это история успехов, трудностей и преодолений. Желаем вам новых путешествий, улыбок и замечательных встреч на этом пути!",
        "С днем юбилея! Пусть каждый ваш день будет наполнен радостью, добротой и любовью. Желаем вам благополучия, крепкого здоровья и исполнения самых сокровенных желаний!",
        "Поздравляем с юбилеем, который символизирует вашу жизненную мудрость и силу! Пусть каждый день приносит вам новые возможности, успехи и незабываемые моменты радости!",
        "С наступлением юбилея хочется пожелать вам море счастливых мгновений и незабываемых приключений. Пусть ваша жизнь будет наполнена великолепными впечатлениями и бесценными воспоминаниями!",
        "Поздравляем с юбилеем! Это ваше особенное время, когда можно ощутить гордость за все достигнутое и с нетерпением встретить новые горизонты. Желаем вам ярких возможностей и вдохновения на каждом шагу!,
        "С днем юбилея! Жизнь – это чудесное путешествие, и вы прошли по нему с достоинством и силой. Пусть ваше будущее будет наполнено любовью, счастьем и прекрасными возможностями!",
        "Поздравляем с юбилеем! Этот день является подтверждением вашего великолепного пути и уникальности. Желаем вам вдохновения, успеха во всех начинаниях и бесконечного счастья!"
        "С наступлением юбилея хочется пожелать вам прекрасных моментов в кругу любимых людей и искренних друзей. Пусть каждый день приносит вам улыбку на лицо и тепло в сердце!",
        "Поздравляем с юбилеем! Этот день – символ вашей силы, мудрости и достижений. Пусть каждый день вашей жизни будет наполнен радостью, благополучием и самыми яркими эмоциями!",
        "С днем юбилея! Это особый повод отметить вашу значимость и вклад в жизнь окружающих. Желаем вам неиссякаемого оптимизма, здоровья и сбывания самых заветных мечт!",
        "Поздравляем с юбилеем! Это великолепный юбилей, который свидетельствует о вашем богатом опыте и прожитых годах. Желаем вам сохранить яркость души и молодость сердца, наслаждаться каждым мгновением и ценить каждую радостную мелочь!",
        "С наступлением юбилея хочется пожелать вам исполнения самых заветных желаний, чтобы каждый ваш день был наполнен чудесами и приятными сюрпризами. Пусть ваше счастье будет бесконечным и непрерывным!",
        "Поздравляем с юбилеем, который олицетворяет вашу уникальность и ценность в этом мире! Желаем вам дальнейших побед, крепкого здоровья и много радостных моментов, которые будут украшать вашу жизнь!",
        "С юбилеем! Вы как вино, со временем становитесь только лучше и ценнее. Пусть ваш юбилей будет началом новой 'винтажной' главы в вашей жизни, наполненной радостью и удивительными вкусами!",
        "Поздравляем с юбилеем! Вы как прекрасная картина, созданная мастерскими мазками времени. Пусть каждый ваш юбилейный день станет еще ярче и насыщеннее, как холст, на котором вы рисуете свою жизнь!",
        "С днем юбилея! Вы – настоящий жемчужина, бесценное сокровище в нашей жизни. Пусть этот юбилей будет сияющим, как ваше внутреннее блеск, и наполненным радостью, словно морской бриз!",
        "Поздравляем с юбилеем! Вы как феерический фейерверк, который заполняет нашу жизнь красками и радостью. Пусть ваш юбилей станет незабываемым событием, взрывом радости и счастья!",
        "С наступлением юбилея хочется пожелать вам, чтобы ваша жизнь была как волшебная сказка – полна загадок, приключений и волшебства. Пусть каждый ваш день будет наполнен необыкновенными моментами и магией!",
        "Поздравляем с юбилеем! Вы – настоящий космический рокетмен, и ваш юбилей – это запуск в новые высоты и невероятные приключения. Пусть ваше путешествие через жизнь будет полным звездных мгновений и ошеломляющих открытий!",
        "С днем юбилея! Вы – настоящий гений юмора, чьи шутки всегда поднимают настроение. Пусть ваш юбилей станет праздником смеха, шуток и улыбок, которые звучат в течение всей жизни!",
        "Поздравляем с юбилеем! Вы – настоящий мастер кулинарного искусства, способный превратить обычную еду в произведение гастрономического искусства. Пусть ваш юбилей станет пиршеством вкуса и гастрономическим событием!",
        "С наступлением юбилея хочется пожелать вам, чтобы ваша жизнь была как увлекательный головоломка. Пусть каждый ваш юбилейный день становится новым пазлом, который вы с радостью собираете!,
        "Поздравляем с юбилеем! Вы – настоящий капитан своей жизни. Пусть ваш юбилей станет морским приключением, где вы смело идете по волнам судьбы, достигая новых горизонтов и завоевывая сердца людей!",
        "С юбилеем! Вы – настоящий маг в искусстве жизни, способный превращать обычные моменты в волшебные. Пусть ваш юбилей станет великолепным шоу, наполненным фокусами счастья, и пусть каждый день будет волшебным путешествием!",
        "Поздравляем с юбилеем! Вы – непревзойденный танцор жизни, чьи шаги наполнены грацией и энергией. Пусть ваш юбилей станет ярким танцевальным шоу, где вы воплощаете свои мечты на пути к успеху!",
        "С наступлением юбилея хочется пожелать вам, чтобы ваша жизнь была как захватывающий приключенческий роман, полный опасностей, любви и неожиданных поворотов сюжета. Пусть каждая глава вашей жизни оставляет ощущение удивления и восхищения!",
        "Поздравляем с юбилеем! Вы – настоящий магнит для успеха и процветания. Пусть ваш юбилей станет мощным магнитом, притягивающим все лучшее в вашу жизнь – любовь, достаток и благополучие!",
        "С днем юбилея! Вы – настоящая звезда на сцене жизни, способная восхищать всех своим талантом и сиянием. Пусть ваш юбилей станет настоящим зрелищем, где вы продолжаете восхищать мир своей яркостью и уникальностью!",
        "Поздравляем с юбилеем! Вы – настоящий художник, чьи кисти создают шедевры жизни. Пусть ваш юбилей станет выставкой ваших достижений, где каждая работа восхищает и вдохновляет окружающих!",
        "С наступлением юбилея хочется пожелать вам, чтобы ваша жизнь была как фантастический фильм. Пусть каждый ваш юбилейный день становится захватывающим сюжетом, который оставляет след в сердцах всех, кто видит ваше киношоу!",
        "С юбилеем! Вы – истинный мастер своего ремесла, способный творить чудеса из простых материалов. Пусть ваш юбилей станет выставкой вашего таланта, где каждое произведение искусства олицетворяет вашу неповторимую креативность!",
        "Поздравляем с юбилеем! Вы – настоящий рок-звезда, чьи аккорды и мелодии покоряют сердца. Пусть ваш юбилей станет грандиозным концертом, где вы продолжаете завоевывать музыкальный мир своим неповторимым стилем и энергией!",
        "Пусть каждый ваш юбилей становится точкой нового начала, наполненного радостью и достижениями. Поздравляю с этим значимым днем!",
        "Сегодняшний юбилей - это повод отпраздновать все, что вы достигли, и вдохновиться новыми целями. Желаю вам продолжать шагать к успеху и сиять своим счастьем!",
        "Пусть каждый прожитый год будет драгоценным камнем в вашей жизни, образующим великолепный жизненный мозаику. С днем юбилея!",
        "Ваш юбилей - это свидетельство вашей прочной души и силы духа. Продолжайте восхищать нас своей удивительной энергией и страстью к жизни!",
        "Юбилей - это веха, отмечающая вашу необычайную жизненную историю. Пусть следующие главы будут наполнены еще большими приключениями и счастьем!",
        "С юбилеем! Желаю вам море вдохновения, океан счастья и небоскребы исполнения всех ваших мечтаний. Вы достойны самого лучшего!",
        "Ваш юбилей - это повод заглянуть в прошлое с гордостью, в настоящее с удовольствием и в будущее с оптимизмом. Пусть каждый момент вашей жизни будет наполнен радостью и благополучием!",
        "Юбилей - это знак того, что вы преодолели преграды и сияете собственным светом. Пусть ваше путешествие продолжается, наполняя вашу жизнь новыми впечатлениями и счастьем!",
        "Сегодня я хочу поздравить вас с вашим юбилеем и поблагодарить вас за то, что вы вносите свет и радость в жизни всех вокруг. Вы поистине вдохновляющий человек!",
        "Юбилей - это момент, когда мы можем остановиться и взглянуть на все, что мы достигли. Ваша жизнь - это история мудрости, силы и любви. Пусть ваш путь продолжается быть ярким и интересным!",
        "Юбилей - это время, когда мы отмечаем вашу уникальность и значимость. Вы - звезда, светящаяся своими достижениями и добротой. Сияйте дальше!",
        "Пусть каждый ваш юбилей становится новым началом, полным возможностей и незабываемых моментов. Сегодня я желаю вам счастья, здоровья и исполнения всех мечт!",
        "Ваш юбилей - это повод подарить себе больше времени на радость и благополучие. Желаю вам незабываемых приключений и вдохновляющих открытий!",
        "Ваш юбилей напоминает нам, что возраст - это просто число, а настоящая молодость живет в сердце. Счастливого юбилея, оставайтесь молодыми душой всегда!",
        "Празднуя ваш юбилей, мы отмечаем вашу прочность и устойчивость перед вызовами времени. Пусть ваша жизнь будет наполнена радостью и благодарностью!",
        "Юбилей - это мгновение, когда мы осознаем, как много восхитительных моментов мы разделили вместе. Пусть эти воспоминания будут источником радости и счастья на протяжении всей жизни!",
        "Ваш юбилей - это повод вспомнить о прошлых достижениях и заглянуть в будущие возможности. Желаю вам вдохновения, энтузиазма и невероятных успехов впереди!",
        "Юбилей - это свидетельство того, что ваша жизнь была полна значимых мгновений и прекрасных воспоминаний. Пусть эти мгновения продолжают приносить вам радость и счастье!",
        "Ваш юбилей - это повод благодарить вас за то, что вы делаете этот мир ярче и прекраснее. Пусть ваша жизнь будет наполнена любовью, миром и счастьем!",
        "С днем юбилея! Желаю вам сохранить свою уникальность, распространять свет и вдохновлять всех вокруг своим примером. Вы поистине особенный человек!",
        "Юбилей - это время, чтобы отметить вашу жизненную силу и стойкость. Вы продолжаете сиять ярко, преодолевая преграды и вдохновляя всех вокруг. Поздравляю вас с этим знаменательным днем!",
        "С юбилеем! Пусть каждый ваш день будет наполнен радостью, смехом и улыбками. Вы заслуживаете только самые прекрасные и светлые моменты в жизни!",
        "Ваш юбилей - это повод вспомнить все прекрасные мгновения, которые вы пережили, и посмотреть с улыбкой на то, что ждет вас впереди. Пусть ваша жизнь будет наполнена любовью, исполнением мечт и счастьем!",
        "Жизнь - это путешествие, и ваш юбилей - это момент остановиться и насладиться пройденным путем. Пусть ваше путешествие продолжается быть захватывающим, наполненным новыми открытиями и удивительными приключениями!",
        "Ваш юбилей - это не только отметка времени, но и отражение вашего благородства, доброты и мудрости. Пусть каждый день вашей жизни будет наполнен радостью, достижениями и любовью!",
        "Сегодня мы празднуем ваш юбилей и хотим выразить нашу благодарность за то, что вы являетесь источником вдохновения и поддержки. Пусть ваша жизнь будет наполнена счастьем, здоровьем и безграничной радостью!",
        "Юбилей - это повод поверить в себя и в свою способность преодолевать любые препятствия. Пусть ваша сила и уверенность сопровождают вас на каждом шагу вашего жизненного пути!",
        "Ваш юбилей - это повод погрузиться в море радости и празднования. Пусть эта особая дата станет отправной точкой для новых приключений и незабываемых моментов в вашей жизни!",
        "Юбилей - это время, чтобы посмотреть на свои достижения и оценить свой путь. Вы проделали долгий путь, и мы гордимся тем, кем вы стали. Счастливого юбилея!",
        "Юбилей - это чудесная возможность отметить ваш вклад в этот мир и подчеркнуть вашу значимость. Пусть ваше влияние продолжает распространяться и вдохновлять других на превосходство!",
        "Сегодня мы поднимаем бокал в честь вашего юбилея и хотим пожелать вам море радости, мирного счастья и исполнения самых заветных желаний. Вы заслуживаете только самое лучшее!",
        "Юбилей - это время, чтобы вспомнить о всех трудностях, которые вы преодолели, и быть гордым своими достижениями. Пусть ваш юбилей станет началом новых возможностей и великих побед!",
        "Ваш юбилей - это прекрасный повод подумать о значимости каждого мгновения и о том, какие чудеса могут произойти, если мы верим в себя. Пусть ваша жизнь будет наполнена вдохновением и неизведанными горизонтами!",
        "Поздравляю с юбилеем! Пусть каждый год вашей жизни будет наполнен радостью, любовью и исполнением самых смелых желаний. Вы достойны только самого прекрасного!",
        "Юбилей - это время, чтобы отпраздновать вашу жизнь и позволить себе расслабиться, наслаждаясь моментом. Пусть этот день станет началом новой главы полной незабываемых приключений и радостных сюрпризов!",
        "Ваш юбилей - это повод быть гордым своими достижениями и наслаждаться прекрасной компанией друзей и близких. Пусть каждый день вашей жизни будет наполнен счастьем и удовлетворением!",
        "Юбилей - это время, чтобы отпраздновать ваше прекрасное влияние на мир и все добро, которое вы сеете вокруг себя. Пусть ваше сияние никогда не угасает!",
        "С юбилеем! Желаю вам ощутить всю глубину любви и благодарности, которую вам испытывают близкие и друзья. Пусть этот юбилей станет самым ярким и незабываемым в вашей жизни!",
        "С юбилеем, дорогой друг! Желаю, чтобы каждый миг твоей жизни был наполнен радостью, смехом и вдохновением. Пусть новый этап принесет тебе неисчерпаемую энергию и неожиданные приключения!",
        "Поздравляю с юбилеем! Пусть этот день станет символом новых начинаний, и ты осуществишь все свои мечты. Будь смелым, находчивым и не бойся сделать шаг в неизведанное!",
        "Спешу поздравить с юбилеем! Пусть этот день будет началом невероятного путешествия, наполненного приятными сюрпризами и незабываемыми впечатлениями. Не забывай радоваться каждому мгновению!",
        "Поздравляю с юбилеем! Пусть он станет вехой в твоей жизни, отмечающей твои достижения и преодоления. Ты силен и талантлив, и я верю, что у тебя ещё много прекрасных путей вперед!",
        "Сегодня ты отмечаешь юбилей, и я хочу пожелать тебе безграничного счастья и исполнения самых заветных желаний. Пусть каждый день становится для тебя новой возможностью раскрыть свой потенциал!",
        "Поздравляю с юбилеем! Этот день — прекрасный повод осознать свои достижения и посмотреть на будущее с оптимизмом. Пусть тебя окружают любовь, дружба и гармония!",
        "В этот знаменательный день я желаю тебе ощутить всю мощь своего внутреннего света и зажечь огни успеха вокруг себя. С юбилеем! Пусть твоя жизнь будет наполнена яркими моментами и счастливыми мгновениями!",
        "Поздравляю с юбилеем! Пусть этот день станет точкой отсчета для новых замыслов и возможностей. Желаю тебе неиссякаемого вдохновения, чтобы ты всегда шел вперед и достигал своих целей!",
        "С юбилеем! Пусть каждый твой день становится настоящим фейерверком искрометных идей, гениальных открытий и невероятных приключений! Ты — настоящий капитан своей собственной судьбы, плыви к новым горизонтам смело и с улыбкой!",
        "Поздравляю с юбилеем! Пусть твоя жизнь будет словно книга, наполненная захватывающими главами, неожиданными поворотами сюжета и волнующими финалами. Ты — главный герой своей истории, пиши её ярко и незабываемо!",
        "Сегодня ты отмечаешь юбилей, и я хочу пожелать тебе обнаружить в себе внутреннего художника. Рисуй свою жизнь яркими красками, сочными оттенками и гармонией композиции.",
        "С юбилеем, капитан Приключений! Пусть твоя жизнь будет заполнена удивительными экспедициями, необычными открытиями и встречами с настоящими сокровищами. Не забывай, что каждый день — новая глава в твоей захватывающей истории!",
        "Поздравляю с юбилеем, человек Вдохновения! Пусть твоя жизнь будет как калейдоскоп ярких идей, прозрений и творческой эйфории. Используй каждую мгновение, чтобы вдохнуть жизнь в свои самые смелые и необычные проекты!",
        "Сегодня ты отмечаешь юбилей, и я желаю тебе обнаружить свою внутреннюю суперсилу. Будь смелым, как Супергерой, и преодолевай все преграды на своем пути к успеху. Ты — настоящий герой своей собственной сказки!",
        "Поздравляю с юбилеем! Пусть твоя жизнь будет как галерея современного искусства, наполненная яркими экспозициями и непредсказуемыми шедеврами. Разбуди в себе художника и впечатляй мир своей оригинальностью и креативностью!",
        "С юбилеем! Пусть твоя жизнь будет словно непрерывный фестиваль веселья и радости. Зажги огни праздника, танцуй под звуки смеха и позволь себе быть главным героем самого яркого шоу на свете — своей собственной жизни!",
        "Поздравляю с юбилеем, о, Великий Путешественник! Пусть каждый твой шаг открывает новые горизонты, каждое приключение наполняет твою душу впечатлениями, а каждое путешествие приносит тебе бесконечные волшебные мгновения!",
        "С юбилеем! Пусть твоя жизнь будет словно палитра художника, где каждый цвет отражает яркость твоих эмоций, а каждый мазок создает прекрасное произведение искусства. Ты — художник своей собственной судьбы, создавай шедевр каждым днем!",
        "Поздравляю с юбилеем, Универсальный Гений! Пусть твоя жизнь будет полна разнообразных интересов, открытий и саморазвития. Продолжай расширять свои горизонты, погружайся в новые сферы знаний и восхищай мир своим неиссякаемым умом!",
        "Сегодня ты отмечаешь юбилей, и я желаю тебе стать настоящим Магом Творчества! Пусть каждая идея, которую ты воплощаешь в жизнь, становится источником вдохновения для других. Раскрой свои таланты и волшебным образом создавай прекрасное!",
        "Поздравляю с юбилеем, Вечный Оптимист! Пусть твоя жизнь будет наполнена солнечными лучами радости и благодарности. Преодолевай трудности с улыбкой на лице и делай мир вокруг себя ярче и добрее. Ты — источник света и вдохновения!",
        "С юбилеем! Пусть каждый день твоей жизни будет полон маленьких радостей и волшебных моментов. Не забывай находить красоту в простых вещах и ценить магию окружающего мира. Ты — коллекционер счастливых моментов!",
        "С юбилеем! Пусть твоя жизнь станет грандиозным спектаклем, где ты выступаешь в роли главного актера. Пусть каждое действие, каждое слово, каждая мысль, которые ты приносишь на сцену жизни, завораживают аудиторию и оставляют неизгладимый след!",
        "Поздравляю с юбилеем, Непревзойденный Мечтатель! Пусть каждая твоя мечта становится реальностью, каждое желание превращается в яркую звезду на небе возможностей. Иди за своими целями смело и не останавливайся до их полного осуществления!",
        "Сегодня ты отмечаешь юбилей, и я хочу пожелать тебе раскрыть свою Внутреннюю Звезду. Пусть ты сияешь ярким светом вокруг себя, вдохновляя других и принося радость и гармонию. Ты — источник непреходящего блеска!",
        "Поздравляю с юбилеем, Волшебник Хорошего Настроения! Пусть каждое твое прикосновение создает вокруг тебя волшебную атмосферу радости, улыбок и счастливых моментов. Распространяй положительное влияние и делай мир вокруг себя волшебным местом!",
        "С юбилеем! Пусть твоя жизнь станет настоящим Карнавалом Вдохновения, где каждый день ты находишь новые и удивительные источники вдохновения. Развлекайся, погружайся в красочный мир и позволь себе быть безудержно творческим!",
        "Сегодня ты отмечаешь юбилей, и я хочу пожелать тебе стать настоящим Архитектором Счастья. Пусть каждый твой шаг строит прочные фундаменты благополучия и каждое решение создает красивую и гармоничную архитектуру твоей жизни!",
        "С юбилеем! Пусть твоя жизнь станет громким симфоническим произведением, где каждая нота символизирует твои достижения, стойкость и смелость. Будь дирижером своей жизни и создавай гармонию в каждой ее ноте!",
        "Поздравляю с юбилеем, Неиссякаемый Источник Энергии! Пусть твоя жизнь будет наполнена бесконечным запасом энтузиазма, страсти и силы. Используй эту энергию, чтобы преодолевать любые трудности и сиять ярким светом вокруг себя!",
        "Сегодня ты отмечаешь юбилей, и я хочу пожелать тебе стать настоящим Загадочным Волшебником. Пусть ты обладаешь силой преображения, способностью создавать магию вокруг себя и привлекать к себе только самые волшебные и благоприятные события!",
        "Поздравляю с юбилеем, Гений Несгибаемого Оптимизма! Пусть твоя жизнь будет источником вечного света, который преодолевает темноту и отражает весь спектр радуги. Не теряй веру в себя и продолжай восхищать мир своим непоколебимым оптимизмом!",
        "С юбилеем! Пусть твоя жизнь будет словно галактика звезд, где каждая звезда является твоим достижением, каждое сияние — твоим вдохновением. Раскрой всю красоту своего внутреннего космоса и позволь миру восхищаться твоим ярким сиянием!",
        "С днем юбилея! Пусть этот волшебный день станет началом новых приключений, смелых идей и великих побед!",
        "Самые теплые поздравления с юбилеем! Пусть каждая минута жизни будет наполнена радостью, счастьем и незабываемыми моментами.",
        "Великий юбилей - время для особого праздника! Пусть каждый день вашей жизни станет маленьким чудом, а каждое сердце, которое вы тронете, наполнится благодарностью и любовью.",
        "Сегодня ваш юбилей, и весь мир сияет в вашу честь! Пусть все ваши мечты сбудутся, а успех и процветание будут сопутствовать вам на каждом шагу.",
        "Поздравляем с юбилеем! Пусть жизнь будет красочной палитрой, на которой каждый день будет ярким и запоминающимся штрихом.",
        "Желаем вам юбилейного волшебства! Пусть каждое утро приносит радость, а каждый вечер наполняется благодарностью за прожитый день.",
        "Пусть ваш юбилей станет новым началом, полным невероятных возможностей! Пусть все ваши мечты осуществляются, а сердце радуется каждому дню.",
        "С днем юбилея! Желаем вам незабываемых приключений, вдохновляющих встреч и радостных моментов, которые запомнятся на всю жизнь.",
        "Поздравляем с замечательным юбилеем! Пусть ваши дни будут наполнены смехом, дружбой и любовью, а каждый новый год приносит больше счастья, чем предыдущий.",
        "Самые теплые пожелания в этот особенный день! Пусть каждый ваш шаг будет направлен к успеху, а каждое сердце, которое вы тронете, заполняется радостью и благодарностью!",
        "Сегодня ваш юбилей, и мир прекраснее благодаря вам! Пусть каждый день жизни становится новым приключением, а каждый год - мудростью и счастьем.",
        "Пусть ваш юбилей будет началом нового главного героя! Пусть вы создаете свою собственную историю, наполненную смелыми решениями и незабываемыми моментами.",
        "В этот юбилейный день желаем вам непреходящей радости и вдохновения! Пусть каждый ваш шаг будет направлен к достижению высот, а каждое сердце, которое вы осязаете, зажигается огнем страсти и любви.",
        "Сегодня ваш день, ваш юбилей! Желаем вам невероятных открытий, великолепных возможностей и безграничного счастья. Пусть каждый ваш день будет наполнен волшебством и улыбками.",
        "Поздравляем с золотым юбилеем! Пусть ваша жизнь будет наполнена богатством знаний, мудростью опыта и яркими мгновениями счастья.",
        "Юбилей - это особенный момент в жизни, когда все оказывается возможным! Пусть каждая ваша мечта станет реальностью, а каждая улыбка озарит ваш путь.",
        "С днем юбилея! Пусть этот день будет началом новых приключений, встреч и возможностей. Желаем вам непрерывного роста и исполнения самых заветных желаний.",
        "Поздравляем с юбилеем! Пусть каждый ваш день будет наполнен добром, миром и гармонией. Желаем вам благополучия, любви и радости в каждой мельчайшей детали жизни.",
        "Самые искренние пожелания с юбилеем! Пусть ваши дни будут наполнены прекрасными мгновениями, а ваша душа - бесконечной молодостью и счастьем.",
        "В честь вашего юбилея хотим пожелать вам море впечатлений, гору приятных сюрпризов и небо, полное достижений! Пусть ваш путь будет освещен яркими звездами удачи.",
        "С днем юбилея! Желаем вам жизни, наполненной яркими красками, благополучия и успеха. Пусть каждый день приносит вам новые возможности для саморазвития и счастья.",
        "Поздравляем с юбилеем! Пусть ваше сердце будет источником вдохновения, ваш разум - фонтаном мудрости, а ваша душа - источником бесконечной любви.",
        "Сегодня ваш юбилей, и хочется пожелать вам сиять ярче солнца, лететь выше облаков и обнимать мир всей своей добротой и теплотой.",
        "Юбилей - это повод для радости и гордости! Пусть каждый ваш успех станет звездой на небе, каждая ваша улыбка - лучом солнца, а каждое достижение - вдохновением для других.",
        "С днем юбилея! Желаем вам бесконечного оптимизма, смелости и стойкости духа. Пусть ваше сердце всегда наполняется любовью, а ваша жизнь - яркими цветами.",
        "Поздравляем с юбилеем, который олицетворяет силу и упорство! Пусть каждый пройденный этап вашей жизни станет зеркалом успеха, а каждая преодоленная трудность - ступенькой к победе.",
        "В этот особенный день пусть все ваши мечты станут реальностью! Желаем вам вдохновения, креативности и неиссякаемого энтузиазма на пути к достижению новых вершин.",
        "С днем юбилея! Пусть ваша жизнь будет наполнена яркими моментами, волнующими приключениями и незабываемыми встречами. Желаем вам небесного счастья и земной благодарности.",
        "Поздравляем с юбилеем, который приходит с мудростью и опытом! Пусть каждый ваш шаг будет направлен к саморазвитию и самоосознанию, а каждая победа станет новым этапом в вашей жизни.",
        "В этот особый день пусть ваши мечты воплощаются в жизнь! Желаем вам искренней радости, гармонии в сердце и вдохновения для совершения больших дел.",
        "Поздравляем с юбилеем, который символизирует непреходящую молодость души! Пусть ваша энергия и страсть к жизни не знают границ, а каждый день принесет новые возможности для саморазвития и самовыражения.",
        "В этот день юбилея хотим пожелать вам быть свободным, как птица в небе, и сильным, как лев на пути к своей цели. Пусть вся ваша жизнь превращается в самое захватывающее приключение.",
        "С днем юбилея! Желаем вам непрерывного роста духа и развития. Пусть каждый день принесет новые возможности для самореализации, а каждый год будет еще ярче и насыщеннее.",
        "Поздравляем с юбилеем, который олицетворяет величие и достижения! Пусть ваша жизнь будет наполнена гордостью за собственные успехи, а каждая победа будет стимулом для новых высот.",
        "В этот день юбилея пусть ваше сердце бьется в ритме счастья и исполнения желаний! Желаем вам море любви, здоровья и благополучия на протяжении всей вашей жизни.",
        "С днем юбилея! Пусть каждая минута вашей жизни будет наполнена чудесами и волшебством, а каждое дело, которое вы осуществите, принесет вам гордость и удовлетворение.",
        "Поздравляем с юбилеем, который олицетворяет уверенность и достижения! Пусть каждый ваш шаг будет направлен к новым горизонтам, а каждая преграда будет преодолена смелостью и решительностью.",
        "В этот особый день пусть вас окружают люди, которые любят и ценят вас! Желаем вам много счастливых мгновений, незабываемых воспоминаний и бесконечной радости.",
        "С днем юбилея! Пусть каждая встреча становится поводом для радости, каждое достижение - поводом для гордости, а каждая любовь - поводом для благодарности.",
        "В этот особый день юбилея хотим пожелать вам сохранить свою детскую наивность и веру в чудеса. Пусть ваша жизнь будет наполнена смехом, игрой и безграничной радостью.",
        "С днем юбилея! Желаем вам вдохновения, чтобы вы всегда могли видеть прекрасное в мире, мудрости, чтобы преодолевать трудности, и любви, чтобы делиться ею с близкими.",
        "Поздравляем с юбилеем, который символизирует неподвластность времени! Пусть каждый год приносит вам новые возможности для саморазвития, новые цели и достижения.",
        "В этот день юбилея пусть каждый ваш вдох будет наполнен жизнью, а каждый выдох - благодарностью за прожитые мгновения. Желаем вам быть счастливым и полным энергии всегда!",
        "С днем юбилея! Пусть ваша жизнь будет наполнена светом, теплом и добротой. Желаем вам искренней любви, стабильности и успеха во всех начинаниях.",
        "Поздравляем с юбилеем, который пришел с благодарностью за прожитые годы! Пусть каждый день вашей жизни будет наполнен смыслом, а каждое достижение становится заслуженной наградой.",
        "В этот особый день юбилея хотим пожелать вам сохранить свою жизнерадостность и энтузиазм. Пусть ваше сердце будет открыто для новых возможностей и приключений.",
        "С днем юбилея! Пусть ваша жизнь будет как прекрасная симфония, в которой каждая нота звучит гармонично, а каждая пауза - дарует время для отдыха и наслаждения.",
        "Поздравляем с юбилеем, который олицетворяет силу духа и настойчивость! Пусть каждый ваш шаг будет направлен к осуществлению ваших самых заветных мечтаний, а каждая победа станет доказательством вашей неоспоримой силы.
        "В этот юбилейный день хотим пожелать вам бесконечного вдохновения и творческого роста! Пусть каждый ваш творческий порыв станет магией, которая преображает вашу жизнь.
        "С днем юбилея! Желаем вам быть окруженным добрыми и искренними людьми, с которыми вы сможете разделить свои радости и трудности. Пусть ваше сердце будет наполнено любовью и поддержкой.",
        "Поздравляем с юбилеем, который приходит с благодарностью за каждый прожитый год! Пусть каждый ваш день будет наполнен улыбками, радостью и незабываемыми моментами счастья.",
        "В этот особый день юбилея хотим пожелать вам сохранить свою непоколебимую веру в себя и в свои возможности. Пусть каждая ваша цель становится реальностью, а каждое испытание - шансом для роста.",
        "С днем юбилея! Пусть каждый ваш день будет наполнен радостью, миром и любовью. Желаем вам сохранить свою молодость души и радость открытий на протяжении всей жизни.",
        "Поздравляем с юбилеем, который олицетворяет созревание и мудрость! Пусть ваш опыт превращается в ценные уроки, а каждый ваш совет помогает другим на их жизненном пути.",
        "В этот день юбилея хотим пожелать вам сохранить свою страсть к жизни и неуемную энергию! Пусть ваша жизнь будет яркой и насыщенной, а каждый новый день принесет вам новые возможности для саморазвития и самовыражения. ",
        "С днем юбилея! Пусть ваше сердце будет полным любви и доброты, ваш разум - проникнут мудростью, а ваша жизнь - наполнена смыслом и благополучием.",
        "В этот юбилейный день хотим пожелать вам сохранить свою неподкупную смелость и решительность. Пусть каждый ваш шаг будет направлен к осуществлению ваших самых смелых идей и мечтаний.",
        "С днем юбилея! Пусть ваша жизнь будет наполнена вдохновением и прекрасными мгновениями. Желаем вам здоровья, успеха и любви, которые сопровождают вас на протяжении всего пути.",
        "Поздравляем с юбилеем, который символизирует созревание и расцвет! Пусть каждый день вашей жизни принесет новые возможности для саморазвития и самовыражения, а каждое достижение станет подтверждением вашей силы и таланта.",
        "В этот особый день юбилея хотим пожелать вам сохранить свою уникальность и неповторимость. Пусть ваш путь будет освещен светом вашей индивидуальности, а каждая ваша идея - прекрасным проявлением вашей креативности.",
        "С днем юбилея! Желаем вам быть окруженным истинными друзьями, которые поддерживают вас во всех жизненных ситуациях. Пусть ваша жизнь будет наполнена радостью, смехом и взаимным пониманием.",
        "Поздравляем с юбилеем, который пришел с благодарностью за каждое прожитое мгновение! Пусть каждый ваш день будет наполнен любовью и благодарностью за все, что вы уже достигли, и за все, что еще вас ждет.",
        "В этот юбилейный день хотим пожелать вам сохранить свою настойчивость и целеустремленность. Пусть каждая ваша мечта станет реальностью, а каждое усилие - шагом к вашему счастью и успеху.",




    )

    private val spanish = listOf(
        "¡Felicitaciones por tu jubileo! ¡Que este día esté lleno de alegría, felicidad y un ambiente festivo! Te deseo buena salud, amor y el cumplimiento de todos tus sueños!",
        "¡Feliz jubileo! ¡Que cada día esté lleno de alegría, logros y satisfacción con la vida! ¡Que el éxito te acompañe en todo lo que hagas!",
        "¡Felicitaciones por este maravilloso jubileo! ¡Te deseo una salud fuerte, felicidad, inspiración y nuevas experiencias brillantes! ¡Que tu vida esté llena de alegría y prosperidad!",
        "¡Feliz jubileo! ¡Que este jubileo marque un nuevo comienzo lleno de nuevas oportunidades y logros! ¡Te deseo felicidad, suerte y éxito en todos tus emprendimientos!",
        "¡Felicitaciones por este jubileo significativo! ¡Que cada momento de tu vida esté lleno de alegría, risas y bienestar! ¡Que los años solo traigan los momentos más brillantes e inolvidables!",
        "¡Feliz jubileo! ¡Deseo que este jubileo se convierta en una nueva página en tu vida, llena de felicidad, satisfacción y amor! ¡Que cada día traiga solo alegría y el cumplimiento de los sueños!",
        "¡Felicitaciones por este hermoso jubileo! ¡Te deseo salud sólida, longevidad y la sensación de una felicidad completa! ¡Que siempre haya espacio para la alegría y el amor en tu vida!",
        "¡Feliz jubileo! ¡Que este día se convierta en un nuevo comienzo lleno de eventos vibrantes, impresiones y momentos felices! ¡Te deseo éxito, prosperidad y el cumplimiento de todos tus deseos!",
        "¡Felicitaciones por tu jubileo! ¡Te deseo mantener una brillante energía vital, alegría y optimismo durante muchos años por venir! ¡Que todo tu camino esté coronado de éxito y bienestar!",
        "¡Felicitaciones por su aniversario! ¡Deseo que mantenga una brillante vitalidad, alegría y optimismo durante muchos años más! ¡Que todo su viaje se vea coronado por el éxito y la prosperidad!",
        "¡Felicitaciones por su aniversario! Este día especial es una gran oportunidad para celebrar todos los logros y desafíos que ha superado. Le deseo éxito continuo y momentos inolvidables en su vida",
        "¡Feliz Aniversario! Que este día sea un hito en tu vida, reflejando todos los grandes momentos, logros y felices recuerdos",
        "¡Felicitaciones por su aniversario! Le deseo bienestar, salud, inspiración y más viajes felices por la vida",
        "¡Feliz aniversario! Este es un momento especial para mirar hacia atrás y estar orgulloso de tu camino. Te deseo felicidad, amor y nuevas aventuras increíbles",
        "¡Felicitaciones por tu aniversario! Que este día sea el comienzo de nuevas oportunidades, el cumplimiento de tus preciados deseos y la continuación de tus sueños más salvajes",
        "¡Feliz aniversario! Te deseo sabiduría, felicidad y prosperidad en cada paso de tu camino",
        "¡Felicitaciones por tu aniversario! Que este día esté lleno de alegría, risas y cálidos recuerdos de los años pasados",
        "¡Feliz aniversario! Te deseo éxito continuo, bienestar y el cumplimiento de todos los deseos que te pidas",
        "¡Felicitaciones por tu aniversario! Que cada próximo día de tu vida esté lleno de alegría, sonrisas y agradables sorpresas",
        "¡Feliz Aniversario! Deseo que mantengas un espíritu joven, te mantengas activo y disfrutes cada momento del viaje de tu vida",
        "¡Felicidades por tu aniversario! Que este día sea un nuevo comienzo, lleno de oportunidades y logros",
        "¡Feliz aniversario! Deseo que continúes viviendo tu vida con confianza, disfrutes cada momento y te esfuerces incansablemente por alcanzar nuevas alturas",
        "¡Felicidades por tu aniversario! Que todos los días de tu vida estén llenos de alegría, amor y felicidad. ¡Te mereces lo mejor!",
        "¡Feliz aniversario! Deseo que conserves la invaluable experiencia y sabiduría que has acumulado a lo largo de los años, y disfrutes cada nuevo día",
        "¡Felicitaciones por tu aniversario! Que cada momento de tu vida esté lleno de colores brillantes e impresiones inolvidables",
        "¡Feliz aniversario! Te deseo momentos felices, prosperidad y el logro de nuevas alturas en tu vida",
        "¡Felicitaciones por tu aniversario! Que cada paso de tu camino esté lleno de alegría, éxito y gratitud por todo lo que ya has logrado",
        "¡Feliz aniversario! Deseo que mantengas fuego en tus ojos y juventud en tu corazón para que cada día esté lleno de nuevas oportunidades y gratas sorpresas",
        "¡Felicitaciones por tu aniversario! Que todos los días de tu vida estén llenos de alegría, sonrisas y calidez de corazones amorosos",
        "¡Feliz aniversario! Que sigas superando los obstáculos de la vida con confianza y disfrutes de los maravillosos momentos que trae",
        "¡Felicidades por tu aniversario! Que este día sea el comienzo de un nuevo capítulo en tu vida lleno de salud, alegría y el cumplimiento de todos los sueños",
        "¡Feliz Aniversario! Les deseo optimismo continuo, entusiasmo y la capacidad de disfrutar de las pequeñas cosas que hacen que la vida sea hermosa",
        "¡Felicitaciones por tu aniversario! Que todos los días de tu vida estén llenos de risas, apoyo amistoso y armonía en tu corazón",
        "¡Feliz Aniversario! Deseo que conserves el brillo del alma, la juventud del espíritu y disfrutes de todos los beneficios que la vida te ofrece",
        "¡Felicidades por tu aniversario! Que cada día de tu vida esté lleno de felicidad, logros y grandes victorias",
        "¡Feliz aniversario! Deseo que mantengas una nueva perspectiva de la vida, alegría sincera e inspiración todos los días",
        "¡Felicidades por tu aniversario! Que tu camino se llene de flores de alegría, lleno de melodías de felicidad e iluminado por la luz del éxito",
        "¡Feliz aniversario! Deseo que conserves tu vitalidad, mente brillante y capacidad para ver la belleza que te rodea",
        "¡Felicidades por tu aniversario! Que tu corazón se llene de amor, tu mente de sabiduría y tu vida de aventuras inolvidables",
        "¡Feliz aniversario! Deseo que sigas compartiendo tu sabiduría de vida, disfrutes de las pequeñas alegrías y seas una inspiración para los demás",
        "¡Feliz Aniversario! Que este día sea el comienzo de un nuevo capítulo en tu vida mientras compartes sabiduría y cuentas historias que comienzan con: (Cuando era joven...)",
        "¡Felicidades por tu aniversario! Te deseo que cada nuevo día de tu vida sea tan hermoso como tu recuerdo de estos días",
        "¡Feliz aniversario! No te preocupes por envejecer, te estás convirtiendo en un clásico. Y, como sabes, ¡lo clásico siempre está de moda!",
        "¡Felicidades por tu aniversario! Te deseo una vida tan activa que luzcas más joven que tu pasaporte, y una vida tan saludable que tu médico se sorprenda cada vez que vengas a la cita",
        "¡Feliz aniversario! ¡Que cada nuevo año de tu edad te traiga no solo sabiduría, sino también superpoderes para hacer frente a cualquier situación de la vida!",
        "¡Felicitaciones por tu aniversario! Te deseo tanta energía como a los 20 años y tanta experiencia como a los 80, ¡y que nunca se crucen!",
        "¡Feliz aniversario! Felicitaciones por llegar a la edad en la que empiezas a mirar a los jóvenes y decir: '¡Ay, qué lindos niños, pero qué jóvenes son!'",
        "¡Felicidades por tu aniversario! ¡Ahora que has llegado a esta edad, tienes todo el derecho de quejarte de la música alta y explicar que todo era mejor en tu época cuando eras joven y directamente gracioso!",
        "¡Feliz aniversario! ¡Te deseo tanta energía para despertarte por la mañana sin la ayuda del café, tanto dinero para comprar regalos para ti y tantos amigos para ayudarte a gastarlos!",
        "¡Feliz aniversario! ¡Ahora tienes una gran excusa para declarar oficialmente que 'la vida comienza después de los 50' y comenzar a acumular descuentos en todo, desde entradas para el cine hasta visitas a museos!",
        "¡Feliz aniversario! Deje que su edad sea su arma secreta: puede mostrar su tarjeta de jubilación para llamar la atención o saltarse la fila, ¡y todos lo considerarán digno de respeto y reverencia!",
        "¡Felicitaciones por tu aniversario! Deseo que no envejezcas, sino que, por el contrario, te vuelvas cada vez más brillante, atractivo y divertido cada año. ¡Sé la estrella del aniversario en tu propia serie de comedia!",
        "¡Feliz Aniversario! Felicidades por este maravilloso momento en el que puedes decir: '¡Sé cómo era el mundo sin Internet!'",
        "¡Felicitaciones por tu aniversario! ¡Deseo que tengas mucha energía no solo para sobrellevar el sueño diurno, sino también para organizar tu propia banda de rock!",
        "¡Feliz aniversario! Ahora que has llegado a esa edad, oficialmente puedes usar calcetines con sandalias y hablar con las plantas de interior. ¡Es tu privilegio!",
        "¡Felicitaciones por tu aniversario! ¡Deseo que siempre tengas las llaves de la casa, pero a veces olvidas por qué viniste a la habitación para mantener la intriga en tu vida!",
        "¡Feliz aniversario! Que tu pastel de aniversario sea tan grande que tendrás que invitar a todos los vecinos a ayudar a comerlo. ¡Comparte felicidad y calorías!",
        "¡Felicidades por tu aniversario! ¡Te deseo mucha ilusión y optimismo en la vida para que te olvides siempre de lo que es la seriedad y la edad adulta!",
        "¡Feliz aniversario! Felicitaciones por alcanzar la edad en la que puedes llamarte 'vintage' y no 'viejo'. Eres como una costosa y fragante cosecha: ¡cada año mejora!",
        "¡Felicidades por tu aniversario! ¡Deseo que ahorres mucha energía para que puedas participar en todas las competencias del país y ganar en cada una de ellas!",
        "¡Feliz aniversario! Ahora puedes dejar oficialmente de usar la mala memoria como excusa. ¡Solo di que vas a ser una celebridad y no tienes que recordar cosas ordinarias!",
        "¡Felicitaciones por tu aniversario! ¡Deseo que estés tan saludable que tu médico se decepcione cada vez que vengas a la cita y te extrañe!",
        "¡Feliz aniversario! ¡Que tu aniversario sea tan brillante y memorable que lo recordarás incluso a través de anteojos para leer!",
        "¡Feliz aniversario! ¡Te deseo mucha ilusión y coraje para cumplir todos tus sueños, y mucho humor para reírte de ti mismo cuando algo no sale bien!"
    )

    private val german = listOf(
        "Herzlichen Glückwunsch zu deinem Jubiläum! Möge dieser Tag voller Freude, Glück und festlicher Stimmung sein! Ich wünsche dir gute Gesundheit, Liebe und die Erfüllung all deiner Träume!",
        "Alles Gute zum Jubiläum! Mögen jeden Tag Freude, Erfolge und Zufriedenheit dein Leben erfüllen! Möge dir der Erfolg in allem, was du tust, stets begleiten!",
        "Herzlichen Glückwunsch zu diesem wunderbaren Jubiläum! Ich wünsche dir stabile Gesundheit, Glück, Inspiration und neue strahlende Erfahrungen! Möge dein Leben von Freude und Wohlstand erfüllt sein!",
        "Alles Gute zum Jubiläum! Möge dieses Jubiläum einen neuen Anfang markieren, der voller neuer Möglichkeiten und Errungenschaften ist! Ich wünsche dir Glück, Erfolg und Wohlergehen in all deinen Vorhaben!",
        "Herzlichen Glückwunsch zu diesem bedeutenden Jubiläum! Mögen alle Momente deines Lebens von Freude, Gelächter und Wohlbefinden erfüllt sein! Mögen die Jahre nur die hellsten und unvergesslichsten Momente bringen!",
        "Alles Gute zum Jubiläum! Ich wünsche dir, dass dieses Jubiläum eine neue Seite in deinem Leben wird, die voller Glück, Zufriedenheit und Liebe ist! Möge jeder Tag nur Freude und die Erfüllung von Träumen bringen!",
        "Herzlichen Glückwunsch zu diesem wunderschönen Jubiläum! Ich wünsche dir stabile Gesundheit, Langlebigkeit und das Gefühl vollkommener Glückseligkeit! Möge immer Raum für Freude und Liebe in deinem Leben sein!",
        "Alles Gute zum Jubiläum! Möge dieser Tag zu einem neuen Anfang werden, der von lebendigen Ereignissen, Eindrücken und glücklichen Momenten erfüllt ist! Ich wünsche dir Erfolg, Wohlstand und die Erfüllung all deiner Wünsche!",
        "Herzlichen Glückwunsch zu deinem Jubiläum! Ich wünsche dir, dass du deine strahlende Lebensenergie, Freude und Optimismus für viele kommende Jahre bewahrst! Möge deine gesamte Reise von Erfolg und Wohlbefinden gekrönt sein!",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie Ihre lebhafte Lebensenergie, Freude und Optimismus für viele Jahre erhalten! Möge Ihr gesamter Weg mit Erfolg und Wohlergehen gekrönt sein!",
        "Herzlichen Glückwunsch zum Jubiläum! Dieser besondere Tag ist eine großartige Gelegenheit, alle Errungenschaften und überstandenen Herausforderungen zu feiern. Ich wünsche Ihnen weiterhin Erfolg und unvergessliche Momente im Leben.",
        "Alles Gute zum Jubiläum! Möge dieser Tag zu einem Meilenstein in Ihrem Leben werden, der all die großartigen Momente, Erfolge und glücklichen Erinnerungen widerspiegelt.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen Wohlstand, Gesundheit, Inspiration und weiterhin freudige Reisen durchs Leben.",
        "Alles Gute zum Jubiläum! Dies ist ein besonderer Moment, um zurückzublicken und stolz auf Ihren Weg zu sein. Ich wünsche Ihnen Glück, Liebe und neue erstaunliche Abenteuer.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge dieser Tag der Beginn neuer Möglichkeiten sein, in dem Ihre tiefsten Wünsche in Erfüllung gehen und Sie Ihre mutigsten Träume weiterverfolgen.",
        "Alles Gute zum Jubiläum! Ich wünsche Ihnen Weisheit, Glück und Wohlergehen bei jedem Schritt Ihres zukünftigen Weges.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge dieser Tag voller Freude, Gelächter und warmen Erinnerungen an die vergangenen Jahre sein.",
        "Alles Gute zum Jubiläum! Ich wünsche Ihnen weiterhin Erfolg, Wohlstand und die Erfüllung aller Wünsche, die Sie sich setzen.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge jeder folgende Tag in Ihrem Leben mit Freude, Lächeln und angenehmen Überraschungen gefüllt sein.",
        "Alles Gute zum Jubiläum! Ich wünsche Ihnen, dass Sie Ihren jugendlichen Geist bewahren, aktiv bleiben und jeden Moment auf Ihrem Lebensweg genießen.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge dieser Tag ein neuer Anfang voller Möglichkeiten und Erfolge sein.",
        "Alles Gute zum Jubiläum! Ich wünsche Ihnen, dass Sie Ihr Leben weiterhin mit Zuversicht führen, jeden Moment genießen und unermüdlich nach neuen Gipfeln streben.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Freude, Liebe und Glück erfüllt sein. Sie verdienen nur das Beste!",
        "Alles Gute zum Jubiläum! Ich wünsche Ihnen, dass Sie die wertvolle Erfahrung und Weisheit bewahren, die Sie in all den Jahren gesammelt haben, und jeden neuen Tag genießen.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge jeder Augenblick in Ihrem Leben mit lebendigen Farben und unvergesslichen Eindrücken erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen glückliche Momente, Wohlstand und das Erreichen neuer Höhen in Ihrem Leben.",
        "Alles Gute zum Jubiläum! Möge jeder Schritt auf Ihrem weiteren Weg mit Freude, Erfolg und Dankbarkeit für alles, was Sie bereits erreicht haben, erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie den Funken in den Augen und die Jugend im Herzen bewahren, damit jeder Tag mit neuen Möglichkeiten und angenehmen Überraschungen gefüllt ist.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Freude, Lächeln und der Wärme liebevoller Herzen erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen weiterhin, dass Sie Lebensfreude, jugendlichen Geist und alle Segnungen, die das Leben zu bieten hat, bewahren.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Glück, Erfolgen und großen Triumphen erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie den frischen Blick auf das Leben, aufrichtige Freude und tägliche Inspiration bewahren.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Glück, Lachen, freundlicher Unterstützung und Harmonie im Herzen erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie den Glanz der Seele, die Jugend des Geistes bewahren und alle Vorzüge genießen, die das Leben bieten kann.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Glück, Erfolgen und dem Erreichen neuer Höhen erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie den frischen Blick auf das Leben, aufrichtige Freude und tägliche Inspiration bewahren.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Glück, Lachen, freundlicher Unterstützung und Harmonie im Herzen erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie den Glanz der Seele, die Jugend des Geistes bewahren und alle Vorzüge genießen, die das Leben bieten kann.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit lebendiger Freude, anhaltendem Optimismus und der Fähigkeit, die kleinen Dinge zu genießen, die das Leben schön machen, erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge Ihr Weg von Blumen der Freude, Melodien des Glücks und dem Licht des Erfolgs gesäumt sein."
    )
}