package com.sosinvitalii.database.congratulations

object AnniversariesCongratulations {
    fun fetch(language: Language): List<String> {
        return when (language) {
            Language.EN -> english
            Language.IT -> italian
            Language.RU -> russian
            Language.ES -> spanish
            Language.DE -> german
        }
    }

    private val english = listOf(
        "Congratulations on your jubilee! May this day be filled with joy, happiness, and a festive atmosphere! Wishing you good health, love, and the fulfillment of all your dreams!",
        "Happy jubilee! May every day be filled with joy, achievements, and satisfaction with life! May success accompany you in everything you do!",
        "Congratulations on this wonderful jubilee! Wishing you strong health, happiness, inspiration, and new bright experiences! May your life be filled with joy and prosperity!",
        "Happy jubilee! May this jubilee mark a new beginning filled with new opportunities and achievements! Wishing you happiness, luck, and success in all your endeavors!",
        "Congratulations on this significant jubilee! May every moment of your life be filled with joy, laughter, and well-being! May the years bring only the brightest and unforgettable moments!",
        "Happy jubilee! Wishing you that this jubilee becomes a new page in your life, filled with happiness, satisfaction, and love! May every day bring only joy and the fulfillment of dreams!",
        "Congratulations on this beautiful jubilee! Wishing you robust health, longevity, and a feeling of complete happiness! May there always be room for joy and love in your life!",
        "Happy jubilee! May this day become a new beginning filled with vibrant events, impressions, and happy moments! Wishing you success, prosperity, and the fulfillment of all your desires!",
        "Congratulations on your jubilee! Wishing you to maintain a bright life energy, joy, and optimism for many years ahead! May your entire journey be crowned with success and well-being!",
        "Congratulations on your anniversary! I wish you to maintain a bright life energy, joy, and optimism for many years to come! May your entire journey be crowned with success and well-being!",
        "Congratulations on your anniversary! This special day is a great opportunity to celebrate all your achievements and the challenges you've overcome. I wish you further success and unforgettable moments in life.",
        "Happy anniversary! May this day become a milestone in your life, reflecting all the wonderful moments, accomplishments, and happy memories.",
        "Congratulations on your anniversary! I wish you prosperity, good health, inspiration, and further joyful journeys through life.",
        "Happy anniversary! It's a special moment to look back and take pride in your path. I wish you happiness, love, and new amazing adventures.",
        "Congratulations on your anniversary! May this day mark the beginning of new opportunities, the fulfillment of cherished desires, and the continuation of your boldest dreams.",
        "Happy anniversary! I wish you wisdom, happiness, and well-being at every step of your future journey.",
        "Congratulations on your anniversary! May this day be filled with joy, laughter, and warm memories of the years lived.",
        "Happy anniversary! I wish you further success, well-being, and the fulfillment of all the desires you set for yourself.",
        "Congratulations on your anniversary! May every following day of your life be filled with happiness, smiles, and pleasant surprises.",
        "Happy anniversary! May you preserve a youthful spirit, remain active, and enjoy every moment of your life's journey.",
        "Congratulations on your anniversary! May this day become a new beginning full of opportunities and achievements.",
        "Happy anniversary! I wish you to continue leading your life with confidence, savoring each moment, and relentlessly striving for new heights.",
        "Congratulations on your anniversary! May every day of your life be filled with joy, love, and happiness. You deserve the very best!",
        "Happy anniversary! I wish you to preserve the invaluable experience and wisdom you've accumulated over all these years and enjoy each new day.",
        "Congratulations on your anniversary! May every moment of your life be filled with vibrant colors and unforgettable impressions.",
        "Happy anniversary! I wish you happy moments, well-being, and reaching new heights in your life.",
        "Congratulations on your anniversary! May every step of your future path be filled with joy, success, and gratitude for everything you have already achieved.",
        "Happy anniversary! I wish you to keep the fire in your eyes and youth in your heart, so that each day is filled with new opportunities and pleasant surprises.",
        "Congratulations on your anniversary! May every day of your life be filled with joy, smiles, and the warmth of loving hearts.",
        "Happy anniversary! I wish you to continue overcoming life's obstacles with confidence and enjoy the beautiful moments it brings.",
        "Congratulations on your anniversary! May this day be the beginning of a new chapter in your life, filled with health, joy, and the fulfillment of all your dreams.",
        "Happy anniversary! I wish you unwavering optimism, enthusiasm, and the ability to find joy in the little things that make life beautiful.",
        "Congratulations on your anniversary! May every day of your life be filled with laughter, friendly support, and harmony in your heart.",
        "Happy anniversary! I wish you to maintain the brightness of your soul, the youthfulness of your spirit, and enjoy all the blessings life can offer.",
        "Congratulations on your anniversary! May every day of your life be filled with happiness, achievements, and great victories.",
        "Happy anniversary! I wish you to keep a fresh perspective on life, genuine joy, and inspiration every day.",
        "Congratulations on your anniversary! May your path be strewn with flowers of joy, filled with melodies of happiness, and illuminated by the light of success.",
        "Happy anniversary! I wish you to maintain your life energy, brilliant mind, and the ability to see beauty all around you.",
        "Congratulations on your anniversary! May your heart be filled with love, your mind with wisdom, and your life with unforgettable adventures.",
        "Happy anniversary! I wish you to continue sharing your life wisdom, finding joy in the little things, and being a source of inspiration for others.",
        "Happy anniversary! May this day mark the beginning of a new chapter in your life when you share wisdom and tell stories that begin with the words 'When I was young...'",
        "Congratulations on your anniversary! I wish that every new day of your life is as beautiful as your memories of these days.",
        "Happy anniversary! Don't worry about getting older - you're just becoming a classic. And as you know, classics are always in style!",
        "Congratulations on your anniversary! I wish you such an active life that you look younger than your passport, and such a healthy life that your doctor is surprised every time you visit.",
        "Happy anniversary! May each new year of your age bring you not only wisdom but also superpowers to handle any life situation!",
        "Congratulations on your anniversary! I wish you as much energy as a 20-year-old and as much experience as an 80-year-old - and may they never overlap!",
        "Happy anniversary! Congratulations on reaching an age when you start looking at young people and saying, 'Oh, how adorable, but they're so young!'",
        "Congratulations on your anniversary! Now that you've reached this age, you have every right to complain about loud music and explain how everything was better in your time when you were young and downright hilarious!",
        "Happy anniversary! I wish you enough energy to wake up in the morning without coffee, enough money to buy yourself gifts, and enough friends to help you spend them!",
        "Congratulations on your anniversary! Now you have a wonderful reason to officially declare that 'life begins after 50' and start collecting discounts on everything - from movie tickets to museum visits!",
        "Happy anniversary! May your age become your secret weapon - you can show your pension card to grab attention or skip a line, and everyone will consider you worthy of respect and admiration!",
        "Congratulations on your anniversary! I wish you not to grow old, but instead, become brighter, more attractive, and funnier with each passing year - be the jubilee star of your own comedy series!",
        "Happy anniversary! Congratulations on this wonderful moment when you can say officially, 'I know what the world was like before the internet!'",
        "Congratulations on your anniversary! I wish you to have enough energy not only to cope with daytime naps but also to start your own rock band!",
        "Happy anniversary! Now that you've reached this age, you officially have the right to wear socks with sandals and have conversations with houseplants - it's your privilege!",
        "Congratulations on your anniversary! I wish you always have the keys to your home but occasionally forget why you entered a room to keep the intrigue in your life!",
        "Happy anniversary! May your jubilee cake be so big that you'll have to invite all the neighbors to help you eat it - share happiness and calories!",
        "Congratulations on your anniversary! I wish you so much enthusiasm and life optimism that you always forget what seriousness and adulthood mean!",
        "Happy anniversary! Congratulations on reaching an age where you can call yourself 'vintage' instead of 'old.' You're like a precious, aromatic vintage wine - getting better with each year!",
        "Congratulations on your anniversary! I wish you to maintain enough energy to participate in all the competitions at the summer house and win each one of them!",
        "Happy anniversary! Now you can officially stop using a bad memory as an excuse. Just say that you're going to become a celebrity and you don't need to remember ordinary things!",
        "Congratulations on your anniversary! I wish you to be so healthy that your doctor gets disappointed every time you visit and misses you when you're not there!",
        "Happy anniversary! May your jubilee be so bright and memorable that you'll remember it even through reading glasses!",
        "Congratulations on your anniversary! I wish you enough enthusiasm and courage to pursue all your dreams and enough humor to laugh at yourself when things don't go as planned!"
    )

    private val italian = listOf(
        "Congratulazioni per il tuo giubileo! Che questo giorno sia pieno di gioia, felicità e un'atmosfera festosa! Ti auguro buona salute, amore e il raggiungimento di tutti i tuoi sogni!",
        "Buon giubileo! Che ogni giorno sia pieno di gioia, successi e soddisfazione nella vita! Che il successo ti accompagni in tutto ciò che fai!",
        "Congratulazioni per questo meraviglioso giubileo! Ti auguro una salute robusta, felicità, ispirazione e nuove esperienze luminose! Che la tua vita sia piena di gioia e prosperità!",
        "Buon giubileo! Che questo giubileo segni un nuovo inizio pieno di nuove opportunità e successi! Ti auguro felicità, fortuna e successo in tutti i tuoi sforzi!",
        "Congratulazioni per questo significativo giubileo! Che ogni momento della tua vita sia pieno di gioia, risate e benessere! Che gli anni portino solo momenti più luminosi e indimenticabili!",
        "Buon giubileo! Ti auguro che questo giubileo diventi una nuova pagina nella tua vita, piena di felicità, soddisfazione e amore! Che ogni giorno porti solo gioia e il raggiungimento dei sogni!",
        "Congratulazioni per questo bellissimo giubileo! Ti auguro una robusta salute, longevità e la sensazione di completa felicità! Che ci sia sempre spazio per la gioia e l'amore nella tua vita!",
        "Buon giubileo! Che questo giorno diventi un nuovo inizio pieno di eventi vibranti, impressioni e momenti felici! Ti auguro successo, prosperità e il raggiungimento di tutti i tuoi desideri!",
        "Congratulazioni per il tuo giubileo! Ti auguro di mantenere una brillante energia vitale, gioia e ottimismo per molti anni a venire! Che tutto il tuo percorso sia coronato da successo e benessere!",
        "Congratulazioni per il tuo anniversario! Ti auguro di mantenere una brillante energia vitale, gioia e ottimismo per molti anni a venire! Che tutto il tuo cammino sia coronato dal successo e dalla prosperità!",
        "Congratulazioni per il tuo anniversario! Questo giorno speciale è un'ottima opportunità per celebrare tutti i tuoi successi e le sfide affrontate. Ti auguro ulteriori successi e momenti indimenticabili nella vita.",
        "Buon anniversario! Che questo giorno diventi una pietra miliare nella tua vita, riflettendo tutti i meravigliosi momenti, le realizzazioni e i ricordi felici.",
        "Congratulazioni per il tuo anniversario! Ti auguro prosperità, salute, ispirazione e ulteriori viaggi gioiosi nella vita.",
        "Buon anniversario! È un momento speciale in cui puoi guardare indietro e essere orgoglioso del tuo percorso. Ti auguro felicità, amore e nuove avventure straordinarie.",
        "Congratulazioni per il tuo anniversario! Che questo giorno segni l'inizio di nuove opportunità, la realizzazione dei tuoi desideri più cari e la continuazione dei tuoi sogni più audaci.",
        "Buon anniversario! Ti auguro saggezza, felicità e benessere ad ogni passo del tuo futuro cammino.",
        "Congratulazioni per il tuo anniversario! Che questo giorno sia pieno di gioia, risate e caldi ricordi degli anni trascorsi.",
        "Buon anniversario! Ti auguro ulteriori successi, benessere e il conseguimento di tutti i desideri che ti poni.",
        "Congratulazioni per il tuo anniversario! Che ogni giorno successivo della tua vita sia pieno di gioia, sorrisi e piacevoli sorprese.",
        "Buon anniversario! Ti auguro di mantenere lo spirito giovane, rimanere attivo e goderti ogni momento del tuo percorso di vita.",
        "Congratulazioni per il tuo anniversario! Che questo giorno segni un nuovo inizio, pieno di opportunità e realizzazioni.",
        "Buon anniversario! Ti auguro di continuare a condurre la tua vita con fiducia, goderti ogni istante e perseguire incansabilmente nuove vette.",
        "Congratulazioni per il tuo anniversario! Che ogni giorno della tua vita sia pieno di gioia, amore e felicità. Meriti il meglio!",
        "Buon anniversario! Ti auguro di preservare l'esperienza preziosa e la saggezza che hai accumulato in tutti questi anni e goderti ogni nuovo giorno.",
        "Congratulazioni per il tuo anniversario! Che ogni istante della tua vita sia pieno di colori vivaci e impressioni indimenticabili.",
        "Buon anniversario! Ti auguro momenti felici, benessere e il raggiungimento di nuove vette nella tua vita.",
        "Congratulazioni per il tuo anniversario! Che ogni passo del tuo futuro cammino sia pieno di gioia, successi e gratitudine per tutto ciò che hai già raggiunto.",
        "Congratulazioni per il tuo anniversario! Che ogni giorno della tua vita sia riempito di gioia, sorrisi e il calore dei cuori affettuosi.",
        "Buon anniversario! Ti auguro di continuare a superare le sfide della vita con fiducia e goderti i meravigliosi momenti che essa porta.",
        "Congratulazioni per il tuo anniversario! Che questo giorno segni l'inizio di un nuovo capitolo nella tua vita, ricco di salute, felicità e il raggiungimento di tutti i tuoi sogni.",
        "Buon anniversario! Ti auguro un ottimismo costante, entusiasmo e la capacità di gioire delle piccole cose che rendono la vita meravigliosa.",
        "Congratulazioni per il tuo anniversario! Che ogni giorno della tua vita sia riempito di risate, sostegno amichevole e armonia nel cuore.",
        "Buon anniversario! Ti auguro di preservare la vivacità dell'anima, la giovinezza dello spirito e goderti tutti i beni che la vita può offrirti.",
        "Congratulazioni per il tuo anniversario! Che ogni giorno della tua vita sia pieno di felicità, realizzazioni e grandi vittorie.",
        "Buon anniversario! Ti auguro di mantenere uno sguardo fresco sulla vita, gioia sincera e ispirazione ogni giorno.",
        "Congratulazioni per il tuo anniversario! Che il tuo cammino sia costellato di fiori di gioia, melodie di felicità e illuminato dalla luce del successo.",
        "Auguri per il tuo anniversario! Ti auguro di conservare la tua energia vitale, una mente brillante e la capacità di vedere la bellezza intorno a te.",
        "Auguri per il tuo anniversario! Che il tuo cuore sia pieno d'amore, la tua mente di saggezza e la tua vita di avventure indimenticabili.",
        "Auguri per il tuo anniversario! Ti auguro di continuare a condividere la tua saggezza di vita, gioire delle piccole gioie e essere una fonte di ispirazione per gli altri.",
        "Auguri per il tuo anniversario! Che questo giorno segni l'inizio di un nuovo capitolo della tua vita, in cui condividerai saggezza e racconterai storie che iniziano con le parole: 'Quando ero giovane...'",
        "Auguri per il tuo anniversario! Ti auguro che ogni nuovo giorno della tua vita sia bello come i ricordi di questi giorni.",
        "Auguri per il tuo anniversario! Non preoccuparti di invecchiare, stai solo diventando un classico. E come si sa, il classico è sempre di moda!",
        "Auguri per il tuo anniversario! Ti auguro una vita così attiva che sembrerai più giovane della tua età anagrafica e una vita così sana che il tuo medico si stupirà ogni volta che vai a una visita.",
        "Auguri per il tuo anniversario! Che ogni nuovo anno della tua età ti porti non solo saggezza, ma anche superpoteri per affrontare qualsiasi situazione della vita!",
        "Auguri per il tuo anniversario! Ti auguro di avere tanta energia quanto un ventenne e tanta esperienza quanto un ottantenne, e che non si incrocino mai!",
        "Auguri per il tuo anniversario! Congratulazioni per aver raggiunto un'età in cui guardi i giovani e dici: 'Oh, che cari ragazzi, ma quanto sono giovani!'",
        "Auguri per il tuo anniversario! Ora che hai raggiunto questa età, hai il diritto di lamentarti della musica alta e spiegare che tutto era migliore ai tuoi tempi, quando eri giovane e immediatamente divertente!",
        "Auguri per il tuo anniversario! Ti auguro abbastanza energia per svegliarti al mattino senza l'aiuto del caffè, abbastanza soldi per comprarti regali e abbastanza amici per aiutarti a spenderli!",
        "Auguri per il tuo anniversario! Ora hai un'ottima scusa per dichiarare ufficialmente che 'la vita inizia dopo i 50' e iniziare a ottenere sconti su tutto, dai biglietti del cinema alle visite ai musei!",
        "Auguri per il tuo anniversario! Che la tua età diventi la tua arma segreta: puoi mostrare la tua tessera di pensionato per attirare l'attenzione o saltare la fila, e tutti ti considereranno degno di rispetto e onore!",
        "Auguri per il tuo anniversario! Ti auguro di non invecchiare, ma diventare sempre più luminoso, attraente e divertente ogni anno - sii la star del tuo proprio show comico!",
        "Auguri per il tuo anniversario! Congratulazioni per questo meraviglioso momento in cuipuoi dire ufficialmente: 'So com'era il mondo senza internet!'",
        "Auguri per il tuo anniversario! Ti auguro di avere così tanta energia da non solo gestire un sonnellino pomeridiano, ma anche formare la tua band rock!",
        "Auguri per il tuo anniversario! Ora che hai raggiunto questa età, hai ufficialmente il diritto di indossare calze con i sandali e parlare con le piante di casa - è un tuo privilegio!",
        "Auguri per il tuo anniversario! Ti auguro di avere sempre le chiavi di casa, ma di dimenticare occasionalmente perché sei entrato in una stanza, per mantenere il mistero nella tua vita!",
        "Auguri per il tuo anniversario! Che la tua torta di compleanno sia così grande da dover invitare tutti i vicini per aiutarti a mangiarla - condividi la felicità e le calorie!",
        "Auguri per il tuo anniversario! Ti auguro tanto entusiasmo e ottimismo per la vita, al punto da dimenticare sempre cosa significhi essere seri e adulti!",
        "Auguri per il tuo anniversario! Congratulazioni per aver raggiunto un'età in cui puoi definirti 'vintage' anziché 'vecchio'. Sei come un pregiato vino invecchiato, migliore di anno in anno!",
        "Auguri per il tuo anniversario! Ti auguro di conservare così tanta energia da poter partecipare a tutte le gare al tuo giardino e vincerne tutte!",
        "Auguri per il tuo anniversario! Ora puoi ufficialmente rinunciare all'uso di una memoria cattiva come scusa. Basta dire che stai per diventare una celebrità e non hai bisogno di ricordare le cose comuni!",
        "Auguri per il tuo anniversario! Ti auguro di essere così sano che il tuo medico sarà deluso ogni volta che vai per una visita e sentirà la tua mancanza!",
        "Auguri per il tuo anniversario! Che il tuo anniversario sia così vivido e memorabile che lo ricorderai anche attraverso gli occhiali da lettura!",
        "Auguri per il tuo anniversario! Ti auguro tanto entusiasmo e coraggio per realizzare tutti i tuoi sogni e tanto senso dell'umorismo da ridere di te stesso quando le cose non vanno come previsto!"
    )

    private val russian = listOf(
        "Поздравляю с юбилеем! Пусть этот день будет наполнен радостью, счастьем и праздничным настроением! Желаю здоровья, любви и исполнения всех мечтаний!",
        "С юбилеем! Желаю, чтобы каждый день был наполнен радостью, достижениями и удовлетворением от жизни! Пусть успех сопутствует во всем, что вы делаете!",
        "Поздравляю с замечательным юбилеем! Желаю вам крепкого здоровья, счастья, вдохновения и новых ярких впечатлений! Пусть ваша жизнь будет полна радости и благополучия!",
        "С юбилеем! Пусть этот юбилей станет новым началом, наполненным новыми возможностями и достижениями! Желаю счастья, удачи и благополучия во всех делах!",
        "Поздравляю с знаменательным юбилеем! Желаю, чтобы каждый момент вашей жизни был наполнен радостью, смехом и благополучием! Пусть годы приносят только самые яркие и незабываемые моменты!",
        "С юбилеем! Желаю, чтобы этот юбилей стал новой страницей в вашей жизни, полной счастья, удовлетворения и любви! Пусть каждый день приносит только радость и исполнение мечтаний!",
        "Поздравляю с прекрасным юбилеем! Желаю крепкого здоровья, долголетия и ощущения полного счастья! Пусть в вашей жизни всегда будет место для радости и любви!",
        "С юбилеем! Пусть этот день станет новым началом, наполненным яркими событиями, впечатлениями и счастливыми моментами! Желаю успехов, процветания и сбывания всех желаний!",
        "Поздравляю с юбилеем! Желаю вам сохранить яркую жизненную энергию, радость и оптимизм на долгие годы вперед! Пусть весь ваш путь будет увенчан успехом и благополучием!",
        "Поздравляю с юбилеем! Этот особый день — отличная возможность отметить все достижения и пройденные испытания. Желаю вам дальнейших успехов и незабываемых моментов в жизни",
        "С юбилеем! Пусть этот день станет вехой в вашей жизни, отражая все великолепные моменты, достижения и счастливые воспоминания",
        "Поздравляю с юбилеем! Желаю вам благополучия, здоровья, вдохновения и дальнейших радостных путешествий по жизни",
        "С юбилеем! Это особый момент, когда можно оглянуться назад и гордиться своим пути. Желаю вам счастья, любви и новых удивительных приключений",
        "Поздравляю с юбилеем! Пусть этот день станет началом новых возможностей, исполнения заветных желаний и продолжения ваших самых смелых мечтаний",
        "С юбилеем! Желаю вам мудрости, счастья и благополучия на каждом шагу вашего дальнейшего пути",
        "Поздравляю с юбилеем! Пусть этот день будет наполнен радостью, смехом и теплыми воспоминаниями о прожитых годах",
        "С юбилеем! Желаю вам дальнейших успехов, благополучия и исполнения всех желаний, которые вы себе задаете",
        "Поздравляю с юбилеем! Пусть каждый следующий день вашей жизни будет наполнен радостью, улыбками и приятными сюрпризами",
        "С юбилеем! Желаю вам сохранить молодой дух, оставаться активными и наслаждаться каждым моментом вашего жизненного пути",
        "Поздравляю с юбилеем! Пусть этот день станет новым началом, полным возможностей и достижений",
        "С юбилеем! Желаю вам продолжать вести свою жизнь с уверенностью, наслаждаться каждым мгновением и неутомимо стремиться к новым вершинам",
        "Поздравляю с юбилеем! Пусть каждый день вашей жизни будет наполнен радостью, любовью и счастьем. Вы заслужили самое лучшее!",
        "С юбилеем! Желаю вам сохранять бесценный опыт и мудрость, которые накопили за все эти годы, и наслаждаться каждым новым днем",
        "Поздравляю с юбилеем! Пусть каждый мгновенье вашей жизни будет наполнено яркими красками и незабываемыми впечатлениями",
        "С юбилеем! Желаю вам счастливых мгновений, благополучия и достижения новых вершин в вашей жизни",
        "Поздравляю с юбилеем! Пусть каждый шаг вашего дальнейшего пути будет наполнен радостью, успехами и благодарностью за все, что вы уже достигли",
        "С юбилеем! Желаю вам сохранять огонь в глазах и молодость в сердце, чтобы каждый день был наполнен новыми возможностями и приятными сюрпризами",
        "Поздравляю с юбилеем! Пусть каждый день вашей жизни будет наполнен радостью, улыбками и теплом любящих сердец",
        "С юбилеем! Желаю вам продолжать преодолевать жизненные преграды с уверенностью и наслаждаться прекрасными моментами, которые она приносит",
        "Поздравляю с юбилеем! Пусть этот день будет началом новой главы в вашей жизни, наполненной здоровьем, радостью и исполнением всех мечт",
        "С юбилеем! Желаю вам неизменного оптимизма, энтузиазма и способности радоваться мелочам, которые делают жизнь прекрасной",
        "Поздравляю с юбилеем! Пусть каждый день вашей жизни будет наполнен смехом, дружеской поддержкой и гармонией в сердце",
        "С юбилеем! Желаю вам сохранять яркость души, молодость духа и наслаждаться всеми благами, которые жизнь может предложить",
        "Поздравляю с юбилеем! Пусть каждый день вашей жизни будет наполнен счастьем, достижениями и великими победами",
        "С юбилеем! Желаю вам сохранять свежий взгляд на жизнь, искреннюю радость и вдохновение каждый день",
        "Поздравляю с юбилеем! Пусть ваш путь будет усыпан цветами радости, исполнен мелодий счастья и озарен светом успеха",
        "С юбилеем! Желаю вам сохранять свою жизненную энергию, блестящий ум и способность видеть прекрасное вокруг себя",
        "Поздравляю с юбилеем! Пусть ваше сердце будет наполнено любовью, ваш ум - мудростью, а ваша жизнь - незабываемыми приключениями",
        "С юбилеем! Желаю вам продолжать делиться своей жизненной мудростью, радоваться малым радостям и быть источником вдохновения для других",
        "С юбилеем! Пусть этот день станет началом нового раздела в вашей жизни, когда вы будете делиться мудростью и рассказывать истории, которые начинаются со слов: (Когда я был молодым...)",
        "Поздравляю с юбилеем! Желаю вам, чтобы каждый новый день вашей жизни был так же прекрасен, как ваша память об этих днях",
        "С юбилеем! Не волнуйтесь, что вы стареете - вы просто становитесь классиком. И, как известно, классика всегда в тренде!",
        "Поздравляю с юбилеем! Желаю вам такую активную жизнь, что вы будете выглядеть моложе своего паспорта, и такую здоровую жизнь, что ваш врач будет удивлен каждый раз, когда вы приходите на прием",
        "С юбилеем! Пусть каждый новый год вашего возраста приносит вам не только мудрость, но и суперспособности, чтобы справиться с любыми жизненными ситуациями!",
        "Поздравляю с юбилеем! Желаю вам столько энергии, сколько у 20-летнего, и столько опыта, сколько у 80-летнего - и пусть они никогда не пересекаются!",
        "С юбилеем! Поздравляю с достижением такого возраста, когда вы начинаете смотреть на молодежь и говорить: 'Ах, какие милые детишки, но какие же они молоды!'",
        "Поздравляю с юбилеем! Теперь, когда вы достигли такого возраста, вы имеете полное право жаловаться на громкую музыку и объяснять, что все было лучше в ваше время, когда вы были молодыми и непосредственно смешными!",
        "С юбилеем! Желаю вам столько энергии, чтобы просыпаться утром без помощи кофе, столько денег, чтобы покупать подарки себе и столько друзей, чтобы помогать вам их потратить!",
        "Поздравляю с юбилеем! Теперь у вас есть прекрасный повод заявить официально, что 'жизнь начинается после 50', и начать собирать скидку на все - начиная от билетов в кино до посещения музеев!",
        "С юбилеем! Пусть ваш возраст станет вашим секретным оружием - вы можете показывать свою пенсионную карточку, чтобы получить внимание или пропустить очередь, и каждый будет считать вас достойным уважения и почтения!",
        "Поздравляю с юбилеем! Желаю вам не стареть, а наоборот, становиться все более и более ярким, привлекательным и смешным с каждым годом - будьте юбилейной звездой в своей собственной комедийной серии!",
        "С юбилеем! Поздравляю с этим замечательным моментом, когда вы можете сказать: 'Я знаю, каким был мир без интернета!'",
        "Поздравляю с юбилеем! Желаю вам иметь столько энергии, чтобы не только справиться с дневным сном, но и организовать собственную рок-группу!",
        "С юбилеем! Теперь, когда вы достигли этого возраста, вы официально имеете право носить носки в сандалиях и разговаривать с домашними растениями - это ваша привилегия!",
        "Поздравляю с юбилеем! Желаю вам всегда иметь ключи от дома, но иногда забывать, зачем вы пришли в комнату, чтобы поддерживать интригу в вашей жизни!",
        "С юбилеем! Пусть ваш юбилейный торт будет такой большой, что вам придется пригласить всех соседей, чтобы помочь его съесть - делитесь счастьем и калориями!",
        "Поздравляю с юбилеем! Желаю вам столько энтузиазма и жизненного оптимизма, чтобы вы всегда забывали, что такое серьезность и взрослость!",
        "С юбилеем! Поздравляю с достижением возраста, когда вы можете называть себя 'винтажным', а не 'старым'. Вы как дорогой ароматный винтаж — с каждым годом только лучше!",
        "Поздравляю с юбилеем! Желаю вам сохранять столько энергии, чтобы вы могли поучаствовать во всех конкурсах на даче и выигрывать в каждом из них!",
        "С юбилеем! Теперь вы можете официально отказаться от использования плохой памяти в качестве оправдания. Просто говорите, что вы собираетесь стать знаменитостью и вам не нужно помнить обычные вещи!",
        "Поздравляю с юбилеем! Желаю вам быть таким здоровым, что ваш врач будет разочаровываться каждый раз, когда вы приходите на прием, и скучать без вас!",
        "С юбилеем! Пусть ваш юбилей будет столь ярким и запоминающимся, что вы будете вспоминать его даже через очки для чтения!",
        "Поздравляю с юбилеем! Желаю вам столько энтузиазма и смелости, чтобы исполнять все свои мечты, и столько юмора, чтобы смеяться над собой, когда что-то не получается!"
    )

    private val spanish = listOf(
        "¡Felicitaciones por tu jubileo! ¡Que este día esté lleno de alegría, felicidad y un ambiente festivo! Te deseo buena salud, amor y el cumplimiento de todos tus sueños!",
        "¡Feliz jubileo! ¡Que cada día esté lleno de alegría, logros y satisfacción con la vida! ¡Que el éxito te acompañe en todo lo que hagas!",
        "¡Felicitaciones por este maravilloso jubileo! ¡Te deseo una salud fuerte, felicidad, inspiración y nuevas experiencias brillantes! ¡Que tu vida esté llena de alegría y prosperidad!",
        "¡Feliz jubileo! ¡Que este jubileo marque un nuevo comienzo lleno de nuevas oportunidades y logros! ¡Te deseo felicidad, suerte y éxito en todos tus emprendimientos!",
        "¡Felicitaciones por este jubileo significativo! ¡Que cada momento de tu vida esté lleno de alegría, risas y bienestar! ¡Que los años solo traigan los momentos más brillantes e inolvidables!",
        "¡Feliz jubileo! ¡Deseo que este jubileo se convierta en una nueva página en tu vida, llena de felicidad, satisfacción y amor! ¡Que cada día traiga solo alegría y el cumplimiento de los sueños!",
        "¡Felicitaciones por este hermoso jubileo! ¡Te deseo salud sólida, longevidad y la sensación de una felicidad completa! ¡Que siempre haya espacio para la alegría y el amor en tu vida!",
        "¡Feliz jubileo! ¡Que este día se convierta en un nuevo comienzo lleno de eventos vibrantes, impresiones y momentos felices! ¡Te deseo éxito, prosperidad y el cumplimiento de todos tus deseos!",
        "¡Felicitaciones por tu jubileo! ¡Te deseo mantener una brillante energía vital, alegría y optimismo durante muchos años por venir! ¡Que todo tu camino esté coronado de éxito y bienestar!",
        "¡Felicitaciones por su aniversario! ¡Deseo que mantenga una brillante vitalidad, alegría y optimismo durante muchos años más! ¡Que todo su viaje se vea coronado por el éxito y la prosperidad!",
        "¡Felicitaciones por su aniversario! Este día especial es una gran oportunidad para celebrar todos los logros y desafíos que ha superado. Le deseo éxito continuo y momentos inolvidables en su vida",
        "¡Feliz Aniversario! Que este día sea un hito en tu vida, reflejando todos los grandes momentos, logros y felices recuerdos",
        "¡Felicitaciones por su aniversario! Le deseo bienestar, salud, inspiración y más viajes felices por la vida",
        "¡Feliz aniversario! Este es un momento especial para mirar hacia atrás y estar orgulloso de tu camino. Te deseo felicidad, amor y nuevas aventuras increíbles",
        "¡Felicitaciones por tu aniversario! Que este día sea el comienzo de nuevas oportunidades, el cumplimiento de tus preciados deseos y la continuación de tus sueños más salvajes",
        "¡Feliz aniversario! Te deseo sabiduría, felicidad y prosperidad en cada paso de tu camino",
        "¡Felicitaciones por tu aniversario! Que este día esté lleno de alegría, risas y cálidos recuerdos de los años pasados",
        "¡Feliz aniversario! Te deseo éxito continuo, bienestar y el cumplimiento de todos los deseos que te pidas",
        "¡Felicitaciones por tu aniversario! Que cada próximo día de tu vida esté lleno de alegría, sonrisas y agradables sorpresas",
        "¡Feliz Aniversario! Deseo que mantengas un espíritu joven, te mantengas activo y disfrutes cada momento del viaje de tu vida",
        "¡Felicidades por tu aniversario! Que este día sea un nuevo comienzo, lleno de oportunidades y logros",
        "¡Feliz aniversario! Deseo que continúes viviendo tu vida con confianza, disfrutes cada momento y te esfuerces incansablemente por alcanzar nuevas alturas",
        "¡Felicidades por tu aniversario! Que todos los días de tu vida estén llenos de alegría, amor y felicidad. ¡Te mereces lo mejor!",
        "¡Feliz aniversario! Deseo que conserves la invaluable experiencia y sabiduría que has acumulado a lo largo de los años, y disfrutes cada nuevo día",
        "¡Felicitaciones por tu aniversario! Que cada momento de tu vida esté lleno de colores brillantes e impresiones inolvidables",
        "¡Feliz aniversario! Te deseo momentos felices, prosperidad y el logro de nuevas alturas en tu vida",
        "¡Felicitaciones por tu aniversario! Que cada paso de tu camino esté lleno de alegría, éxito y gratitud por todo lo que ya has logrado",
        "¡Feliz aniversario! Deseo que mantengas fuego en tus ojos y juventud en tu corazón para que cada día esté lleno de nuevas oportunidades y gratas sorpresas",
        "¡Felicitaciones por tu aniversario! Que todos los días de tu vida estén llenos de alegría, sonrisas y calidez de corazones amorosos",
        "¡Feliz aniversario! Que sigas superando los obstáculos de la vida con confianza y disfrutes de los maravillosos momentos que trae",
        "¡Felicidades por tu aniversario! Que este día sea el comienzo de un nuevo capítulo en tu vida lleno de salud, alegría y el cumplimiento de todos los sueños",
        "¡Feliz Aniversario! Les deseo optimismo continuo, entusiasmo y la capacidad de disfrutar de las pequeñas cosas que hacen que la vida sea hermosa",
        "¡Felicitaciones por tu aniversario! Que todos los días de tu vida estén llenos de risas, apoyo amistoso y armonía en tu corazón",
        "¡Feliz Aniversario! Deseo que conserves el brillo del alma, la juventud del espíritu y disfrutes de todos los beneficios que la vida te ofrece",
        "¡Felicidades por tu aniversario! Que cada día de tu vida esté lleno de felicidad, logros y grandes victorias",
        "¡Feliz aniversario! Deseo que mantengas una nueva perspectiva de la vida, alegría sincera e inspiración todos los días",
        "¡Felicidades por tu aniversario! Que tu camino se llene de flores de alegría, lleno de melodías de felicidad e iluminado por la luz del éxito",
        "¡Feliz aniversario! Deseo que conserves tu vitalidad, mente brillante y capacidad para ver la belleza que te rodea",
        "¡Felicidades por tu aniversario! Que tu corazón se llene de amor, tu mente de sabiduría y tu vida de aventuras inolvidables",
        "¡Feliz aniversario! Deseo que sigas compartiendo tu sabiduría de vida, disfrutes de las pequeñas alegrías y seas una inspiración para los demás",
        "¡Feliz Aniversario! Que este día sea el comienzo de un nuevo capítulo en tu vida mientras compartes sabiduría y cuentas historias que comienzan con: (Cuando era joven...)",
        "¡Felicidades por tu aniversario! Te deseo que cada nuevo día de tu vida sea tan hermoso como tu recuerdo de estos días",
        "¡Feliz aniversario! No te preocupes por envejecer, te estás convirtiendo en un clásico. Y, como sabes, ¡lo clásico siempre está de moda!",
        "¡Felicidades por tu aniversario! Te deseo una vida tan activa que luzcas más joven que tu pasaporte, y una vida tan saludable que tu médico se sorprenda cada vez que vengas a la cita",
        "¡Feliz aniversario! ¡Que cada nuevo año de tu edad te traiga no solo sabiduría, sino también superpoderes para hacer frente a cualquier situación de la vida!",
        "¡Felicitaciones por tu aniversario! Te deseo tanta energía como a los 20 años y tanta experiencia como a los 80, ¡y que nunca se crucen!",
        "¡Feliz aniversario! Felicitaciones por llegar a la edad en la que empiezas a mirar a los jóvenes y decir: '¡Ay, qué lindos niños, pero qué jóvenes son!'",
        "¡Felicidades por tu aniversario! ¡Ahora que has llegado a esta edad, tienes todo el derecho de quejarte de la música alta y explicar que todo era mejor en tu época cuando eras joven y directamente gracioso!",
        "¡Feliz aniversario! ¡Te deseo tanta energía para despertarte por la mañana sin la ayuda del café, tanto dinero para comprar regalos para ti y tantos amigos para ayudarte a gastarlos!",
        "¡Feliz aniversario! ¡Ahora tienes una gran excusa para declarar oficialmente que 'la vida comienza después de los 50' y comenzar a acumular descuentos en todo, desde entradas para el cine hasta visitas a museos!",
        "¡Feliz aniversario! Deje que su edad sea su arma secreta: puede mostrar su tarjeta de jubilación para llamar la atención o saltarse la fila, ¡y todos lo considerarán digno de respeto y reverencia!",
        "¡Felicitaciones por tu aniversario! Deseo que no envejezcas, sino que, por el contrario, te vuelvas cada vez más brillante, atractivo y divertido cada año. ¡Sé la estrella del aniversario en tu propia serie de comedia!",
        "¡Feliz Aniversario! Felicidades por este maravilloso momento en el que puedes decir: '¡Sé cómo era el mundo sin Internet!'",
        "¡Felicitaciones por tu aniversario! ¡Deseo que tengas mucha energía no solo para sobrellevar el sueño diurno, sino también para organizar tu propia banda de rock!",
        "¡Feliz aniversario! Ahora que has llegado a esa edad, oficialmente puedes usar calcetines con sandalias y hablar con las plantas de interior. ¡Es tu privilegio!",
        "¡Felicitaciones por tu aniversario! ¡Deseo que siempre tengas las llaves de la casa, pero a veces olvidas por qué viniste a la habitación para mantener la intriga en tu vida!",
        "¡Feliz aniversario! Que tu pastel de aniversario sea tan grande que tendrás que invitar a todos los vecinos a ayudar a comerlo. ¡Comparte felicidad y calorías!",
        "¡Felicidades por tu aniversario! ¡Te deseo mucha ilusión y optimismo en la vida para que te olvides siempre de lo que es la seriedad y la edad adulta!",
        "¡Feliz aniversario! Felicitaciones por alcanzar la edad en la que puedes llamarte 'vintage' y no 'viejo'. Eres como una costosa y fragante cosecha: ¡cada año mejora!",
        "¡Felicidades por tu aniversario! ¡Deseo que ahorres mucha energía para que puedas participar en todas las competencias del país y ganar en cada una de ellas!",
        "¡Feliz aniversario! Ahora puedes dejar oficialmente de usar la mala memoria como excusa. ¡Solo di que vas a ser una celebridad y no tienes que recordar cosas ordinarias!",
        "¡Felicitaciones por tu aniversario! ¡Deseo que estés tan saludable que tu médico se decepcione cada vez que vengas a la cita y te extrañe!",
        "¡Feliz aniversario! ¡Que tu aniversario sea tan brillante y memorable que lo recordarás incluso a través de anteojos para leer!",
        "¡Feliz aniversario! ¡Te deseo mucha ilusión y coraje para cumplir todos tus sueños, y mucho humor para reírte de ti mismo cuando algo no sale bien!"
    )

    private val german = listOf(
        "Herzlichen Glückwunsch zu deinem Jubiläum! Möge dieser Tag voller Freude, Glück und festlicher Stimmung sein! Ich wünsche dir gute Gesundheit, Liebe und die Erfüllung all deiner Träume!",
        "Alles Gute zum Jubiläum! Mögen jeden Tag Freude, Erfolge und Zufriedenheit dein Leben erfüllen! Möge dir der Erfolg in allem, was du tust, stets begleiten!",
        "Herzlichen Glückwunsch zu diesem wunderbaren Jubiläum! Ich wünsche dir stabile Gesundheit, Glück, Inspiration und neue strahlende Erfahrungen! Möge dein Leben von Freude und Wohlstand erfüllt sein!",
        "Alles Gute zum Jubiläum! Möge dieses Jubiläum einen neuen Anfang markieren, der voller neuer Möglichkeiten und Errungenschaften ist! Ich wünsche dir Glück, Erfolg und Wohlergehen in all deinen Vorhaben!",
        "Herzlichen Glückwunsch zu diesem bedeutenden Jubiläum! Mögen alle Momente deines Lebens von Freude, Gelächter und Wohlbefinden erfüllt sein! Mögen die Jahre nur die hellsten und unvergesslichsten Momente bringen!",
        "Alles Gute zum Jubiläum! Ich wünsche dir, dass dieses Jubiläum eine neue Seite in deinem Leben wird, die voller Glück, Zufriedenheit und Liebe ist! Möge jeder Tag nur Freude und die Erfüllung von Träumen bringen!",
        "Herzlichen Glückwunsch zu diesem wunderschönen Jubiläum! Ich wünsche dir stabile Gesundheit, Langlebigkeit und das Gefühl vollkommener Glückseligkeit! Möge immer Raum für Freude und Liebe in deinem Leben sein!",
        "Alles Gute zum Jubiläum! Möge dieser Tag zu einem neuen Anfang werden, der von lebendigen Ereignissen, Eindrücken und glücklichen Momenten erfüllt ist! Ich wünsche dir Erfolg, Wohlstand und die Erfüllung all deiner Wünsche!",
        "Herzlichen Glückwunsch zu deinem Jubiläum! Ich wünsche dir, dass du deine strahlende Lebensenergie, Freude und Optimismus für viele kommende Jahre bewahrst! Möge deine gesamte Reise von Erfolg und Wohlbefinden gekrönt sein!",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie Ihre lebhafte Lebensenergie, Freude und Optimismus für viele Jahre erhalten! Möge Ihr gesamter Weg mit Erfolg und Wohlergehen gekrönt sein!",
        "Herzlichen Glückwunsch zum Jubiläum! Dieser besondere Tag ist eine großartige Gelegenheit, alle Errungenschaften und überstandenen Herausforderungen zu feiern. Ich wünsche Ihnen weiterhin Erfolg und unvergessliche Momente im Leben.",
        "Alles Gute zum Jubiläum! Möge dieser Tag zu einem Meilenstein in Ihrem Leben werden, der all die großartigen Momente, Erfolge und glücklichen Erinnerungen widerspiegelt.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen Wohlstand, Gesundheit, Inspiration und weiterhin freudige Reisen durchs Leben.",
        "Alles Gute zum Jubiläum! Dies ist ein besonderer Moment, um zurückzublicken und stolz auf Ihren Weg zu sein. Ich wünsche Ihnen Glück, Liebe und neue erstaunliche Abenteuer.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge dieser Tag der Beginn neuer Möglichkeiten sein, in dem Ihre tiefsten Wünsche in Erfüllung gehen und Sie Ihre mutigsten Träume weiterverfolgen.",
        "Alles Gute zum Jubiläum! Ich wünsche Ihnen Weisheit, Glück und Wohlergehen bei jedem Schritt Ihres zukünftigen Weges.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge dieser Tag voller Freude, Gelächter und warmen Erinnerungen an die vergangenen Jahre sein.",
        "Alles Gute zum Jubiläum! Ich wünsche Ihnen weiterhin Erfolg, Wohlstand und die Erfüllung aller Wünsche, die Sie sich setzen.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge jeder folgende Tag in Ihrem Leben mit Freude, Lächeln und angenehmen Überraschungen gefüllt sein.",
        "Alles Gute zum Jubiläum! Ich wünsche Ihnen, dass Sie Ihren jugendlichen Geist bewahren, aktiv bleiben und jeden Moment auf Ihrem Lebensweg genießen.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge dieser Tag ein neuer Anfang voller Möglichkeiten und Erfolge sein.",
        "Alles Gute zum Jubiläum! Ich wünsche Ihnen, dass Sie Ihr Leben weiterhin mit Zuversicht führen, jeden Moment genießen und unermüdlich nach neuen Gipfeln streben.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Freude, Liebe und Glück erfüllt sein. Sie verdienen nur das Beste!",
        "Alles Gute zum Jubiläum! Ich wünsche Ihnen, dass Sie die wertvolle Erfahrung und Weisheit bewahren, die Sie in all den Jahren gesammelt haben, und jeden neuen Tag genießen.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge jeder Augenblick in Ihrem Leben mit lebendigen Farben und unvergesslichen Eindrücken erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen glückliche Momente, Wohlstand und das Erreichen neuer Höhen in Ihrem Leben.",
        "Alles Gute zum Jubiläum! Möge jeder Schritt auf Ihrem weiteren Weg mit Freude, Erfolg und Dankbarkeit für alles, was Sie bereits erreicht haben, erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie den Funken in den Augen und die Jugend im Herzen bewahren, damit jeder Tag mit neuen Möglichkeiten und angenehmen Überraschungen gefüllt ist.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Freude, Lächeln und der Wärme liebevoller Herzen erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen weiterhin, dass Sie Lebensfreude, jugendlichen Geist und alle Segnungen, die das Leben zu bieten hat, bewahren.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Glück, Erfolgen und großen Triumphen erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie den frischen Blick auf das Leben, aufrichtige Freude und tägliche Inspiration bewahren.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Glück, Lachen, freundlicher Unterstützung und Harmonie im Herzen erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie den Glanz der Seele, die Jugend des Geistes bewahren und alle Vorzüge genießen, die das Leben bieten kann.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Glück, Erfolgen und dem Erreichen neuer Höhen erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie den frischen Blick auf das Leben, aufrichtige Freude und tägliche Inspiration bewahren.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit Glück, Lachen, freundlicher Unterstützung und Harmonie im Herzen erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Ich wünsche Ihnen, dass Sie den Glanz der Seele, die Jugend des Geistes bewahren und alle Vorzüge genießen, die das Leben bieten kann.",
        "Alles Gute zum Jubiläum! Möge jeder Tag in Ihrem Leben mit lebendiger Freude, anhaltendem Optimismus und der Fähigkeit, die kleinen Dinge zu genießen, die das Leben schön machen, erfüllt sein.",
        "Herzlichen Glückwunsch zum Jubiläum! Möge Ihr Weg von Blumen der Freude, Melodien des Glücks und dem Licht des Erfolgs gesäumt sein."
    )
}