package com.sosinvitalii.database.congratulations

/// Поздравление с днем рождения
object BirthdayCongratulations {
    fun fetch(language: Language): List<String> {
        return when (language) {
            Language.EN -> english
            Language.IT -> italian
            Language.RU -> russian
            Language.ES -> spanish
            Language.DE -> german
        }
    }

    private val english = listOf(
        "May your life be full of amazing moments, wonderful people, and bright events! Happy Birthday!",
        "May every day of your life be filled with joy and happiness, and may your eyes sparkle with pleasure! Happy Birthday!",
        "I wish for every new day to be better than the previous one, and every coming year to be happier than the previous one! May all your dreams come true! Happy Birthday!",
        "May every day of your life be a wonderful gift, full of amazing discoveries and joyful moments! Happy Birthday!",
        "I wish you immense happiness, well-being, love, health, prosperity, and everything else you could wish for. Happy Birthday!",
        "Today is your special day, so let it be filled with smiles, happiness, and everything you love. Happy Birthday!",
        "May your day be as bright and special as you are. Happy Birthday!",
        "Today is your day! I wish you a festive mood, warmth, love, and smiles from your loved ones. Happy Birthday!",
        "May your day be filled with love, joy, and smiles! Happy Birthday!",
        "Happy Birthday! I wish you happiness, health, and all the best in the world. You deserve it!",
        "Happy birthday! I wish you happiness, health, and all the best in the world. You deserve it!",
        "May the stars in the sky shine especially bright on your day, filling your life with joy, happiness, and love.",
        "Today you have become a year wiser, may each new day be full of adventures and discoveries.",
        "Your birthday is just another reminder of how special you are. Happy birthday!",
        "Happy birthday! May every day be unique, and every minute unforgettable.",
        "I wish you love without boundaries, happiness without limits, and luck without exceptions. Happy birthday!",
        "May this day be filled with smiles, warmth, and pleasant surprises, and the year ahead is full of promises of new opportunities. Happy birthday!",
        "Today is your day, and nothing should hinder you from fully enjoying it. Happy birthday, and may all your dreams come true!",
        "Dream big and never be afraid to pursue your dreams, may they become a reality. Happy birthday!",
        "May your day be as radiant as your smile and as joyful as you are. Happy birthday!",
        "I wish you a day full of smiles, happiness, and fun. Happy birthday!",
        "Happy birthday! May every day be filled with joy, happiness, and new possibilities.",
        "May your day be as wonderful and beautiful as you... Although it will be quite difficult to achieve. Happy birthday!",
        "Happy birthday! Celebrating you today! May all your dreams come true, and may every day be filled with happiness.",
        "Happy birthday! You're getting wiser... but most importantly, you're becoming even more beautiful!",
        "May your day be as fantastic as you... Well, that would be quite hard to achieve. Happy birthday!",
        "Happy birthday! Remember, wine only gets better with time. So, you're not getting older, you're 'improving'.",
        "Congratulations on your birthday! If you feel sad about getting older, just remember: you're not old, you're vintage!",
        "Happy birthday! Remember, age is just a number... but the bill that comes with that number is another matter!",
        "Congratulations on your birthday! Remember, old age is when you show your friends photos on your phone, and they start swiping left and right. But for now, you're still safe!",
        "Happy birthday! You're still so young that Google doesn't know everything about you yet!",
        "Congratulations on your birthday! Remember, youth is a gift, and old age is an art. And you still have time to master the art!",
        "Happy birthday! Remember when you were afraid of growing up? Well, I hope now you understand that you were right to be afraid!",
        "Congratulations on your birthday! If you ever feel sad about getting older, just think about the dinosaurs. They were so old, they went extinct!",
        "Happy birthday! May your life be filled with wonderful moments, and may every day bring you smiles and happiness.",
        "Happy birthday! You are an inspiration to all of us. May your day be filled with joy, love, and warm moments.",
        "Happy birthday! May each new year make you even happier. Wishing you an unforgettable celebration and a fantastic year.",
        "May your birthday be filled with warmth, love, and joy. I wish you all the best today and always. Happy birthday!",
        "You're an amazing person, and you deserve nothing but the best. Wishing you an unforgettable day and an incredibly happy year. Happy birthday!",
        "Happy birthday! I wish you all the best in the world, and may all your dreams come true.",
        "May every day be filled with happiness and joy. Happy birthday!",
        "Happy birthday! I wish you boundless happiness, health, and love.",
        "I congratulate you on your birthday! May all your dreams come true.",
        "May your birthday be filled with happiness and smiles. Happy birthday!",
        "Happy birthday! I wish you incredible happiness, good health, and success in everything you undertake.",
        "Happy birthday! May each new day in your life be better than the previous one.",
        "I congratulate you on your birthday! I wish you smiles, joy, and all kinds of blessings.",
        "Happy birthday! May your life be filled with happy moments and pleasant surprises.",
        "May this day mark the beginning of the happiest year in your life. Happy birthday!",
        "Happy birthday! I wish you love, joy, and endless happiness.",
        "I congratulate you on your birthday! I wish you continuous growth and development, love, and well-being.",
        "Happy birthday! May your life be as bright and unforgettable as you are.",
        "I congratulate you on your birthday! I wish you a day filled with laughter, joy, and warmth.",
        "Happy birthday! May each day of your life be beautiful and full of pleasant surprises.",
        "I congratulate you on your birthday! I wish you endless happiness, success, and love.",
        "Happy birthday! I wish you smiles, happiness, and amazing things in life.",
        "May every day in your life be special and unforgettable. Happy birthday!",
        "Happy birthday! May your life be filled with joyful moments and vibrant events.",
        "I congratulate you on your birthday! I wish you boundless happiness, robust health, and all the best.",
        "Happy birthday! May each day be filled with love, happiness, and inspiration.",
        "I congratulate you on your birthday! I wish you mountains of joy and seas of happiness.",
        "Happy birthday! I wish you limitless happiness, wonderful discoveries, and an incredibly exciting life.",
        "May your birthday be as unforgettable as you are. Happy birthday!"

    )

    private val italian = listOf(
        "Che la tua vita sia piena di momenti sorprendenti, persone meravigliose ed eventi luminosi! Buon compleanno!",
        "Che ogni giorno della tua vita sia colmo di gioia e felicità, e che i tuoi occhi brillino di piacere! Buon compleanno!",
        "Ti auguro che ogni nuovo giorno sia migliore del precedente e che ogni anno successivo sia più felice del precedente! Che tutti i tuoi sogni si avverino! Buon compleanno!",
        "Che ogni giorno della tua vita sia un meraviglioso regalo, pieno di incredibili scoperte e momenti gioiosi! Buon compleanno!",
        "Ti auguro una felicità immensa, prosperità, amore, salute, ricchezza e tutto ciò che si possa desiderare. Buon compleanno!",
        "Oggi è il tuo giorno speciale, quindi che sia pieno di sorrisi, felicità e tutto ciò che ami. Buon compleanno!",
        "Che il tuo giorno sia luminoso e speciale come te. Auguri di buon compleanno!",
        "Oggi è il tuo giorno! Ti auguro un umore festoso, calore, amore e sorrisi dalle persone care. Buon compleanno!",
        "Che il tuo giorno sia pieno di amore, gioia e sorrisi! Buon compleanno!",
        "Buon compleanno! Ti auguro felicità, salute e tutto il meglio del mondo. Te lo meriti!",
        "Buon compleanno! Ti auguro felicità, salute e tutto il meglio del mondo. Te lo meriti!",
        "Che le stelle nel cielo brillino particolarmente luminose nel tuo giorno, riempiendo la tua vita di gioia, felicità e amore",
        "Oggi diventi ancora più saggio di un anno, che ogni nuovo giorno sia pieno di avventure e scoperte",
        "Il tuo compleanno è solo un'altra occasione per ricordare quanto tu sia speciale. Buon compleanno!",
        "Buon compleanno! Che ogni giorno sia unico e ogni minuto indimenticabile",
        "Ti auguro un amore senza confini, felicità senza limiti e fortuna senza eccezioni. Buon compleanno!",
        "Che questo giorno sia pieno di sorrisi, calore e piacevoli sorprese, e l'anno a venire sia ricco di promesse di nuove opportunità. Buon compleanno!",
        "Oggi è il tuo giorno e niente dovrebbe impedirti di goderne appieno. Buon compleanno e che tutti i tuoi sogni si avverino!",
        "Sogna in grande e non avere mai paura di inseguire i tuoi sogni, che diventino realtà. Buon compleanno!",
        "Che il tuo giorno sia luminoso come il tuo sorriso e gioioso come te. Buon compleanno!",
        "Ti auguro un giorno pieno di sorrisi, felicità e divertimento. Buon compleanno!",
        "Buon compleanno! Che ogni giorno sia pieno di gioia, felicità e nuove opportunità",
        "Che il tuo giorno sia meraviglioso come te... Anche se sarà abbastanza difficile da raggiungere. Buon compleanno!",
        "Buon compleanno! Festeggiamo te! Che tutti i tuoi sogni si avverino e che ogni giorno sia pieno di felicità. Buon compleanno!",
        "Buon compleanno! Diventi più saggio... ma soprattutto diventi ancora più bello!",
        "Che il tuo giorno sia altrettanto splendente e meraviglioso come te. Buon compleanno!",
        "Oggi festeggiamo te! Che tutti i tuoi sogni si avverino e che ogni giorno sia pieno di felicità. Buon compleanno!",
        "Buon compleanno! Ricorda, il vino migliora solo con il tempo. Quindi, non stai invecchiando, ti stai (migliorando).",
        "Auguri di compleanno! Se ti senti triste per il fatto di diventare più grande, ricorda semplicemente che non sei vecchio, sei un pezzo da collezione!",
        "Buon compleanno! Ricorda che l'età è solo un numero... ma il conto che arriva con quel numero è un'altra storia!",
        "Auguri di compleanno! Ricorda, la vecchiaia arriva quando mostri le foto sul tuo telefono agli amici e iniziano a scorrerle a sinistra e a destra. Ma finché sei al sicuro!",
        "Buon compleanno! Sei ancora così giovane che Google non sa ancora tutto di te!",
        "Auguri di compleanno! Ricorda, la giovinezza è un dono, la vecchiaia è un'arte. E hai ancora del tempo per raggiungere l'arte!",
        "Buon compleanno! Ricorda quando avevi paura di crescere? Beh, spero che ora tu capisca che avevi ragione ad averne paura!",
        "Auguri di compleanno! Se ti senti triste per il fatto di diventare più grande, ricorda i dinosauri. Erano così vecchi che si sono estinti!",
        "Buon compleanno! Che la tua vita sia piena di momenti meravigliosi e che ogni giorno ti porti sorrisi e felicità.",
        "Buon compleanno! Sei una fonte di ispirazione per tutti noi. Che il tuo giorno sia pieno di gioia, amore e momenti caldi.",
        "Buon compleanno! Che ogni nuovo anno ti renda sempre più felice. Ti auguro una festa indimenticabile e un anno meraviglioso.",
        "Che il tuo compleanno sia pieno di calore, amore e gioia. Ti auguro il meglio, oggi e sempre. Buon compleanno!",
        "Sei una persona meravigliosa e meriti solo il meglio. Ti auguro una giornata indimenticabile e un anno incredibilmente felice. Buon compleanno!",
        "Buon compleanno! Ti auguro tutto il meglio in questo mondo e che tutti i tuoi sogni si avverino."
    )

    private val russian = listOf(
        "Пусть твоя жизнь будет полна удивительных моментов, замечательных людей и ярких событий! С днем рождения!",
        "Пусть каждый день твоей жизни будет наполнен радостью и счастьем, а глаза сияют от удовольствия! С днем рождения!",
        "Желаю тебе, чтобы каждый новый день был лучше предыдущего, а каждый следующий год – счастливее предыдущего! Пусть все мечты сбываются! С днем рождения!",
        "Пусть каждый день твоей жизни будет прекрасным подарком, полным удивительных открытий и радостных моментов! С днем рождения!",
        "Желаю тебе огромного счастья, благополучия, любви, здоровья, достатка и всего, что только можно пожелать. С днем рождения!",
        "Сегодня твой особенный день, поэтому пусть он будет заполнен улыбками, счастьем и всем тем, что ты любишь. С днем рождения!",
        "Пусть твой день будет таким же ярким и специальным, как ты. Поздравляю тебя с днем рождения!",
        "Сегодня твой день! Желаю тебе праздничного настроения, тепла, любви и улыбок близких людей. С днем рождения!",
        "Пусть твой день будет наполнен любовью, радостью и улыбками! С днем рождения!",
        "С днем рождения! Желаю тебе счастья, здоровья и всего наилучшего в этом мире. Ты это заслуживаешь!",
        "Пусть звезды на небе сверкают особенно ярко в твой день, наполняя твою жизнь радостью, счастьем и любовью",
        "Сегодня ты еще на год стал мудрее, пусть каждый новый день будет полон приключений и открытий",
        "Твой день рождения - это лишь еще один повод напомнить, насколько ты особенный. С днем рождения!",
        "С днем рождения! Пусть каждый день будет уникальным, а каждая минута - незабываемой",
        "Желаю тебе любви без границ, счастья без пределов и удачи без исключений. С днем рождения!",
        "Пусть этот день будет полон улыбок, тепла и приятных сюрпризов, а год впереди - полон обещаний о новых возможностях. С днем рождения!",
        "Сегодня твой день, и ничто не должно помешать тебе наслаждаться им в полной мере. С днем рождения и пусть все твои мечты осуществятся!",
        "Мечтай крупно и никогда не бойся идти за своими мечтами, пусть они станут реальностью. С днем рождения!",
        "Пусть твой день будет таким же сияющим, как твоя улыбка, и таким же радостным, как ты. С днем рождения!",
        "Желаю тебе дня, полного улыбок, счастья и веселья. С днем рождения!",
        "С днем рождения! Пусть каждый день будет полон радости, счастья и новых возможностей",
        "Пусть твой день будет таким же ярким и прекрасным, как ты. С днем рождения!",
        "Сегодня празднуем тебя! Пусть все твои мечты сбудутся, и пусть каждый день будет полон счастья. С днем рождения!",
        "С днем рождения! Ты становишься мудрее...но главное, что становишься еще красивее!",
        "Пусть твой день будет таким же замечательным, как ты... Хотя, это будет довольно сложно добиться. С днем рождения!",
        "С днем рождения! Помни, вино становится только лучше со временем. Так что, ты не стареешь, ты 'улучшаешься'",
        "Поздравляю с днем рождения! Если тебе грустно от того, что ты становишься старше, просто вспомни: ты не старый, ты винтаж!",
        "С днем рождения! Помни, в возрасте всего лишь цифры, а ты еще не готов для математики!",
        "Сегодня твой день, и ты заслуживаешь лучшего... но так как лучшее уже занято (я!), придется довольствоваться пирогом и подарками. С днем рождения!",
        "С днем рождения! Помни, возраст - это всего лишь число... а счет, который приходит с этим числом, это уже другой вопрос!",
        "Поздравляю с днем рождения! Помни, старость - это когда показываешь друзьям фото в телефоне, а они начинают листать влево и вправо. Но пока ты еще в безопасности!",
        "С днем рождения! Ты еще настолько молод, что Google еще не все о тебе знает!",
        "Поздравляю с днем рождения! Помни, молодость - это дар, старость - это искусство. И у тебя еще есть время до достижения искусства!",
        "С днем рождения! Вспомни, как ты боялся взрослеть? Ну, надеюсь, сейчас ты понимаешь, что боялся не зря!",
        "Поздравляю с днем рождения! Если тебе станет грустно от того, что ты становишься старше, просто вспомни о динозаврах. Они были так стары, что вымерли!",
        "С днем рождения! Пусть твоя жизнь будет полна чудесных моментов, и пусть каждый день приносит тебе улыбки и счастье",
        "С днем рождения! Ты - источник вдохновения для всех нас. Пусть твой день будет полон радости, любви и теплых моментов",
        "С днем рождения! Пусть с каждым новым годом ты становишься только счастливее. Желаю тебе незабываемого праздника и замечательного года",
        "Пусть твой день рождения будет наполнен теплом, любовью и радостью. Желаю тебе всего наилучшего, сегодня и всегда. С днем рождения!",
        "Ты - замечательный человек, и ты заслуживаешь только самого лучшего. Желаю тебе незабываемого дня и невероятно счастливого года. С днем рождения!",
        "С днем рождения! Желаю тебе всего наилучшего в этом мире и чтобы все твои мечты сбылись",
        "Пусть каждый день будет полон счастья и радости. С днем рождения!",
        "С днем рождения! Желаю тебе неиссякаемого счастья, здоровья и любви",
        "Поздравляю тебя с днем рождения! Пусть все твои мечты станут реальностью",
        "Пусть твой день рождения будет наполнен счастьем и улыбками. С днем рождения!",
        "С днем рождения! Желаю тебе невероятного счастья, здоровья и успеха во всем, что ты предпримешь",
        "С днем рождения! Пусть каждый новый день в твоей жизни будет лучше предыдущего",
        "Поздравляю с днем рождения! Желаю тебе улыбок, радости и всяческих благ",
        "С днем рождения! Пусть твоя жизнь будет полна счастливых моментов и приятных сюрпризов",
        "Пусть этот день станет началом самого счастливого года в твоей жизни. С днем рождения!",
        "С днем рождения! Желаю тебе любви, радости и бесконечного счастья",
        "Поздравляю тебя с днем рождения! Желаю тебе непрерывного роста и развития, любви и благополучия",
        "С днем рождения! Пусть твоя жизнь будет такой же яркой и незабываемой, как ты",
        "Поздравляю с днем рождения! Желаю тебе дня, наполненного смехом, радостью и теплом",
        "С днем рождения! Пусть каждый день твоей жизни будет прекрасным и полным приятных сюрпризов",
        "Поздравляю с днем рождения! Желаю тебе нескончаемого счастья, успеха и любви",
        "С днем рождения! Желаю тебе улыбок, счастья и всяческих удивительных вещей",
        "Пусть каждый день в твоей жизни будет особенным и незабываемым. С днем рождения!",
        "С днем рождения! Пусть в твоей жизни будет больше радостных моментов и ярких событий",
        "Поздравляю с днем рождения! Желаю тебе безграничного счастья, крепкого здоровья и всего самого наилучшего",
        "С днем рождения! Пусть каждый день будет наполнен любовью, счастьем и вдохновением",
        "Поздравляю с днем рождения! Желаю тебе гор моментов радости и морей счастья",
        "С днем рождения! Желаю тебе неограниченного счастья, замечательных открытий и безумно интересной жизни",
        "Пусть твой день рождения будет таким же незабываемым, как ты. С днем рождения!"
    )

    private val spanish = listOf(
        "¡Que tu vida esté llena de momentos sorprendentes, personas maravillosas y eventos brillantes! ¡Feliz cumpleaños!",
        "¡Que cada día de tu vida esté lleno de alegría y felicidad, y que tus ojos brillen de placer! ¡Feliz cumpleaños!",
        "Deseo que cada nuevo día sea mejor que el anterior y que cada año siguiente sea más feliz que el anterior. ¡Que todos tus sueños se hagan realidad! ¡Feliz cumpleaños!",
        "¡Que cada día de tu vida sea un regalo maravilloso, lleno de descubrimientos increíbles y momentos felices! ¡Feliz cumpleaños!",
        "Te deseo una felicidad inmensa, bienestar, amor, salud, prosperidad y todo lo que puedas desear. ¡Feliz cumpleaños!",
        "Hoy es tu día especial, así que que esté lleno de sonrisas, felicidad y todo lo que amas. ¡Feliz cumpleaños!",
        "Que tu día sea tan brillante y especial como tú. ¡Feliz cumpleaños!",
        "¡Hoy es tu día! Te deseo un estado de ánimo festivo, calidez, amor y sonrisas de tus seres queridos. ¡Feliz cumpleaños!",
        "Que tu día esté lleno de amor, alegría y sonrisas. ¡Feliz cumpleaños!",
        "¡Feliz cumpleaños! Te deseo felicidad, salud y todo lo mejor en el mundo. ¡Te lo mereces!",
        "Feliz cumpleaños. Te deseo felicidad, salud y todo lo mejor en este mundo. ¡Te lo mereces!",
        "Que las estrellas en el cielo brillen especialmente brillantes en tu día, llenando tu vida de alegría, felicidad y amor.",
        "Hoy te has vuelto un año más sabio, que cada día nuevo esté lleno de aventuras y descubrimientos.",
        "Tu cumpleaños es solo otra razón para recordar lo especial que eres. ¡Feliz cumpleaños!",
        "Feliz cumpleaños. Que cada día sea único y cada minuto inolvidable.",
        "Te deseo amor sin límites, felicidad sin fronteras y suerte sin excepciones. ¡Feliz cumpleaños!",
        "Que este día esté lleno de sonrisas, calidez y agradables sorpresas, y el año que viene esté lleno de promesas de nuevas oportunidades. ¡Feliz cumpleaños!",
        "Hoy es tu día y nada debería impedirte disfrutarlo al máximo. ¡Feliz cumpleaños y que todos tus sueños se hagan realidad!",
        "Sueña en grande y nunca temas perseguir tus sueños, que se hagan realidad. ¡Feliz cumpleaños!",
        "Que tu día sea tan brillante como tu sonrisa y tan alegre como tú. ¡Feliz cumpleaños!",
        "Te deseo un día lleno de sonrisas, felicidad y diversión. ¡Feliz cumpleaños!",
        "Feliz cumpleaños. Que cada día esté lleno de alegría, felicidad y nuevas oportunidades.",
        "Que tu día sea tan maravilloso como tú... aunque será difícil de lograr. ¡Feliz cumpleaños!",
        "Hoy celebramos a ti. Que todos tus sueños se hagan realidad y que cada día esté lleno de felicidad. ¡Feliz cumpleaños!",
        "Feliz cumpleaños. Te estás volviendo más sabio... ¡pero lo más importante es que te estás volviendo más hermoso/a!",
        "Que tu día sea tan maravilloso como tú... aunque será difícil de lograr. ¡Feliz cumpleaños!",
        "Feliz cumpleaños. Recuerda, el vino solo mejora con el tiempo. Así que no estás envejeciendo, te estás (mejorando).",
        "¡Felicitaciones por tu cumpleaños! Si te entristece hacerte mayor, simplemente recuerda: ¡no estás viejo/a, eres de época!",
        "Feliz cumpleaños. Recuerda, la edad es solo un número... pero la cuenta bancaria que viene con ese número es otra historia.",
        "Felicitaciones por tu cumpleaños. Recuerda, la vejez es cuando le muestras fotos a tus amigos en el teléfono y empiezan a deslizar hacia la izquierda y la derecha. Pero mientras tanto, estás a salvo.",
        "Feliz cumpleaños. Eres tan joven que Google aún no sabe todo sobre ti.",
        "Felicitaciones por tu cumpleaños. Recuerda, la juventud es un regalo, la vejez es un arte. Y aún tienes tiempo para dominar ese arte.",
        "Felicitaciones por tu cumpleaños. Si te pones triste por hacerte mayor, solo recuerda a los dinosaurios. ¡Eran tan viejos que se extinguieron!",
        "Feliz cumpleaños. Que tu vida esté llena de momentos maravillosos y que cada día te traiga sonrisas y felicidad.",
        "Feliz cumpleaños. Eres una fuente de inspiración para todos nosotros. Que tu día esté lleno de alegría, amor y momentos cálidos.",
        "Feliz cumpleaños. Que cada año nuevo te haga aún más feliz. Te deseo una celebración inolvidable y un año increíble.",
        "Que tu cumpleaños esté lleno de calidez, amor y alegría. Te deseo lo mejor, hoy y siempre. ¡Feliz cumpleaños!",
        "Eres una persona maravillosa y mereces solo lo mejor. Te deseo un día inolvidable y un año increíblemente feliz. ¡Feliz cumpleaños!",
        "Feliz cumpleaños. Te deseo todo lo mejor en este mundo y que todos tus sueños se hagan realidad.",
        "Que cada día esté lleno de felicidad y alegría. ¡Feliz cumpleaños!",
        "¡Feliz cumpleaños! Te deseo una felicidad inagotable, salud y amor.",
        "¡Felicitaciones por tu cumpleaños! Que todos tus sueños se hagan realidad.",
        "Que tu día de cumpleaños esté lleno de felicidad y sonrisas. ¡Feliz cumpleaños!",
        "¡Feliz cumpleaños! Te deseo una felicidad increíble, salud y éxito en todo lo que emprendas.",
        "¡Feliz cumpleaños! Que cada nuevo día en tu vida sea mejor que el anterior.",
        "¡Felicitaciones por tu cumpleaños! Te deseo sonrisas, alegría y todas las bendiciones.",
        "¡Feliz cumpleaños! Que tu vida esté llena de momentos felices y sorpresas agradables.",
        "Que este día marque el comienzo del año más feliz de tu vida. ¡Feliz cumpleaños!",
        "¡Feliz cumpleaños! Te deseo amor, alegría y felicidad infinita.",
        "¡Felicitaciones por tu cumpleaños! Te deseo un crecimiento continuo, amor y bienestar.",
        "¡Feliz cumpleaños! Que tu vida sea tan brillante e inolvidable como tú.",
        "¡Felicitaciones por tu cumpleaños! Te deseo un día lleno de risas, alegría y calidez.",
        "¡Feliz cumpleaños! Que cada día de tu vida sea maravilloso y lleno de sorpresas agradables.",
        "¡Felicitaciones por tu cumpleaños! Te deseo felicidad interminable, éxito y amor.",
        "¡Feliz cumpleaños! Te deseo sonrisas, felicidad y cosas maravillosas de todo tipo.",
        "Que cada día en tu vida sea especial e inolvidable. ¡Feliz cumpleaños!",
        "¡Feliz cumpleaños! Que en tu vida haya más momentos felices y eventos emocionantes.",
        "¡Felicitaciones por tu cumpleaños! Te deseo felicidad ilimitada, excelente salud y todo lo mejor.",
        "¡Feliz cumpleaños! Que cada día esté lleno de amor, felicidad e inspiración.",
        "¡Felicitaciones por tu cumpleaños! Te deseo montañas de momentos de alegría y mares de felicidad.",
        "¡Feliz cumpleaños! Te deseo felicidad sin límites, descubrimientos maravillosos y una vida increíblemente interesante.",
        "Que tu cumpleaños sea tan inolvidable como tú. ¡Feliz cumpleaños!"
    )

    private val german = listOf(
        "Möge dein Leben voller erstaunlicher Momente, wunderbarer Menschen und strahlender Ereignisse sein! Alles Gute zum Geburtstag!",
        "Mögen all deine Tage mit Freude und Glück erfüllt sein und deine Augen vor Vergnügen leuchten! Alles Gute zum Geburtstag!",
        "Ich wünsche dir, dass jeder neue Tag besser ist als der vorherige und jedes kommende Jahr glücklicher als das vorherige! Mögen sich all deine Träume erfüllen! Alles Gute zum Geburtstag!",
        "Mögen all deine Tage ein wundervolles Geschenk sein, voller erstaunlicher Entdeckungen und freudiger Momente! Alles Gute zum Geburtstag!",
        "Ich wünsche dir unermessliches Glück, Wohlstand, Liebe, Gesundheit, Wohlstand und alles andere, was du dir wünschen kannst. Alles Gute zum Geburtstag!",
        "Heute ist dein besonderer Tag, also lass ihn voller Lächeln, Glück und allem sein, was du liebst. Alles Gute zum Geburtstag!",
        "Möge dein Tag genauso hell und besonders sein wie du. Herzlichen Glückwunsch zum Geburtstag!",
        "Heute ist dein Tag! Ich wünsche dir eine festliche Stimmung, Wärme, Liebe und Lächeln von den Menschen, die dir nahestehen. Alles Gute zum Geburtstag!",
        "Möge dein Tag voller Liebe, Freude und Lächeln sein! Alles Gute zum Geburtstag!",
        "Herzlichen Glückwunsch zum Geburtstag! Ich wünsche dir Glück, Gesundheit und alles Gute in der Welt. Du hast es verdient!",
        "Alles Gute zum Geburtstag! Ich wünsche dir Glück, Gesundheit und alles Beste in dieser Welt. Du verdienst es!",
        "Mögen die Sterne am Himmel an deinem Tag besonders hell leuchten und dein Leben mit Freude, Glück und Liebe erfüllen.",
        "Heute bist du ein Jahr weiser geworden. Mögen jeden neuen Tag Abenteuer und Entdeckungen für dich bereithalten.",
        "Dein Geburtstag ist nur ein weiterer Grund daran zu erinnern, wie besonders du bist. Herzlichen Glückwunsch zum Geburtstag!",
        "Alles Gute zum Geburtstag! Möge jeder Tag einzigartig sein und jede Minute unvergesslich.",
        "Ich wünsche dir grenzenlose Liebe, unermessliches Glück und unbestreitbares Glück. Herzlichen Glückwunsch zum Geburtstag!",
        "Möge dieser Tag voller Lächeln, Wärme und angenehmer Überraschungen sein, und das kommende Jahr voller Versprechen neuer Möglichkeiten. Herzlichen Glückwunsch zum Geburtstag!",
        "Heute ist dein Tag, und nichts sollte dich daran hindern, ihn in vollen Zügen zu genießen. Alles Gute zum Geburtstag, und mögen all deine Träume wahr werden!",
        "Träume groß und habe keine Angst, deinen Träumen zu folgen, mögen sie Wirklichkeit werden. Alles Gute zum Geburtstag!",
        "Möge dein Tag genauso strahlend sein wie dein Lächeln und genauso glücklich wie du. Herzlichen Glückwunsch zum Geburtstag!",
        "Ich wünsche dir einen Tag voller Lächeln, Glück und Freude. Alles Gute zum Geburtstag!",
        "Alles Gute zum Geburtstag! Möge jeder Tag voller Freude, Glück und neuen Möglichkeiten sein.",
        "Möge dein Tag genauso wunderbar sein wie du... Obwohl das ziemlich schwer zu erreichen sein wird. Herzlichen Glückwunsch zum Geburtstag!",
        "Alles Gute zum Geburtstag! Denke daran, Wein wird nur besser mit der Zeit. Also wirst du nicht älter, sondern 'verbesserst' dich!",
        "Herzlichen Glückwunsch zum Geburtstag! Wenn du traurig bist, älter zu werden, denke daran: Du bist nicht alt, du bist vintage!",
        "Alles Gute zum Geburtstag! Denke daran, Alter ist nur eine Zahl... aber die Rechnung, die damit kommt, ist eine andere Geschichte!",
        "Herzlichen Glückwunsch zum Geburtstag! Denke daran, dass du erst alt bist, wenn du deinen Freunden Fotos auf deinem Handy zeigst und sie anfangen, nach links und rechts zu blättern. Aber solange du noch sicher bist!",
        "Alles Gute zum Geburtstag! Du bist so jung, dass Google noch nicht alles über dich weiß!",
        "Herzlichen Glückwunsch zum Geburtstag! Denke daran, Jugend ist ein Geschenk, Alter ist eine Kunst. Und du hast noch Zeit, um die Kunst zu beherrschen!",
        "Alles Gute zum Geburtstag! Erinnerst du dich daran, wie du Angst hattest, älter zu werden? Nun, hoffentlich verstehst du jetzt, dass du dich nicht umsonst gefürchtet hast!",
        "Alles Gute zum Geburtstag! Wenn es dich traurig macht, älter zu werden, dann denke einfach an Dinosaurier. Sie waren so alt, dass sie ausgestorben sind!",
        "Alles Gute zum Geburtstag! Möge dein Leben voller wundervoller Momente sein und mögen dir jeder Tag lächeln und Glück bringen.",
        "Alles Gute zum Geburtstag! Du bist eine Quelle der Inspiration für uns alle. Möge dein Tag voller Freude, Liebe und herzlicher Momente sein.",
        "Alles Gute zum Geburtstag! Mögest du mit jedem neuen Jahr nur glücklicher werden. Ich wünsche dir einen unvergesslichen Feiertag und ein fantastisches Jahr.",
        "Möge dein Geburtstagstag mit Wärme, Liebe und Freude erfüllt sein. Ich wünsche dir nur das Beste, heute und immer. Alles Gute zum Geburtstag!",
        "Du bist eine wunderbare Person und du verdienst nur das Beste. Ich wünsche dir einen unvergesslichen Tag und ein unglaublich glückliches Jahr. Alles Gute zum Geburtstag!",
        "Alles Gute zum Geburtstag! Ich wünsche dir alles Beste in dieser Welt und dass all deine Träume wahr werden.",
        "Jeden Tag möge voller Glück und Freude sein. Alles Gute zum Geburtstag!",
        "Alles Gute zum Geburtstag! Ich wünsche dir unerschöpfliches Glück, Gesundheit und Liebe.",
        "Ich gratuliere dir zum Geburtstag! Mögen all deine Träume wahr werden.",
        "Möge dein Geburtstagstag mit Glück und Lächeln erfüllt sein. Alles Gute zum Geburtstag!",
        "Alles Gute zum Geburtstag! Ich wünsche dir unglaubliches Glück, Gesundheit und Erfolg in allem, was du unternimmst.",
        "Alles Gute zum Geburtstag! Möge jeder neue Tag in deinem Leben besser sein als der vorherige.",
        "Ich gratuliere dir zum Geburtstag! Ich wünsche dir Lächeln, Freude und alle erdenklichen Güter.",
        "Alles Gute zum Geburtstag! Möge dein Leben voller glücklicher Momente und angenehmer Überraschungen sein.",
        "Möge dieser Tag der Beginn des glücklichsten Jahres in deinem Leben sein. Alles Gute zum Geburtstag!",
        "Alles Gute zum Geburtstag! Ich wünsche dir Liebe, Freude und endloses Glück.",
        "Ich gratuliere dir zum Geburtstag! Ich wünsche dir kontinuierliches Wachstum und Entwicklung, Liebe und Wohlstand.",
        "Alles Gute zum Geburtstag! Möge dein Leben genauso hell und unvergesslich sein wie du.",
        "Ich gratuliere dir zum Geburtstag! Ich wünsche dir einen Tag voller Lachen, Freude und Wärme.",
        "Alles Gute zum Geburtstag! Möge jeder Tag in deinem Leben wunderbar sein und mit angenehmen Überraschungen gefüllt sein.",
        "Ich gratuliere dir zum Geburtstag! Ich wünsche dir unendliches Glück, Erfolg und Liebe.",
        "Alles Gute zum Geburtstag! Ich wünsche dir Lächeln, Glück und erstaunliche Dinge aller Art.",
        "Möge jeder Tag in deinem Leben besonders und unvergesslich sein. Alles Gute zum Geburtstag!",
        "Alles Gute zum Geburtstag! Mögen mehr glückliche Momente und lebhafte Ereignisse in dein Leben treten.",
        "Ich gratuliere dir zum Geburtstag! Ich wünsche dir grenzenloses Glück, robuste Gesundheit und alles Beste.",
        "Alles Gute zum Geburtstag! Mögen Liebe, Glück und Inspiration jeden Tag in deinem Leben präsent sein.",
        "Ich gratuliere dir zum Geburtstag! Ich wünsche dir Berge voller Freude und Meere voller Glück.",
        "Alles Gute zum Geburtstag! Ich wünsche dir grenzenloses Glück, faszinierende Entdeckungen und ein unglaublich interessantes Leben.",
        "Möge dein Geburtstagstag genauso unvergesslich sein wie du. Alles Gute zum Geburtstag!"
    )
}