package com.sosinvitalii.database.congratulations

/// Поздравление с новым годом
object NewYearCongratulations {
    fun fetch(language: Language): List<String> {
        return when (language) {
            Language.EN -> english
            Language.IT -> italian
            Language.RU -> russian
            Language.ES -> spanish
            Language.DE -> german
        }
    }

    private val english = listOf(
        "May the New Year bring joy and happiness, fulfill all your dreams and desires! Happy New Year!",
        "May the upcoming year be filled with new opportunities, bright moments, and pleasant surprises! Happy New Year!",
        "I wish the New Year to be the beginning of something new and amazing in your life. May it bring prosperity and success! Happy New Year!",
        "Happiness, health, love, and the fulfillment of your deepest wishes in the New Year! May every day be filled with joy and good fortune! Happy New Year!",
        "May the New Year bring new possibilities, bold decisions, and glorious victories! Happy New Year!",
        "I wish each day of the New Year to be filled with happiness, smiles, and prosperity. May it bring many joyful moments! Happy New Year!",
        "May the New Year bring warmth and light to your home, fulfill your dearest dreams, and fill each day with smiles! Happy New Year!",
        "I wish the coming year to bring magic, happiness, and success in all your endeavors. May it be bright and memorable! Happy New Year!",
        "May the New Year mark the beginning of a new life full of opportunities and achievements. Wishing you a happy and successful year!",
        "Happy New Year! I wish you and your loved ones abundant joy, health, prosperity, and success in all your endeavors!",
        "Happy New Year! I wish you and your loved ones lots of joy, good health, prosperity, and success in all your endeavors!",
        "Happy New Year! May the upcoming year bring you joy, happiness, and good luck.",
        "May the New Year be filled with pleasant surprises, wonderful moments, and vibrant experiences. Happy New Year!",
        "Congratulations on the New Year! Wishing you an unforgettable celebration and many happy moments in the coming year.",
        "Happy New Year! May it be filled with magic, happiness, and love.",
        "May the New Year be a year of new opportunities, successes, and victories for you. Happy New Year!",
        "Happy New Year! Wishing you peace, love, and prosperity in the coming year.",
        "Happy New Year! May it bring you peace, happiness, and the fulfillment of your boldest dreams.",
        "Congratulations on the New Year! Wishing you unforgettable experiences, new discoveries, and successful beginnings in all your endeavors.",
        "Happy New Year! May it be filled with pleasant surprises, exciting encounters, and vibrant emotions.",
        "Congratulations on the New Year! Wishing you peace, joy, happiness, and prosperity in the coming year.",
        "Happy New Year! May it be filled with exciting events, joyful moments, and new achievements.",
        "May the New Year be a year of new accomplishments, successes, and victories for you. Happy New Year!",
        "Happy New Year! May this year be filled with luck, new opportunities, and bright moments.",
        "Congratulations on the New Year! Wishing you peace, joy, and infinite happiness in the coming year.",
        "Happy New Year! May it bring you many happy moments, new achievements, and a great deal of luck.",
        "Congratulations on the New Year! Wishing you unforgettable experiences, bright moments, and many happy days.",
        "Happy New Year! May it be filled with pleasant surprises, new discoveries, and incredible successes.",
        "May the New Year be a year of joy, happiness, and success. Happy New Year!",
        "Happy New Year! May it bring you peace, love, and boundless happiness.",
        "Congratulations on the New Year! Wishing you many smiles, endless inspiration, and bright, memorable moments.",
        "Happy New Year! May it bring you the fulfillment of your cherished dreams, success in all your endeavors, and plenty of positive emotions.",
        "Congratulations on the New Year! Wishing you incredible adventures, new discoveries, and stunning achievements.",
        "Happy New Year! May it be filled with happiness, love, and unforgettable moments.",
        "May the New Year mark the beginning of amazing achievements and victories in your life. Happy New Year!",
        "Happy New Year! May it be filled with happiness, new opportunities, and amazing moments.",
        "Congratulations on the New Year! Wishing you peace, love, and prosperity in the coming year.",
        "Happy New Year! May it be the start of something great and incredible in your life.",
        "Congratulations on the New Year! Wishing you luck, good health, and many joyful moments.",
        "Happy New Year! May it bring you happiness, success, and the fulfillment of all your wishes.",
        "May the New Year be filled with amazing discoveries, exciting encounters, and new achievements. Happy New Year!",
        "Happy New Year! May it bring you as much happiness as my cat weighs. And trust me, that's a lot!",
        "Congratulations on the New Year! I hope this year your neighbors finally discover what silence looks like.",
        "Happy New Year! May your commitment to a healthy lifestyle last longer than the leftovers from the New Year's table.",
        "Congratulations on the New Year! I wish you as much joy as there are stars in the sky... well, maybe it's better to wish you as much money in the bank.",
        "Happy New Year! I wish you so much luck that not even last year's New Year decorations break.",
        "May your life be as sweet in the New Year as a chocolate advent calendar. Just remember: don't lick it! Happy New Year!",
        "Happy New Year! May it be better than the previous one... Well, that doesn't seem too difficult, right?",
        "Congratulations on the New Year! I wish you health and happiness. And wealth too, if it doesn't spoil anything.",
        "Happy New Year! I wish you so much success that your former school teacher talks about you at parent-teacher meetings.",
        "Congratulations on the New Year! I wish you patience... because you can buy everything else.",
        "Happy New Year! May all your problems disappear as quickly as my money does at the supermarket.",
        "May all your friends understand your jokes without explanations in the New Year. Happy New Year!",
        "Happy New Year! May your Christmas tree be slimmer than you, and the gifts under it be thicker than your wallet.",
        "Congratulations on the New Year! I wish you the fulfillment of all your wishes... but remember, some are better left unspoken.",
        "Happy New Year! I wish you more luck than a cat that found a whole box to play with.",
        "Congratulations on the New Year! I wish you to reach such heights that people start asking where you got your oxygen mask from.",
        "Happy New Year! May your wallet be as healthy this year as my Christmas tree.",
        "May the New Year be full of amazing discoveries. For example, may you discover that you haven't used up all your vacation days yet. Happy New Year!"

    )

    private val italian = listOf(
        "Che il Nuovo Anno porti gioia e felicità, realizzi tutti i tuoi sogni e desideri! Buon anno nuovo!",
        "Che l'anno imminente sia pieno di nuove opportunità, momenti luminosi e piacevoli sorprese! Felice anno nuovo!",
        "Ti auguro che il Nuovo Anno sia l'inizio di qualcosa di nuovo e straordinario nella tua vita. Possa portare prosperità e successo! Buon anno nuovo!",
        "Felicità, salute, amore e il raggiungimento dei tuoi desideri più profondi nel Nuovo Anno! Possa ogni giorno essere pieno di gioia e fortuna! Buon anno nuovo!",
        "Che il Nuovo Anno porti nuove possibilità, decisioni coraggiose e vittorie gloriose! Felice anno nuovo!",
        "Auguro che ogni giorno del Nuovo Anno sia pieno di felicità, sorrisi e prosperità. Possa portare molti momenti gioiosi! Buon anno nuovo!",
        "Che il Nuovo Anno porti calore e luce nella tua casa, realizzi i tuoi sogni più cari e riempia ogni giorno di sorrisi! Buon anno nuovo!",
        "Ti auguro che l'anno in arrivo porti magia, felicità e successo in tutte le tue imprese. Possa essere luminoso e memorabile! Buon anno nuovo!",
        "Che il Nuovo Anno segni l'inizio di una nuova vita piena di opportunità e successi. Ti auguro un anno felice e di successo!",
        "Felice anno nuovo! Ti auguro a te e ai tuoi cari abbondante gioia, salute, prosperità e successo in tutte le tue imprese!",
        "Buon anno nuovo! Auguro a te e ai tuoi cari molta gioia, salute, prosperità e fortuna in tutte le tue imprese!",
        "Buon anno nuovo! Che l'anno a venire ti porti gioia, felicità e fortuna",
        "Che il nuovo anno sia pieno di piacevoli sorprese, momenti meravigliosi e impressioni vivaci. Buon anno nuovo!",
        "Auguri di buon anno! Ti auguro una festa indimenticabile e molti momenti felici nell'anno a venire",
        "Buon anno nuovo! Che sia pieno di magia, felicità e amore",
        "Che il nuovo anno sia per te un anno di nuove opportunità, successi e vittorie. Buon anno nuovo!",
        "Buon anno nuovo! Ti auguro pace, amore e prosperità nell'anno a venire",
        "Buon anno nuovo! Che porti pace, felicità e realizzazione dei sogni più audaci",
        "Auguri di buon anno! Ti auguro esperienze indimenticabili, nuove scoperte e un inizio di successo in tutte le tue imprese",
        "Buon anno nuovo! Che sia pieno di piacevoli sorprese, incontri interessanti e emozioni vivaci",
        "Auguri di buon anno! Ti auguro pace, amore, felicità e prosperità nell'anno a venire",
        "Buon anno nuovo! Che sia pieno di eventi vivaci, momenti divertenti e nuovi traguardi",
        "Che il nuovo anno sia per te un anno di nuovi successi, realizzazioni e vittorie. Buon anno nuovo!",
        "Buon anno nuovo! Che quest'anno sia pieno di fortuna, nuove opportunità e momenti luminosi",
        "Auguri di buon anno! Ti auguro pace, gioia e felicità infinita nell'anno a venire",
        "Buon anno nuovo! Che porti molti momenti felici, nuovi traguardi e molta fortuna",
        "Auguri di buon anno! Ti auguro esperienze indimenticabili, momenti intensi e molti giorni felici",
        "Buon anno nuovo! Che sia pieno di piacevoli sorprese, nuove scoperte e incredibili successi",
        "Che il nuovo anno sia un anno di gioia, felicità e successo. Buon anno nuovo!",
        "Buon anno nuovo! Che porti pace, amore e felicità illimitata",
        "Auguri di buon anno! Ti auguro molti sorrisi, ispirazione inesauribile e momenti luminosi e memorabili",
        "Buon anno nuovo! Che porti l'esaudimento dei tuoi sogni più cari, successo in tutte le tue imprese e molte emozioni positive",
        "Auguri di buon anno! Ti auguro avventure incredibili, nuove scoperte e sorprendenti successi",
        "Buon anno nuovo! Che sia pieno di felicità, amore e momenti indimenticabili",
        "Che il nuovo anno sia l'inizio di nuove meravigliose realizzazioni e vittorie. Buon anno nuovo!",
        "Buon anno nuovo! Che sia pieno di felicità, nuove opportunità e momenti straordinari",
        "Buon anno nuovo! Che sia l'inizio di qualcosa di grande e incredibile nella tua vita",
        "Auguri di buon anno! Ti auguro fortuna, salute e molti momenti gioiosi",
        "Buon anno nuovo! Che porti felicità, successo e realizzazione di tutti i tuoi desideri",
        "Che il nuovo anno sia pieno di meravigliose scoperte, incontri interessanti e nuovi traguardi. Buon anno nuovo!",
        "Buon anno nuovo! Che porti tanta felicità quanto pesa il mio gatto. E credimi, è molto!",
        "Auguri di buon anno! Spero che quest'anno i tuoi vicini finalmente scoprano com'è fatta la quiete",
        "Buon anno nuovo! Che le tue decisioni per uno stile di vita sano durino più a lungo dei resti del pranzo di Capodanno",
        "Auguri di buon anno! Ti auguro tanta gioia quanto le stelle nel cielo... anche se forse è meglio quanti soldi in banca",
        "Buon anno nuovo! Ti auguro tanta fortuna che nemmeno gli addobbi dell'albero di Natale dell'anno scorso si rompono",
        "Che la tua vita nel nuovo anno sia dolce come una cioccolata del calendario dell'Avvento. Ma ricorda: non leccarti! Buon anno nuovo!",
        "Buon anno nuovo! Che sia migliore dell'anno precedente... Beh, in teoria non dovrebbe essere così difficile, vero?",
        "Auguri di buon anno! Ti auguro salute e felicità. E ricchezza, se non guasta nulla",
        "Buon anno nuovo! Ti auguro tanto successo che la tua ex insegnante parlerà di te alle riunioni dei genitori",
        "Auguri di buon anno! Ti auguro pazienza... perché il resto puoi comprarlo",
        "Buon anno nuovo! Che in questo anno tutti i tuoi problemi scompaiano così rapidamente come i miei soldi al supermercato",
        "Che nel nuovo anno tutti i tuoi amici capiscano le tue battute senza spiegazioni. Buon anno nuovo!",
        "Buon anno nuovo! Che il tuo albero di Natale sia più slanciato di te e i regali sotto di esso siano più pieni del tuo portafoglio",
        "Auguri di buon anno! Ti auguro che tutti i tuoi desideri si avverino... ma ricorda che alcuni è meglio non esprimerli ad alta voce",
        "Buon anno nuovo! Ti auguro più fortuna di un gatto che ha trovato una scatola piena di giocattoli",
        "Auguri di buon anno! Ti auguro di raggiungere altezze tale che la gente inizierà a chiederti da dove hai preso la maschera dell'ossigeno",
        "Buon anno nuovo! Che il tuo portafoglio quest'anno sia altrettanto sano quanto il mio albero di Natale",
        "Che il nuovo anno sia pieno di meravigliose scoperte. Ad esempio, che scopri che non hai ancora utilizzato tutti i tuoi giorni di ferie. Buon anno nuovo!"
    )

    private val russian = listOf(
        "Пусть Новый год принесет с собой радость и счастье, исполнит все мечты и желания! Счастливого Нового года!",
        "Пусть наступающий год будет наполнен новыми возможностями, яркими моментами и приятными сюрпризами! С Новым годом!",
        "Желаю, чтобы Новый год был началом чего-то нового и удивительного в твоей жизни. Пусть он принесет процветание и успехи! С Новым годом!",
        "Счастья, здоровья, любви и исполнения самых заветных желаний в Новом году! Пусть каждый день будет наполнен радостью и удачей! С Новым годом!",
        "Пусть Новый год принесет с собой новые возможности, смелые решения и яркие победы! Счастливого Нового года!",
        "Желаю, чтобы каждый день Нового года был полон счастья, улыбок и благополучия. Пусть он принесет много радостных моментов! С Новым годом!",
        "Пускай Новый год принесет тепло и свет в твой дом, сбудутся самые сокровенные мечты и каждый день будет наполнен улыбками! С Новым годом!",
        "Желаю, чтобы наступающий год принес волшебство, счастье и успех во всех начинаниях. Пусть он будет ярким и запоминающимся! С Новым годом!",
        "Пусть Новый год станет началом новой жизни, полной возможностей и достижений. Счастливого и успешного года!",
        "С наступающим Новым годом! Желаю вам и вашим близким много радости, здоровья, благополучия и удачи во всех начинаниях!",
        "С Новым годом! Пусть наступающий год принесет тебе радость, счастье и удачу",
        "Пусть Новый год будет полон приятных сюрпризов, замечательных моментов и ярких впечатлений. С Новым годом!",
        "Поздравляю с Новым годом! Желаю тебе незабываемого праздника и много счастливых моментов в наступающем году",
        "С Новым годом! Пусть он будет полон волшебства, счастья и любви",
        "Пусть Новый год станет для тебя годом новых возможностей, успехов и побед. С Новым годом!",
        "С Новым годом! Желаю тебе мира, любви и благополучия в наступающем году",
        "С Новым годом! Пусть он принесет тебе мир, счастье и исполнение самых смелых мечт",
        "Поздравляю с Новым годом! Желаю тебе незабываемых впечатлений, новых открытий и успешного начала всех начинаний",
        "С Новым годом! Пусть он будет полон приятных сюрпризов, интересных встреч и ярких эмоций",
        "Поздравляю с Новым годом! Желаю тебе мира, любви, счастья и благополучия в наступающем году",
        "С Новым годом! Пусть он будет насыщен яркими событиями, веселыми моментами и новыми достижениями",
        "Пусть Новый год станет для тебя годом новых свершений, успехов и побед. С Новым годом!",
        "С Новым годом! Пусть этот год будет полон удач, новых возможностей и светлых моментов",
        "Поздравляю с Новым годом! Желаю тебе мира, радости и бесконечного счастья в наступающем году",
        "С Новым годом! Пусть он принесет тебе много счастливых моментов, новых достижений и большое количество удачи",
        "Поздравляю с Новым годом! Желаю тебе незабываемых впечатлений, ярких моментов и много счастливых дней",
        "С Новым годом! Пусть он будет полон приятных сюрпризов, новых открытий и невероятных успехов",
        "Пусть Новый год будет годом радости, счастья и успеха. С Новым годом!",
        "С Новым годом! Пусть он принесет тебе мир, любовь и неограниченное счастье",
        "Поздравляю с Новым годом! Желаю тебе много улыбок, неиссякаемого вдохновения и ярких, запоминающихся моментов",
        "С Новым годом! Пусть он принесет тебе исполнение самых заветных мечт, успех во всех начинаниях и много позитивных эмоций",
        "Поздравляю с Новым годом! Желаю тебе невероятных приключений, новых открытий и ошеломляющих успехов",
        "С Новым годом! Пусть он будет полон счастья, любви и незабываемых моментов",
        "Пусть Новый год станет началом новых удивительных достижений и побед. С Новым годом!",
        "С Новым годом! Пусть он будет полон счастья, новых возможностей и удивительных моментов",
        "Поздравляю с Новым годом! Желаю тебе мира, любви и благополучия в наступающем году",
        "С Новым годом! Пусть он станет началом чего-то великого и невероятного в твоей жизни",
        "Поздравляю с Новым годом! Желаю тебе удачи, здоровья и много радостных моментов",
        "С Новым годом! Пусть он принесет тебе счастье, успех и исполнение всех желаний",
        "Пусть Новый год будет полон удивительных открытий, интересных встреч и новых достижений. С Новым годом!",
        "С Новым годом! Пусть он принесет тебе столько счастья, сколько весит мой кот. И верь мне, это много!",
        "Поздравляю с Новым годом! Желаю, чтобы в этом году твои соседи наконец-то узнали, как выглядит тишина",
        "С Новым годом! Пусть твои решения о здоровом образе жизни длится дольше, чем остатки от новогоднего стола",
        "Поздравляю с Новым годом! Желаю тебе столько радости, сколько звезд на небе... хотя, может, лучше сколько денег в банке",
        "С Новым годом! Желаю тебе столько удачи, чтобы даже прошлогодние новогодние игрушки не ломались",
        "Пусть в Новом году твоя жизнь будет такой же сладкой, как новогодний шоколадный календарь. Но только помни: не оближись! С Новым годом!",
        "С Новым годом! Пусть он будет лучше предыдущего... Ну, это вроде бы не так сложно, правда?",
        "Поздравляю с Новым годом! Желаю тебе здоровья и счастья. Ну и богатства, если оно ничего не испортит",
        "С Новым годом! Желаю тебе столько успеха, чтобы твоя бывшая школьная учительница рассказывала о тебе на родительских собраниях",
        "Поздравляю с Новым годом! Желаю тебе терпения... потому что остальное ты можешь купить",
        "С Новым годом! Пусть в этом году все твои проблемы исчезнут так же быстро, как исчезают мои деньги в супермаркете",
        "Пусть в Новом году все твои друзья понимают твои шутки без объяснений. С Новым годом!",
        "С Новым годом! Пусть твоя новогодняя елка будет стройнее тебя, а подарки под ней - толще твоего кошелька",
        "Поздравляю с Новым годом! Желаю тебе исполнения всех желаний... но помни, что некоторые лучше не загадывать вслух",
        "С Новым годом! Желаю тебе больше удачи, чем у кошки, которая нашла целую коробку для игры",
        "Поздравляю с Новым годом! Желаю тебе достичь таких высот, чтобы люди начали спрашивать, откуда у тебя кислородная маска",
        "С Новым годом! Пусть твой кошелек в этом году станет таким же здоровым, как моя новогодняя елка",
        "Пусть Новый год будет полон удивительных открытий. Например, пусть ты обнаружишь, что ты еще не использовал все отпускные. С Новым годом!"
    )

    private val spanish = listOf(
        "¡Que el Año Nuevo traiga alegría y felicidad, cumpla todos tus sueños y deseos! ¡Feliz Año Nuevo!",
        "¡Que el próximo año esté lleno de nuevas oportunidades, momentos brillantes y agradables sorpresas! ¡Feliz Año Nuevo!",
        "Deseo que el Año Nuevo sea el comienzo de algo nuevo y sorprendente en tu vida. ¡Que traiga prosperidad y éxito! ¡Feliz Año Nuevo!",
        "Felicidad, salud, amor y la realización de tus deseos más profundos en el Año Nuevo. ¡Que cada día esté lleno de alegría y buena fortuna! ¡Feliz Año Nuevo!",
        "¡Que el Año Nuevo traiga nuevas posibilidades, decisiones audaces y gloriosas victorias! ¡Feliz Año Nuevo!",
        "Deseo que cada día del Año Nuevo esté lleno de felicidad, sonrisas y prosperidad. ¡Que traiga muchos momentos de alegría! ¡Feliz Año Nuevo!",
        "¡Que el Año Nuevo traiga calidez y luz a tu hogar, cumpla tus sueños más queridos y llene cada día de sonrisas! ¡Feliz Año Nuevo!",
        "Deseo que el próximo año traiga magia, felicidad y éxito en todas tus empresas. ¡Que sea brillante y memorable! ¡Feliz Año Nuevo!",
        "¡Que el Año Nuevo marque el comienzo de una nueva vida llena de oportunidades y logros. ¡Te deseo un año feliz y exitoso!",
        "¡Feliz Año Nuevo! ¡Deseo a ti y a tus seres queridos abundante alegría, salud, prosperidad y éxito en todas tus empresas!",
        "¡Feliz Año Nuevo! Te deseo a ti y a tus seres queridos mucha alegría, salud, prosperidad y éxito en todas tus empresas",
        "¡Feliz Año Nuevo! Que el próximo año te traiga alegría, felicidad y éxito",
        "Que el Año Nuevo esté lleno de sorpresas agradables, momentos maravillosos y experiencias vibrantes. ¡Feliz Año Nuevo!",
        "¡Feliz Año Nuevo! Te deseo unas fiestas inolvidables y muchos momentos felices en el próximo año",
        "¡Feliz Año Nuevo! Que esté lleno de magia, felicidad y amor",
        "Que el Año Nuevo sea un año lleno de nuevas oportunidades, éxitos y victorias. ¡Feliz Año Nuevo!",
        "¡Feliz Año Nuevo! Te deseo paz, amor y prosperidad en el próximo año",
        "¡Feliz Año Nuevo! Que te brinde paz, felicidad y la realización de tus sueños más audaces",
        "¡Feliz Año Nuevo! Te deseo experiencias inolvidables, nuevos descubrimientos y un comienzo exitoso en todas tus empresas",
        "¡Feliz Año Nuevo! Que esté lleno de sorpresas agradables, encuentros interesantes y emociones intensas",
        "¡Feliz Año Nuevo! Te deseo paz, alegría y felicidad infinita en el próximo año",
        "¡Feliz Año Nuevo! Que esté lleno de eventos emocionantes, momentos divertidos y nuevos logros",
        "Que el Año Nuevo sea un año de nuevos logros, éxitos y victorias. ¡Feliz Año Nuevo!",
        "¡Feliz Año Nuevo! Que este año esté lleno de suerte, nuevas oportunidades y momentos brillantes",
        "¡Feliz Año Nuevo! Te deseo paz, alegría y felicidad infinita en el próximo año",
        "¡Feliz Año Nuevo! Que te traiga muchos momentos felices, nuevos logros y mucha suerte",
        "¡Feliz Año Nuevo! Te deseo experiencias inolvidables, momentos brillantes y muchos días felices",
        "¡Feliz Año Nuevo! Que esté lleno de sorpresas agradables, nuevos descubrimientos e increíbles éxitos",
        "Que el Año Nuevo sea un año de alegría, felicidad y éxito. ¡Feliz Año Nuevo!",
        "¡Feliz Año Nuevo! Que te traiga paz, amor y felicidad ilimitada",
        "¡Feliz Año Nuevo! Te deseo muchas sonrisas, una inspiración inagotable y momentos brillantes e inolvidables",
        "¡Feliz Año Nuevo! Que te traiga la realización de tus sueños más preciados, éxito en todas tus empresas y muchas emociones positivas",
        "¡Feliz Año Nuevo! Te deseo aventuras increíbles, nuevos descubrimientos y asombrosos éxitos",
        "¡Feliz Año Nuevo! Que esté lleno de felicidad, amor y momentos inolvidables",
        "Que el Año Nuevo sea el comienzo de nuevos logros y victorias asombrosas. ¡Feliz Año Nuevo!",
        "¡Feliz Año Nuevo! Que esté lleno de felicidad, nuevas oportunidades y momentos sorprendentes",
        "¡Feliz Año Nuevo! Que sea el comienzo de algo grandioso e increíble en tu vida",
        "¡Feliz Año Nuevo! Te felicito y te deseo suerte, salud y muchos momentos de alegría",
        "¡Feliz Año Nuevo! Que te traiga felicidad, éxito y la realización de todos tus deseos",
        "Que el Año Nuevo esté lleno de descubrimientos asombrosos, encuentros interesantes y nuevos logros. ¡Feliz Año Nuevo!",
        "¡Feliz Año Nuevo! Que te traiga tanta felicidad como pesa mi gato. ¡Y créeme, eso es mucho!",
        "Felicitaciones por el Año Nuevo. ¡Deseo que este año tus vecinos finalmente descubran cómo se ve el silencio!",
        "¡Feliz Año Nuevo! Que tus resoluciones de estilo de vida saludable duren más que los restos de la mesa de Año Nuevo",
        "Felicitaciones por el Año Nuevo. ¡Deseo que tengas tanta alegría como estrellas en el cielo... aunque tal vez sea mejor cuánto dinero tienes en el banco!",
        "¡Feliz Año Nuevo! Deseo que tengas tanta suerte que incluso los adornos de Año Nuevo del año pasado no se rompan",
        "Que tu vida en el Año Nuevo sea tan dulce como un calendario de chocolate navideño. ¡Pero recuerda: no te lo comas todo! ¡Feliz Año Nuevo!",
        "¡Feliz Año Nuevo! Que sea mejor que el anterior... Bueno, eso parece que no es tan difícil, ¿verdad?",
        "Felicitaciones por el Año Nuevo. Te deseo salud y felicidad. Y riqueza, si no arruina nada",
        "¡Feliz Año Nuevo! Deseo que tengas tanto éxito que tu antigua maestra de escuela hable de ti en las reuniones de padres",
        "Felicitaciones por el Año Nuevo. Te deseo paciencia... porque el resto lo puedes comprar",
        "¡Feliz Año Nuevo! Deseo que todos tus problemas desaparezcan tan rápido como mi dinero en el supermercado",
        "Que en el Año Nuevo todos tus amigos entiendan tus chistes sin explicaciones. ¡Feliz Año Nuevo!",
        "¡Feliz Año Nuevo! Que tu árbol de Navidad sea más delgado que tú y los regalos debajo de él sean más gruesos que tu billetera",
        "Felicitaciones por el Año Nuevo. Deseo que se cumplan todos tus deseos... pero recuerda que algunos es mejor no decirlos en voz alta",
        "¡Feliz Año Nuevo! Deseo que tengas más suerte que un gato que encuentra una caja entera para jugar",
        "Felicitaciones por el Año Nuevo. Deseo que alcances alturas tan grandes que las personas te pregunten de dónde obtienes la máscara de oxígeno",
        "¡Feliz Año Nuevo! Que tu billetera este año esté tan sana como mi árbol de Navidad",
        "Que el Año Nuevo esté lleno de descubrimientos asombrosos. Por ejemplo, que descubras que aún no has usado todos tus días de vacaciones. ¡Feliz Año Nuevo!"
    )

    private val german = listOf(
        "Möge das neue Jahr Freude und Glück bringen, all deine Träume und Wünsche erfüllen! Frohes Neues Jahr!",
        "Möge das kommende Jahr neue Möglichkeiten, strahlende Momente und angenehme Überraschungen bringen! Frohes Neues Jahr!",
        "Ich wünsche dir, dass das neue Jahr der Beginn von etwas Neuem und Erstaunlichem in deinem Leben ist. Möge es Wohlstand und Erfolg bringen! Frohes Neues Jahr!",
        "Glück, Gesundheit, Liebe und die Erfüllung deiner tiefsten Wünsche im neuen Jahr! Möge jeder Tag voller Freude und Glück sein! Frohes Neues Jahr!",
        "Möge das neue Jahr neue Möglichkeiten, mutige Entscheidungen und glorreiche Siege bringen! Frohes Neues Jahr!",
        "Ich wünsche jedem Tag im neuen Jahr Glück, Lächeln und Wohlstand. Möge es viele freudige Momente bringen! Frohes Neues Jahr!",
        "Möge das neue Jahr Wärme und Licht in dein Zuhause bringen, deine liebsten Träume erfüllen und jeden Tag mit Lächeln füllen! Frohes Neues Jahr!",
        "Ich wünsche dir, dass das kommende Jahr Magie, Glück und Erfolg in all deinen Unternehmungen bringt. Möge es hell und unvergesslich sein! Frohes Neues Jahr!",
        "Möge das neue Jahr den Beginn eines neuen Lebens voller Möglichkeiten und Erfolge markieren. Ich wünsche dir ein glückliches und erfolgreiches Jahr!",
        "Frohes Neues Jahr! Ich wünsche dir und deinen Lieben reichlich Freude, Gesundheit, Wohlstand und Erfolg in all deinen Unternehmungen!",
        "Frohes neues Jahr! Ich wünsche Ihnen und Ihren Lieben viel Freude, Gesundheit, Wohlstand und Erfolg in all Ihren Unternehmungen!",
        "Frohes neues Jahr! Möge das kommende Jahr dir Freude, Glück und Erfolg bringen.",
        "Möge das neue Jahr voller angenehmer Überraschungen, wunderbarer Momente und lebendiger Eindrücke sein. Frohes neues Jahr!",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir ein unvergessliches Fest und viele glückliche Momente im kommenden Jahr.",
        "Frohes neues Jahr! Möge es voller Magie, Glück und Liebe sein.",
        "Möge das neue Jahr für dich ein Jahr neuer Möglichkeiten, Erfolge und Siege sein. Frohes neues Jahr!",
        "Frohes neues Jahr! Ich wünsche dir Frieden, Liebe und Wohlstand im kommenden Jahr.",
        "Frohes neues Jahr! Möge es dir Frieden, Glück und die Erfüllung deiner mutigsten Träume bringen.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir unvergessliche Erlebnisse, neue Entdeckungen und einen erfolgreichen Start in all deine Vorhaben.",
        "Frohes neues Jahr! Möge es voller angenehmer Überraschungen, interessanter Begegnungen und lebendiger Emotionen sein.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir Frieden, Freude und endloses Glück im kommenden Jahr.",
        "Frohes neues Jahr! Möge es voller aufregender Ereignisse, fröhlicher Momente und neuer Errungenschaften sein.",
        "Möge das neue Jahr für dich ein Jahr neuer Erfahrungen, Erfolge und Siege sein. Frohes neues Jahr!",
        "Frohes neues Jahr! Möge dieses Jahr voller Glück, neuer Möglichkeiten und strahlender Momente sein.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir Frieden, Freude und grenzenloses Glück im kommenden Jahr.",
        "Frohes neues Jahr! Möge es dir viele glückliche Momente, neue Errungenschaften und jede Menge Glück bringen.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir unvergessliche Erlebnisse, lebendige Momente und viele glückliche Tage.",
        "Frohes neues Jahr! Möge es voller angenehmer Überraschungen, neuer Entdeckungen und unglaublicher Erfolge sein.",
        "Möge das neue Jahr ein Jahr voller Freude, Glück und Erfolg sein. Frohes neues Jahr!",
        "Frohes neues Jahr! Möge es dir Frieden, Liebe und unendliches Glück bringen.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir viele Lächeln, unerschöpfliche Inspiration und lebhafte, unvergessliche Momente.",
        "Frohes neues Jahr! Möge es dir die Erfüllung deiner tiefsten Wünsche, Erfolg in all deinen Unternehmungen und eine Fülle positiver Emotionen bringen.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir unglaubliche Abenteuer, neue Entdeckungen und überwältigende Erfolge.",
        "Möge das neue Jahr der Beginn neuer wundervoller Errungenschaften und Siege sein. Frohes neues Jahr!",
        "Frohes neues Jahr! Möge es voller Glück, neuen Möglichkeiten und erstaunlichen Momenten sein.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir Frieden, Liebe und Wohlstand im kommenden Jahr.",
        "Frohes neues Jahr! Möge es der Beginn von etwas Großartigem und Unglaublichem in deinem Leben sein.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir Glück, Gesundheit und viele freudige Momente.",
        "Frohes neues Jahr! Möge es dir Glück, Erfolg und die Erfüllung aller Wünsche bringen.",
        "Möge das neue Jahr voller erstaunlicher Entdeckungen, interessanter Begegnungen und neuer Erfolge sein. Frohes neues Jahr!",
        "Frohes neues Jahr! Möge es dir so viel Glück bringen, wie meine Katze wiegt. Und glaube mir, das ist viel!",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir, dass deine Nachbarn endlich kennenlernen, wie Stille aussieht.",
        "Frohes neues Jahr! Mögen deine Vorsätze für einen gesunden Lebensstil länger halten als die Überbleibsel vom Neujahrstisch.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir so viel Freude, wie Sterne am Himmel... obwohl vielleicht besser so viel Geld, wie du auf der Bank hast.",
        "Frohes neues Jahr! Ich wünsche dir so viel Glück, dass selbst die Weihnachtsdekoration vom letzten Jahr nicht kaputtgeht.",
        "Möge dein Leben im neuen Jahr genauso süß sein wie ein Schokoladen-Adventskalender. Aber denk daran: Nicht ablecken! Frohes neues Jahr!",
        "Frohes neues Jahr! Möge es besser sein als das letzte... Nun ja, das sollte nicht allzu schwer sein, oder?",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir Gesundheit und Glück. Und Reichtum, wenn es nichts kaputt macht.",
        "Frohes neues Jahr! Ich wünsche dir so viel Erfolg, dass deine ehemalige Schul-Lehrerin über dich bei Elternversammlungen spricht.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir Geduld... denn den Rest kannst du kaufen.",
        "Frohes neues Jahr! Mögen alle deine Probleme im neuen Jahr genauso schnell verschwinden wie mein Geld im Supermarkt.",
        "Möge in diesem Jahr all deine Freunde deine Witze ohne Erklärung verstehen. Frohes neues Jahr!",
        "Frohes neues Jahr! Möge dein Weihnachtsbaum dünner sein als du und die Geschenke darunter dicker als dein Geldbeutel.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir, dass sich alle deine Wünsche erfüllen... aber bedenke, dass manche besser unausgesprochen bleiben.",
        "Frohes neues Jahr! Ich wünsche dir mehr Glück als eine Katze, die eine ganze Schachtel mit Spielzeug gefunden hat.",
        "Ich gratuliere zum neuen Jahr! Ich wünsche dir, dass du so hoch hinaufsteigst, dass die Leute sich fragen, woher du den Sauerstoffbehälter hast.",
        "Frohes neues Jahr! Möge dein Geldbeutel in diesem Jahr genauso gesund sein wie mein Weihnachtsbaum.",
        "Möge das neue Jahr voller erstaunlicher Entdeckungen sein. Zum Beispiel, dass du noch nicht all deine Urlaubstage verbraucht hast. Frohes neues Jahr!"
    )
}