package com.sosinvitalii.database.congratulations

object WeddingCongratulations {
    fun fetch(language: Language): List<String> {
        return when (language) {
            Language.EN -> english
            Language.IT -> italian
            Language.RU -> russian
            Language.ES -> spanish
            Language.DE -> german
        }
    }

    private val english = listOf(
        "May your marriage be a strong union of love, understanding, and happiness! Congratulations on your long-awaited wedding day!",
        "I wish that every day of your married life is filled with joy, mutual support, and tenderness! Congratulations on your union!",
        "May your hearts always beat in unison, and may your days be filled with love and happiness! Best wishes on your wedding day!",
        "Congratulations on the most wonderful day of your life! May your marriage be long, happy, and filled with only the most beautiful moments!",
        "I wish you infinite love, mutual respect, and happiness on this beautiful journey you have chosen together. Congratulations on your union!",
        "May your marriage be like a fairytale, where every day is filled with magic and happiness! Congratulations on this significant and romantic milestone in your life!",
        "Wishing you all the best on this special day! May your marriage be filled with joy, comfort, and harmony. Congratulations on your wedding!",
        "Congratulations on the beginning of a new chapter in your life! Wishing you beautiful moments, tenderness, and unforgettable memories together. Happy wedding!",
        "May your family happiness be unshakable, and may your days be filled with love and happy smiles! Congratulations on your wedding day!",
        "Happy wedding! I wish you many years of a happy and harmonious life, filled with love, understanding, and joyful moments!",
        "Happy wedding! Wishing you many years of a happy and harmonious life, filled with love, understanding, and joyful moments!",
        "Congratulations on the most important day of your life! May your marriage be filled with love, joy, and understanding.",
        "Happy wedding to you! Wishing you abundant growing love and eternal happiness together.",
        "Congratulations on this magical day! May you experience all the joys and trials that life brings together.",
        "Today your love is crowned with marriage, and I wholeheartedly congratulate you on this wonderful event! Wishing you unforgettable moments of happiness and joy.",
        "I wish you to build a strong and happy marriage, full of love, kindness, and mutual respect.",
        "May your marriage be as beautiful and vibrant as today. Happy wedding to you!",
        "On this beautiful day! May your marriage be filled with warmth, love, and mutual support.",
        "Congratulations on this wonderful occasion! Wishing you unforgettable moments of happiness, love, and prosperity.",
        "Today you embark on a new chapter in your life, and I wholeheartedly congratulate you on this! Wishing you to always remain faithful to each other.",
        "I wish you to create a strong and happy marriage, full of love, joy, and kindness.",
        "May your marriage be filled with happiness, love, and understanding. Happy wedding to you!",
        "May your marriage be as bright and joyful as this day. Congratulations!",
        "Happy wedding to you! May your partnership be filled with laughter, adventures, and boundless love.",
        "Congratulations on this special day! Wishing you a long and happy life together, full of mutual understanding and tenderness.",
        "Today, you promise to love, respect, and support each other. Congratulations on this significant step in your life! Wishing you infinite love and happiness.",
        "May your marriage be adorned with mutual trust, tenderness, and warmth. Congratulations on this wonderful union!",
        "Wishing you many long and happy years together, filled with joy, understanding, and harmony. Happy wedding to you!",
        "Congratulations on this important day in your life! Wishing you endless love, inspiration, and joy together.",
        "Happy wedding! May your journey through life together be filled with tenderness, laughter, and mutual support.",
        "Congratulations on this beautiful day! Wishing that every day of yours is filled with love and harmony.",
        "Today, you unite in an unbreakable bond, and I am happy for both of you! Wishing you countless happy moments and unforgettable adventures together.",
        "May your marriage be strong and enduring, like a diamond. Congratulations on this splendid beginning of your journey together!",
        "Wishing you a happy and radiant wedding! May your hearts always be filled with love and warmed by the embrace of reciprocity.",
        "Congratulations on this significant day in your life! Wishing you endless love, joy, and prosperity throughout your journey together.",
        "Happy wedding! May every day of your marriage be filled with smiles, happiness, and mutual admiration.",
        "Congratulations on this beautiful beginning of a new chapter in your life! Wishing you enduring love and unforgettable moments together.",
        "Today you become husband and wife, and it's wonderful! Congratulations on this wonderful union, and may you have many happy years together.",
        "May your marriage be as strong as a ship sailing through the turbulent waves of life. Congratulations on this important step, and may you have a smooth and joyful journey.",
        "Wishing you many years of happiness together, filled with love, understanding, and great adventures. Happy wedding!",
        "Congratulations on your wedding! Wishing you lots of love, a comfortable bed, and an endless supply of humor.",
        "Happy wedding! May your marriage be filled with precious moments, harmony, and mutual respect.",
        "Congratulations on this wonderful day! Wishing you infinite love, joyful adventures, and happy family traditions.",
        "Today you promise to be there for each other in all the joys and challenges of life. Congratulations on this momentous occasion, and may you have a strong marriage.",
        "May your marriage be a source of inspiration, support, and mutual growth. Congratulations on this important step together!",
        "Wishing you a happy and long-lasting marriage! May your home be filled with love, warmth, and coziness.",
        "Congratulations on this beautiful union! Wishing you to be each other's support, understanding, and faithful companions on the journey of life.",
        "Happy wedding! May your marriage be so strong that no mother-in-law can break it.",
        "Congratulations on this special day! Wishing you lots of love, agreement, and a good sense of humor to diffuse family disputes.",
        "Today you embark on a new chapter in your life, which means you will have someone to share cookies with and argue over TV programs. Congratulations!",
        "May your marriage be so wonderful that even your partner won't dream of superhero adventures.",
        "Wishing you a happy wedding! May your marriage be filled not only with love and understanding but also with healthy doses of laughter and sarcasm.",
        "Congratulations on this momentous day! Wishing you a journey through life together where every mistake becomes a beautiful anecdote in the future.",
        "Happy wedding! May your marriage be so stable that even the TV remote won't cause marital disputes.",
        "Congratulations on this wonderful day! Wishing you as much agreement as needed to choose a movie for the evening.",
        "Today you enter into marriage, which means you will always have someone who agrees with you even when you're wrong. Congratulations!",
        "May your marriage be like a good comedy - funny, unforgettable, and happy until the very end.",
        "Wishing you a happy wedding! May your marriage be like a salad - a combination of different ingredients that make life tastier.",
        "Congratulations on this special day! Wishing you fewer marital quarrels and more funny moments that you will remember with a smile."
    )

    private val italian = listOf(
        "Che il vostro matrimonio sia una solida unione d'amore, comprensione e felicità! Congratulazioni per il vostro tanto atteso giorno di nozze!",
        "Auguro che ogni giorno della vostra vita matrimoniale sia pieno di gioia, sostegno reciproco e tenerezza! Congratulazioni per il vostro matrimonio!",
        "Che i vostri cuori batano sempre all'unisono e che i vostri giorni siano pieni di amore e felicità! I migliori auguri per il vostro giorno di nozze!",
        "Congratulazioni per il giorno più meraviglioso della vostra vita! Che il vostro matrimonio sia lungo, felice e pieno solo dei momenti più belli!",
        "Vi auguro un amore infinito, rispetto reciproco e felicità in questo bellissimo cammino che avete scelto insieme. Congratulazioni per il vostro matrimonio!",
        "Che il vostro matrimonio sia come una fiaba, in cui ogni giorno sia pieno di magia e felicità! Congratulazioni per questo traguardo significativo e romantico nella vostra vita!",
        "I migliori auguri in questo giorno speciale! Che il vostro matrimonio sia pieno di gioia, conforto e armonia. Congratulazioni per il vostro matrimonio!",
        "Congratulazioni per l'inizio di un nuovo capitolo nella vostra vita! Vi auguro momenti splendidi, tenerezza e ricordi indimenticabili insieme. Felice matrimonio!",
        "Che la vostra felicità familiare sia salda e che i vostri giorni siano pieni di amore e sorrisi felici! Congratulazioni per il vostro giorno di nozze!",
        "Felice matrimonio! Vi auguro tanti anni di una vita felice e armoniosa, piena di amore, comprensione e momenti gioiosi!",
        "Auguri di matrimonio! Vi auguro anni felici di vita insieme, piena di amore, comprensione e momenti felici!",
        "Vi congratulo per il giorno più importante della vostra vita! Possa il vostro matrimonio essere pieno di amore, gioia e comprensione reciproca",
        "Buon matrimonio! Vi auguro un amore che cresca abbondantemente e una felicità eterna insieme",
        "Congratulazioni per questo giorno magico! Vi auguro di affrontare insieme tutte le gioie e le sfide che la vita porta",
        "Oggi il vostro amore è coronato dal matrimonio e vi congratulo di cuore per questo meraviglioso evento! Vi auguro momenti indimenticabili di felicità e gioia",
        "Vi auguro di creare un matrimonio solido e felice, pieno di amore, gentilezza e rispetto reciproco",
        "Che il vostro matrimonio sia tanto bello e luminoso quanto l'odierna giornata. Buon matrimonio!",
        "In questa splendida giornata! Possa il vostro matrimonio essere pieno di calore, amore e supporto reciproco",
        "Vi congratulo per questo meraviglioso evento! Vi auguro momenti indimenticabili di felicità, amore e prosperità",
        "Oggi iniziate un nuovo capitolo della vostra vita e vi congratulo di cuore! Vi auguro di rimanere sempre fedeli l'uno all'altro",
        "Vi auguro di creare un matrimonio forte e felice, pieno di amore, gioia e gentilezza",
        "Che il vostro matrimonio sia pieno di felicità, amore e comprensione reciproca. Buon matrimonio!",
        "Vi auguro che il vostro matrimonio sia altrettanto luminoso e gioioso come l'odierna giornata. Congratulazioni!",
        "Buon matrimonio! Possa la vostra partnership essere riempita di risate, avventure e amore infinito",
        "Congratulazioni per questo giorno speciale! Vi auguro una lunga e felice vita insieme, piena di comprensione reciproca e tenerezza",
        "Oggi promettete di amarvi, rispettarvi e sostenervi reciprocamente. Congratulazioni per questo importante passo nella vostra vita! Vi auguro un amore infinito e felicità",
        "Che il vostro matrimonio sia adornato da fiducia reciproca, dolcezza e calore. Vi congratulo per questa meravigliosa unione!",
        "Vi auguro anni lunghi e felici insieme, pieni di gioia, comprensione reciproca e armonia. Buon matrimonio!",
        "Congratulazioni per questo giorno importante nella vostra vita! Vi auguro un amore infinito, ispirazione e gioia insieme",
        "Buon matrimonio! Che il vostro viaggio insieme nella vita sia riempito di tenerezza, risate e supporto reciproco",
        "Congratulazioni per questo splendido giorno! Vi auguro che ogni vostro giorno sia pieno di amore e armonia",
        "Oggi vi unite in un indissolubile legame e sono felice per entrambi! Vi auguro molti momenti felici e avventurosi insieme",
        "Che il vostro matrimonio sia solido e duraturo come un diamante. Congratulazioni per questo magnifico inizio del vostro cammino insieme!",
        "Vi auguro un matrimonio felice e luminoso! Che il vostro cuore sia sempre pieno d'amore e si riscaldi con il calore della reciproca affezione",
        "Congratulazioni per questo significativo giorno nella vostra vita! Vi auguro un amore infinito, gioia e prosperità lungo tutto il vostro percorso insieme",
        "Auguri per il vostro matrimonio! Che ogni giorno del vostro matrimonio sia riempito di sorrisi, felicità e ammirazione reciproca",
        "Congratulazioni per questo meraviglioso inizio di un nuovo capitolo nella vostra vita! Vi auguro un amore duraturo e momenti indimenticabili insieme",
        "Oggi diventate marito e moglie, ed è stupendo! Congratulazioni per questa meravigliosa unione e vi auguro molti anni felici insieme",
        "Che il vostro matrimonio sia forte come una nave che naviga tra le onde agitate della vita. Congratulazioni per questo passo importante e vi auguro una navigazione tranquilla e gioiosa",
        "Vi auguro anni felici e pieni di amore, comprensione reciproca e grandi avventure. Felice matrimonio!",
        "Congratulazioni per il vostro matrimonio! Vi auguro tanto amore, un letto comodo e una riserva infinita di umorismo",
        "Auguri per il vostro matrimonio! Che il vostro matrimonio sia ricco di momenti preziosi, accordo e rispetto reciproco",
        "Congratulazioni per questo splendido giorno! Vi auguro un amore infinito, avventure divertenti e felici tradizioni familiari",
        "Oggi vi impegnate a stare l'uno accanto all'altro in tutte le gioie e le sfide della vita. Congratulazioni per questo evento significativo e vi auguro un matrimonio solido",
        "Che il vostro matrimonio sia una fonte di ispirazione, supporto e sviluppo reciproco. Congratulazioni per questo passo importante insieme!",
        "Vi auguro un matrimonio felice e duraturo! Che la vostra casa sia piena di amore, calore e comfort",
        "Congratulazioni per questa bellissima unione! Vi auguro di essere un sostegno l'uno per l'altro, di capirvi e di essere fedeli compagni di viaggio lungo il cammino della vita",
        "Felice matrimonio! Che il vostro matrimonio sia così solido che nemmeno una suocera possa distruggerlo",
        "Congratulazioni per questo splendido giorno! Vi auguro tanto amore, accordo e una scorta di buon umore per risolvere le dispute familiari",
        "Oggi iniziate un nuovo capitolo della vostra vita e questo significa che avrete qualcuno con cui condividere i biscotti e che vi impedirà di scegliere il programma in TV. Congratulazioni!",
        "Che il vostro matrimonio sia così meraviglioso che nemmeno il vostro partner sognerebbe avventure da supereroi",
        "Vi auguro un matrimonio felice! Che il vostro matrimonio sia riempito non solo di amore e comprensione reciproca, ma anche di sane dosi di risate e sarcasmo",
        "Congratulazioni per questo giorno significativo! Vi auguro di viaggiare insieme lungo la vita, dove ogni errore diventerà un bel racconto divertente per il futuro",
        "Felice matrimonio! Che il vostro matrimonio sia così stabile che nemmeno il telecomando della TV possa causare litigi coniugali",
        "Congratulazioni per questo splendido giorno! Vi auguro tanta armonia quanto basta per scegliere un film serale",
        "Oggi vi state unendo in matrimonio, il che significa che avrete sempre qualcuno che sarà d'accordo con voi, anche quando avete torto. Congratulazioni!",
        "Che il vostro matrimonio sia come una commedia di qualità: divertente, indimenticabile e felice fino alla fine",
        "Auguri per il vostro matrimonio! Che il vostro matrimonio sia come un'insalata russa: una combinazione di diversi ingredienti che rende la vita più gustosa",
        "Congratulazioni per questo giorno speciale! Vi auguro meno litigi coniugali e più momenti divertenti che ricorderete con un sorriso"
    )

    private val russian = listOf(
        "Пусть ваш брак будет крепким союзом любви, взаимопонимания и счастья! Поздравляю с долгожданным свадебным днем!",
        "Желаю вам, чтобы каждый день вашей совместной жизни был наполнен радостью, взаимной поддержкой и нежностью! Поздравляю с бракосочетанием!",
        "Пусть ваши сердца всегда бьются в едином ритме, а ваши дни наполнены любовью и счастьем! С наилучшими пожеланиями в день вашей свадьбы!",
        "Поздравляю с самым замечательным днем в вашей жизни! Пусть ваш брак будет долгим, счастливым и наполненным только самыми прекрасными моментами!",
        "Желаю вам бесконечной любви, взаимного уважения и счастья на этом прекрасном пути, который вы выбрали вместе. Поздравляю с бракосочетанием!",
        "Пусть ваш брак будет как сказка, в которой каждый день будет наполнен волшебством и счастьем! Поздравляю с важным и романтичным событием в вашей жизни!",
        "С наилучшими пожеланиями в этот особый день! Пусть ваш брак будет полон радости, уюта и гармонии. Поздравляю с свадьбой!",
        "Поздравляю с началом новой главы в вашей жизни! Желаю вам прекрасных мгновений, нежности и незабываемых моментов вместе. Счастливой свадьбы!",
        "Пусть ваше семейное счастье будет непоколебимым, а ваши дни будут наполнены любовью и счастливыми улыбками! Поздравляю с днем свадьбы!",

        "Счастливой свадьбы! Желаю вам долгих лет счастливой и согласованной жизни, полной любви, взаимопонимания и счастливых мгновений!",
        "Поздравляю вас с самым важным днем в вашей жизни! Пусть ваш брак будет полон любви, радости и взаимопонимания",
        "Счастливой вам свадьбы! Желаю вам обильно растущей любви и вечного счастья вместе",
        "Поздравляю с этим волшебным днем! Желаю вам вместе пережить все радости и испытания, которые приносит жизнь",
        "Сегодня ваша любовь увенчана браком, и я от всего сердца поздравляю вас с этим замечательным событием! Желаю вам незабываемых моментов счастья и радости",
        "Желаю вам создать прочный и счастливый брак, полный любви, доброты и взаимного уважения",
        "Пусть ваш брак будет таким же красивым и ярким, как сегодняшний день. Счастливой вам свадьбы!",
        "С этим прекрасным днем! Пусть ваш брак будет полон теплоты, любви и взаимной поддержки",
        "Поздравляю вас с этим замечательным событием! Желаю вам незабываемых моментов счастья, любви и благополучия",
        "Сегодня вы начинаете новую главу в вашей жизни, и я от всего сердца поздравляю вас с этим! Желаю вам всегда оставаться верными друг другу",
        "Желаю вам создать сильный и счастливый брак, полный любви, радости и доброты",
        "Пусть ваш брак будет полон счастья, любви и взаимопонимания. Счастливой вам свадьбы!",
        "Желаю вам, чтобы ваш брак был таким же ярким и радостным, как сегодняшний день. Поздравляю!",
        "Счастливой вам свадьбы! Пусть ваше партнерство будет наполнено смехом, приключениями и безграничной любовью",
        "Поздравляю с этим особенным днем! Желаю вам долгой и счастливой жизни вместе, полной взаимного понимания и нежности",
        "Сегодня вы обещаете любить, уважать и поддерживать друг друга. Поздравляю с этим знаменательным шагом в вашей жизни! Желаю вам бесконечной любви и счастья",
        "Пусть ваш брак будет украшен взаимным доверием, лаской и теплотой. Поздравляю вас с этим чудесным союзом!",
        "Желаю вам долгих и счастливых лет вместе, наполненных радостью, взаимопониманием и гармонией. Счастливой вам свадьбы!",
        "Поздравляю с этим важным днем в вашей жизни! Желаю вам бесконечной любви, вдохновения и радости вместе",
        "Счастливой свадьбы! Пусть ваше совместное путешествие жизнью будет наполнено нежностью, смехом и взаимной поддержкой",
        "Поздравляю вас с этим прекрасным днем! Желаю, чтобы каждый ваш день был наполнен любовью и гармонией",
        "Сегодня вы объединяетесь в неразрывный союз, и я рад за вас обоих! Желаю вам множество счастливых мгновений и незабываемых приключений вместе",
        "Пусть ваш брак будет крепким и стойким, как диамант. Поздравляю с этим великолепным началом вашего совместного пути!",
        "Желаю вам счастливой и яркой свадьбы! Пусть ваше сердце всегда будет полно любви и согреваться теплом взаимности",
        "Поздравляю с этим знаменательным днем в вашей жизни! Желаю вам бесконечной любви, радости и благополучия на протяжении всего вашего совместного пути",

        "Счастливой свадьбы! Пусть каждый день вашего брака будет наполнен улыбками, счастьем и взаимным восхищением",
        "Поздравляю вас с этим прекрасным началом новой главы в вашей жизни! Желаю вам непреходящей любви и незабываемых моментов вместе",
        "Сегодня вы становитесь мужем и женой, и это великолепно! Поздравляю с этим замечательным объединением и желаю вам множество счастливых лет вместе",
        "Пусть ваш брак будет крепким, как судно, плывущее по бурным волнам жизни. Поздравляю с этим важным шагом и желаю вам плавного и радостного плавания",
        "Желаю вам долгих и счастливых лет вместе, наполненных любовью, взаимопониманием и великими приключениями. Счастливой свадьбы!",
        "Поздравляю с вашей свадьбой! Желаю вам много любви, мягкой постели и никогда не заканчивающейся дозы юмора",
        "Счастливой свадьбы! Пусть ваш брак будет наполнен драгоценными моментами, согласием и взаимным уважением",
        "Поздравляю вас с этим замечательным днем! Желаю вам бесконечной любви, веселых приключений и счастливых семейных традиций",
        "Сегодня вы обещаете быть рядом друг с другом во всех радостях и испытаниях жизни. Поздравляю с этим знаменательным событием и желаю вам крепкого брака",
        "Пусть ваш брак будет источником вдохновения, поддержки и взаимного развития. Поздравляю вас с этим важным шагом вместе!",
        "Желаю вам счастливой и долгой свадьбы! Пусть ваш дом будет наполнен любовью, теплом и уютом",
        "Поздравляю с этим прекрасным союзом! Желаю вам быть друг для друга опорой, пониманием и верными спутниками на пути жизни",
        "Счастливой свадьбы! Пусть ваш брак будет так прочен, что ни одна теща не сможет его разрушить",
        "Поздравляю вас с этим замечательным днем! Желаю вам много любви, согласия и запаса хорошего юмора для разрядки семейных споров",
        "Сегодня вы начинаете новую главу в своей жизни, а это значит, что теперь у вас будет кто-то, кто будет делить с вами печенье и мешать вам выбирать программу на телевизоре. Поздравляю!",
        "Пусть ваш брак будет столь прекрасен, что даже ваш партнер не будет мечтать о приключениях супергероев",
        "Желаю вам счастливой свадьбы! Пусть ваш брак будет наполнен не только любовью и взаимопониманием, но и здоровыми дозами смеха и сарказма",
        "Поздравляю с этим знаменательным днем! Желаю вам совместного путешествия по жизни, где каждая ошибка станет прекрасным анекдотом в будущем",
        "Счастливой свадьбы! Пусть ваш брак будет таким стабильным, что даже пульт от телевизора не вызовет супружеских споров",
        "Поздравляю вас с этим замечательным днем! Желаю вам столько согласия, сколько нужно, чтобы выбрать фильм на вечер",
        "Сегодня вы вступаете в брак, а это значит, что у вас будет кто-то, кто всегда будет согласен с тем, что вы правы, даже когда вы не правы. Поздравляю!",
        "Пусть ваш брак будет как добротная комедия — смешной, незабываемый и счастливый до самого конца",
        "Желаю вам счастливой свадьбы! Пусть ваш брак будет как оливье — сочетание разных ингредиентов, которое делает жизнь вкуснее",
        "Поздравляю с этим особенным днем! Желаю вам меньше супружеских ссор и больше смешных моментов, которые будете вспоминать с улыбкой"
    )

    private val spanish = listOf(
        "¡Que su matrimonio sea una sólida unión de amor, comprensión y felicidad! ¡Felicitaciones en su esperado día de bodas!",
        "Deseo que cada día de su vida matrimonial esté lleno de alegría, apoyo mutuo y ternura. ¡Felicitaciones en su unión!",
        "¡Que sus corazones siempre latan al unísono y que sus días estén llenos de amor y felicidad! ¡Mis mejores deseos en su día de bodas!",
        "¡Felicitaciones en el día más maravilloso de sus vidas! ¡Que su matrimonio sea largo, feliz y lleno solo de los momentos más hermosos!",
        "Les deseo un amor infinito, respeto mutuo y felicidad en este hermoso camino que han elegido juntos. ¡Felicitaciones en su unión!",
        "¡Que su matrimonio sea como un cuento de hadas, donde cada día esté lleno de magia y felicidad! ¡Felicitaciones en este hito significativo y romántico en su vida!",
        "¡Mis mejores deseos en este día especial! ¡Que su matrimonio esté lleno de alegría, confort y armonía! ¡Felicitaciones en su boda!",
        "¡Felicitaciones por el comienzo de un nuevo capítulo en su vida! Les deseo momentos hermosos, ternura e inolvidables recuerdos juntos. ¡Feliz matrimonio!",
        "¡Que su felicidad familiar sea inquebrantable y que sus días estén llenos de amor y sonrisas felices! ¡Felicitaciones en su día de bodas!",
        "¡Feliz matrimonio! ¡Les deseo muchos años de una vida feliz y armoniosa, llena de amor, comprensión y momentos alegres!",
        "Feliz matrimonio. Les deseo años felices de vida en común, llenos de amor, comprensión y momentos felices",
        "¡Felicitaciones en el día más importante de sus vidas! Que su matrimonio esté lleno de amor, alegría y comprensión mutua",
        "¡Feliz matrimonio! Les deseo un amor creciente y felicidad eterna juntos",
        "¡Felicitaciones en este día mágico! Les deseo que juntos vivan todas las alegrías y desafíos que trae la vida",
        "Hoy su amor se corona con el matrimonio y les felicito de todo corazón por este maravilloso evento. Les deseo momentos inolvidables de felicidad y alegría",
        "Les deseo construir un matrimonio sólido y feliz, lleno de amor, amabilidad y respeto mutuo",
        "Que su matrimonio sea tan hermoso y brillante como el día de hoy. ¡Feliz matrimonio!",
        "¡En este hermoso día! Que su matrimonio esté lleno de calidez, amor y apoyo mutuo",
        "¡Felicitaciones en este maravilloso evento! Les deseo momentos inolvidables de felicidad, amor y bienestar",
        "Hoy comienzan un nuevo capítulo en su vida y les felicito de todo corazón. Les deseo que siempre sean fieles el uno al otro",
        "Les deseo construir un matrimonio fuerte y feliz, lleno de amor, alegría y amabilidad",
        "Que su matrimonio esté lleno de felicidad, amor y comprensión mutua. ¡Feliz matrimonio!",
        "Les deseo que su matrimonio sea tan brillante y alegre como el día de hoy. ¡Felicidades!",
        "¡Feliz matrimonio! Que su compañerismo esté lleno de risas, aventuras y amor infinito",
        "¡Felicidades en este día especial! Les deseo una larga y feliz vida juntos, llena de comprensión mutua y ternura",
        "Hoy prometen amarse, respetarse y apoyarse mutuamente. ¡Felicitaciones por este paso significativo en sus vidas! Les deseo amor infinito y felicidad",
        "Que su matrimonio esté adornado con confianza mutua, caricias y calidez. ¡Felicitaciones por esta maravillosa unión!",
        "Les deseo muchos años felices juntos, llenos de alegría, comprensión y armonía. ¡Feliz matrimonio!",
        "¡Felicidades en este día importante en sus vidas! Les deseo amor infinito, inspiración y alegría juntos",
        "¡Feliz matrimonio! Que su viaje juntos por la vida esté lleno de ternura, risas y apoyo mutuo",
        "Les felicito en este hermoso día. Les deseo que cada día esté lleno de amor y armonía",
        "Hoy se unen en una unión indisoluble y estoy feliz por ambos. Les deseo muchos momentos felices e inolvidables juntos",
        "Que su matrimonio sea fuerte y duradero como un diamante. ¡Felicitaciones por este maravilloso comienzo en su camino juntos!",
        "Les deseo un matrimonio feliz y brillante. Que su corazón esté siempre lleno de amor y se caliente con el calor mutuo.",
        "Feliz matrimonio. Que cada día de su matrimonio esté lleno de sonrisas, felicidad y admiración mutua",
        "¡Felicitaciones por este hermoso comienzo de un nuevo capítulo en sus vidas! Les deseo un amor perdurable y momentos inolvidables juntos",
        "Hoy se convierten en esposo y esposa, ¡y eso es maravilloso! Felicidades por esta maravillosa unión y les deseo muchos años felices juntos",
        "Que su matrimonio sea fuerte como un barco navegando por las turbulentas olas de la vida. Felicidades por este paso importante y les deseo un viaje suave y lleno de alegría",
        "Les deseo muchos años felices juntos, llenos de amor, comprensión y grandes aventuras. ¡Feliz matrimonio!",
        "¡Felicitaciones por su boda! Les deseo mucho amor, una cama cómoda y una dosis interminable de humor",
        "¡Feliz matrimonio! Que su matrimonio esté lleno de preciosos momentos, acuerdo y respeto mutuo",
        "¡Felicidades en este maravilloso día! Les deseo un amor infinito, aventuras divertidas y felices tradiciones familiares",
        "Hoy prometen estar juntos en todas las alegrías y desafíos de la vida. Felicidades por este evento significativo y les deseo un matrimonio sólido",
        "Que su matrimonio sea una fuente de inspiración, apoyo y crecimiento mutuo. ¡Felicidades por este importante paso juntos!",
        "¡Les deseo un matrimonio feliz y duradero! Que su hogar esté lleno de amor, calidez y confort",
        "Felicidades por esta maravillosa unión. Les deseo ser el apoyo, comprensión y compañeros fieles el uno del otro en el camino de la vida",
        "¡Feliz matrimonio! Que su matrimonio sea tan sólido que ni una suegra pueda romperlo",
        "Felicidades en este día especial. Les deseo mucho amor, acuerdo y una buena dosis de humor para resolver los conflictos familiares",
        "Hoy comienzan un nuevo capítulo en sus vidas, lo que significa que ahora tendrán a alguien con quien compartir las galletas y pelear por el control remoto de la televisión. ¡Felicidades!",
        "Que su matrimonio sea tan hermoso que ni siquiera su pareja sueñe con aventuras de superhéroes",
        "¡Les deseo un matrimonio feliz! Que su matrimonio esté lleno no solo de amor y comprensión, sino también de risas y sarcasmo en cantidades saludables",
        "Felicidades por este día significativo. Les deseo un viaje conjunto por la vida donde cada error se convierta en una anécdota divertida en el futuro",
        "¡Feliz matrimonio! Que su matrimonio sea tan estable que ni siquiera el control remoto de la televisión provoque disputas conyugales",
        "Felicidades en este maravilloso día. Les deseo la cantidad justa de acuerdo para elegir una película para la noche"
    )

    private val german = listOf(
        "Möge eure Ehe eine starke Verbindung aus Liebe, Verständnis und Glück sein! Herzlichen Glückwunsch zu eurem lang ersehnten Hochzeitstag!",
        "Ich wünsche euch, dass jeder Tag eures gemeinsamen Lebens voller Freude, gegenseitiger Unterstützung und Zärtlichkeit ist! Herzlichen Glückwunsch zu eurer Vermählung!",
        "Mögen eure Herzen immer im gleichen Rhythmus schlagen und eure Tage voller Liebe und Glück sein! Die besten Wünsche zu eurem Hochzeitstag!",
        "Herzlichen Glückwunsch zu dem schönsten Tag eures Lebens! Möge eure Ehe lang, glücklich und nur von den schönsten Momenten erfüllt sein!",
        "Ich wünsche euch unendliche Liebe, gegenseitigen Respekt und Glück auf diesem wundervollen gemeinsamen Weg, den ihr gewählt habt. Herzlichen Glückwunsch zu eurer Eheschließung!",
        "Möge eure Ehe wie ein Märchen sein, in dem jeder Tag voller Magie und Glück ist! Herzlichen Glückwunsch zu diesem bedeutsamen und romantischen Meilenstein in eurem Leben!",
        "Die besten Wünsche an diesem besonderen Tag! Möge eure Ehe voller Freude, Geborgenheit und Harmonie sein. Herzlichen Glückwunsch zu eurer Hochzeit!",
        "Herzlichen Glückwunsch zum Beginn eines neuen Kapitels in eurem Leben! Ich wünsche euch wunderschöne Momente, Zärtlichkeit und unvergessliche Erinnerungen zusammen. Alles Gute zur Hochzeit!",
        "Möge euer familiäres Glück unerschütterlich sein und mögen eure Tage voller Liebe und glücklicher Lächeln sein! Herzlichen Glückwunsch zu eurem Hochzeitstag!",
        "Alles Gute zur Hochzeit! Ich wünsche euch viele Jahre eines glücklichen und harmonischen Lebens, erfüllt von Liebe, Verständnis und fröhlichen Momenten!",
        "Alles Gute zur Hochzeit! Ich wünsche euch viele glückliche und harmonische Jahre voller Liebe, Verständnis und glücklicher Momente!",
        "Herzlichen Glückwunsch zu eurem wichtigsten Tag im Leben! Möge eure Ehe voller Liebe, Freude und Verständnis sein.",
        "Alles Gute für eure Hochzeit! Ich wünsche euch wachsende Liebe und ewiges Glück gemeinsam.",
        "Herzlichen Glückwunsch zu diesem magischen Tag! Ich wünsche euch, alle Freuden und Herausforderungen, die das Leben mit sich bringt, gemeinsam zu erleben.",
        "Heute ist eure Liebe mit der Ehe gekrönt, und ich gratuliere euch von ganzem Herzen zu diesem wunderbaren Ereignis! Ich wünsche euch unvergessliche Momente des Glücks und der Freude.",
        "Ich wünsche euch, eine starke und glückliche Ehe voller Liebe, Güte und gegenseitigem Respekt zu schaffen.",
        "Möge eure Ehe genauso schön und strahlend sein wie der heutige Tag. Alles Gute zur Hochzeit!",
        "Zu diesem wundervollen Tag! Möge eure Ehe voller Wärme, Liebe und gegenseitiger Unterstützung sein.",
        "Herzlichen Glückwunsch zu diesem großartigen Ereignis! Ich wünsche euch unvergessliche Momente des Glücks, der Liebe und des Wohlergehens.",
        "Heute beginnt ihr ein neues Kapitel in eurem Leben, und ich gratuliere euch von ganzem Herzen dazu! Ich wünsche euch, einander immer treu zu bleiben.",
        "Ich wünsche euch eine starke und glückliche Ehe, voller Liebe, Freude und Güte.",
        "Möge eure Ehe voller Glück, Liebe und Verständnis sein. Alles Gute zur Hochzeit!",
        "Ich wünsche euch, dass eure Ehe genauso strahlend und freudig ist wie der heutige Tag. Herzlichen Glückwunsch!",
        "Alles Gute zur Hochzeit! Möge eure Partnerschaft mit Lachen, Abenteuern und bedingungsloser Liebe gefüllt sein.",
        "Herzlichen Glückwunsch zu diesem besonderen Tag! Ich wünsche euch ein langes und glückliches Leben zusammen, voller gegenseitigem Verständnis und Zärtlichkeit.",
        "Heute versprecht ihr euch, einander zu lieben, zu respektieren und zu unterstützen. Herzlichen Glückwunsch zu diesem bedeutenden Schritt in eurem Leben! Ich wünsche euch unendliche Liebe und Glückseligkeit.",
        "Möge eure Ehe von gegenseitigem Vertrauen, Zärtlichkeit und Wärme geschmückt sein. Herzlichen Glückwunsch zu diesem wunderbaren Bund!",
        "Ich wünsche euch viele glückliche und harmonische Jahre gemeinsam, erfüllt von Freude, Verständnis und Harmonie. Alles Gute zur Hochzeit!",
        "Herzlichen Glückwunsch zu diesem bedeutenden Tag in eurem Leben! Ich wünsche euch endlose Liebe, Inspiration und Freude zusammen.",
        "Alles Gute zur Hochzeit! Möge jeder Tag eurer Ehe mit Lächeln, Glück und gegenseitiger Bewunderung erfüllt sein.",
        "Herzlichen Glückwunsch zu diesem wunderschönen Beginn eines neuen Kapitels in eurem Leben! Ich wünsche euch anhaltende Liebe und unvergessliche Momente zusammen.",
        "Heute werdet ihr Ehemann und Ehefrau, und das ist großartig! Herzlichen Glückwunsch zu dieser wunderbaren Vereinigung und ich wünsche euch viele glückliche Jahre zusammen.",
        "Möge eure Ehe stark sein wie ein Schiff, das auf den stürmischen Wellen des Lebens segelt. Herzlichen Glückwunsch zu diesem wichtigen Schritt und ich wünsche euch eine ruhige und freudige Reise.",
        "Ich wünsche euch lange und glückliche Jahre zusammen, gefüllt mit Liebe, gegenseitigem Verständnis und spannenden Abenteuern. Alles Gute zur Hochzeit!",
        "Herzlichen Glückwunsch zu eurer Hochzeit! Ich wünsche euch viel Liebe, ein gemütliches Bett und niemals endenden Humor.",
        "Alles Gute zur Hochzeit! Möge eure Ehe mit kostbaren Momenten, Einverständnis und gegenseitigem Respekt erfüllt sein.",
        "Herzlichen Glückwunsch zu diesem wundervollen Tag! Ich wünsche euch unendliche Liebe, lustige Abenteuer und glückliche Familientraditionen.",
        "Heute versprecht ihr euch, in allen Freuden und Herausforderungen des Lebens füreinander da zu sein. Herzlichen Glückwunsch zu diesem bedeutenden Ereignis und ich wünsche euch eine starke Ehe.",
        "Möge eure Ehe eine Quelle der Inspiration, Unterstützung und gemeinsamen Entwicklung sein. Herzlichen Glückwunsch zu diesem wichtigen Schritt gemeinsam!",
        "Ich wünsche euch eine glückliche und lange Ehe! Möge euer Zuhause voller Liebe, Wärme und Gemütlichkeit sein.",
        "Herzlichen Glückwunsch zu dieser wunderbaren Vereinigung! Ich wünsche euch, füreinander eine Stütze, Verständnis und treue Begleiter auf eurem Lebensweg zu sein.",
        "Alles Gute zur Hochzeit! Möge eure Ehe so stark sein, dass keine Schwiegermutter sie zerstören kann.",
        "Herzlichen Glückwunsch zu diesem besonderen Tag! Ich wünsche euch viel Liebe, Einverständnis und eine gute Portion Humor, um familiäre Streitigkeiten zu entschärfen.",
        "Heute beginnt ihr ein neues Kapitel in eurem Leben, und das bedeutet, dass ihr nun jemanden habt, der euch Kekse teilt und euch daran hindert, das Fernsehprogramm zu wählen. Herzlichen Glückwunsch!",
        "Möge eure Ehe so wunderbar sein, dass euer Partner nicht einmal von Abenteuern mit Superhelden träumt.",
        "Ich wünsche euch eine glückliche Hochzeit! Möge eure Ehe nicht nur mit Liebe und Verständnis, sondern auch mit gesunden Dosen von Lachen und Sarkasmus gefüllt sein."
    )
}