package com.sosinvitalii.database.goodDeeds

object EnglishGoodDeeds {
    fun fetch(): List<String> {
        return goodDeeds
    }

    private val goodDeeds = listOf(
        "Helping local homeless people",
        "Volunteering at a children's shelter",
        "Assisting elderly people with shopping",
        "Participating in environmental campaigns",
        "Blood donation",
        "Assisting in organizing a charity event",
        "Participating in tree planting projects",
        "Volunteering at an animal shelter",
        "Assisting children with special needs",
        "Supporting a local school with extracurricular activities",
        "Donating unwanted items to local charitable organizations",
        "Assisting neighbors with heavy shopping",
        "Participating in a small business support program",
        "Volunteering at a local medical center",
        "Assisting in the care of local parks or gardens",
        "Promoting digital literacy skills for people",
        "Assisting in environmental care and recycling",
        "Donating funds for research and treatment of rare diseases",
        "Volunteering at a shelter for victims of domestic violence",
        "Assisting the local community in cleaning and beautifying public spaces",
        "Helping local homeless children",
        "Donating food and clothing to a charitable organization",
        "Volunteering in a children's reading program at the library",
        "Assisting local farmers at the market",
        "Supporting the organization of sports events for children",
        "Assisting local migrants with adaptation and language learning",
        "Volunteering in an adult literacy and basic skills program",
        "Assisting a local hospital with patient care",
        "Donating time and materials to a program for repairing and renovating homes for those in need",
        "Volunteering in a program supporting people with mental illnesses",
        "Assisting local animal rights organizations",
        "Donating funds for the education of children from low-income families",
        "Volunteering in a program supporting elderly people with social and home services",
        "Assisting a local museum in conducting tours and organizing events",
        "Donating money to charities fighting hunger",
        "Volunteering in a program supporting youth with special needs",
        "Assisting local programs for rehabilitating drug addicts",
        "Donating funds to improve living conditions in local prisons",
        "Volunteering in a program supporting the unemployed in job search",
        "Assisting local programs for environmental protection and nature conservation",
        "Assisting local programs in combating drug abuse and preventing addiction",
        "Donating time and skills to help local small businesses develop and promote",
        "Volunteering in a program supporting victims of violence and domestic abuse",
        "Assisting local programs in recovering from natural disasters and emergencies",
        "Donating books and materials to school and community libraries",
        "Volunteering in a program supporting young parents and families",
        "Assisting local programs in integrating refugees and displaced persons",
        "Donating funds for scientific research to combat diseases",
        "Volunteering in a program supporting local artists and creative communities",
        "Assisting local programs in providing meals for those in need",
        "Donating funds for the construction and repair of local schools and kindergartens",
        "Volunteering in a program supporting people suffering from mental disorders",
        "Assisting local programs in providing legal aid and protecting citizens' rights",
        "Donating time and skills to assist people with disabilities",
        "Volunteering in a program supporting local sports clubs and teams",
        "Assisting local programs in combating childhood diseases and illnesses",
        "Donating funds to support feeding programs for children in low-income countries",
        "Volunteering in a program organizing cultural events and festivals",
        "Assisting local youth programs in teaching entrepreneurship skills",
        "Donating time to care for orphans and children without parental care",
        "Supporting local programs for women's empowerment and combating domestic violence",
        "Donating funds for the construction and renovation of local playgrounds",
        "Volunteering in a program supporting children with special educational needs",
        "Assisting local programs in providing shelter for the homeless",
        "Donating time and talents to conduct free lessons and workshops",
        "Volunteering in a program supporting people suffering from serious illnesses",
        "Assisting local programs in advocating for and providing aid to migrants",
        "Donating funds to support art and culture in your region",
        "Volunteering in a program supporting local initiatives to ensure educational accessibility",
        "Assisting local programs in combating family violence and sexual harassment",
        "Donating time and resources to organize events for the elderly",
        "Volunteering in a program supporting local projects on environmental education",
        "Assisting local programs in fighting child labor and exploitation",
        "Donating funds to support children's development and education programs in developing countries",
        "Volunteering in a program supporting single mothers",
        "Assisting local programs in the integration and support of persons with disabilities",
        "Donating time and resources to provide aid to migrants and refugees",
        "Volunteering in a program supporting local youth in career orientation",
        "Assisting local programs in combating discrimination and protecting minority rights",
        "Donating funds to support programs providing clean drinking water in water-deficient countries",
        "Assisting local programs in combating school violence and supporting victims of bullying",
        "Donating funds to support cancer treatment and research programs",
        "Volunteering in a program supporting local rehabilitation programs for drug addicts",
        "Assisting local programs in combating child hunger",
        "Donating time and talents to entertain patients in hospitals and nursing homes",
        "Volunteering in a program supporting local programs to ensure foreign language accessibility",
        "Assisting local programs in protecting and preserving nature reserves and national parks",
        "Donating funds to support local programs combating home fires",
        "Volunteering in a program supporting vocational rehabilitation for people with disabilities",
        "Assisting local programs in providing housing for the homeless and those in need",
        "Donating time and resources to aid rural and isolated areas in development and improvement",
        "Volunteering in a program supporting local efforts to combat bullying and cyberbullying",
        "Assisting local programs in supporting and protecting women's rights and combating gender-based violence",
        "Donating funds to support programs for the conservation and restoration of marine ecosystems",
        "Volunteering in a program supporting the development of children's creativity and artistic activities",
        "Assisting local programs in providing psychological support to people in crisis situations",
        "Donating time and skills to help local programs in career orientation for teenagers",
        "Volunteering in the program to support local home care services for elderly people",
        "Assisting local programs in combating child marriages and protecting children's rights",
        "Donating funds to support accessible education programs for children from low-income families",
        "Volunteering in the program to support local rehabilitation and adaptation programs for refugees and displaced persons",
        "Assisting local programs in protecting and preserving historical and cultural heritage",
        "Donating time and talents to conduct creative and artistic workshops for children",
        "Volunteering in the program to support local programs for the integration and education of children with special needs",
        "Assisting local programs in providing psychological support to victims of violence and trauma",
        "Donating funds to support programs for the accessibility and utilization of adaptive technologies",
        "Volunteering in the program to combat child labor exploitation",
        "Assisting local programs in providing support and social assistance to the unemployed and job seekers",
        "Donating time and resources to organize local sports events and competitions",
        "Volunteering in the program to support local youth initiatives and development",
        "Assisting local programs in organizing holidays and events for children from disadvantaged families",
        "Donating funds to support programs combating animal rights violations",
        "Volunteering in the program to support local rehabilitation and integration programs for former prisoners",
        "Assisting local programs in providing material support to families in difficult life situations",
        "Donating time and skills to help local programs in post-disaster recovery",
        "Assisting local programs in training and supporting youth from low-income families",
        "Donating funds to support programs combating childhood tuberculosis",
        "Volunteering in the program to combat domestic conflicts",
        "Assisting local programs in providing support and assistance to families with children with special needs",
        "Donating time and talents to conduct entertainment events in children's hospitals",
        "Volunteering in the program to support the organization of children's summer camps",
        "Assisting local programs in supporting and rehabilitating post-violence victims",
        "Donating funds to support programs combating childhood diseases and lack of medical aid",
        "Volunteering in the program to support local self-employment and entrepreneurship development programs",
        "Assisting local programs in providing support and facilitating employment for young people",
        "Donating time and resources to organize sports and recreational activities for children",
        "Volunteering in the program to combat child trafficking and exploitation",
        "Assisting local programs in organizing and supporting active aging programs for the elderly",
        "Donating funds to support programs combating hunger and malnutrition in children in developing countries",
        "Volunteering in the program to support the development and promotion of creative industries",
        "Supporting local programs to provide assistance and support to young families in early childhood",
        "Donating time and skills to conduct classes and workshops for children with special needs",
        "Assisting local programs in providing legal support and consultations for low-income individuals",
        "Donating funds to support programs fighting childhood autism",
        "Volunteering in programs supporting local initiatives to help refugees and migrants with language learning and adaptation",
        "Supporting local programs to provide assistance and support to families with children with mental disorders",
        "Donating time and talents to conduct creative and recreational activities for elderly people",
        "Volunteering in programs supporting local initiatives to organize children's art circles",
        "Supporting local programs to provide support and social assistance to families with low-income children",
        "Donating funds to support programs fighting childhood obesity and eating disorders",
        "Volunteering in programs supporting local initiatives to organize volunteer projects and events",
        "Assisting local programs in providing support and assistance to victims of domestic violence",
        "Donating time and resources to organize cultural events and festivals for youth",
        "Volunteering in programs supporting local initiatives to fight childhood tuberculosis",
        "Supporting local programs providing shelter and support to women and children affected by violence",
        "Donating funds to support programs fighting child poverty and social inequality",
        "Volunteering in programs supporting local initiatives for the development and support of youth initiatives",
        "Assisting local programs in organizing holidays and events for children from underprivileged families",
        "Supporting local programs providing medical assistance and medication to those in need",
        "Donating funds to support programs fighting childhood diseases and rare illnesses",
        "Volunteering in programs supporting local initiatives for inclusive education for children with special needs",
        "Assisting local programs in providing support and assistance to youth in job search and professional development",
        "Donating time and talents to conduct sports events and training for children",
        "Volunteering in programs supporting local initiatives to fight childhood depression and mental disorders",
        "Supporting local programs in organizing and conducting cultural exchange programs for youth",
        "Donating funds to support programs for the protection and restoration of natural resources",
        "Volunteering in programs supporting local initiatives to provide assistance and support for homeless people",
        "Assisting local programs in providing psychological support and consultations for youth",
        "Donating time and resources to organize professional training courses and workshops for unemployed youth",
        "Volunteering in programs supporting local initiatives for the development and support of small businesses and startups",
        "Supporting local programs to provide support and assistance to people with disabilities in their daily lives",
        "Donating funds to support programs fighting child unemployment and developing employability skills",
        "Volunteering in programs supporting local initiatives to organize cultural and artistic events",
        "Assisting local programs in providing material and financial support to low-income families"
    )
}