package com.sosinvitalii.database.goodDeeds

/// Хорошие дела на английском языке
object EnglishGoodDeeds {
    fun fetch(): List<String> {
        return goodDeeds
    }

    private val goodDeeds = listOf(
        "Helping local homeless people",
        "Volunteering in a children's shelter",
        "Helping elderly people with shopping",
        "Participation in environmental actions",
        "Blood donation",
        "Assistance in organizing a charity event",
        "Participation in a tree planting project",
        "Volunteering in an animal shelter",
        "Help children with special needs",
        "Helping a local school with extracurricular activities",
        "Donating unnecessary things to local charities",
        "Helping neighbors with heavy shopping",
        "Participating in a small business support program",
        "Volunteering at a local medical center",
        "Assistance in caring for a local park or garden",
        "Assistance in teaching people digital skills",
        "Assistance in caring for the environment and recycling",
        "Donation of funds for research and treatment of rare diseases",
        "Volunteering at a local shelter for victims of domestic violence",
        "Assistance to a local community in cleaning and improvement of public places",
        "Assistance to local street children",
        "Donation of food and clothing to a charity organization",
        "Volunteering in the reading program for children in the library",
        "Assistance to local farmers in the market",
        "Assistance in organizing sports events for children",
        "Assistance to local migrants with adaptation and language learning",
        "Volunteering in the adult literacy and basic skills training program",
        "Assistance to a local hospital with patients and care for them",
        "Donation of time and materials to the program of repair and renovation of houses for those in need",
        "Volunteering in the program to support people with mental illness",
        "Assistance to local organizations for the protection of animal rights",
        "Donation of funds for the education of children from low-income families",
        "Volunteering in the program to support the elderly with social and home services",
        "Assistance to the local museum in conducting excursions and organizing events",
        "Donation of money to charities fighting hunger",
        "Volunteering in the program to support youth with special needs",
        "Assistance to local programs for the rehabilitation of drug addicts",
        "Donation of funds to improve living conditions in local prisons",
        "Volunteering in the program to support the unemployed in finding work",
        "Assistance to local programs for environmental protection and nature conservation",
        "Assistance to local programs to combat drugs and prevent drug addiction",
        "Donation of time and skills to help local small businesses develop and promote",
        "Volunteering in the program to support victims of violence and domestic violence",
        "Assistance to local programs for recovery after natural disasters and disasters",
        "Donation of books and materials to school and public libraries",
        "Volunteering in the support program for young parents and families",
        "Assistance to local programs for the integration of refugees and displaced persons",
        "Donation of funds for scientific research to combat diseases",
        "Volunteering in the program to support local artists and creative communities",
        "Assistance to local catering programs for those in need",
        "Donation of funds for the construction and repair of local schools and kindergartens",
        "Volunteering in the program to support people suffering from mental disorders",
        "Assistance to local legal aid programs and protection of citizens' rights",
        "Donation of time and skills to help people with disabilities",
        "Volunteering in the program to support local sports clubs and teams",
        "Assistance to local programs to combat childhood diseases and diseases",
        "Donation of funds to support nutrition programs for children in low-development countries",
        "Volunteering in the program to organize cultural events and festivals",
        "Assistance to local training programs entrepreneurship skills for young people",
        "Donating time to care for orphans and children without parental care",
        "Assistance to local programs to support women and combat domestic violence",
        "Donation of funds for the construction and renovation of local playgrounds",
        "Volunteering in the program to support children with special educational needs",
        "Assistance to local programs to provide shelter for the homeless",
        "Donation of time and talents for free lessons and workshops",
        "Volunteering in the program to support people suffering from severe diseases",
        "Assistance to local programs to protect the rights and provide assistance to migrants",
        "Donation of funds to support art and culture in your region",
        "Volunteering in the program to support local programs to ensure accessibility of education",
        "Assistance to local programs to combat domestic violence and sexual harassment",
        "Donation of time and resources to organize events for the elderly",
        "Volunteering in the program to support local environmental education projects",
        "Assistance to local programs to combat child employment and exploitation",
        "Donation of funds to support programs for the development and education of children in developing countries",
        "Volunteering in a program to support single mothers",
        "Assistance to local programs for the integration and support of persons with disabilities",
        "Donation of time and resources to assist migrants and refugees",
        "Volunteering in the program to support local vocational guidance programs for young people",
        "Assistance to local programs to combat discrimination and violation of minority rights",
        "Donation of funds to support programs to provide drinking water in countries with water scarcity",
        "Assistance to local programs to combat violence in schools and support victims of school violence",
        "Donation of funds to support cancer treatment and research programs",
        "Volunteering in the program to support local drug rehabilitation programs",
        "Assistance to local programs to combat child hunger strikers",
        "Donation of time and talents for the entertainment of patients in hospitals and nursing homes",
        "Volunteering in the program to support local programs to ensure the availability of foreign languages",
        "Assistance to local programs for the protection and preservation of nature reserves and national parks",
        "Donation of funds to support local programs to combat domestic fires",
        "Volunteering in the program to support local programs for the vocational rehabilitation of persons with disabilities",
        "Assistance local programs to provide housing for the homeless and needy",
        "Donation of time and resources to help rural and isolated areas in development and improvement",
        "Volunteering in the program to support local programs to combat bullying and cyberbullying",
        "Assistance to local programs to support and protect women's rights and combat gender-based violence",
        "Donation of funds to support programs for the protection and restoration of marine ecosystems",
        "Volunteering in the program to support local programs for the development of children's creativity and artistic activity",
        "Assistance to local programs to provide psychological support to people in crisis situations",
        "Donation of time and skills to help local vocational guidance programs for teenagers",
        "Volunteering in the program to support local programs to provide home care services for the elderly",
        "Assistance to local programs to combat child marriage and protect children's rights",
        "Donation of funds to support affordable education programs for children from low-income families",
        "Volunteering in the program to support local programs for the rehabilitation and adaptation of refugees and displaced persons",
        "Assistance to local programs for the protection and preservation of historical and cultural heritage",
        "Donation of time and talents for conducting creative and artistic workshops for children",
        "Volunteering in the program to support local programs for the integration and education of children with special needs",
        "Assistance to local programs to provide psychological support to victims of violence and trauma",
        "Donation of funds to support programs to ensure the availability and use of adaptive technologies",
        "Volunteering in the program to support local programs to combat child labor exploitation",
        "Assistance to local programs to provide support and social assistance to the unemployed and job seekers",
        "Donation of time and resources for the organization of local sports events and competitions",
        "Volunteering in the program to support local programs for the development and support of youth initiatives",
        "Assistance to local programs for the organization of holidays and events for children from disadvantaged families",
        "Donation of funds to support programs to combat violations of animal rights",
        "Volunteering in the program to support local programs for the rehabilitation and integration of former prisoners",
        "Assistance to local programs to provide material support to families in difficult life situations",
        "Donation of time and skills to assist local programs for recovery after natural disasters",
        "Assistance to local programs for training and support of young people from low-income families",
        "Donation of funds to support programs to combat childhood tuberculosis",
        "Volunteering in the program to support local programs to combat domestic conflicts",
        "Assistance local programs to provide support and assistance to families with children with special needs",
        "Donation of time and talents for entertainment events in children's hospitals",
        "Volunteering in the program to support local programs for organizing children's summer camps",
        "Assistance to local programs to support and restore post-violent victims",
        "Donation of funds to support programs to combat childhood diseases and lack of medical care",
        "Volunteering in the program to support local programs to promote self-employment and entrepreneurship development",
        "Assistance local programs to support and promote the employment of young people",
        "Donation of time and resources to organize sports and recreational activities for children",
        "Volunteering in the program to support local programs to combat child trafficking and exploitation",
        "Assistance to local programs to organize and support active longevity programs for the elderly",
        "Donation of funds to support programs to combat hunger and malnutrition in children in developing countries",
        "Volunteering in the program to support local programs for the development and support of creative industries",
        "Assistance to local programs to provide support and assistance to young families in early childhood",
        "Donation of time and skills to conduct classes and workshops for children with special needs",
        "Assistance to local programs to provide legal support and advice for poor people",
        "Donation of funds to support programs to combat child autism",
        "Volunteering in the program to support local programs to support refugees and migrants in language learning and adaptation",
        "Assistance to local programs to support and assist families with children with mental disorders",
        "Donation of time and talents for creative and recreational activities for the elderly",
        "Volunteering in the program to support local programs for organizing children's art circles",
        "Assistance to local programs for support and social assistance to families with poor children",
        "Donation of funds to support programs to combat childhood obesity and eating disorders",
        "Volunteering in the program to support local programs to organize volunteer projects and events",
        "Assistance to local programs to support and assist victims of domestic violence",
        "Donation of time and resources for organizing cultural events and festivals for young people",
        "Volunteering in the program to support local programs to combat childhood tuberculosis",
        "Assistance local programs to provide shelter and support to women and children affected by violence",
        "Donation of funds to support programs to combat child poverty and social inequality",
        "Assistance to local programs for organizing holidays and events for children from low-income families",
        "Assistance to local programs for providing medical care and medicines to those in need",
        "Donation of funds to support programs to combat childhood diseases and rare diseases",
        "Volunteering in the program to support local programs for inclusive education for children with special needs",
        "Assistance to local programs to support and assist young people in finding work and professional development",
        "Donating time and talents for sports events and training for children",
        "Volunteering in the program to support local programs to combat child depression and mental disorders",
        "Assistance to local programs to organize and conduct cultural exchange programs for young people",
        "Donation of funds to support programs to protect and restore natural resources",
        "Volunteering in the program to support local programs to provide assistance and support for the homeless people",
        "Assistance to local programs to provide psychological support and counseling for young people",
        "Donation of time and resources for the organization of vocational training courses and trainings for young unemployed people",
        "Volunteering in the program to support local programs for the development and support of small businesses and startups",
        "Assistance to local programs to support and help people with disabilities in everyday life",
        "Donation of funds to support programs to combat child unemployment and the development of employment skills",
        "Volunteering in the program to support local programs for the organization of cultural and artistic events",
        "Assistance to local programs to provide material and financial support to low-income families",
        "Help a stranger carry heavy bags or open a door.",
        "Visit a hospital or nursing home and spend time with patients, telling them stories or just listening to them.",
        "Give a smile and kind words to passers-by on the street.",
        "Leave a tip to service workers in a restaurant or cafe.",
        "Share food or drinking water with homeless people.",
        "Help parents by offering to look after their children for a few hours.",
        "Make compliments to colleagues or neighbors to cheer them up.",
        "Clean up trash on the street or in public places.",
        "Donate blood in a hospital or become an organ donor.",
        "Support poor families by offering them food or essentials.",
        "Help a stranger deal with by public transport or tell him the way.",
        "Open the door for someone, especially if they are carrying heavy bags or have mobility problems.",
        "Provide financial assistance to families in need or charities.",
        "Help older people master a computer or smartphone so they can be more connected to the world.",
        "Spend time with children from an orphanage or orphanage, playing games or helping them with their studies.",
        "Support local small businesses by buying goods or services from them.",
        "Help neighbors with cleaning or repair work in their house.",
        "Share your skills and knowledge by offering free lessons or consultations.",
        "Donate books or study materials to a library or school.",
        "Arrange a charity event, collecting clothes or food for those in need.",
        "Spend the day helping animal care volunteers at the shelter.",
        "Donate blood or become a plasma donor for those in need.",
        "To support a person experiencing difficulties by simply listening to him and showing that he is not alone.",
        "To help colleagues or friends with a job or project by offering their help.",
        "To help people with disabilities overcome obstacles, for example, by conducting physical rehabilitation classes or helping them in everyday affairs.",
        "Provide assistance to families with children by offering free child care or assistance with child care.",
        "To help students with their studies by offering tutoring or counseling.",
        "To support local creative projects by attending exhibitions, concerts or performances.",
        "To help older people with shopping or walking, especially if they are limited in their mobility.",
        "To share their cooking skills by arranging ready meals for those in need or students.",
        "To offer a free confidential hearing for people who are experiencing emotional difficulties.",
        "To help garbage collectors by offering them drinks or a light snack.",
        "Help someone find a job, share information about vacancies or provide recommendations.",
        "Support local environmental initiatives by participating in the cleaning of parks or beaches.",
        "Spend time with people who are in a nursing home, reading books to them or just talking.",
        "Donate your time and help at charity events, such as festivals or concerts.",
        "Help people with limited access to information by offering them assistance in using the Internet or social networks.",
        "Support local schools or kindergartens by offering free educational materials or organizing entertainment events.",
        "Give a smile to passers-by, smiling and greeting the people you meet.",
        "To help people who are in a difficult life situation, for example, divorce or the loss of a loved one, offering them support and understanding.",
        "Help mom or dad with household chores, such as cleaning or cooking.",
        "Share your repair or restoration skills by helping someone with home repairs.",
        "To help new immigrants adapt to a new country by offering them help with language or orientation.",
        "To donate time in an orphanage or animal shelter, studying with children or walking dogs.",
        "To support local museums and galleries by visiting their exhibitions and events.",
        "To help students with exam preparation by offering free study materials or conducting classes.",
        "To give stationery or textbooks to schoolchildren from low-income families.",
        "To support local sports teams by attending their games and competitions.",
        "To help older people learn new technologies by offering instructions or personal lessons.",
        "To support pregnant women or newborns by offering help with shopping or child care.",
        "To donate a bed or clothes to children in orphanages or orphanages.",
        "Support local farmers by buying fresh produce directly from them.",
        "Help people with disabilities with workplace adaptation or creating an accessible environment.",
        "To help pregnant women or young mothers by offering support and advice.",
        "Share your skills and knowledge by organizing free workshops or lectures.",
        "Help local unemployed people with resume preparation or preparation for an interview.",
        "Give children from low-income families new toys or books.",
        "To help participants of the rehabilitation program by offering their support and inspiration.",
        "To support local shelters for the homeless by offering donations in the form of food, clothing or hygiene supplies.",
        "To help older people with computer literacy by teaching them to use the Internet and email.",
        "To support young entrepreneurs by buying their goods or services.",
        "Spend time with children from low-income families by organizing festive events or excursions for them.",
        "Help local schools with updating classrooms or purchasing educational materials.",
        "Donate your time and talents to perform at a charity concert or event.",
        "To help people coming out of prison by offering them support and resources to return to society.",
        "To support local environmental conservation programs by participating in tree planting or garbage collection actions.",
        "To help single parents with child care so that they can take a break and relax.",
        "To give pets in a shelter or on the street your care and attention, offering help with care or just playing with them.",
        "To help young people with career development by providing them with an internship opportunity or giving advice on career building.",
        "Provide support to people suffering from mental health problems by offering listening and understanding.",
        "To help neighbors with the care of the garden or vegetable garden.",
        "Share your skills in music by offering free lessons or performances for children or adults.",
        "Help people with disabilities with finding specialized devices or technologies that can improve their lives.",
        "Support local theaters or cultural centers by attending their performances and events.",
        "To help local migrants with language and adaptation by offering free lessons or consultations.",
        "To spend the day with children from low-income families, arranging entertainment events or excursions for them.",
        "To help students prepare for university by offering assistance in writing applications or preparing for entrance exams.",
        "Support local programs for teenagers by offering their help in organizing events or volunteering.",
        "To help people with disabilities with specialized education or vocational training.",
        "To help victims of violence or domestic violence by offering support and advice.",
        "To donate books or magazines to a library or school to expand access to literature.",
        "To help older people with computer literacy training and the use of the Internet to communicate with loved ones.",
        "To support local projects for the protection of animals and ecosystems, for example, by participating in actions to clean up reservoirs or protect nature reserves.",
        "To help children with disabilities integrate into public schools and kindergartens by offering their support and assistance to teachers.",
        "To share their skills in sports by offering training or individual classes for children or adults.",
        "To help people who have experienced traumatic events by providing them with emotional support and counseling.",
        "Support local programs to combat drug addiction and alcoholism by participating in educational events or providing resources for rehabilitation.",
        "To help young families with the care of infants or children by offering help with supervision or giving recommendations on care.",
        "To support local programs for adolescents with aggression or behavior problems by offering their assistance in conducting trainings or consultations.",
        "To help local small businesses with development and promotion by buying their goods or services and making recommendations to their friends and acquaintances.",
        "To give toys or clothes to pets at the shelter to make their stay more comfortable.",
        "To help people with disabilities gain access to sports or recreational activities by providing them with support or adaptive equipment.",
        "Support local programs to combat childhood illnesses or disabilities by offering donations or assistance in organizing fundraising.",
        "Help students with disabilities prepare for college or university by providing information about available resources or a support program.",
        "Share their skills and experience in entrepreneurship, offering free consultations or training.",
        "To help young people with finding housing or accommodation by providing information about available resources or helping with relocation.",
        "To support local programs for children with special needs by offering their assistance in organizing events or conducting classes.",
        "To help women suffering from domestic violence by providing them with a safe haven or assistance in finding legal support.",
        "To give a smile to catering workers by leaving generous tips and expressing their gratitude for their work.",
        "To provide assistance to veterans or former military personnel by offering support in obtaining medical care, finding a job or in adapting to civilian life.",
        "Help older people with paperwork or filling out forms.",
        "Support local hunger programs by donating food or time to work in a free kitchen.",
        "To help people with disabilities in finding adaptive technologies or devices.",
        "To share their drawing or painting skills by organizing free lessons or exhibitions for local residents.",
        "To help homeless people find temporary housing or access to social support services.",
        "To support local environmental protection programs by participating in tree planting or cleaning of rivers and lakes.",
        "To help children with special needs integrate into school or kindergarten by offering additional assistance or resources.",
        "To support local programs for teenagers on career guidance and skills development by offering their expertise or conducting master classes.",
        "To help people who have experienced the loss of a loved one by offering emotional support and understanding.",
        "To assist young families with children by offering free consultations on the upbringing and development of children.",
        "To support local programs to support victims of violence by providing safe havens and counseling.",
        "To help students with disabilities gain access to higher education by offering information about available program resources and scholarships.",
        "Share your knitting or sewing skills by creating and giving warm garments to those in need.",
        "Help young people with planning and achieving their career goals by offering mentoring or counseling.",
        "To support local programs to combat childhood diseases and medical problems by donating funds or providing assistance in organizing fundraising.",
        "To help children from low-income families with studies by offering free lessons or support in homework.",
        "Support local programs for young unemployed people by offering internships or job search skills training.",
        "To help women during pregnancy or after childbirth by offering support in the form of information, advice or financial assistance.",
        "To donate their skills and time for the repair or reconstruction of public buildings or facilities.",
        "To help local disaster recovery programs by providing assistance in organizing and distributing humanitarian aid.",
        "To support programs for children with hearing or speech impairments by offering assistance in rehabilitation and development of communication skills.",
        "To help young people with disabilities in finding a job by offering job training or helping to compile a resume.",
        "To support local disease prevention and medical care programs by offering their assistance in conducting educational events or donations.",
        "To help people with mental problems or mental health disorders by providing emotional support and information about resources.",
        "To share their skills in organization and management by offering their help in organizing local events or projects.",
        "To help youth groups or organizations with attracting funding by providing advice on financial planning or helping with the preparation of grant applications.",
        "To support local programs to support women in business by offering their expertise and advice.",
        "To help children with visual impairments in gaining access to specialized services and education by offering their assistance in organizing adaptive programs.",
        "To support local programs for teenagers on drug and alcohol addiction prevention by offering educational activities or assistance in organizing support.",
        "To assist people in finding missing relatives or loved ones by offering their expertise and support in finding information.",
        "To help young parents with child care so that they can relax or do your business.",
        "Support local programs to educate children from low-income families by offering free educational materials or additional classes.",
        "To help people with disabilities in the search for adaptive technology or devices to improve their quality of life.",
        "Share your gardening or gardening skills, helping with tips or crafts for the garden.",
        "Help homeless animals by offering donations to shelters or assisting in their care.",
        "To support local programs for the preservation and restoration of historical or cultural monuments, offering their assistance in restoration or maintenance.",
        "To help children with special needs access sports or recreational activities by offering adaptive workouts or games.",
        "To support local programs for teenagers to develop leadership skills by offering their assistance in training or mentoring.",
        "To help people who have experienced traumatic events by providing emotional support or support for psychological counseling.",
        "To help young families with children's education by offering free consultations on school choice or pedagogical support.",
        "Support local domestic violence programs by offering shelter assistance or providing legal support.",
        "To help local programs to support orphans: to offer their assistance in education, organization of events or donation.",
        "To hold a charity event to raise funds for the equipment of specialized classrooms and classrooms in schools.",
        "To help local programs for social integration for people with special needs: to offer their assistance in education and entertainment.",
        "To hold a fundraising campaign for the construction or renovation of a home for the elderly or elderly.",
        "Provide support and assistance to a local disaster or disaster recovery program.",
        "To help local programs to protect the rights of migrants or refugees: to offer their assistance in consultations or translations.",
        "To hold a charity event to raise funds to provide children from low-income families with food and clothing.",
        "To help local programs for the social rehabilitation of former prisoners: to offer their assistance in training and professional adaptation.",
        "To hold a campaign to collect stationery for orphanages or schools.",
        "To support and help local programs for rehabilitation and support of persons with disabilities.",
        "To help local vocational guidance programs for young people: to conduct master classes or offer internships.",
        "To hold a charity event to raise funds for the construction or renovation of local parks and squares.",
        "To help local programs for education and support of children with special needs.",
        "To offer their assistance to local programs for to support single women and young mothers.",
        "To hold a fundraising campaign to provide orphans and children from disadvantaged families with the necessary supplies.",
        "To help local programs to combat child employment: to conduct trainings or offer internships to young people.",
        "To hold a charity event to raise funds to provide children from disadvantaged areas with educational materials and computers.",
        "To help local programs to combat hunger in children: to offer financial support or to hold a campaign to collect food.",
        "Offer your assistance to local adult education programs: conduct free classes or support them financially.",
        "To help local programs for the socialization of young people from disadvantaged families: to offer their help in organizing events and trainings.",
        "To hold a campaign to collect clothes and personal hygiene items for homeless women.",
        "To support and assist local programs to protect the rights and well-being of children.",
        "To help local programs to combat domestic violence: offer your help in organizing consultations and support groups.",
        "Hold a charity event to raise funds to provide medical drugs and medicines for those in need.",
        "To help local programs for the social adaptation of people released from prison: to offer their assistance in education and vocational training.",
        "To hold a campaign to collect toys and books for orphans or children being treated in hospitals.",
        "To help local programs to support victims of domestic violence: to offer their assistance in providing consultations and emotional support.",
        "To support and assist local rehabilitation programs for people with drug addiction.",
        "To help local environmental protection and environmental education programs: to conduct environmental actions or organize cleaning of the territory.",
        "To hold a charity event to raise funds for the construction or repair of houses for low-income families.",
        "To help local programs for the prevention and treatment of diseases such as cancer or HIV/AIDS.",
        "Offer assistance to local programs for recovery after natural disasters or natural disasters.",
        "Help local programs to support people with disabilities in obtaining affordable services and infrastructure.",
        "To hold a fundraising campaign to organize a summer camp for children from poor families.",
        "To support and assist local programs to combat child illiteracy and lack of education.",
        "To help local programs to support young talents in the field of art, music or sports.",
        "To hold a charity event to raise funds for organizing excursions and trips for children from poor families.",
        "To help local programs for the social rehabilitation of unemployed and homeless people.",
        "To offer their assistance to local programs to teach migrants the language and culture of the local community.",
        "To help local programs to promote entrepreneurship among young people.",
        "To carry out an action to collect food and basic necessities for victims of natural disasters or conflicts.",
        "To provide support and assistance to local programs for the restoration and preservation of historical heritage.",
        "To help local programs for the social adaptation of orphans or children left without parental care.",
        "To hold a charity event to raise funds for the education of children from poor families in a music, art or sports school.",
        "To help local programs for the protection and protection of nature reserves and parks.",
        "To offer their assistance to local programs for social integration and support of people with autism spectrum disorders.",
        "To help local programs to protect women's rights and combat gender-based violence.",
        "To hold a campaign to collect clothes and shoes for teenagers and young people from poor families.",
        "To provide support and assistance to local programs for the socialization and employment of graduates of orphanages and boarding schools.",
        "To help local programs for the prevention and treatment of mental illness.",
        "To hold a charity event to raise funds to provide homeless people with warm clothes and sleeping accessories.",
        "To help local programs for social support and care for the elderly.",
        "To offer assistance to local programs for teaching adults basic reading, writing and computing skills.",
        "To help local programs to combat injuries and accidents among children and youth.",
        "To carry out an action to collect stationery and educational materials for schools in remote and low-income areas.",
        "To support and assist local programs to protect the rights of minors and their social rehabilitation.",
        "To help local programs to combat childhood diseases and support medical institutions.",
        "To hold a charity event to raise funds for the purchase and installation of specialized devices for people with disabilities.",
        "To help local programs to provide nutrition and care for homeless families with children.",
        "To offer their assistance to local programs for vocational rehabilitation and support for persons with disabilities.",
        "To help local programs to combat childhood tuberculosis and support children's tuberculosis dispensaries.",
        "To hold a campaign of collecting toys and books for orphans and children in orphanages.",
        "To support and assist local programs for teaching children with special needs.",
        "To help local programs for social adaptation and rehabilitation of persons released from prison.",
        "To hold a charity event to raise funds for the provision of medical equipment and medicines for hospitals and clinics.",
    )
}