package com.sosinvitalii.database.giftIdeas

/// Подарки на английском языке
object EnglishGiftIdeas {
    fun fetch(gender: Gender): List<String> {
        return if (gender == Gender.MALE) {
            maleGiftIdeas
        } else {
            femaleGiftIdeas
        }
    }

    private val maleGiftIdeas = listOf(
        "Swiss wristwatch",
        "Leather wallet",
        "Barbecue set",
        "Electronic book",
        "Coffee machine",
        "Gym membership or golf game pass",
        "Subscription to a magazine or streaming platform",
        "Stylish pen and notebook",
        "Set of quality beer or wine",
        "Portable acoustic system",
        "Shaving kit",
        "Retro video games",
        "Professional tool set",
        "Messenger bag or backpack",
        "Smart home assistant",
        "Air humidifier",
        "Sushi set",
        "Compact binoculars",
        "Video shooting drone",
        "Textbook or course for learning a new language or skill",
        "Board game",
        "T-shirt with the logo of a favorite sports team",
        "Fitness bracelet",
        "Compact camping tent",
        "Sunglasses",
        "Pizza making kit",
        "Wireless headphones",
        "Experience of driving a sports car",
        "Bottle of vintage wine or expensive whiskey",
        "Books or audiobooks by a favorite author",
        "Original survival knife",
        "3D puzzle or construction set",
        "Soft bathrobe and slippers",
        "GoPro camera for extreme sports",
        "World map for a traveler",
        "Gift certificate to a favorite restaurant",
        "Model ship building kit",
        "Portable power bank",
        "Thermos mug",
        "Virtual reality glasses",
        "Stylish tie or bow tie",
        "Wine tasting certificate",
        "Guidebook for the country or city he wants to visit",
        "Painting or poster with the image of a favorite band, movie, or character",
        "Cookbook for cooking enthusiasts",
        "Yoga or fitness mat",
        "Fishing accessories",
        "Table lamp for reading",
        "External hard drive or SSD",
        "Home theater projector",
        "Smartwatch",
        "Leather bracelet",
        "Vinyl records of a favorite artist",
        "Whiskey glasses",
        "Moleskine notebook",
        "Indoor plant growing kit",
        "Karaoke microphone",
        "Laptop bag",
        "Open fire grill",
        "Crafting or DIY project kit",
        "Gift certificate for a professional massage",
        "Shoe cleaning kit",
        "Quality skewer for shish kebab",
        "Subscription to online masterclasses on his hobby",
        "Set of collectible coins or stamps",
        "Thematic calendar",
        "Skydiving certificate",
        "Tickets to a concert or sporting event",
        "Table tennis tabletop",
        "Comfortable sneakers or boots",
        "Gourmet gift set (e.g., cheeses, sausages, chocolates)",
        "Professional camera or lens",
        "Smart bracelet or fitness tracker",
        "Poker set",
        "Golf or tennis lessons",
        "Record player stand",
        "Gift certificate for a real-life quest",
        "Latest model smartphone",
        "Exclusive coffee subscription",
        "Subscription to an online language learning platform",
        "Stylish keychain",
        "Custom engraved hot plate stand",
        "Thermos for food",
        "Radio-controlled car or helicopter model",
        "Memorable football or basketball",
        "Electric toothbrush",
        "Mini refrigerator for drinks",
        "Sommelier lessons",
        "Tickets to a themed festival",
        "Charging station for electronic devices",
        "Swiss Army knife",
        "Gift set of essential oils for relaxation",
        "Drawing or painting set",
        "Bottle of personal whiskey or rum blend",
        "One-year subscription to a yoga or meditation course",
        "Action camera for extreme sports",
        "Electronic bracelet for tracking a healthy lifestyle",
        "Compact massager",
        "Stylish leather belt",
        "Home theater with projector and sound system",
        "Custom portrait or caricature",
        "Vintage stylish umbrella",
        "Swimming lessons or scuba diving certificate",
        "Retro typewriter",
        "Compact espresso machine",
        "Art book on his interested topic",
        "Gift set of spices and sauces",
        "Manual coffee grinder.",
        "Wooden checkers or chess set",
        "Beard grooming gift set",
        "Winemaking kit",
        "Compact portable smartphone projector",
        "Muay Thai or other martial arts set",
        "Expensive stylish lighter",
        "Beer brewing kit",
        "Book lamp",
        "Strategy board game",
        "Fisherman's gift set",
        "Watch or jewelry box",
        "Mini desktop billiards",
        "Tasty gourmet gifts (nuts, chocolate, delicacies)",
        "Specialized gear for cyclists",
        "Subscription to audiobooks",
        "Bottle of good Georgian wine",
        "Biscuit icing set",
        "Souvenir t-shirt or tank top with a unique design",
        "Stylish headwear (hat, cap, panama)",
        "Wine and cheese gift box",
        "Wall map for marking visited countries",
        "Camera cleaning kit",
        "Art or design history book",
        "Bottle of expensive cognac or rum",
        "Textbook for learning foreign languages",
        "Set of unique wine glasses",
        "Board game 'Dixit' or 'Codenames'",
        "Gourmet coffee gift set",
        "Compact drawing set",
        "Gift certificate for culinary school",
        "Photo book of his childhood places",
        "Professional headphones",
        "Stylish smartphone or laptop case",
        "Mini barbecue for picnics",
        "Gift set of hot sauces",
        "Ushanka hat for winter adventures",
        "E-book reader",
        "Subscription to a favorite sports channel",
        "Ergonomic laptop stand",
        "Swimming goggles",
        "Memorable medal or trophy related to his interests",
        "Gift set of branded golf tees",
        "Fitbit bracelet or other activity tracker",
        "Compact blender for making smoothies",
        "Board game 'Carcassonne' or 'Dominion'",
        "Subscription to a music streaming service",
        "Compact bicycle repair tool kit",
        "Wine rack",
        "Expensive silk scarf or shawl",
        "Grooming gift set for skincare",
        "Handgrip strengthener",
        "World atlas for geography enthusiasts",
        "Bracelet for sleep tracking",
        "Wall clock with an interesting design",
        "Pen with personalized engraving",
        "Professional back or foot massager",
        "Grooming kit for shaving",
        "Sweatshirt or sweater with the logo of a favorite sports team",
        "Star projector for creating a romantic atmosphere",
        "Heated mouse pad",
        "Tickets to a football match or basketball game",
        "Books on philosophy or psychology",
        "Tabletop game 'Real Football'",
        "Wireless smartphone charger",
        "Steel thermos for keeping drinks hot or cold",
        "Homebrewing kit",
        "Bike computer for tracking speed and distance",
        "Shoe care kit",
        "Subscription to a magazine related to his interests",
        "Electric razor",
        "Drawing tablet",
        "Sushi making kit",
        "Electric toothbrush with whitening function",
        "Charging station for devices",
        "Gift set of sports supplements",
        "Acoustic guitar or other musical instrument",
        "Cocktail and bartending equipment set",
        "Air purifier and freshener device",
        "Gift set of premium teas",
        "Football with the autograph of a famous player",
        "Beard care kit and accessories",
        "Book with the autograph of a favorite author",
        "Hoverboard or electric scooter",
        "Camping and picnic accessories set",
        "Notepad with a personalized cover",
        "Cassette player",
        "Gift set of massage oils and lotions",
        "Kit for making your own chocolate",
        "Sports backpack or gym bag",
        "Headphone stand",
        "Smart gloves for winter use with touchscreen technology",
        "Interactive robot or drone",
        "Home theater set (projector, screen, sound system)",
        "Stylish briefcase or work bag",
        "Gift set of quality brushes and paints for artistic creation",
        "Solar-powered device charging station",
        "Personalized golf set",
        "Smartphone with an enhanced camera and photography features",
        "Gift set of retro games or video games",
        "Bowling set",
        "Skateboard or longboard",
        "Gourmet exotic spice and seasoning set",
        "Picnic or barbecue set in a convenient bag",
        "Set for creating your own perfume compositions",
        "Device for preserving and aging wine",
        "Certificate for indoor skydiving or wakeboarding",
        "Tabletop football or billiards",
        "Smart wristwatch with activity tracking function",
        "Gift set of rare and exotic teas",
        "Barbershop tool set",
        "Homebrewing kit with original recipes",
        "Puzzle with an unusual shape or a large number of pieces",
        "Smart glasses with augmented reality function",
        "Desk calendar with photos and important dates",
        "Set for creating your own micro-garden or mini-garden",
        "Certificate for a massage session or spa procedures",
        "Professional makeup brush set",
        "Interactive gaming console",
        "Gift set of rare and premium whiskies",
        "Electric dental floss or irrigator",
        "Knitting or embroidery kit",
        "Hammock for outdoor relaxation",
        "Gift set for brewing your own beer",
        "Stylish leather wallet",
        "Carving set for fruits and vegetables",
        "Boot or glove dryer",
        "Premium coffee set with a grinder",
        "Retro film camera",
        "Gift set for baristas",
        "Croquet set",
        "Shaving station with a mirror",
        "Wooden board game 'Connect Four' or 'Nine Men's Morris'",
        "Gift set of premium cigars",
        "Winemaking kit with the ability to create your own wine",
        "Folding bicycle for easy transport",
        "Set for making your own soaps and aromatic candles",
        "Subscription to a culinary magazine or recipe database",
        "Device for mobile photo printing",
        "Table tennis set",
        "Gift set of branded cosmetics",
        "Backpack with an integrated solar panel for device charging",
        "Professional pencils and watercolor paints for artists",
        "Gaming keyboard and mouse for gamers",
        "Charging station for electronic devices on the desk",
        "Anti-stress set with toys and gadgets",
        "Book with interactive elements or 3D illustrations",
        "Barbecue grill for outdoor use",
        "Gyroscope-powered light garland for creating atmosphere",
        "Gift set of plush towels and bathrobe",
        "Home massage chair",
        "Set for creating your own perfumes or aromatic fragrances",
        "Music speaker with built-in lighting and illumination",
        "Gift set of exotic spices and sauces for Asian cuisine",
        "Mini projector for watching movies and videos on a big screen",
        "Gift certificate for sauna sessions and spa treatments",
        "Set for pin-up style photography and shooting",
        "Electronic bureaucratic game for strategic thinking development",
        "Travel accessories set (neck pillow, sleep mask, skincare set)",
        "Subscription to online courses or workshops on photography or videography",
        "Road tool kit for cars",
        "Interactive toy robot",
        "Gift set for creating your own cosmetics",
        "Set for creating your own mini-garden or vertical garden",
        "Wireless Bluetooth speaker with built-in lighting",
        "Beard care set and mustache grooming",
        "Tabletop fountain for relaxation and ambiance",
        "Gift set of high-quality cutlery",
        "Smart helmet for cyclists or motorcyclists",
        "Kit for making your own jewelry",
        "Interactive set for learning robotics and programming",
        "Home smoking kit for food",
        "Gift set for creating your own cocktails",
        "Smart door lock",
        "Set of professional brushes and paints for artists",
        "Video shooting and editing kit",
        "Gift set of elite tea",
        "Device for air grilling or multi-cooking",
        "Desk lamp with built-in device charger",
        "Gift set for creating your own souvenirs",
        "Compact station for charging electric vehicles",
        "Set of tools for DIY repairs and construction",
        "Interactive children's construction set",
        "Gift set of rare tea leaves",
        "Robotic vacuum cleaner for automatic cleaning",
        "Kit for homemade chocolate fondue",
        "Set for creating your own natural cosmetics",
        "Tabletop game in steampunk style",
        "Gift set of premium grill tools",
        "Activity and sleep tracking device",
        "Interactive electronic drawing and note board",
        "Gift set of elite cognacs",
        "Kit for creating personalized perfumes with customized fragrances",
        "Set for creating your own furniture projects",
        "Smart home assistant robot",
        "Gift set of elite tea blends",
        "Brewing kit with the ability to create your own beer",
        "Tabletop game in fantasy or science fiction style",
        "Gift set for creating your own aromatic massage oil",
        "Compact fitness trainer for home workouts",
        "Set of professional culinary knives",
        "Gift set of rare and premium spirits",
        "Device for creating electronic music and compositions",
        "Interactive tabletop game in cyberpunk style",
        "Gift set for creating your own ice cream",
        "Set for creating your own leather goods",
        "Device for shooting and streaming video blogs",
        "Gift set of exotic spices and seasonings for gastronomic experiments",
        "Kit for creating your own gallery or art exhibition",
        "Interactive robot dog or robot cat",
        "Set of professional pencils and markers for illustrations and comics",
        "Skydiving experience",
        "Masterclass",
        "Resort vacation",
        "Wallet",
        "Wristwatch",
        "Personalized embroidered bathrobe",
        "Perfume",
        "GPS navigator",
        "Tool set",
        "Gym membership",
        "Laptop",
        "Remote-controlled car",
        "Mini bar",
        "Tabletop fireplace",
        "Grill",
        "Electric grill",
        "Smartphone",
        "Celebration cake",
        "Smartphone case",
        "Tent",
        "Suitcase",
        "Document holder",
        "Football match ticket",
        "Tabletop hockey",
        "Action camera",
        "Photo-to-painting",
        "Video clip about the birthday person",
        "Telescope",
        "Rocking chair",
        "Hammock",
        "Power bank",
        "USB flash drive",
        "Necktie",
        "Lighter",
        "Sauna set",
        "Scarf",
        "House slippers",
        "Gloves",
        "Trip to a shooting range",
        "Photo album",
        "Piggy bank",
        "Newton's cradle",
        "Fireworks",
        "Sweatshirt",
        "Go-kart voucher",
        "Subscription to an online streaming service",
        "Cardholder",
        "Nesser",
        "Car cup holder with heating function",
        "Paintball ticket",
        "Electric scooter",
        "Fitness bracelet",
        "Sleeping bag",
        "Multitool",
        "Orthopedic pillow",
        "Shoe dryer",
        "Ice scraper",
        "Water filter",
        "Aromatherapy diffuser",
        "Beard care kit",
        "Indoor skydiving experience",
        "Massage session certificate",
        "Camera",
        "Star projector",
        "Lunch box",
        "Smart alarm clock",
        "Tray table",
        "Thermal underwear",
        "Keychain",
        "Graphic tablet",
        "Bracelet",
        "Inflatable mattress",
        "Car vacuum cleaner",
        "Mulled wine kit",
        "Travel neck pillow",
        "Raincoat",
        "Music player",
        "Romantic dinner",
        "Hand warmer",
        "Electric blanket",
        "Computer game",
        "Laptop case",
        "Fanny pack",
        "Trip to a water park",
        "Boat trip",
        "Nightlight",
        "Ticket to a concert of their favorite band",
        "High-quality set of spices or exotic sauces",
        "Tickets to their favorite team's match",
        "New sports equipment",
        "Bicycle",
        "Skateboard",
        "Swimming gear",
        "Gym membership for yoga or fitness classes",
        "Weekend or week-long trip to their favorite destination",
        "Gaming headset",
        "High-quality headphones",
        "Leather briefcase",
        "High-quality leather belt",
        "Set of woodworking or metalworking tools",
        "Crafting workshop or book",
        "Model plane, ship, or car kit",
        "Pocket printer",
        "Tabletop bio fireplace",
        "Levitating globe",
        "Wireless car compressor",
        "Oura Ring smart ring",
        "Table lamp with wireless smartphone charging",
        "Personalized 3D lamp",
        "YOTA mobile router",
        "Apple AirTag tracker",
        "Himalayan salt lamp",
        "Battery case",
        "Inflatable lounger",
        "Globe bar",
        "Baseball cap",
        "Portable projector",
        "Camera drone",
        "Pillow with your photo or a unique print",
        "Useful online course",
        "Gift set of meat delicacies for men",
        "Instant print camera",
        "Fleece blanket with your photo or a unique print",
        "Handheld steamer",
        "Table lamp LED tree",
        "Lamp with your photo or a unique print",
        "Chameleon mug",
        "Thermos cup with your photo or a unique print",
        "Smart speaker",
        "Bathrobe",
        "Ice cream maker",
        "Bedding set",
        "Smart garland",
        "Vinyl record player",
        "Digital photo frame",
        "Safe piggy bank",
        "Scratch-off world map",
        "String art picture based on a photo",
        "Gift set of soap for men",
        "Neon flex lamp",
        "Glowing mouse pad",
        "Gift set of glasses",
        "Gift set 'Real Man'",
        "Plasma ball",
        "Smart backpack with a display",
        "Glowing star map",
        "LED strip for room lighting",
        "Fluid art painting kit",
        "XPower trimmer",
        "Painting kit 'Hands of Lovers'",
        "Puzzle",
        "Easel",
        "Helium-filled balloon bouquet",
        "Photo holder",
        "Paint by numbers and contour kits",
        "Puzzle box",
        "3D night light",
        "Box of chocolate candies",
        "Aromatic candle",
        "Bath hat",
        "Monopoly game",
        "Engraving on canvas",
        "Chocolate bar",
        "Gift set of honey",
        "Epoxy resin painting kit",
        "Cufflinks",
        "3D origami constructor",
    )

    private val femaleGiftIdeas = listOf(
        "Jewelry",
        "Perfume",
        "Books on her interests",
        "SPA certificate",
        "Unique tea or coffee",
        "Technical gadget like a new phone or headphones",
        "Vintage vinyl",
        "Subscription to hobby masterclasses",
        "Gift basket with gourmet products",
        "Drawing set or other hobby-related items",
        "Tickets to her favorite artist's concert",
        "A trip to the city she has always wanted to visit",
        "Exquisite wine",
        "High-quality cosmetics set",
        "Year-long magazine subscription",
        "Romantic dinner at a restaurant",
        "Subscription to online courses (language, culinary, art, etc.)",
        "Cozy blanket for home comfort",
        "Gift certificate to her favorite store",
        "Horseback riding lessons",
        "Silk robe",
        "Yoga or fitness club sessions",
        "Gift certificate for a professional photoshoot",
        "Hot air balloon ride",
        "Elegant bags or wallets",
        "Exotic plants for home",
        "Surprise party arrangement",
        "Certificate for a winery or brewery visit",
        "Premium chocolates or desserts",
        "Board games based on her interests",
        "Unique designer home accessory",
        "Cooking class for her favorite dish",
        "Subscription to audiobooks or streaming service",
        "Kit for growing her own herbs or spices",
        "Yacht trip or cruise",
        "Gift certificate for dance classes",
        "Exclusive bottle of her favorite alcoholic beverage",
        "Skincare set",
        "High-quality art supplies",
        "Luxurious dress or blouse",
        "Concert ticket for her favorite band or artist",
        "Cookbook with recipes from around the world",
        "Quality coffee maker or kettle",
        "Massage chair for relaxation",
        "Subscription to a fitness club or yoga studio",
        "Invitation to a cooking workshop with a renowned chef",
        "Ticket to a fashion show or art exhibition",
        "Kit for creating her own custom perfume",
        "Gift certificate for meditation or massage classes",
        "Experience of driving a sports car on a track",
        "Theater performance ticket",
        "Home winemaking kit",
        "Professional camera",
        "Luxury bedding set",
        "Assortment of cheeses from different countries",
        "Handmade decorative candles",
        "Participation in a workshop on gardening or floristry",
        "Picnic set with quality equipment",
        "Year-long access to a music streaming service",
        "Books by her favorite authors in beautiful editions",
        "Professional sommelier lesson",
        "Silk lingerie",
        "Set for writing with a pen and ink",
        "Subscription to a magazine related to her interests",
        "Luxurious cosmetic bag",
        "Experience of enjoying hot springs",
        "Gift certificate to a bookstore",
        "Sushi-making masterclass",
        "Stylish passport and document covers",
        "Singing or musical instrument lessons",
        "Set for creating her own mini-library",
        "High-quality cutlery set",
        "Certificate for rock climbing or skydiving",
        "Aromatherapy set with essential oils",
        "Stylish umbrellas or raincoats",
        "Tickets to a sports event",
        "Cooking classes with a professional chef",
        "Stylish cases for her devices",
        "Luxurious nightshirt or pajamas",
        "Gift certificate to a hair salon or beauty salon",
        "Tickets to a hot spring or thermal baths",
        "Scenic helicopter flight",
        "Safari experience or visit to the zoo",
        "Chocolate-making workshop",
        "Gastronomic tour tickets",
        "High-quality barbecue set",
        "Exclusive set for bath and relaxation",
        "Chic boots or sneakers",
        "Gift certificate for painting or sculpture lessons",
        "Astronomy set with a telescope",
        "Beadwork or embroidery kit",
        "Gift certificate for Pilates classes",
        "Stylish kitchen gadgets",
        "Professional hair care set",
        "Excursion to a winery or brewery",
        "Tickets to a circus performance",
        "Pottery kit",
        "Subscription for monthly flower delivery",
        "Excursion to a tea or coffee plantation",
        "Gift certificate to a high-fashion boutique",
        "Gift certificate for lecture courses on her interests",
        "Retro vinyl record player",
        "A beautifully decorated photo album with your shared photos",
        "Lessons for learning a new language",
        "Gift certificate to a classy restaurant",
        "Tickets for a hot air balloon ride",
        "Bicycle or electric scooter",
        "Art supplies, if she enjoys painting",
        "Subscription to virtual yoga or fitness workouts",
        "High-quality camera for vlogging, if she enjoys making videos",
        "Subscription for organic food delivery",
        "Exclusive set of coffee-making utensils",
        "Excursion to a horse farm with horseback riding",
        "Jewelry with her zodiac sign",
        "Gift certificate to a luxury hotel for a weekend getaway",
        "Luxurious home decor items",
        "Tickets to a music festival",
        "Retro typewriter, if she enjoys writing",
        "Home brewing kit",
        "Tickets for a boat or yacht trip",
        "Books or book series by her favorite authors",
        "Wine education or wine tasting course",
        "Experience of a culinary masterclass for exotic dishes",
        "Picturesque trip to a scenic island",
        "Stylish and functional workout attire",
        "Tickets to a seminar or lecture in her field of interest",
        "Personal training session with a professional trainer",
        "Smart home appliance set",
        "Comfortable and stylish home office chair",
        "Gift certificate to a local library or bookstore",
        "Subscription to online drawing or crafting classes",
        "Set of exotic spices and sauces from around the world",
        "Stylish yoga mat",
        "Certificate for dance lessons",
        "Luxurious lingerie set",
        "Tickets to a charity dinner or event",
        "Barbecue or picnic set for outdoor activities",
        "Subscription to podcast streaming service",
        "Foot or hand care set",
        "Gift certificate for a hot air balloon adventure",
        "Experience of canoeing or kayaking",
        "Subscription to online drawing or painting classes",
        "Tickets for a winery tour",
        "Professional culinary tools for favorite dishes",
        "Exotic massage or spa treatments",
        "Subscription to online language courses",
        "Gift set of luxury teas",
        "Tickets to a philharmonic concert or opera",
        "Jewelry-making masterclass",
        "Gift certificate for motorcycle riding lessons",
        "Book by her favorite author in a leather binding",
        "Lessons on scriptwriting or creative writing",
        "Gift certificate for skincare treatments at a salon",
        "Tickets to a ballet or theater performance",
        "Professional makeup set",
        "Photography lessons or photo editing course",
        "Adventure park excursion",
        "Gift certificate for interior decor workshop",
        "Set of exquisite wines or champagne",
        "Ceramics or pottery-making lessons",
        "Professional diving or snorkeling gear",
        "Music instrument lessons",
        "Beautiful dress or other wardrobe item",
        "Set of books for reading while traveling",
        "Gift certificate for yoga or Pilates classes",
        "Basket weaving masterclass",
        "Tickets to a symphony orchestra concert",
        "Stylish hair accessories",
        "Dance lessons",
        "Fandom merchandise from her favorite movie or TV show",
        "Guitar or other musical instrument lessons",
        "Subscription to a music streaming service",
        "Stylish covers for her gadgets",
        "Calligraphy lessons",
        "Retro games or board games",
        "Sushi-making kit",
        "Trendy coffee-making equipment",
        "Farm cheese tour",
        "Exclusive concert tickets",
        "Gift certificate for golf lessons",
        "Home cocktail-making kit",
        "Tickets to a popular sports event",
        "Watercolor or other art form lessons",
        "Statuette or artwork from her favorite era",
        "Set of exquisite cheeses and wines",
        "Pizza-making masterclass",
        "Stylish sneakers for workouts",
        "Yacht excursion",
        "Drum lessons",
        "Subscription to a gourmet magazine",
        "Set of brushes and paints for artists",
        "Guided tour of a gallery or museum",
        "Comfortable and stylish urban backpacks",
        "Subscription to a fashion or culture magazine",
        "Tour of a pastry factory",
        "Tickets to a zoo or water park",
        "Fencing lessons or another unusual sport",
        "Certificate for cosmetic procedures or massage",
        "Gift certificate for rock climbing",
        "Tour of a local apiary",
        "Tickets to a concert by a famous performer",
        "Retro letter-writing set with wax seals",
        "Lessons for learning a new foreign language",
        "Subscription to a meditation learning service",
        "Tasty delicacies from local farms",
        "Acting or improvisation lessons",
        "Tickets to an art festival or exhibition",
        "Subscription to virtual yoga classes",
        "High-quality camera for vlogging",
        "Subscription to fitness or healthy eating courses",
        "Experience of driving a racing car on a track",
        "Stationary exercise bike for home workouts",
        "Tour of a historical site or museum",
        "Subscription to an audiobook service",
        "Singing or vocal lessons",
        "Certificate for professional makeup lessons",
        "Culinary masterclass for exotic desserts",
        "Tickets to a sports match of her favorite team",
        "Individual piano lessons",
        "Exclusive bath essence",
        "Set of stylish eco-friendly tableware",
        "Subscription to online sommelier classes",
        "Kit for making homemade scented candles",
        "Tickets to hot springs or thermal baths",
        "Gift certificate for surfing lessons",
        "Stylish laptop bag",
        "Premium chocolate gift set",
        "Subscription to a personalized playlist service",
        "Lessons for creating animations or designs",
        "Certificate for neck and collar zone massage",
        "Clay sculpting masterclass",
        "Sailing trip",
        "Decorative painting lessons",
        "Subscription to a psychology or self-improvement magazine",
        "Subscription to gardening courses",
        "Luxurious pendant with her initials",
        "World map for marking visited places",
        "Gift certificate for graphic design lessons",
        "Tickets to the taping of her favorite TV show",
        "Luxurious kimono for home",
        "High-quality photography equipment set for beginners",
        "Tour of a chocolate factory",
        "Fashion design lessons",
        "Gift certificate for beadwork or jewelry making lessons",
        "Subscription to a distance learning service",
        "Experience of participating in a reality quest",
        "Kit of high-quality ingredients for home brewing",
        "Music production lessons on a computer",
        "Certificate for a course on philosophy or history",
        "Knitting lessons",
        "Tickets to a fashion show",
        "Subscription to healthy cooking classes",
        "Gift set of her favorite cosmetics",
        "Aqua makeup lessons",
        "Craft kit using recycled materials",
        "Luxurious bath or spa set",
        "Subscription to online photography or video editing courses",
        "Tickets for a winery tour with wine tasting",
        "Lessons for creating jewelry from polymer clay",
        "Gift certificate for pole dancing lessons",
        "Luxurious personalized cosmetic bag",
        "Barista kit with quality coffee and accessories",
        "Subscription to online meditation and relaxation services",
        "Ceramics making masterclass",
        "Tickets to a tour of an ancient castle or palace",
        "Quilling or paper art lessons",
        "Luxurious cashmere gloves or scarf",
        "Set for creating homemade natural cosmetics",
        "Certificate for beach or nature park yoga lessons",
        "Subscription to a service for online history and culture studies",
        "Acrobatics or gymnastics lessons",
        "Luxurious vintage-style jointed doll",
        "Tour of a chocolate candy factory",
        "Gift certificate for a romantic yacht trip",
        "Subscription to a service for creating personalized playlists",
        "Certificate for a neck and collar zone massage",
        "Set for creating your own perfumes",
        "Tickets to a musical or theater production",
        "Lessons for learning a foreign language in its country of origin",
        "Gift certificate for a bike tour",
        "Exclusive book collection from her favorite author",
        "Lessons for creating plaster sculptures",
        "Subscription to online nature photography courses",
        "Luxurious set for relaxation and aromatherapy",
        "Candle-making masterclass",
        "Tickets to an opera house concert",
        "Gift certificate for archery lessons",
        "Luxurious Egyptian cotton bedding set",
        "Artificial rock climbing lessons",
        "Subscription to an online fashion shopping service",
        "Tour of a crystal factory",
        "Badminton set or another active game",
        "Gift certificate for Muay Thai classes",
        "Macrame or weaving lessons",
        "Luxurious collection of tea leaves from around the world",
        "Subscription to an online service for psychology and self-development courses",
        "Tickets to a music festival or open-air event",
        "Graffiti or street art lessons",
        "Gift certificate for horseback riding lessons",
        "Tour of a coffee plantation or coffee roasting factory",
        "High-quality headphones or portable speaker system",
        "Subscription to an online workout and fitness service",
        "Luxurious set for spa procedures and body care",
        "Tickets to a film festival or movie premiere",
        "Gift certificate for parkour or acrobatics lessons",
        "Unique vintage home decor item",
        "Tour of the filming location of her favorite movie or TV show",
        "Kit for home craft beer brewing",
        "Polymer clay doll-making lessons",
        "Gift certificate for facial massage or spa treatments",
        "Luxurious collection of cosmetics or perfumes",
        "Photo booth or photo show kit",
        "Leathercraft lessons",
        "Gift certificate for a stylist or personal shopper consultation",
        "Subscription to an online cooking and baking course service",
        "Tickets to a play or comedy show",
        "Lessons for creating her own blog or vlog",
        "Gift certificate for aromatherapy lessons",
        "Tour of an organic farm with participation in the work",
        "High-quality briefcase or work bag",
        "Scrapbooking or photo album-making masterclass",
        "Subscription to an online service for organic product shopping",
        "Tickets to a circus performance or show",
        "Gift certificate for salsa or other dance lessons",
        "Lessons for creating jewelry with precious stones",
        "Tour of a perfume manufacturing factory",
        "Yoga or Pilates kit",
        "Gift certificate for thermal springs or spa salon visit",
        "Luxurious set of tea cups and mugs",
        "Ceramics making lessons",
        "Subscription to an online service for stylish clothing and accessory shopping",
        "Fabric doll-making masterclass",
        "Gift certificate for a massage session at a spa center",
        "Bouquet of her favorite flowers",
        "Silver heart-shaped necklace",
        "Set of high-quality cosmetics from a well-known brand",
        "Certificate for spa procedures at a luxurious spa salon",
        "Trip to Bali for a romantic week",
        "New iPhone smartphone, the latest model",
        "Set of art brushes and easel for her artistic activities",
        "Gift certificate to her favorite online store",
        "Personalized silver pendant with her initials",
        "Stylish leather bag from her favorite designer",
        "Yoga class pass",
        "Smart headphones with noise cancellation",
        "Stylish and comfortable home slippers",
        "Plush robe",
        "Wristwatch with an elegant design and leather strap",
        "Subscription to a magazine or newspaper she enjoys reading",
        "Kit for creating her own jewelry: necklaces, bracelets, earrings, etc.",
        "Perfume from her favorite brand",
        "Stainless steel thermos with her name or personalized design",
        "Gift certificate for a professional photo shoot or family portrait",
        "Luxurious bath set with aromatic oils, bath foam, and candles",
        "Set of high-quality brushes and cosmetics for makeup",
        "Subscription to an online course or masterclass in her area of interest",
        "E-reader, so she can enjoy reading anytime, anywhere",
        "Smart bracelet for activity tracking",
        "Sports headphones",
        "Ticket pass for a concert by her favorite artist or band",
        "Ticket pass for a musical concert",
        "Ticket pass for a theatrical performance",
        "Stylish coffee machine",
        "Relaxation pillow with massage effect",
        "Gift set for creating your own cocktails with recipes and necessary ingredients",
        "Subscription to a streaming service",
        "Fashionable laptop or tablet bag",
        "Air fryer device",
        "Multi-cooker",
        "Set of high-quality cookware and kitchen utensils",
        "Set for macrame or embroidery",
        "Electric toothbrush",
        "Virtual reality (VR) device",
        "Stylish personalized portfolio",
        "Set for creating your own garden: seeds, pots, gardening tools, and plant care",
        "Gift subscription to a streaming platform",
        "Yoga and meditation course",
        "Individual lesson or course in desired art form",
        "Kit for creating aromatic candles with the option to choose ingredients",
        "Trip to an exotic island",
        "Bicycle",
        "Skateboard",
        "Ski equipment",
        "Subscription to a culinary magazine or online platform with recipes and culinary ideas",
        "Tea set with various types of tea, mugs, and tea accessories",
        "Personalized photo book with memories and photographs",
        "Yoga accessories such as a mat, blocks, straps",
        "Kit for creating your own indoor garden on a windowsill or balcony",
        "Excursion or workshop related to her interests or hobbies",
        "Kit for a home spa day with aromatic oils, face masks, scrubs, and candles",
        "Pendant with her name or initials",
        "Bracelet with her name or initials",
        "Set of exotic spices and seasonings",
        "Voice assistant",
        "Smart lighting system",
        "Gift subscription to a massage salon",
        "Physical therapy sessions",
        "High-quality dinnerware set",
        "Kit for creating your own natural cosmetics",
        "Stylish and comfortable headphones or wireless Bluetooth headphones",
        "Dance course or lessons",
        "Stylish and functional smart bracelet",
        "Electronic children's gaming console",
        "Tablet",
        "Culinary tour",
        "Gastronomic excursion",
        "Interactive fitness platform",
        "Set for creating your own smoothies",
        "Exclusive wine collection",
        "Personalized journal or notebook with her name or motivational message",
        "Nail airbrushing device",
        "Kit for professional manicure and pedicure",
        "Stylish and protective sunwear",
        "Accessories for summer travel",
        "Kit for creating your own handmade soap",
        "Subscription to a food delivery service",
        "Ready-to-use recipe kits",
        "Exclusive leather gloves",
        "Accessories for winter fashion",
        "Photography course or lessons",
        "Streaming device for movies and TV shows",
        "Set of tools and materials for crafts",
        "Lamp-speaker for wake-up light and music",
        "Pocket printer",
        "Rowenta facial and body massagers",
        "Iziq obsidian stone bracelets",
        "Rowenta brush hairdryer",
        "LED tree table lamp",
        "Oura Ring smart ring",
        "Personalized 3D lamp",
        "TANGLE TEEZER comb",
        "Blanket with sleeves",
        "LED lamp with your photo or original print",
        "Rose in a glass dome",
        "Wireless phone charger",
        "Blanket with your photo or original print",
        "Glasses with original inscription",
        "Table mirror with lighting",
        "Thermos cup with your photo or original print",
        "I love You pendant in 100 languages",
        "Casting in a modeling school",
        "Strawberry bouquet in chocolate",
        "Robot vacuum cleaner",
        "Tabletop fountain with lighting",
        "Digital photo frame",
        "Coffee gift set",
        "Electric straightening brush",
        "Desk lamp with wireless smartphone charging",
        "Large manicure set",
        "Jewelry box",
        "Star projector",
        "Gold earrings",
        "Smart garland",
        "Lava lamp",
        "String art picture based on a photograph",
        "Inflatable lounger",
        "Beauty case",
        "Sleep mask with built-in headphones",
        "3D rose teddy bear",
        "Photo holder",
        "Zodiac sign pendant",
        "Smartphone lens",
        "Liquid soap dispenser",
        "Chameleon mug",
        "Desk organizer",
        "Xiaomi drawing tablet",
        "Curling iron",
        "Flexible neon lamp",
        "Bean bag chair",
        "Sushi and rolls making kit",
        "Photoshoot",
        "Epoxy resin art kit",
        "Sewing machine",
        "Curtain garland",
        "Cosmetic set",
        "Yogurt maker",
        "Bedding set",
        "Hairpins",
        "Dancing cactus toy",
        "Chocolate bouquet",
        "Sunset lamp",
        "Paint by numbers and contour kits",
        "Shopper bag",
    )
}