package com.sosinvitalii.database.giftIdeas

import com.sosinvitalii.database.giftIdeas.Gender

object EnglishGiftIdeas {
    fun fetch(gender: Gender): List<String> {
        return if (gender == Gender.MALE) {
            maleGiftIdeas
        } else {
            femaleGiftIdeas
        }
    }

    private val maleGiftIdeas = listOf(
        "Swiss wristwatch",
        "Leather wallet",
        "Barbecue set",
        "E-book",
        "Coffee machine",
        "Gym membership or golf game pass",
        "Subscription to a magazine or streaming platform",
        "Stylish pen and notebook",
        "Set of quality beer or wine",
        "Portable acoustic system",
        "Shaving kit",
        "Retro video games",
        "Professional tool set",
        "Messenger bag or backpack",
        "Smart home assistant",
        "Air humidifier",
        "Sushi-making kit",
        "Compact binoculars",
        "Video shooting drone",
        "Textbook or course for learning a new language or skill",
        "Board game",
        "T-shirt with the logo of a favorite sports team",
        "Fitness bracelet",
        "Compact camping tent",
        "Sunglasses",
        "Pizza-making kit",
        "Wireless headphones",
        "Experience of driving a sports car",
        "Bottle of vintage wine or expensive whiskey",
        "Books or audiobooks by a favorite author",
        "Original survival knife",
        "3D puzzle or construction set",
        "Soft robe and slippers",
        "GoPro camera for extreme sports",
        "World map for a traveler",
        "Gift certificate to a favorite restaurant",
        "Ship model building kit",
        "Portable power bank",
        "Thermos mug",
        "Virtual reality goggles",
        "Stylish tie or bowtie",
        "Wine tasting certificate",
        "Guidebook to the country or city they want to visit",
        "Painting or poster with the image of a favorite band, movie, or hero",
        "Cookbook for cooking enthusiasts",
        "Yoga or fitness mat",
        "Fishing accessories",
        "Table lamp for reading",
        "External hard drive or SSD",
        "Home theater projector",
        "Smartwatch",
        "Leather bracelet",
        "Vinyl records of a favorite artist",
        "Whiskey glasses",
        "Moleskine notebook",
        "Home plant growing kit",
        "Karaoke microphone",
        "Laptop bag",
        "Open fire grill",
        "Crafting or DIY project set",
        "Gift certificate for a professional massage",
        "Shoe cleaning kit",
        "Quality skewer for shish kebab",
        "Subscription to online master classes for their hobby",
        "Set of collectible coins or stamps",
        "Thematic calendar",
        "Skydiving voucher",
        "Tickets to a concert or sports event",
        "Table tennis tabletop",
        "Comfortable sneakers or boots",
        "Gourmet gift set (e.g., cheeses, sausages, chocolates)",
        "Professional camera or lens",
        "Smart bracelet or fitness tracker",
        "Poker set",
        "Golf or tennis lessons",
        "Turntable for vinyl records",
        "Gift certificate for a real-life quest",
        "Latest model smartphone",
        "Exclusive coffee subscription",
        "Subscription to an online platform for learning foreign languages",
        "Stylish keychain",
        "Personalized hot pot holder",
        "Food thermos",
        "Radio-controlled car or helicopter model",
        "Memorable soccer or basketball",
        "Electric toothbrush",
        "Mini fridge for beverages",
        "Wine lessons with a sommelier",
        "Personalized hot pot holder",
        "Food thermos",
        "Radio-controlled car or helicopter model",
        "Memorable soccer or basketball",
        "Electric toothbrush",
        "Mini fridge for beverages",
        "Wine lessons with a sommelier",
        "Tickets to a themed festival",
        "Charging station for electronic devices",
        "Swiss army knife",
        "Gift set of essential oils for relaxation",
        "Drawing or painting set",
        "Bottle of personalized whiskey or rum",
        "One-year subscription to a yoga or meditation course",
        "Action camera for extreme sports",
        "Electronic bracelet for monitoring a healthy lifestyle",
        "Compact massager",
        "Stylish leather belt",
        "Home theater with projector and sound system",
        "Custom portrait or caricature",
        "Vintage stylish umbrella",
        "Swimming lessons or scuba diving certificate",
        "Vintage typewriter",
        "Compact espresso machine",
        "Art book on his/her interests",
        "Gift set of spices and sauces",
        "Manual coffee grinder",
        "Wooden checkers or chess set",
        "Gift set for beard care",
        "Winemaking kit",
        "Compact portable projector for smartphones",
        "Muay Thai or other martial arts kit",
        "Luxurious stylish lighter",
        "Beer-making kit",
        "Book light for reading",
        "Tabletop game with strategic elements",
        "Gift set for fishermen",
        "Watch or jewelry box",
        "Mini desktop billiards",
        "Delicious gourmet gifts (nuts, chocolate, delicacies)",
        "Specialized equipment for cyclists",
        "Subscription to audiobooks",
        "Bottle of fine Georgian wine",
        "Cookie icing kit",
        "Souvenir t-shirt or tank top with a unique design",
        "Stylish headwear (hat, cap, Panama hat)",
        "Gift box with wine and cheeses",
        "Wall map to mark visited countries",
        "Camera cleaning kit",
        "Book on art history or design",
        "Bottle of fine cognac or rum",
        "Language learning textbook",
        "Set of unique wine glasses",
        "Board game 'Dixit' or 'Codenames'",
        "Gift set of good coffee",
        "Compact drawing set",
        "Gift certificate for a culinary school",
        "Photo book with places from his/her childhood",
        "Professional headphones",
        "Stylish case for smartphone or laptop",
        "Mini barbecue for picnics",
        "Gift set of hot sauces",
        "Ushanka hat for winter adventures",
        "E-book reader for reading books",
        "Subscription to favorite sports channel",
        "Ergonomic laptop stand",
        "Swimming goggles",
        "Memorable medal or trophy related to his/her interests",
        "Gift set of branded golf tees",
        "Fitbit bracelet or other activity tracker",
        "Compact blender for making smoothies",
        "Board game 'Carcassonne' or 'Dominion'",
        "Subscription to a music streaming service",
        "Compact bicycle repair tool kit",
        "Wine rack",
        "Luxurious silk scarf or shawl",
        "Gift set for skincare",
        "Hand exerciser for strengthening arm muscles",
        "World atlas for geography enthusiasts",
        "Bracelet for sleep tracking",
        "Wall clock with an interesting design",
        "Personalized engraved pen",
        "Professional back or foot massager",
        "Gift set of shaving cosmetics",
        "Sweatshirt or sweater with the logo of a favorite sports team",
        "Star projector for creating a romantic atmosphere",
        "Heated mouse pad",
        "Tickets to a football match or basketball game",
        "Books on philosophy or psychology",
        "Tabletop game 'Real Football'",
        "Wireless smartphone charger",
        "Stainless steel thermos for keeping drinks hot or cold",
        "Gift set for making homemade beer",
        "Bicycle computer for tracking speed and distance",
        "Shoe care kit",
        "Subscription to a magazine based on his interests",
        "Electric shaver",
        "Drawing tablet",
        "Sushi-making kit",
        "Electric toothbrush with whitening function",
        "Device charging station",
        "Gift set of sports nutrition",
        "Acoustic guitar or another musical instrument",
        "Cocktail kit and bar equipment",
        "Air purifier and freshener device",
        "Gift set of premium teas",
        "Football with the autograph of a famous player",
        "Grooming kit and accessories for beard care",
        "Book with the autograph of a favorite author",
        "Hoverboard or electric scooter",
        "Camping and picnic accessories set",
        "Notebook with a personalized cover",
        "Portable cassette player",
        "Gift set of massage oils and lotions",
        "DIY chocolate-making kit",
        "Sports backpack or gym bag",
        "Headphone stand",
        "Smart gloves for winter use with touchscreen technology",
        "Interactive robot or drone",
        "Home theater kit (projector, screen, sound system)",
        "Stylish portfolio or work bag",
        "Gift set of quality brushes and paints for artistic creativity",
        "Solar device charging station",
        "Personalized golf set",
        "Smartphone with improved camera and photography features",
        "Gift set of retro games or video games",
        "Bowling set",
        "Skateboard or longboard",
        "Gift set of exotic spices and seasonings",
        "Picnic or barbecue set in a convenient bag",
        "Set for creating custom perfume compositions",
        "Device for maintaining wine freshness and long-term storage",
        "Certificate for indoor skydiving session or wakeboarding",
        "Tabletop foosball or billiards",
        "Smart wristwatch with fitness tracking function",
        "Gift set of rare and exotic teas",
        "Barbershop tools set",
        "Home beer brewing kit with original recipes",
        "Unconventional or high-piece-count puzzle",
        "Smart glasses with augmented reality function",
        "Desktop calendar with photos and important dates",
        "Set for creating your own micro-garden or mini-garden",
        "Certificate for a massage session or spa treatment",
        "Set of professional makeup brushes",
        "Interactive gaming console",
        "Gift set of expensive and rare whiskies",
        "Electric dental flosser or irrigator",
        "Knitting or embroidery kit",
        "Hammock for outdoor relaxation",
        "Gift set for brewing your own beer",
        "Stylish leather wallet",
        "Carving set for fruits and vegetables",
        "Boot or glove dryer",
        "Premium coffee set with a grinder",
        "Retro film camera",
        "Gift set for baristas",
        "Croquet game set",
        "Shaving kit with a mirror",
        "Wooden tabletop game 'Checkers' or 'Nine Men's Morris'",
        "Gift set of elite cigars",
        "Winemaking kit for creating your own wine",
        "Foldable bicycle for convenient transportation",
        "Set for making your own soaps and scented candles",
        "Subscription to a culinary magazine or recipe database",
        "Device for mobile phone photo printing",
        "Ping-pong game set",
        "Gift set of branded cosmetic products",
        "Backpack with an integrated solar panel for device charging",
        "Set of professional pencils and watercolor paints for artists",
        "Gaming keyboard and mouse for gamers",
        "Charging station for electronic devices on a desk",
        "Anti-stress kit with toys and gadgets",
        "Book with interactive elements or 3D illustrations",
        "BBQ grill for outdoor use",
        "Gyroscope-powered light garland for creating ambiance",
        "Gift set of plush towels and a robe",
        "Home massage chair",
        "Set for creating your own perfumes or aromatic fragrances",
        "Music speaker with built-in lighting and illumination",
        "Gift set of exotic spices and sauces for Asian cuisine",
        "Mini projector for watching movies and videos on a large screen",
        "Gift certificate for sauna sessions and spa treatments",
        "Set for pin-up style photography and shooting",
        "Electronic bureaucratic game for developing strategic thinking",
        "Travel accessories set (pillow, sleep mask, skincare kit)",
        "Subscription to online photography or videography courses or masterclasses",
        "Roadside tool kit for automobiles",
        "Interactive toy robot",
        "Gift set for creating your own cosmetics",
        "Kit for creating your own mini-garden or vertical garden",
        "Wireless Bluetooth speaker with built-in lighting",
        "Beard and mustache grooming kit",
        "Desktop fountain for relaxation and ambiance",
        "Gift set of high-quality cutlery",
        "Smart helmet for cyclists or motorcyclists",
        "Kit for creating your own jewelry",
        "Interactive set for learning robotics and programming",
        "Set for creating your own perfumes or aromatic fragrances",
        "Desktop fountain for relaxation and ambiance",
        "Home smoking kit",
        "Gift set for creating your own cocktails",
        "Smart door lock",
        "Set of professional brushes and paints for artists",
        "Video shooting and editing kit",
        "Gift set of premium tea",
        "Device for air grilling or multicooking",
        "Desk lamp with built-in charging station for devices",
        "Gift set for making your own souvenirs",
        "Compact electric vehicle charging station",
        "Tool kit for DIY repairs and construction",
        "Interactive children's construction set",
        "Gift set of expensive and rare tea leaves",
        "Robot vacuum cleaner for automatic cleaning",
        "Home chocolate fondue set",
        "Kit for creating your own natural cosmetics",
        "Tabletop game in steampunk style",
        "Premium grill tool gift set",
        "Activity and sleep tracking device",
        "Interactive electronic drawing and note board",
        "Gift set of elite cognacs",
        "Customizable perfume-making kit",
        "Kit for creating your own furniture project",
        "Smart home assistant robot",
        "Gift set of elite tea blends",
        "Brewing kit with the ability to create your own beer variety",
        "Tabletop game in fantasy or science fiction style",
        "Gift set for creating your own aromatic massage oil",
        "Compact home fitness trainer",
        "Set of professional culinary knives",
        "Gift set of expensive rare spirits",
        "Device for creating electronic music and compositions",
        "Interactive tabletop game in cyberpunk style",
        "Gift set for making your own ice cream",
        "Kit for creating your own leather goods",
        "Device for shooting and streaming video blogs",
        "Gift set of exotic spices and seasonings for gastronomic experiments",
        "Kit for creating your own gallery or art exhibition",
        "Interactive robot dog or robot cat",
        "Set of professional pencils and markers for illustrations and comics"
    )

    private val femaleGiftIdeas = listOf(
        "Jewelry",
        "Perfume",
        "Books on her interests",
        "SPA certificate",
        "Unique tea or coffee",
        "Technical gadget, such as a new phone or headphones",
        "Vintage vinyl",
        "Subscription to hobby-related masterclasses",
        "Gift basket with gourmet products",
        "Drawing set or other hobby-related items",
        "Tickets to her favorite artist's concert",
        "Trip to the city she always wanted to visit",
        "Exquisite wine",
        "High-quality cosmetics set",
        "Yearly magazine subscription",
        "Romantic dinner at a restaurant",
        "Subscription to online courses (language, culinary, artistic, etc.)",
        "Comfortable blanket for home coziness",
        "Gift certificate to her favorite store",
        "Horseback riding lessons",
        "Silk robe",
        "Yoga or fitness club classes",
        "Gift certificate for a professional photoshoot",
        "Hot air balloon ride",
        "Elegant bags or wallets",
        "Exotic houseplants",
        "Surprise party organization",
        "Certificate for a winery or brewery visit",
        "Luxury chocolates or desserts",
        "Board games based on her interests",
        "Unique designer home accessory",
        "Cooking class to prepare her favorite dish",
        "Subscription to audiobooks or streaming service for movies and TV shows",
        "Kit for growing her own herbs or spices",
        "Yacht trip or cruise",
        "Gift certificate for dance classes",
        "Exclusive bottle of her favorite alcoholic beverage",
        "Skincare set",
        "High-quality art supplies",
        "Luxurious dress or blouse",
        "Concert ticket for her favorite band or artist",
        "Cookbook with recipes from around the world",
        "High-quality coffee maker or kettle",
        "Massage chair for relaxation",
        "Fitness club or yoga studio membership",
        "Invitation to a cooking workshop with a famous chef",
        "Ticket to a fashion show or art exhibition",
        "Kit for creating her own perfume",
        "Gift certificate for meditation or massage classes",
        "Experience of driving a sports car on a track",
        "Theater performance tickets",
        "Home winemaking kit",
        "Professional camera",
        "Luxurious bedding set",
        "Assortment of cheeses from different countries",
        "Handmade decorative candles",
        "Participation in a workshop on gardening or floristry",
        "Picnic set with quality equipment",
        "Yearly subscription to a music streaming service",
        "Books by her favorite authors in beautiful editions",
        "Professional sommelier lesson",
        "Silk lingerie",
        "Set for writing with a pen and ink",
        "Subscription to a magazine on her interests",
        "Luxury cosmetic bag",
        "Experience of enjoying hot springs",
        "Gift certificate to a bookstore",
        "Sushi-making masterclass",
        "Stylish passport and document covers",
        "Singing or musical instrument lessons",
        "Set for creating her own mini-library",
        "High-quality cutlery",
        "Certificate for rock climbing or skydiving",
        "Aromatherapy kit with essential oils",
        "Stylish umbrellas or raincoats",
        "Tickets to a sports event",
        "Cooking lessons with a professional chef",
        "Stylish cases for her devices",
        "Luxurious nightshirt or pajamas",
        "Gift certificate to a hair salon or beauty salon",
        "Tickets to a hot spring or thermal baths",
        "Scenic helicopter flight",
        "Safari experience or visit to a zoo",
        "Chocolate-making masterclass",
        "Tickets to a gourmet food tour",
        "High-quality barbecue set",
        "Exclusive bath and relaxation set",
        "Stylish boots or sneakers",
        "Gift certificate for painting or sculpture lessons",
        "Astronomy learning kit with a telescope",
        "Beadwork or embroidery kit",
        "Gift certificate for Pilates classes",
        "Stylish kitchen gadgets",
        "Professional hair care set",
        "Winery or brewery tour",
        "Tickets to a circus show",
        "Pottery kit",
        "Subscription for monthly flower delivery",
        "Tea or coffee plantation tour",
        "Gift certificate to a high-fashion boutique",
        "Gift certificate for a course on her interests",
        "Retro vinyl record player",
        "Beautifully decorated photo album with your shared photos",
        "Lessons for learning a new language",
        "Gift certificate to a classy restaurant",
        "Tickets for a hot air balloon ride",
        "Bicycle or electric scooter",
        "Art supplies if she enjoys painting",
        "Subscription for virtual yoga or fitness workouts",
        "High-quality camera for vlogging if she enjoys making videos",
        "Subscription for organic product delivery",
        "Exclusive coffee-making utensil set",
        "Horse farm excursion with horseback riding",
        "Jewelry with her zodiac sign",
        "Gift certificate to a luxurious weekend hotel",
        "Luxurious home decor items",
        "Tickets to a music festival",
        "Retro typewriter if she enjoys writing",
        "Home brewing kit",
        "Tickets for a boat or yacht trip",
        "Books or book series from her favorite authors",
        "Wine education or wine tasting course",
        "Culinary masterclass for exotic dishes",
        "Picturesque trip to a scenic island",
        "Stylish and functional fitness apparel",
        "Tickets to a seminar or lecture in her field of interest",
        "Personal training session with a professional trainer",
        "Smart home device set",
        "Comfortable and stylish home office chair",
        "Gift certificate to a local library or bookstore",
        "Subscription for online drawing or crafting classes",
        "Exotic spice and sauce set from around the world",
        "Stylish yoga mat",
        "Certificate for dance lessons",
        "Luxurious lingerie set",
        "Tickets to a charity dinner or event",
        "Barbecue or picnic set for outdoor activities",
        "Subscription to a podcast streaming service",
        "Foot or hand care kit",
        "Gift certificate for a hot air balloon adventure",
        "Experience of canoeing or kayaking",
        "Subscription to online drawing or painting lessons",
        "Tickets for a winery tour",
        "Professional culinary tools for favorite dishes",
        "Exotic massage or spa treatments",
        "Subscription to an online foreign language course",
        "Gift set of luxury tea",
        "Tickets to a philharmonic concert or opera",
        "Jewelry making masterclass",
        "Gift certificate for motorcycle driving lessons",
        "Book by a favorite author in a leather binding",
        "Lessons on scriptwriting or creative writing",
        "Gift certificate for skincare treatments at a salon",
        "Tickets to a ballet or theater performance",
        "Professional makeup set",
        "Subscription for monthly delivery of fresh flowers",
        "Photography lessons or photo editing course",
        "Adventure park excursion",
        "Certificate for an interior decoration masterclass",
        "Exquisite wine or champagne set",
        "Hot air balloon ride",
        "Ceramics or pottery lessons",
        "Professional diving or snorkeling equipment",
        "Music instrument lessons",
        "Beautiful dress or other wardrobe item",
        "Set of books for reading while traveling",
        "Gift certificate for yoga or pilates classes",
        "Basket weaving masterclass",
        "Tickets to a symphony orchestra concert",
        "Stylish hair accessories",
        "Voucher for dance lessons",
        "Set for fans of a favorite movie or TV series",
        "Guitar or other musical instrument lessons",
        "Subscription to a music streaming service",
        "Stylish cases for her gadgets",
        "Calligraphy lessons",
        "Retro games or board games",
        "Sushi-making kit",
        "Stylish coffee brewing utensils",
        "Cheese farm tour",
        "Exclusive concert tickets",
        "Gift certificate for golf lessons",
        "Kit for homemade cocktail preparation",
        "Tickets to a popular sports event",
        "Watercolor lessons or other form of art",
        "Statuette or art from her favorite era",
        "Set of exquisite cheeses and wines",
        "Pizza-making masterclass",
        "Stylish sneakers for workouts",
        "Yacht excursion",
        "Drumming lessons",
        "Subscription to a gourmet magazine",
        "Brushes and paints set for artists",
        "Guided tour of a gallery or museum",
        "Comfortable and stylish urban backpacks",
        "Subscription to a fashion or culture magazine",
        "Tour of a pastry factory",
        "Tickets to a zoo or water park",
        "Fencing lessons or other unusual sport",
        "Certificate for cosmetic procedures or massage",
        "Gift certificate for rock climbing",
        "Tour of a local apiary",
        "Tickets to a concert by a famous performer",
        "Retro letter-writing set with wax seals",
        "Lessons in learning a new foreign language",
        "Subscription to a meditation learning service",
        "Delicious delicacies from local farms",
        "Acting or improvisation lessons",
        "Luxurious bedding set",
        "Tickets to an art festival or exhibition",
        "Subscription to virtual yoga classes",
        "High-quality camera for vlogging",
        "Subscription to fitness or healthy eating courses",
        "Experience of driving a racing car on a track",
        "Stationary exercise bike for home workouts",
        "Luxurious home decor items",
        "Excursion to a historical site or museum",
        "Subscription to an audiobook service",
        "Singing or vocal lessons",
        "Certificate for professional makeup lessons",
        "Culinary masterclass for exotic desserts",
        "Tickets to a sports match of her favorite team",
        "Individual piano lessons",
        "Exclusive bath essence",
        "Stylish eco-friendly cookware set",
        "Subscription to online sommelier lessons",
        "Kit for creating homemade aromatic candles",
        "Tickets to hot springs or thermal baths",
        "Gift certificate for surfing lessons",
        "Stylish laptop bag",
        "Premium chocolate gift set",
        "Subscription to a service for creating personalized playlists",
        "Lessons on animation or design",
        "Certificate for neck and collar zone massage",
        "Clay sculpting masterclass",
        "Sailboat excursion",
        "Decorative painting lessons",
        "Subscription to a psychology or self-development magazine",
        "Subscription to gardening courses",
        "Luxurious pendant with her initials",
        "World map for marking visited places",
        "Gift certificate for graphic design lessons",
        "Tickets to the filming of her favorite TV show",
        "Luxurious kimono for home",
        "High-quality photography equipment set for beginners",
        "Tour of a chocolate factory",
        "Clothing modeling lessons",
        "Gift certificate for bead weaving classes",
        "Subscription to a distance learning service",
        "Real-life quest experience",
        "Kit of high-quality materials for home brewing",
        "Lessons on creating music on a computer",
        "Certificate for a course on philosophy or history",
        "Knitting masterclass",
        "Tickets to a fashion show",
        "Subscription to healthy cooking classes",
        "Gift set of her favorite cosmetics",
        "Aquagrim lessons",
        "Kit for creative projects using recycled materials",
        "Luxurious bath or spa set",
        "Subscription to online photography or video editing courses",
        "Tickets to a winery tour with tasting",
        "Lessons on creating polymer clay jewelry",
        "Gift certificate for pole dance lessons",
        "Luxurious personalized cosmetic bag",
        "Excursion to a horse farm with horseback riding",
        "Barista kit with quality coffee and accessories",
        "Subscription to a service for online meditations and relaxation",
        "Ceramic pottery masterclass",
        "Tickets to a tour of an ancient castle or palace",
        "Quilling or paper art lessons",
        "Gift certificate for a professional photoshoot",
        "Luxurious cashmere gloves or scarf",
        "Kit for creating homemade natural cosmetics",
        "Certificate for beach or nature park yoga lessons",
        "Subscription to a service for online history and culture studies",
        "Acrobatics or gymnastics lessons",
        "Luxurious vintage-style doll",
        "Tour of a chocolate candy factory",
        "Gift certificate for a romantic yacht trip",
        "Kit for creating your own perfumes",
        "Tickets to a musical or theatrical performance",
        "Lessons in studying a foreign language in its country of origin",
        "Gift certificate for a bicycle tour",
        "Exclusive collection of books from her favorite author",
        "Lessons in creating plaster sculptures",
        "Subscription to online courses on nature photography",
        "Luxurious set for relaxation and aromatherapy",
        "Masterclass in making your own candles",
        "Tickets to the opera theater concert",
        "Gift certificate for archery lessons",
        "Luxurious set of Egyptian cotton bedding",
        "Rock climbing lessons at an indoor climbing gym",
        "Subscription to a service for online shopping of fashionable items",
        "Sushi-making kit",
        "Tour of a crystal manufacturing factory",
        "Badminton set or another active game",
        "Gift certificate for Thai boxing lessons",
        "Lessons in macrame or weaving",
        "Luxurious collection of tea leaves from around the world",
        "Subscription to a service for online courses on psychology and self-development",
        "Tickets to a music festival or open-air event",
        "Graffiti or street art lessons",
        "Gift certificate for horse riding lessons",
        "Tour of a coffee plantation or coffee roasting factory",
        "Quality headphones or a portable speaker system",
        "Masterclass in creating unique jewelry",
        "Subscription to a service for online workouts and fitness",
        "Luxurious set for spa treatments and body care",
        "Tickets to a film festival or movie premiere",
        "Gift certificate for parkour or acrobatics lessons",
        "Unique vintage home decor item",
        "Tour of the filming location of her favorite movie or TV series",
        "Home brewing craft beer kit",
        "Lessons in creating polymer clay dolls",
        "Gift certificate for facial massage or spa treatments",
        "Luxurious collection of cosmetics or perfumes",
        "Photo booth or photo show kit",
        "Lessons in creating leather goods",
        "Gift certificate for a stylist consultation or personal shopper",
        "Subscription to a service for online courses on cooking and baking",
        "Tickets to a play or comedy show",
        "Lessons in creating your own blog or video blog",
        "Gift certificate for aromatherapy lessons",
        "Tour of an organic farm with the opportunity to participate in the work",
        "Quality briefcase or work bag",
        "Masterclass in creating a photo album or scrapbooking",
        "Subscription to a service for online shopping of organic products",
        "Luxurious set of Egyptian cotton bedding",
        "Tickets to a circus performance or show",
        "Gift certificate for salsa or other dance lessons",
        "Lessons in creating jewelry with precious gemstones",
        "Tour of a perfume manufacturing factory",
        "Yoga or Pilates set",
        "Gift certificate for visiting thermal springs or a spa salon",
        "Luxurious set of tea cups and mugs",
        "Lessons in creating ceramic tableware",
        "Subscription to a service for online shopping of stylish clothes and accessories",
        "Masterclass in creating fabric dolls",
        "Gift certificate for a massage session at a spa center"
    )
}