package com.sosinvitalii.database.quotes

/// Цитаты на английском языке
object EnglishQuotes {
    fun fetch(): List<String> {
        return quotes
    }

    private val quotes = listOf(
        "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
        "The only way to do great work is to love what you do.",
        "Don't wait for opportunity. Create it.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "The greatest glory in living lies not in never falling, but in rising every time we fall.",
        "The best way to predict the future is to create it.",
        "In the middle of difficulty lies opportunity.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "Your time is limited, don't waste it living someone else's life.",
        "The secret of getting ahead is getting started.",
        "Success is not the key to happiness. Happiness is the key to success.",
        "The harder I work, the luckier I get.",
        "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
        "The only person you should try to be better than is the person you were yesterday.",
        "The biggest risk is not taking any risk.",
        "Strive not to be a success, but rather to be of value.",
        "The best revenge is massive success.",
        "The only way to have a friend is to be one.",
        "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
        "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
        "The way to get started is to quit talking and begin doing.",
        "The two most important days in your life are the day you are born and the day you find out why.",
        "Believe you can and you're halfway there.",
        "Success usually comes to those who are too busy to be looking for it.",
        "Don't be afraid to give up the good to go for the great.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "I find that the harder I work, the more luck I seem to have.",
        "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
        "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
        "I attribute my success to this: I never gave or took any excuse.",
        "Success usually comesto those who are too busy to be looking for it.",
        "The only way to do great work is to love what you do.",
        "Don't wait for opportunity. Create it.",
        "In the middle of difficulty lies opportunity.",
        "Your time is limited, don't waste it living someone else's life.",
        "The secret of getting ahead is getting started.",
        "Strive not to be a success, but rather to be of value.",
        "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
        "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
            "The way to get started is to quit talking and begin doing.",
            "The two most important days in your life are the day you are born and the day you find out why.",
            "Believe you can and you're halfway there.",
            "I attribute my success to this: I never gave or took any excuse.",
            "Don't be afraid to give up the good to go for the great.",
            "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
            "Success is not the key to happiness. Happiness is the key to success.",
            "The only limit to our realization of tomorrow will be our doubts of today.",
            "The future belongs to those who believe in the beauty of their dreams.",
            "The best revenge is massive success.",
            "The only person you should try to be better than is the person you were yesterday.",
                "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
                "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
                "The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.",
                "Success is not just about making money. It's about making a difference.",
                "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
                "Success is not measured by how high you climb, but by how many people you bring with you.",
                "The only time you should ever look back is to see how far you've come.",
                "Dream big, work hard, stay focused, and surround yourself with good people.",
                "Great things never come from comfort zones.",
                "The only way to predict the future is to create it.",
                "Success is not in what you have, but who you are.",
                "Every accomplishment starts with the decision to try.",
                    "The difference between a successful person and others is not lack of strength, not a lack of knowledge, but rather a lack in will.",
                    "Happiness is not something ready-made. It comes from your own actions.",
                    "The only way to do great things is to love what you do.",
                    "Success is not the destination, it's the journey.",
                    "The best way to predict your future is to create it.",
                    "If you want to achieve greatness, stop asking for permission.",
                    "The harder you work for something, the greater you'll feel when you achieve it.",
                    "Success is not about the destination, it's about the journey.",
                    "You miss 100% of the shots you don't take.",
                    "The only way to discover the limits of the possible is to go beyond them into the impossible.",
                    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
                    "The greatest mistake you can make in life is to continually fear you will make one.",
                    "Don't watch the clock; do what it does. Keep going.",
                    "Success is not in what you have, but who you are.",
                    "The mind is everything. What you think, you become.",
                    "The greatest pleasure in life is doing what people say you cannot do.",
                    "It does not matter how slowly you go as long as you do not stop.",
                    "Be yourself; everyone else is already taken.",
                    "Success is not about the destination, but the journey.",
                    "Dream big and dare to fail.",
                    "Happiness is not something ready-made. It comes from your own actions.",
                    "Life is 10% what happens to us and 90% how we react to it.",
                    "Your time is limited, so don't waste it living someone else's life.",
                    "If you want to achieve greatness, stop asking for permission.",
                    "The harder you work for something, the greater you'll feel when you achieve it.",
                    "Life is short, and it's up to you to make it sweet.",
                    "The only limit to your impact is your imagination and commitment.",
                    "Great things never came from comfort zones.",
                    "Success is not just about making money. It's about making a difference.",
                    "The biggest adventure you can take is to live the life of your dreams.",
                    "Don't be afraid to stand for what you believe in, even if it means standing alone.",
                    "Every moment is a fresh beginning.",
                    "Your attitude determines your direction.",
                    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward.",
                    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
                    "The only thing standing between you and your goal is the story you keep telling yourself.",
                    "Success is not the absence of failure; it's the persistence through failure.",
                    "Surround yourself with those who believe in your dreams, encourage your ideas, support your ambitions, and bring out the best in you.",
                    "The harder you work, the luckier you get.",
                    "Challenges are opportunities in disguise.",
                    "The only time you should ever look back is to see how far you've come.",
                    "Your life does not get better by chance, it gets better by change.",
                    "The greatest wealth is health.",
                    "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
                    "The greatest risk is not taking any risks.",
                    "Success is not about the destination, it's about the journey.",
                    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
                    "The best time to plant a tree was 20 years ago. The second best time is now.",
                    "The only person you are destined to become is the person you decide to be.",
                    "Life is either a daring adventure or nothing at all.",
                    "The secret to getting ahead is getting started.",
                    "Life is too important to be taken seriously.",
                    "Be the change that you wish to see in the world.",
                    "The only way to predict the future is to create it.",
                    "The best preparation for tomorrow is doing your best today.",
                    "Life is too short to wait for the perfect moment. Take the moment and make it perfect.",
                    "Dream big, work hard, stay focused, and surround yourself with good people.",
                    "Every great achievement was once considered impossible.",
                    "The only limit to your success is your own imagination.",
                    "Be the change you wish to see in the world.",
                    "Don't let yesterday take up too much of today.",
                    "Surround yourself with those who believe in your dreams and encourage your growth.",
                    "Strive for progress, not perfection.",
                    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
                    "Happiness is not something you postpone for the future; it is something you design for the present.",
                    "Don't wait for opportunity, create it.",
                    "The only way to find true happiness is to risk being completely cut open.",
                    "Your success is determined by how hard you work when no one is watching.",
                    "Life begins at the end of your comfort zone.",
                    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
                    "The best way to predict your future is to create it.",
                    "The key to success is to focus on goals, not obstacles.",
                    "A successful person is one who can lay a firm foundation with the bricks others have thrown at them.",
                    "The only thing worse than starting something and failing is not starting something.",
                    "Don't be afraid to fail. Be afraid not to try.",
                    "Life is too short to waste on negativity.",
                    "The best way to get started is to quit talking and begin doing.",
                    "Success is not a result48. The only way to do great work is to love what you do.",
                    "Embrace the uncertainty and enjoy the beauty of becoming.",
                    "The road to success is always under construction.",
                    "Don't let the fear of failure hold you back from achieving greatness.",
                    "Success is not just about reaching the top; it's about helping others climb with you.",
                    "The only thing standing between you and your goals is the story you keep telling yourself.",
                    "Every day is a new opportunity to grow, learn, and become a better version of yourself.",
                    "Your dreams don't work unless you do.",
                    "The only way to discover your limits is by pushing yourself past them.",
                    "Surround yourself with positive people who inspire and uplift you.",
                    "Don't be afraid to take calculated risks and step outside of your comfort zone.",
                    "Success is not measured by how much you have, but by how much you have impacted others.",
                    "Life is too short to waste on negativity and regrets.",
                    "Don't wait for the perfect moment; take the moment and make it perfect.",
                    "Believe in yourself, even when no one else does.",
                    "Hardships often lead to the greatest moments of growth and resilience.",
                    "Failure is not the end; it's just a stepping stone on the path to success.",
                    "Success is not about luck; it's about perseverance and hard work.",
                    "Don't compare your journey to others. Your path is unique and special.",
                    "The greatest achievements come from those who never give up.",
                    "Embrace challenges as opportunities for growth and self-improvement.",
                    "Your attitude determines your altitude in life.",
                    "Success is not an overnight phenomenon; it's the result of consistent effort and dedication.",
                    "The only way to predict your future is to create it.",
                    "Don't let the opinions of others define who you are or what you can achieve.",
                    "Every setback is a setup for a comeback.",
                    "Focus on progress, not perfection.",
                    "Don't be afraid to ask for help and support when needed.",
                    "Your purpose in life is found in service to others.",
                    "The only limits that exist are the ones you create in your mind.",
                    "Take action today, for tomorrow is not promised.",
                    "Success is not about the applause; it's about knowing you gave it your all.",
                    "The biggest risk is not taking any risks at all.",
                    "Believe in the power of your dreams and the potential within you.",
                    "Don't wait for inspiration; create it through action.",
                    "Be grateful for what you have while working towards what you want.",
                    "Success is not about the destination; it's about the journey and the person you become along the way.",
                    "The greatest achievements often come from the hardest challenges.",
                    "Don't be discouraged by temporary setbacks. Keep your eyes on the long-term vision.",
                    "Your words and thoughts have the power to shape your reality.",
                    "Surround yourself with people who believe in your potential and inspire you to be your best self.",
                    "Success is not about the accolades; it's about the impact you make in the lives of others.",
                    "Don't be afraid to start small; every big success begins with small steps.",
                    "The greatest weapon against stress is our ability to choose one thought over another.",
                    "Your beliefs become your thoughts, your thoughts become your words, your words become your actions, your actions become your habits, your habits become your values, and your values become your destiny.",
                    "Success is not about being the best; it's about being better than you were yesterday.",
                    "Don't be a prisoner of your past; be a pioneer of your future.",
                    "The journey of a thousand miles begins with a single step.",
                    "Don't let failures define you; let them refine you.",
                    "Stay focused, stay positive, and never give up on your dreams.",
                    "The only way to do great work is to love what you do and give it your all.",
                    "Your success is determined by your daily choices and actions.",
                    "Don't be afraid to fail; be afraid not to try.",
                    "Success is not a destination, but a journey of constant growth and improvement.",
                    "The only way to make your dreams come true is to wake up and take action.",
                    "Surround yourself with positive people who uplift and inspire you.",
                    "Embrace failure as a stepping stone to success and a valuable learning experience.",
                    "Success is not measured by the amount of money you have, but by the impact you make in the lives of others.",
                    "It's not about how many times you fall, but how many times you get back up.",
                    "The greatest risk in life is not taking any risks at all.",
                    "Don't wait for opportunities; create them.",
                    "Success is not about luck; it's about persistence and hard work.",
                    "The only limit to your success is the limit you set in your mind.",
                    "Don't let the fear of what could go wrong prevent you from taking action.",
                    "Success is not about the destination; it's about the person you become on the journey.",
                    "Don't be afraid to step outside of your comfort zone and embrace new challenges.",
                    "Success is not an overnight achievement; it's the result of consistent effort and dedication.",
                    "The greatest achievements often come from overcoming the greatest obstacles.",
                    "Your purpose in life is found in pursuing what you are passionate about.",
                    "Don't compare your journey to others; focus on your own progress and growth.",
                    "Success is not about the applause; it's about the fulfillment and joy that comes from doing what you love.",
                    "Believe in your abilities and have faith in your potential.",
                    "Success is not about the resources you have; it's about how resourceful you are.",
                    "Embrace failures as valuable lessons that bring you closer to success.",
                    "Surround yourself with positive influences and seek continuous learning and growth.",
                    "Don't let setbacks define you; let them fuel your determination to succeed.",
                    "Success is not about luck; it's about preparation meeting opportunity.",
                    "Your dreams and goals are worth pursuing, no matter how big or small they may seem.",
                    "The path to success may not always be easy, but it will be worth it.",
                    "Don't let negativity and doubt hold you back from achieving greatness.",
                    "Success is not about conforming to the expectations of others; it's about staying true to yourself.",
                    "Don't be afraid to ask for help and support when needed; collaboration leads to greater success.",
                    "Your actions today shape your future; make each moment count.",
                    "Success is not about reaching a destination, but about enjoying the journey and the person you become along the way.",
                    "Don't let fear of failure paralyze you; take calculated risks and learn from the outcomes.",
                    "Stay focused, stay determined, and stay committed to your goals.",
                    "The power to change your life lies within you; take ownership of your choices and actions.",
                    "Success is not about the applause; it's about the satisfaction of knowing you gave it your all.",
                    "Don't let temporary setbacks discourage you; keep your eyes on the long-term vision.",
                    "Your beliefs shape your reality; cultivate a positive mindset and believe in your potential.",
                    "Don't underestimate the power of consistent effort and perseverance.",
                    "Success is not about luck; it's about taking deliberate action and making intentional choices.",
                    "Don't let the opinions of others define your worth; trust in your own abilities and potential.",
                    "Your journey may be unique, but you are never alone on the path to success.",
                    "Remember, success is not just about achieving your goals; it's about enjoying the process and finding fulfillment along the way.",
                    "Don't be afraid to start over. It's a chance to build something better.",
                    "Believe in yourself, and the rest will fall into place.",
                    "Challenges are what make life interesting; overcoming them is what makes life meaningful.",
                    "Success is not just about making money; it's about making a positive impact on the world.",
                    "Your success is determined by your daily habits.",
                    "The only limit to your success is the limit you set for yourself.",
                    "Success is not about being the best; it's about becoming your best self.",
                    "Embrace failure as a stepping stone to success and an opportunity for growth.",
                    "Success is not a one-time event; it's a lifelong journey.",
                    "Don't let fear hold you back; take risks and pursue your dreams.",
                    "The difference between a successful person and others is not lack of strength or knowledge, but rather lack of will.",
                    "Success is not about the destination; it's about the progress and growth you make along the way.",
                    "Success is not about luck; it's about preparation, hard work, and perseverance.",
                    "Don't compare yourself to others; focus on your own journey and progress.",
                    "Success is not about the resources you have; it's about how resourceful you can be.",
                    "Don't be afraid to ask for help and support; collaboration leads to greater success.",
                    "The only way to find true happiness is to do what you love and love what you do.",
                    "Success is not about perfection; it's about progress and continuous improvement.",
                    "Your dreams are worth pursuing, no matter how big or small they may seem.",
                    "Success is not about luck; it's about consistent effort and a positive mindset.",
                    "Embrace challenges as opportunities for growth and self-discovery.",
                    "The key to success is to stay focused, stay committed, and never give up.",
                    "Don't be discouraged by temporary setbacks; keep your eyes on the long-term vision.",
                    "Your purpose in life is found in pursuing what brings you joy and fulfillment.",
                    "Success is not about instant gratification; it's about long-term dedication and persistence.",
                    "Your actions today shapeyour future; make each moment count.",
                    "The greatest accomplishments are often achieved by those who never give up.",
                    "Don't be afraid to step outside of your comfort zone; that's where growth happens.",
                    "Trust the process, even when you can't see the results yet.",
                    "The only way to truly fail is to give up.",
                    "Remember, success is not a one-time event; it's a series of small steps and consistent effort.",
                    "Your dreams are valid. Don't let anyone discourage you from pursuing them.",
                    "The road to success is always under construction. Embrace the journey and keep growing.",
                    "Don't wait for opportunities; create them yourself.",
                    "The only limits in life are the ones you set for yourself.",
                    "Success is not about the applause; it's about the satisfaction of knowing you did your best.",
                    "Surround yourself with those who support and uplift you. You become the average of the people you spend the most time with.",
                    "Believe in your abilities, even when others doubt you.",
                    "Your mindset determines your outcome. Choose to think positively and believe in your success.",
                    "Success is not about luck; it's about perseverance and determination.",
                    "Don't let fear of failure hold you back. Take risks and learn from every experience.",
                    "The greatest accomplishments often come from taking the first step.",
                    "Success is not about how much you have, but how much you give.",
                    "The greatest investment you can make is in yourself and your personal growth.",
                    "Failure is not the end; it's an opportunity to learn, grow, and come back stronger.",
                    "Don't compare yourself to others. Focus on your own journey and progress.",
                    "Success is not about reaching a destination; it's about enjoying the process and the person you become along the way.",
                    "Your time and energy are valuable. Spend them on things that align with your goals and values.",
                    "Believe in your vision, even if others can't see it yet.",
                    "Success is not an overnight achievement; it's a result of consistent effort over time.",
                    "Don't be afraid to ask for help. Collaboration and support can accelerate your success.",
                    "Focus on solutions, not problems. Shift your mindset to find opportunities in every challenge.",
                    "The only way to grow is to step outside of your comfort zone.",
                    "Success is not about the destination; it's about the impact you have on others.",
                    "Don't wait for perfect conditions. Start where you are, use what you have, and do what you can.",
                    "Your attitude determines your success. Choose positivity, resilience, and determination.",
                    "Embrace failure as a valuable teacher. Learn from it and keep moving forward.",
                    "Your actions speak louder than words. Take consistent action towards your goals.",
                    "Success is not guaranteed, but neither is failure. Choose to focus on possibilities and opportunities.",
                    "Don't be afraid to stand out and be different. Your uniqueness is your strength.",
                    "Success is not about how many times you fall, but how many times you get back up.",
                    "Don't let setbacks define you. Use them as stepping stones to success.",
                    "Your potential is limitless. Don't be afraid to dream big and aim high.",
                    "Success is not about external validation; it's about finding fulfillment and happiness from within.",
                    "Don't let the fear of what others think hold you back. Follow your own path and trust your intuition.",
                    "The greatest achievements often come from taking calculated risks.",
                    "Your success is not determined by your circumstances; it's determined by your mindset and actions.",
                    "Don't wait for permission topursue your dreams. Give yourself the permission to go after what you want.",
                    "Success is not about finding yourself; it's about creating yourself.",
                    "The power to change your life lies within you. Take responsibility for your choices and actions.",
                    "Don't let the past define your future. Every day is a chance to start anew.",
                    "Success is not about reaching the top; it's about lifting others up as you climb.",
                    "Trust the process and have faith in your journey. The best is yet to come.",
                    "Your purpose in life is to find and use your gifts to make a positive impact on the world.",
                    "Success is not a destination; it's a lifelong pursuit of growth and fulfillment.",
                    "Don't settle for mediocrity. Strive for greatness and push beyond your limits.",
                    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
                    "Your attitude determines your altitude.",
                    "Success is not about luck; it's about consistency and hard work.",
                    "Embrace challenges as opportunities for growth.",
                    "Believe in yourself, and others will too.",
                    "Success is not about the destination; it's about the journey.",
                    "Don't let small minds convince you that your dreams are too big.",
                    "The only limit to your success is your imagination.",
                    "Success is not for the chosen few; it's for those who choose to take action.",
                    "Don't wait for the perfect moment; create it.",
                    "Surround yourself with people who believe in your dreams and inspire you to achieve them.",
                    "The greatest achievements come from pushing beyond your comfort zone.",
                    "Success is not about how many times you fall; it's about how many times you get back up.",
                    "Don't let fear of failure hold you back from reaching your full potential.",
                    "The path to success is paved with hard work, dedication, and a belief in yourself.",
                    "Success is not about what you have; it's about who you become.",
                    "Don't compare your progress to others. Focus on your own journey.",
                    "Success is not a one-time event; it's a habit.",
                    "Don't be afraid to ask for help. Collaboration leads to greater success.",
                    "Your mindset is the key to unlocking your full potential.",
                    "Success is not about luck; it's about perseverance and resilience.",
                    "Don't be discouraged by setbacks. They are stepping stones to success.",
                    "The greatest reward in life comes from overcoming obstacles and achieving what others thought was impossible.",
                    "Success is not about instant gratification; it's about long-term commitment and consistency.",
                    "Your dreams are worth fighting for. Never give up on what sets your soul on fire.",
                    "Don't be afraid to be different. Embrace your uniqueness and let it shine.",
                    "The only way to guarantee failure is to never try.",
                    "Don't let past failures define your future success.",
                    "Success is not about how much you have; it's about how much you give.",
                    "Your success is a reflection of your daily habits.",
                    "Don't settle for mediocrity. Strive for excellence in everything you do.",
                    "Success is not about getting to the top; it's about helping others climb with you.",
                    "Don't let negative people rent space in your head. Surround yourself with positivity.",
                    "Your success is not determined by your circumstances; it's determined by your mindset.",
                    "Don't let the fear of what could go wrong keep you from what could go right.",
                    "Success is not about the size of your bank account; it's about the impact you make in the world.",
                    "Embrace failure as a necessary stepping stone on the path to success.",
                    "Your journey may be challenging, but the destination will be worth it.",
                    "Don't let self-doubt hold you back. Believe in your abilities and take action.",
                    "The only way to guarantee failure is to never start. Take that first step towards your goals.",
                    "Don't be afraid to go out on a limb. That's where the fruit is.",
                    "Your success is determined by how much you are willing to learn, adapt, and grow.",
                    "Don't let fear of failure hold you back from taking risks and reaching for greatness.",
                    "Success is not a destination; it's a lifelong journey of continuous improvement.",
                    "Believe in yourself and your abilities. You are capable of achieving amazing things.",
                    "Don't let the opinions of others define your worth or dictate your path.",
                    "Success is not about luck; it's about perseverance, dedication, and hard work.",
                    "The biggest risk is not taking any risk at all. Step outside your comfort zone and embrace new challenges.",
                    "Don't wait for the perfect moment. Start now and make each moment count.",
                    "The road to success is rarely a straight line. Embrace the detours and learn from the obstacles.",
                    "Success is not about achieving perfection; it's about progress and growth.",
                    "Surround yourself with positive and supportive people who believe in your dreams.",
                    "Don't underestimate the power of small actions and consistent effort. They add up to significant results.",
                    "Your mindset is your greatest asset. Cultivate a positive and resilient mindset.",
                    "Success is not about the destination; it's about the person you become along the way.",
                    "Don't let failures define you. Learn from them, adjust your course, and keep moving forward.",
                    "The only limit to your success is the limit you set in your own mind.",
                    "Success is not about material possessions; it's about fulfillment and making a meaningful impact.",
                    "Embrace change and adaptability. They are essential for growth and success.",
                    "Don't compare yourself to others. Focus on your own journey and celebrate your unique achievements.",
                    "Success is not an overnight achievement. It requires patience, persistence, and perseverance.",
                    "Believe in the power of your dreams and have the courage to pursue them.",
                    "Don't let setbacks discourage you. Use them as stepping stones to propel you forward.",
                    "Success is not about being the best; it's about being your best self.",
                    "Don't wait for external validation. Trust your instincts and have confidence in your abilities.",
                    "The greatest achievements often come from taking risks and stepping into the unknown.",
                    "Success is not about luck; it's about seizing opportunities and making the most of them.",
                    "Don't be afraid to ask for help and support. Collaboration and mentorship can accelerate your success.",
                    "Your passion and enthusiasm are contagious. Share them with the world and inspire others.",
                    "Success is not about having all the answers; it's about asking the right questions and seeking knowledge.",
                    "Don't let past mistakes define your future. Learn from them and use them as stepping stones to success.",
                    "The greatest rewards in life often come from the challenges we overcome and the lessons we learn.",
                    "Success is not about chasing external validation; it's about finding internal fulfillment and happiness.",
                    "Don't let fear of failure hold you back from pursuing your dreams. Take calculated risks and trust in your abilities.",
                    "Your success is not limited by your circumstances; it's determined by your mindset and actions.",
                    "Embrace uncertainty and embrace the opportunities that come with it. Growth and success often reside outside your comfort zone.",
                    "Your mindset is the foundation of your success. Cultivate a positive and empowering mindset.",
                    "Success is not about luck; it's about resilience, determination, and hard work.",
                    "Don't underestimate the power of consistency. Small daily actions can lead to significant long-term results.",
                    "Your success is not limited by your past. Each day is a fresh opportunity to create the life you desire.",
                    "Embrace failures as valuable lessons and stepping stones on the path to success.",
                    "Don't wait foropportunities to come to you. Create your own opportunities and seize them.",
                    "Success is not about achieving perfection; it's about embracing imperfections and learning from them.",
                    "Your success is not defined by others' opinions; it's defined by your own standards and values.",
                    "Don't let self-doubt overshadow your potential. Believe in yourself and your capabilities.",
                    "Success is not a destination; it's a continuous journey of growth and self-improvement.",
                    "Don't be afraid to stand out and be different. Embrace your uniqueness and let it shine.",
                    "Success is not measured by the heights you reach, but by the obstacles you overcome.",
                    "Don't wait for opportunities to come knocking; create them with your actions and determination.",
                    "Success is not a sprint; it's a marathon that requires consistent effort and perseverance.",
                    "Don't be afraid to take calculated risks. Fortune favors the bold.",
                    "Your mindset is the foundation for your success. Believe you can, and you're halfway there.",
                    "Success is not about luck; it's about being prepared when opportunity arises.",
                    "Don't let the fear of failure stop you from pursuing your dreams. Failure is often a stepping stone to success.",
                    "The greatest achievements often come from pushing beyond your limits and embracing challenges.",
                    "Success is not about the destination; it's about the progress and growth you experience along the way.",
                    "Don't be discouraged by temporary setbacks. Use them as fuel to propel you forward.",
                    "Your success is not defined by the opinions of others. Stay true to yourself and your vision.",
                    "Success is not about reaching a specific goal; it's about continuously setting new goals and striving for improvement.",
                    "Don't wait for perfect conditions to start. Start where you are, use what you have, and do what you can.",
                    "The path to success may be filled with obstacles, but with perseverance and determination, you can overcome them all.",
                    "Success is not about accumulating wealth; it's about making a positive impact on the world.",
                    "Don't compare your journey to others. Everyone has their own unique path to success.",
                    "Your success is not limited by your past. Your future is determined by the choices you make today.",
                    "Success is not about being the best; it's about being your best and giving your best effort.",
                    "Don't let self-doubt hold you back. Believe in yourself and your abilities.",
                    "The key to success is not avoiding failure, but learning from it and growing stronger because of it.",
                    "Success is not about finding shortcuts; it's about putting in the time and effort to achieve your goals.",
                    "Don't let setbacks define you. Rise above them and use them as opportunities for growth.",
                    "Success is not about luck; it's about perseverance, resilience, and a positive attitude.",
                    "Don't be afraid to ask for help. Surround yourself with a supportive network that believes in your potential.",
                    "The road to success may be challenging, but the rewards are worth the journey.",
                    "Success is not about instant gratification; it's about the satisfaction of knowing you gave it your all.",
                    "Don't let fear of failure paralyze you. Embrace failure as a stepping stone on the path to success.",
                    "Your success is not defined by the opinions of others. Trust your instincts and follow your own path.",
                    "Success is not about conforming to societal expectations; it's about staying true to your authentic self.",
                    "Don't let setbacks discourage you. Use them as opportunities to learn and grow.",
                    "The only limits to your success are the ones you place on yourself. Dream big and aim high.",
                    "Success is not about finding a shortcut; it's about putting in the hard work and effort required to achieve your goals.",
                    "Don't let negative thoughts and self-doubt hold you back. Replace them with positive affirmations and belief in your abilities.",
                    "Success is not about the destination; it's about the journey and the lessons learned along the way.",
                    "Don't be afraid to take risks and embrace uncertainty. That's where growth and opportunities lie.",
                    "Your success is not defined by your failures, but by how you rise after every fall.",
                    "Don't wait for the perfect moment; seize the moment and make it perfect.",
                    "The biggest obstacle to success is often the fear of failure. Face it head-on and watch your dreams unfold.",
                    "Your success is not limited by your circumstances; it's amplified by your determination.",
                    "Don't be afraid to challenge the status quo. Break free from the norm and create your own path to success.",
                    "The key to success is not just in the destination; it's in the daily disciplines and habits you cultivate.",
                    "Your success is not determined by the opinions of others. Stay true to yourself and your vision.",
                    "Success is not a one-time event; it's a continuous journey of growth and self-improvement.",
                    "Don't let setbacks define you. Use them as stepping stones to propel you forward.",
                    "The path to success may be uncertain, but your belief in yourself will guide you through.",
                    "Don't let fear of failure hold you back. Embrace failures as valuable lessons on the road to success.",
                    "Your success is not determined by your age, background, or circumstances; it's determined by your mindset and actions.",
                    "Success is not about achieving perfection; it's about progress, growth, and learning from your mistakes.",
                    "Don't wait for inspiration to strike; create your own inspiration through consistent action.",
                    "The true measure of success is not in what you have, but in who you become.",
                    "Your success is not limited by your past; it's defined by the choices you make today and in the future.",
                    "Success is not about being the best; it's about being the best version of yourself.",
                    "Don't let self-doubt sabotage your dreams. Believe in yourself and your abilities.",
                    "The only way to truly fail is to give up. Keep going, even when it gets tough.",
                    "Your success is not determined by external validation; it's about finding fulfillment and happiness from within.",
                    "Success is not about luck; it's about persistence, resilience, and a positive mindset.",
                    "Don't be afraid to dream big and set audacious goals. You have the power to turn them into reality.",
                    "The road to success may be filled with obstacles, but each obstacle is an opportunity for growth and self-discovery.",
                    "Your success is not dependent on the opinions of others; it's about staying true to your own values and beliefs.",
                    "Success is not about reaching the top alone; it's about lifting others up along the way.",
                    "Don't let comparison steal your joy. Focus on your own progress and celebrate your achievements.",
                    "The key to success is not just in the destination; it's in the daily habits and actions you take.",
                    "Your success is not determined by your circumstances; it's determined by your mindset and willingness to adapt.",
                    "Success is not about finding a shortcut; it's about putting in the time, effort, and dedication required to achieve your goals.",
                    "Don't let fear of failure hold you back; let the fear of regret drive youforward.",
                    "Your success is not defined by the challenges you face, but by your resilience in overcoming them.",
                    "Success is not about pleasing everyone; it's about staying true to yourself and your purpose.",
                    "Don't wait for permission to pursue your dreams. Give yourself the permission to chase after what sets your soul on fire.",
                    "The road to success may be long, but the journey is where you find your strength, wisdom, and character.",
                    "Your success is not determined by the opinions of others; it's fueled by your own self-belief and determination.",
                    "Success is not about avoiding failure; it's about learning from it and using it as a stepping stone to greater heights.",
                    "Don't be afraid to stand out and be different. Embrace your uniqueness and let it shine brightly.",
                    "The key to success is not in the absence of challenges, but in your ability to adapt and find solutions.",
                    "Your success is not limited by your past; it's driven by your vision for the future and the actions you take today.",
                    "Success is not about luck; it's about making deliberate choices and taking consistent action.",
                    "Don't let setbacks discourage you; let them fuel your determination to rise stronger and wiser.",
                    "The true essence of success lies not in the accolades you receive, but in the joy and fulfillment you find in your pursuits.",
                    "Your success is not defined by external measures; it's defined by the impact you make on the lives of others.",
                    "Success is not a destination to reach; it's a state of being that comes from aligning your actions with your values and purpose.",
                    "Don't underestimate the power of persistence and perseverance. They are the keys that unlock the doors to success.",
                    "Success is not about the absence of failure; it's about the resilience to keep going despite failures.",
                    "Don't wait for the right opportunity; create it by taking action and making things happen.",
                    "Success is not about being the best; it's about becoming the best version of yourself.",
                    "Don't let self-doubt hold you back; believe in yourself and your abilities.",
                    "The road to success may be challenging, but the view at the top is worth it.",
                    "Your success is not limited by your past; it's shaped by your present choices and future aspirations.",
                    "Success is not about luck; it's about preparation, perseverance, and seizing opportunities.",
                    "Don't be afraid to fail; failure is a stepping stone towards success.",
                    "The key to success is not in achieving perfection, but in embracing progress and continuous improvement.",
                    "Your success is not measured by the size of your accomplishments, but by the impact you make on others.",
                    "Success is not about getting to the top; it's about helping others rise with you.",
                    "Don't wait for validation from others; believe in yourself and your vision.",
                    "The only way to predict your future is to create it with intention and determination.",
                    "Your success is not defined by the opinions of others; it's defined by your own standards and values.",
                    "Success is not a destination; it's a lifelong journey of growth and self-discovery.",
                    "Don't let fear of failure paralyze you; let it fuel your determination to succeed.",
                    "The path to success may be filled with obstacles, but each obstacle is an opportunity to learn and grow.",
                    "Your success is not limited by your circumstances; it's amplified by your resilience and resourcefulness.",
                    "Success is not about what you accomplish; it's about who you become in the process.",
                    "The true measure of success is not in material wealth, but in the fulfillment and joy you find in your pursuits.",
                    "Your success is not determined by external factors; it's determined by your inner drive and determination.",
                    "Success is not about luck; it's about consistent effort and unwavering belief in your abilities.",
                    "Don't wait for the perfect moment; take action now and adjust along the way.",
                    "The greatest achievements often come from stepping outside your comfort zone and embracing challenges.",
                    "Your success is not limited by your past mistakes; it's determined by your ability to learn from them and move forward.",
                    "Don't let setbacks define you; let them refine you and make you stronger.",
                    "The key to success is not in the absence of fear, but in the courage to take action despite fear.",
                    "Your success is not defined by external validation; it's defined by your own sense of fulfillment and accomplishment.",
                    "Success is not about reaching a destination; it's about enjoying the journey and the growth it brings.",
                    "Don't be afraid to dream big and set audacious goals; the only limits are the ones you impose on yourself.",
                    "The road to success may be long, but each step forward brings you closer to your dreams.",
                    "Your success is not determined by your circumstances; it's determined by your mindset and the actions you take.",
    )
}