package com.sosinvitalii.database.jokes

/// Анекдоты на английском языке
object EnglishJokes {
    fun fetch(): List<String> {
        return jokes
    }

    private val jokes = listOf(
        "There are two most common types of beach sports: beach volleyball and tummy tuck.",
        "At 6 a.m., some people turned on cheerful music under the balcony and started doing exercises. I dropped dumbbells for them.",
        "A woman needs a fur coat so that the butterflies in her stomach don't freeze, and a hat so that the cockroaches don't freeze!",
        "And my husband continues to look at me the way he did on the very first day when we first met! - With love? - With horror!",
        "- Please give me the biggest black bag. - Alone? - One. A shovel, please, the longest screeds and lime. - Are you going to hide the corpse? yyyyyyy... - ... two packages...",
        "My wife has not spoken to me for 6 days. Even better, she thinks it's a punishment.",
        "When two truckers come to the cinema, one is watching a movie, and the other is sleeping. They change after an hour.",
        "A five-year-old girl has just asked a question to which there is no answer, and I'm afraid that it may break through the fabric of the space-time continuum: - And why is there no cat food with the taste of a mouse?",
        "The fact that the Earth is by no means flat, you understand especially clearly when you move along our roads. We still need to look for such potholes.",
        "Teacher in biology class: - Children, what is the most important thing in the coniferous forest? - Toilet paper! - answers Vovochka.",
        "The boy Petya was short, so in order to get taller, he hung on the horizontal bar for three hours every day. He didn't get any higher, but after six months he could scratch his knees without bending down.",
        "A woman visits her husband in prison. - Well, how are you? Is there enough money? the prisoner is solicitously interested. Don't worry, honey, we're fine. We've been paid so much for your capture that we don't need anything.",
        " In the X-ray room: - Patient, freeze! The skeleton of a bird is about to fly out!",
        "Darling, do you remember the day you met me?- Of course, the sky immediately darkened, I thought it was rain, but it turned out to be an eclipse.",
        "- Chief, I'm going to be late. There were some problems with the eyes. - Which ones? - I opened them recently.",
        "- Cover one eye. Look here. What letter is that? - El. - And this one? - A. - Read the whole word. - Laboratory. - That's right. Laboratory. And the oculist's office is further down the corridor.",
        "Are you waiting for a prince on a white horse? Know this - it will take a lifetime to clean up the manure. By the way, for the horse, too.",
        "- Let's say I gave you 5 apples. And then I took 3. What do you have left?- Trust issues.",
        "- Professor! To pass the exam for you, I am ready for anything! - FOR EVERYTHING?! - Absolutely! Then go and teach!",
        "Teacher: Who can give examples of what artificial intelligence will easily replace forever? I: * raise my hand* Teacher: Well done, Ivanov. Guys, what other examples will there be besides Ivanov?",
        "- Doctor, what is the condition of the new patient? - A difficult question, but let's hope... enough for treatment.",
        "And God said to Eve, 'Don't eat the fruit from the tree!'. But she disobeyed him... Disobeyed God! And you want your wife to obey her husband.",
        " The ship is sinking. One of the passengers rushes to the captain in a panic:— Tell me, is it far from here to earth?!— No, five hundred meters.— Wonderful! In which direction?— Down...",
        "- They say vegetarians eat only twice a day and live up to 100 years. - Why? - Why what? - Why do they live so long?",
        "I don't want to say that you are a bore, but if you were a city, it would be Dushanbe",
        "- If you have nothing to say, it's better to be silent!, - And if there is!? - Well, you can eat. But in silence!",
        "- Hello, come in. Make yourself at home. - How are you at home? - Yes, of course. - Okay, can you please leave? I don't like guests.",
        "One of the gamblers loses all the time. Partners comfort:- Nothing, no luck in cards, lucky in love. - Yes? I'm forty years old and I'm still not married. - Well, you see!",
        "Vinnie, who is this narrow-eyed guy who just left you? The rabbit borrowed a chervonets until Wednesday, I tied his ears in a knot for memory.",
        "How to explain to clothing manufacturers that when you lose weight and start wearing things a size smaller, your hands don't shorten at the same time?",
        "- I love you more than anyone on this planet! You mean 'on this planet'? So go to your alien friends!",
        "We bought a Barbie house for our granddaughter, brought her home, unpacked, and there on the first floor is already 'Red & White'.",
        "- What a fool I was to marry you! What a fool I am for marrying you. Well, now it's clear why we got together.",
        "There is a doctor on duty in the waiting room of the polyclinic. An old lady enters.— Son, does glazyuk accept? Not an eye doctor, but an optometrist. Already gone!— Son, does zubnyuk take it? Not a dentist, but a dentist. Not anymore.— Son, who are you going to be? According to you, I'm a p3dyuk granny, and in general I'm a gynecologist",
        "A frog swims by:— Man, can I warm up in your boat? All right, get in. The frog climbs in, languidly falls apart in the boat and coquettishly asks:— And what is your name, man? Alexey Nikolaevich. At this moment, another frog floats by: — Oh, can I warm up too? The first frog: — And you wouldn't fuck off! Am I right, Alexey Nikolaevich?",
        "And I'm kind of lying in bed and pretending to be asleep. He takes a chair, sits in front of me and watches. Well, naturally, I can't stand it and ask: – What are you doing? And do you know what he said to me in response?– I want my beloved, to sit in the front row when the concert starts!",
        "Two grandfathers are sitting in the bushes, they are relieving themselves. One to the other, dreamily – Mikhalych, here before the time was the farm already reached the ground. The other, thoughtfully:– Yes, the earth has settled, much.",
        "One man complains to another:— Such people went uncultured. I was leaving the pub yesterday, and some bastard stepped on my ear.",
        "Hello little sister! Where did you get a job?— To the mayor's office!— Well, you give! My mother is in the tax office, my father is in the traffic police — the whole house hates us anyway!",
        "Dad! Tell me a story!— Well, listen! Tomorrow I will come sober, I will buy flowers for my mother, a bicycle for you",
        "The doctor says to the patient: – You can't drink, smoke, play cards ..., -The patient: – Doctor, tell me honestly: has my Sofochka already been here?",
        "Two friends are talking about their family life.– I've been married for fifteen years now,– says one. – At first I pressed her and kissed her so much that she was afraid I would strangle her. – And now? – a friend asks.– Apparently, it's coming to this!",
        "In the store:– A bottle of beer, please. – Do you have a passport?– No.- Poplar fluff? – Heat, July.– I see. Which one do you like?",
        "The whale swims around the female and reproachfully says:– How many countries, hundreds of environmental organizations, outstanding political leaders, millions of people – they are all fighting for our species to survive, and you tell me – my head hurts...",
        "– Grandma! How many kilometers to the neighboring village?– It was five. And then the specialists arrived, measured and measured seven. Now we walk an extra two kilometers.",
        "At the exam, the professor asks the student: - Did you constantly laugh at my lectures in the last row? - I laughed at Newton and Maxwell, who are ignorant against you, Professor. - Enough, the next question.",
        "- Do you believe in the end of the world?- I believe it... Only how did you know that my name is Sveta?",
        "- It seems to me that you don't love me.Don't be silly. I don't like everyone.",
        "Question: What would have happened if Bruce Willis had starred in Titanic instead of DiCaprio? Answer: He would have saved everyone...",
        "- Girl, trim my nails, please! - Young man, we have a barber shop! We only cut our hair. - OK. Then cut my hair, and I'll stick my fingers in there.",
        "According to etiquette, a man should pay for a woman in a restaurant. Fortunately, etiquette does not forbid making a disgruntled face.",
        "Honey, if I throw myself into the river, will you jump to save me? And if I say yes, will you jump?",
        "The exam is underway. The teacher explains: - A question for five. How is the voltage measured? - Question for four. How is the voltage measured? A- voltmeter, B - ammeter, C - ohmmeter. - Question for three. Isn't the voltage measured by a voltmeter?",
        "Women's dictionary or how to understand a woman: Yes = No. No = Yes. Maybe = No. It's my fault = You'll regret it. We need = I want to.",
        "Once the students were sitting with fishing rods on the shore and fishing. The Teacher came up. - Doesn't bite? - he asked. It doesn't bite, the students said with a sigh. And it won't be,the Teacher said. – Fish don't have a beak.",
        "A very good guard dog runs up to the intruder, happily wagging its tail. Otherwise, you can't grab him by the throat.",
        "Wife: Dear, our child spends too much time on the couch! Husband: Well, the sofa gave - the sofa took away",
        "Women's logic —It's better to say it in a good way, otherwise I'll figure it out myself, it will be worse!",
        "The cop stops the student and tells him to show the documents. - Ta-a-a-ak, we are not working, then... - Yes, we are not working. - Ta-a-a-ak, we are devouring state money, then... - Yes, we are devouring. - Ta-a-a-ak, we are students, then... - No, I'm sorry, I'm the only student.",
        "Two 15-16-year-old girls are sitting in a trolleybus, talking. At the bus stop, a guy comes in, stands next to him and says, smiling: - Oh, what pretty girls. The girls are embarrassed: - Yes, they are really cute... Guy: - Okay, kidding, kidding...",
        "When a man stays at home alone, his refrigerator gets up to 300 views in an evening.",
        "Today a boy of three or four years old just made my day happy)) He ran after his parents and shouted: - Stop ze, ek makalek!! I can't run fast! I have molda smoldering!!!!",
        "- Where did you come from on my head? - Hee-hee, I fell out of the bag of beauties. - Tell me straight out, it didn't fall out, but it didn't fit. More than one bag won't fit on you.",
        "At the interview for Israeli citizenship: - In the questionnaire you indicated: mother and father are Russians, and who are Jews in the family? - No one, I'm the first.",
        "- Evaluate the degree of your boredom on a 10-point scale. - 9, 674...",
        "When a doctor writes in an incomprehensible handwriting, he writes all sorts of nasty things to the pharmacist about you! You come to the pharmacy, give the prescription to the pharmacist, he reads, immediately turns away and goes into another room to laugh heartily at you!",
        "After my wife left, I felt very lonely. I got a dog, talked to three women and lost 2 thousand bucks on bets. When my wife returned from the store, she was really angry.",
        "- Rabinovich, the ivory box that you sold me last week is a fake! It's made of plastic! - Well, I don't know, maybe the elephant had an insertion tusk?",
        "In the plastic surgery clinic: - And what kind of a beautiful woman washes your floors? - This is our nurse. There is no money, the head doctor gives her a salary in operations.",
        "I've never understood why people are afraid of dentists? It's not a big deal at all. I arrived, everything is cultured, neat. I visited them yesterday. Even the pulse has not increased and the alarm is zero.However, I drove my wife. Not myself.",
        "In Russian cars there are 3 door positions: open, closed and not closed.",
        "Colombian drug cartels are seriously concerned about the problem of beer alcoholism among young people...",
        " News from Kyrgyzstan: a large army of locusts destroyed all stocks of cannabis, and then with wild laughter drank Lake Issyk-Kul and went to Turkey for sheepskin coats...",
        "If an official requires a bunch of documents from you, attach a permit to carry firearms there, and then your business will go much faster.",
        "xxx: Are you interested in a cybersecurity specialist by any chance? whoo: Yes, throw the resume in the mail xxx: Put it on your computer, on the Desktop. The file is called 'COLLECT!' Just in case, I duplicated in your folder 'Selected frames' at home. uuu: Just a second! home computer - offline! ! He is not connected to the grid and the Internet in any way! xxx: Sorry... From home - deleted ...",
        "Two psychiatrists met, haven't seen each other since university. The first: - And what was the strangest patient you had? - I had a patient who lived in an imaginary world. He believed that he had an uncle in America who was going to leave him a huge inheritance, and therefore the patient was constantly waiting for a letter from there. He didn't go anywhere, sat at home and waited for a letter. I've been treating him for 7 years! And when I was almost cured, this fucking letter came! . .",
        "A shy and well-mannered boy, accidentally grabbing a girl by the chest, said - sorry, but thank you... ",
        "And our work schedule is flexible: if you want, stay late in the evenings, if you want, go out on weekends.",
        "- Sanya, understand, you need to squeeze the anti-stress ball, and not throw it in the face of colleagues. - But it calms me more.",
        "If you pour Coca-Cola and Pepsi into one bottle, you can see how the bubbles are fighting.",
        "I don't get to know anyone, because I don't have the strength to tell the same thing every time.",
        "- Piglet, they say Did you get drunk like a pig at a Rabbit's birthday party? - They're lying, Vinnie, because I'm still small, I'm only up to a piggy squeal.",
        "Vovochka comes from school with a scared look and says: - Mom, Dad, I don't think you should look at my diary today. Mom grabs the heart, dad grabs the belt, they open the diary, and there's a five! Everyone fainted. Vovochka (sadly): That's what I was afraid of.",
        "- And in general, I am a woman of mystery. - And how does this manifest itself? - I won't say!",
        "We do exercises for the soul. They took a sin on their soul. Here we go. One. Two. Three. They repented. We rest.",
        "I always wear a stethoscope around my neck. And if someone unexpectedly needs medical help, I give a lecture on the dangers of template thinking.",
        "Am I doing something wrong? - What nonsense, you absolutely do everything wrong.",
        "- Let's get acquainted?- Mom will forbid you to communicate with such ...",
        "Since Coca-Cola is leaving the Russian market, it was decided to import substitution of this drink. Several samples were offered. Cognac won the blind test by a noticeable margin.",
        "Knock on the door. Person: - Can I talk to you about Jesus? Maria: Well, what did he do again?",
        "In the minibus. - Girl, pass the fare. - And the magic word? - Abracadabra.",
        "- From the point of view of the universe, theft is an imaginary entity. On Earth, things and valuables can only be moved. - Yeah, you're not much of a lawyer.",
        "— Abram, why are you crying?— I was at the dentist. He tore his teeth.— Ah, poor guy. And how much did he pull out?— Two hundred bucks!",
        "I never understood the phrase: We are not looking for easy ways. So look for it! They're easier than complicated ones! Why this pathos? I'm always looking for easy ways. I'm even looking for easy ways to look for easy ways - that's my level. Sometimes I'll sit down to think, and then I'll lie down, because lying down is easier, and then I'll fall asleep at all. Perfect.",
        "A girl asks a guy in the morning:— What kind of breakfast is so strange — one oatmeal porridge on the water. Maybe you're an English lord at all and you also have a castle in England?— I have a mortgage in Russia.",
        "There are two friends who haven't seen each other for a long time - Hi, haven't seen each other for a long time! How are you? - Yes, I have already managed to get married and divorced. - And why did they get divorced? - Yes, my wife couldn't stand me when I was drunk, and I couldn't stand her when I was sober.",
        "Sometimes you look at your psychologist and think, is she really interested or is she with me just for money",
        "The most socially unprotected stratum of the population is an unemployed Muscovite. According to statistics, most of the hijackings of premium-class foreign cars occur at them.",
        "- Parked near the State Duma. A traffic cop approaches and says: You can't leave your car here, deputies work here. And I said to him: Don't worry, I closed it...",
        "Jews treat Muslims somehow, you know, not in a Christian way.",
        "Husband to wife: - And how many men have you had in total? - Seven. So I'm the seventh? - No, the second one...",
        "I was standing in the kitchen, cooking. The daughter comes up and says: - Mommy, when I work, I will buy you groceries and pay for communal services! I already shed tears. She is 29 years old.",
        "- Here, look at this spider. Although it looks intimidating, it is absolutely safe for humans! - What do you mean safe?! And a heart attack?!",
        "Elton John gave his farewell concert in the UK. In the future, the famous singer and composer intends to give three or four farewell concerts a year in Europe and 10-15 in the USA and Canada.",
        "Did you know that if a person eats a plate of chili peppers without wincing, he can apply for Mexican citizenship.",
        "Sugar is not put in tea, but put. For example: - Put in the sugar, please. Answer: - Thank you, I've already done it.",
        "Having got into an accident not wearing a seat belt, I realized why the front window of the car is called the Windshield!",
        " — What is the total work experience in the specialty?— I'm getting a job as a cleaner.— Why did you decide to clean our toilet?",
        "I'm standing in a pharmacy, my grandfather orders a lot of medicines in front of me, and when the list ends, he says so uncertainly, inarticulately: Thank you very much.Wow, what an advanced grandpa - I think. And then the pharmacist brings him zinc ointment.",
        "- Yasha, why did you, an intelligent person, beat up Zyama like that? - Get to work! That scoundrel is sleeping with my wife! - And still sho? If a person's tastes coincide with yours, then he should be beaten for it?",
        " - What did the priest say when he saw lightning strike a crowd of leftists? Good God!",
        "Grandfather came to the doctor's appointment: - Doctor, I have problems with women! - And how old are you, Grandfather? Eighty-five. - A respectable age. How long have you had this? - The third day.",
        "During the matinee, not the teacher, but a fat boy decided which way everyone would lead the dance.",
        "- My wife has a better memory than an elephant. - What do you mean? - Well, elephants remember everything that happened, and my wife remembers everything that didn't even happen.",
        "A well-installed video camera on Kutuzovsky has bypassed the entire Russian cinema in annual fees.",
        "In Israel, unlike other countries, Jews of different nationalities live together.",
        "A concrete mixer collided with a van for transporting criminals. Now the police are carefully examining all the statues in the city.",
        "It's time to raise a generation of borscht. It's like a barista, only for borscht: the patterns there are different on the surface, hearts, arrogance, the marrow bone is smoking, the silver borscht machine.",
        "- Remember, the wise son will always yield to the stupid. Dad, fortunately, I'm not stupid enough to be wise.",
        "The sergeant has lined up his squad, and says: - I have two pieces of news - we are running a march, Private Ivanov is ahead. Everyone was delighted - only a turtle runs slower than Ivanov. The second news, the sergeant continues, Ivanov will go to GAZ-66.",
        "So, patient, hold this tube in your teeth and try to bite through... Have you been bitten? So let's write it down: He easily agrees to stupid requests",
        "An Old Man went to the Blue Sea several times, asking a familiar Goldfish to pump him an Old Woman. And one day he returned, and the Old Woman rolled back to the previous version.",
        "- Your dog tried to sell me heroin right under the windows of the Interior Ministry department!- This is an Afghan greyhound.",
        "- And as one of the great ones said: never make excuses, your friends already know that you are not to blame, your enemies will never believe you - Your Honor, can I have another lawyer?",
        "Two HP are in intensive care. Recovered a little... One says:— How did you get here?— Yes, for fun, I ordered a Porsche in the form of a constipation... The engine there is a piston, glitches are all... I'm driving along the highway, I look — 600 mers km under 200 goes. I pushed the gas pedal in and made it stand up... And then I looked in the mirror, I didn't fit into the turn, and that's it... I'm here... And how are you?— I'm driving on the 600th mers, at a speedometer of 200 km/h... suddenly, as if standing up, constipation makes me... I thought I was really standing — I took it and went out...",
        "Why did you spend money on gifts? You'd better not come yourself.",
        "I just read that the Sun has four billion years left to live. I remember, at the time of my childhood, they wrote about five. How quickly time flies ...",
        "- In the morning, my neighbors really like coffee with a hammer. - Maybe with milk? - No.",
        "- And your plan involves my participation? - Then what are we waiting for? Get to work!",
        "- I have served half of my life. - In the zone? - No, at the computer.",
        "- I don't know if I will be able to achieve your love? - It depends on you! So far, everyone has succeeded.",
        "Our friend trained in China for a year. We meet her at the train station. Her first words when she got out of the car: - Guys! How BIG are you all!",
        "Here I see girls with inflated lips, I immediately fall into childhood... Sunday, holidays, tea in bed, Disney world, duck stories...",
        "Dumplings in the freezer - they're like a five-hundred-ruble bill in a winter jacket.",
        "- Well, don't swear off prison and from the bag. Again, the sooner you sit down, the sooner you get out... - Yes, you are a so-so lawyer...",
        "- Sara Samuilovna, your Izya threw a stone at me! - Oh, did he hurt you? - No, he didn't hit me! - And sho does not suit you?",
        "Broke up with a girl. Then she got married, and now, I see, she travels abroad with her husband. If it wasn't for me, I wouldn't have seen the world!",
        "Why haven't they come up with a show where flatlanders are looking for the edge of the world?",
        "- I have a conversation with my wife here... she says if women ruled the world, there would be no wars at all... - What about you? - And I tell her, they say, you are completely right, because strategy and logic are needed to wage war. - I see. Well, if you have nowhere to spend the night, come, there is a place.",
        "A student walks down the school corridor, twirling a lighter in his hands. To meet him , the teacher OBZH: - What a parasite, do you smoke at school?! - Ivan Petrovich, honestly, I don't smoke! - Then why do you need a lighter? - Yes, I light firecrackers and throw them into the chemistry room. - Oh, well...",
        "Two friends meet.– Hi, how are you? Probably, you and Lenka are already married and living happily?– Almost like this: Lenka lives happily, and I am married.",
        "The scale of a personality is determined by the magnitude of the problems it can cause to others.",
        " - A large vocabulary will make you a stuffy company. - Maybe with your soul? - These are words of similar etymology, but with different semantics, so ...",
        "Start-up capital is such an amount with which you can start shopping for booze.",
        "Is it true that you are a bore?– First, let's define the terminology.",
        "Did you know that if you work naked in the backyard, your neighbors will build you a fence absolutely free of charge for you.",
        "British scientists have found that the size of a portable speaker that a teenager carries on the street is inversely proportional to his IQ.",
        "Went to the shower, saw the shampoo 'Volume and strength'. Just in case, I washed it.",
        "- Eat as much as you want, just carefully, inside the bone. Is that red caviar for sure?",
        "The blonde is buying shoes. - The first two or three days the shoes will squeeze a little, - the seller warns. - It's okay, I'll wear them only next week...",
        "If I die in my sleep, people will say 'At least he died doing what he loved'",
        "The sign on the gate:Careful! There's a dog in the yard. Not evil. But faint of heart!",
        "The dance was so slow that Anatoly twice asked Svetlana to go to the toilet.",
        "Two neighbors: - What are you going to do for the weekend? - As always – agrofitness.",
        "Barrymore, what's for breakfast?— Oatmeal, sir. — And for lunch?— Porridge, sir. — And for dinner?— Cutlets, sir. — Well, thank God!— A joke, sir.",
        " - One day Miss Bok found out who was carrying her buns - and took revenge... - Did you cut off your ears? - No, I poured sugar into the carburetor.",
        "To get to sleep as soon as possible, I count sheep. A good way if you're not paranoid. Yesterday I missed one and did not close my eyes all night, fearing that there was a wolf somewhere nearby.",
        "- Dear, I have to tell you that we are parting, it will be better this way! - For whom is it better? You don't know him!",
        "- Working remotely has a terrible effect on the psyche! I want to communicate with colleagues, find out if the cadre is getting divorced, what is the husband of the chief accountant sick, from whom the secretary is pregnant! - Voot! It is because of people like you that people want to work remotely!",
        "A mother with a four-year-old child went to the store for vodka. My daughter's ear hurt, and she needed to make a compress. A woman is standing at the cash register, with a child in one hand and a bottle of vodka in the other. The cashier looks at the mother with disapproval, and the little daughter says: - My mom doesn't drink, vodka is for me!",
        "— What in the mountains will attentive climbers be able to find at the bottom of the abyss?— Inattentive climbers?..",
        "- Do you really want to divorce your wife? After all, you've lived with her for almost twenty years! So, do you think I haven't suffered enough yet?!",
        "- Witness, you are obliged to tell the court the truth and only the truth. Now tell me how it happened. - Your Honor, I don't know anything. - You don't know? But ten minutes ago you claimed that you knew the case in every detail! - She did. But I didn't think that you would set such strict conditions!",
        "I have touch monitors. One day a fly landed there and tried to enter information into the database and changed the wallpaper. - Rabinovich, you are buying this sausage for nothing. It is certainly cheap, but it is absolutely impossible to eat it, there is only soy there. It's for guests.",
        "I got tired of strange sounds in the songs. It always seems that something is wrong with the car.",
        "Another fight on the project 'House 2'. This time the operators did not restrain themselves.",
        "The lesson of OBZH. Teacher: - It is important to know the safety rules and how to behave in nature. Yesterday I saw a viper in the forest and it didn't bite me, but that's because... From the back desks: Because they don't touch their own!",
        "Husband and wife are waiting for guests. The wife got dressed, made up, curled her hair, and the husband walks around the room in family underpants. Wife: - Get dressed, guests will come any minute. Husband: - No, let them see how thin I am, how you feed me. Wife: - Well, then take off your underpants, let them see what to feed you for.",
        "I sentence you to 5000 monetary fine for insulting a civil servant. Would you like to say something to that, the accused? - Actually, I would like to! But at these prices...",
        "And tell me, Father, what products of your youth do you miss the most? - By natural...",
        "Most people believe that previous generations were stupider than the current one. However, they are not surprised by the fact that once in the instructions for the user of the car they wrote how to adjust the valve clearances, and now they write that you should not drink battery fluid.",
        "- Well, how can you not understand! It's Aesop's language! - Language and what, excuse me?..",
        "Sometimes children make terrible noises. For example, they ask for money.",
        "Yasha Rabinovich comes to the tailor and asks: - Tell me, please, is it true that my son Fima has not been paying for the suit that you sewed for him for five years? - Yes, have you come to pay for it? - No, I just wanted to know if it is possible to sew a suit for me on these terms?",
        "I'm sitting, drinking tea. Opposite is an employee. She is interested in: - I see you drink tea without anything, even without sugar. Diet? — yeah. - I can't sit on diets, I always break down. - You can't get away with this one... - And what kind of diet is it called? - 'There is no money and there will be no salary.'",
        "The groom! Mirrors in the registry office are not for you to be engaged in self-admiration. And in order for you to check whether your future wife and mother-in-law are reflected in them.",
        "Ad: A young attractive blonde asks to return $ 500 for a reward.",
        "- Saturday, are you sober?! - I decided to go against the system, engage in self-development, lead a healthy lifestyle! - No money? - No money.",
        "Geography lesson. Teacher: - Children, tell me, where will we get to if we drill the Earth at the North Pole? Children (together): To the crazy house!",
        "In the old days, of course, people had a brighter personality. Ringtones alone are worth something. Who has a Black boomer playing, who has Misha Krug, someone else has fervent jokes bought from number 4242. And now what? One person's phone rang - half of the street grabbed his pockets...",
        "Aliens are preparing an invasion of earth. The alien chief reports: - Comrade General, we are ready to attack Poland! - And why Poland? 'It's customary on this planet.",
        "Our marriage with my wife is based on the fact that we both believe that everyone is morons. Well, that is, there is nowhere to go.",
        "– You are a persistent person, you work hard, your anniversary is coming soon. And what did you read as a child – the newspaper Murzilka or the magazine Pionerskaya Pravda?– And that, and that.– Well, another spy did not pass the literary test.",
        "- Irk, and how do you get acquainted? - Well, if I'm walking down the street and I like a guy, then I drop a thing in front of him so that he picks it up, takes it to me and that's how we would get acquainted. So I no longer have a wallet, two pairs of headphones, a travel card, and a scarf.",
        "- And my wife has one love: earrings! - Well, that's okay, she's a girl. So I'm Olezhka!",
        "What's the point of paying a psychotherapist if you can just go outside and brutally chop nettles with a stick?",
        "Qualifying round in the Armenian battle of psychics. The task is to find a person in the trunk of a car. Psychic:— Guram, brother, where are you? Voice from the trunk:— Brother, I'm here!",
        "There is a separate boiler in hell for HR managers. They scribble petitions for transfer to Paradise every day. But they are rejected due to lack of experience and experience of being in Paradise.",
        "The case in paradise. - My God, atheists are here for you! Tell them I'm not here.",
        "The ancient Kyrgyz did not know about the existence of Jews, and therefore all the troubles that happened to them were attributed to the dark forces of nature ...",
        "Latest News. Fashion trends have finally reached distant Scotland. Men put on mini...",
        "- And who is it behind your wall that screams like a cut? - Yes, it's Maria Ivanovna who came home from work and is now having a good time. - And who does she work for? - Librarian.",
        "Dating after thirty is more and more like an interview.",
        "A little boy before going to bed asks his father: - Dad, why do all the fairy tales that you tell me begin differently:'Once upon a time...' or 'In the thirtieth kingdom ...', and they end the same way: 'X-r-r, x-r-r, x-r-r'?",
        "I flipped through the Kama Sutra to the last page and shed tears. They never got married.",
        "I don't care about money! They calm me down.",
        " - By the way, in order for the parrot to speak, it is not necessary to plant a female to him. - Yes, I know! I have half of my friends like they got a female in the apartment, so they don't communicate with anyone.",
        "- The majority opinion is not always to be trusted. - Why is that? - Because even three billion flies won't convince me that shit is delicious!",
        "First of September, first class. The teacher says: - Children, you have come to school. You need to sit quietly here, and if you want to ask something, raise your hand. Vovochka pulls his hand. - Is there something you want to ask, Vovochka? - No, I'm just checking how the system works.",
        "The husband made a wish for the New Year that his wife would become economical, and his mother-in-law - smart. After the chimes struck, my wife turned off the TV, blew out the candles, removed the cognac from the table, and my mother-in—law began to tell the details of the Russian-Turkish war of 1877...",
        "- Who do you work for?— Landscape designer.— Cool! Ha computer, then?— Ha bulldozer.",
        "Borya comes home in the morning, does not have time to enter, as he gets a frying pan on his forehead and hears his wife's tearful voice:– Oh, Borenka, I'm sorry - I forgot that you're off the night shift today...",
        "The old man threw a net into the blue sea. Pull-pull, pull-pull… And his voice: - The network is unavailable!",
        "The Germans have a strange attitude to computers: in their language, the word 'Gluck' means happiness.",
        "Ambition is when you go to the exam, you think you know 2, and when they put 4, you wonder why not 5.",
        "Husband As usual, I invited my friends home to play cards. Five o'clock in the morning, and they still don't stop. An enraged wife bursts into the room:— How long will this continue in my house?! !— Masha, don't shout, the house is no longer ours...",
        "Vovochka comes up to her mother and asks:— Mom, why are you standing at the window when I sing? Mother:— So that people don't think that I'm hitting you!",
        "We have a homeless person in our yard. I feed him sometimes. Today he comes up to me and says: Here! I stole it for you! and gives me a jar of red caviar. That's the power of friendship...",
        "Summer is such a time when you stand at 2 o'clock in the morning in your underpants with a slipper in your hand on the bed and look out for this buzzing bastard.",
        "Announcement on the zoo radio: Attention! The boy Sasha, who has lost a tipsy dad, can meet him in the monkey house.",
        "Not the real man who fights the dragon for you, but the one who stays with you when the dragon is you..",
        "Do you have a card attached? - Well, sometimes we notice her.",
        "- Baby, sometimes I get so tired that I want to go to kindergarten instead of you. - And your mom won't take you. - Why is that? - And you won't fit on a potty.",
        "Adam's apple is a piece of apple that got stuck in Adam's throat when Eve told him she was pregnant.",
        "Call to the veterinary clinic: - Hello! We have a poodle sick! - The floor of the poodle? - No, a whole...",
        "- What will the eco-friendly transport of the future work on? - On water and grass. - And how will such a technique work? - Harnessing a mare to a cart ...",
        "High school students today do not write an essay on How I spent the summer, because it is very personal and very indecent.",
        "- Bought his wife an excessively powerful traumatic pistol. - Why did you think it was overly powerful? - So I spent a week in intensive care. And a mistress in general - two.",
        "Sympathy is when you like the appearance. Falling in love is when you like both appearance and character. Love is when you don't understand what you found in it.",
        "- What is American education? - This is when Russian professors teach Chinese students.",
        "The idea with masks, as it turned out, is not so bad. Today I went for a walk with my girlfriend and accidentally met my wife and mother-in-law. They didn't recognize me.",
        "A guy with a huge bouquet of flowers comes to his beloved's parents. - What do you want, Vasya? - the girl's father asks. - You know, Nikolai Petrovich, I've been in love with your daughter for fifteen years now. - Did you come to claim a pension by any chance?",
        "In a house where there are children, silence is a reason for panic.",
        "The teacher tells the students: - Keep in mind that education is needed not for the crust, but for the cerebral cortex!",
        "I read in my horoscope that success, prosperity, and well-being await me in the second half of my life! ... Pancake... How much did God measure me? I'm already 55, and I still have the first half of my life...",
        "- Shall we go to my place? I have a 12-year-old whiskey at home. - How? How could you be silent for all these 12 years!",
        "Husband and wife solve a crossword puzzle: - Dear, do you not remember the name of the device for detecting hidden wiring? - A puncher...",
        "- And why does your computer stink so much? - The basket is full.",
        "The applicant takes an exam in history. Teacher: - Young man, well, if you don't know anything about the First World War, then tell me about the beginning of the Second! - Smoke, explosions, fire, and everywhere tanks, tanks, tanks!",
        "- Son, how do you explain your twos in the diary? - Mom, there's one of two things: either genes, or upbringing ...",
        "- Rabinovich, single women complain that men are absolutely not interested in their problems. Young man, 30 years ago I listened with interest to the problems of a single woman. Since then, from her point of view, I have been OBLIGED to solve this woman's problems for 30 years...",
        "- We have a flat tire. - Take the pump and pump it up. - But I'm a famous TV presenter! ! - So work on the camera.",
        "- How is it at your school, son? - They sow the reasonable, the good, the eternal. - Well, at least they don't put you in jail.",
        "Long-awaited news from mobile operators! Bi-Line and MTS are finally merging! The new logo will be a bee with big red eggs.",
        "A little crocodile runs up to mom:— Mom, where does our dad work? Mother:— Your dad is a 'diplomat' at the embassy.",
        "Chinese wisdom says: if you have nothing to say, tell Chinese wisdom.",
        "- Mom, is it true that I turned out by accident? - Son, I'll be honest - you didn't turn out very well.",
        "The wife did an MRI of the head. My husband's first question: Well, did you find the brains?",
        "Dimon, you pumped up your biceps so much for the vacation! Maybe you didn't get out of the gym? - No, I was courting a girl... - ??? - I dragged her purse, damn it!",
        "— We have reviewed your resume, in general, we are not impressed — Your office also does not overlook Wall Street",
        "After the third wiping of the iPhone with alcohol, Siri asked for a snack.",
        "Fuck them, these 90-60-90... There is no beard — already a plus!",
        "I don't know another country like this, where it doesn't matter that you're a person...",
        "There's a girl standing on the edge of a high bridge. A homeless man approaches her: Is it a pity to jump? You're so beautiful! The girl abjectly: I don't care anymore... Bum: Then maybe we'll spend the night together? The girl is straining: With you?! Never in my life! Homeless man with a smile: Then I'll wait for you downstairs...",
        " — Doctor, I have a bad memory. What should I do? Everyone is laughing at me!— Boxing is the best medicine. Get into boxing!And then my memory will get better?— No, they will laugh less.",
        "They take one man to work. The head of the department tells him, they say, excellent reviews about you, you have an excellent education, you received a lot, why the hell did you quit your last job? - There was a mess, - the man answers. - So after all, we have a mess, - says the boss. - yes. But your women are fresher.",
        "Husband: - You won't believe it, an elephant got tangled in a spider's web in our yard! Wife: - Stop mocking my mom! Let him rest in a hammock, take a nap...",
        "In Ireland, your social media page is automatically blocked if you make more than three grammatical mistakes a week. And what, in my opinion, is quite fair!",
        "- Treat the girl with a glass of red wine?— No, my apartment is not cleaned.What's that got to do with it?— Especially if it has nothing to do with it.",
        "- Citizen policeman. I'm new here. Tell me, isn't it dangerous to walk here? - It would be dangerous, I wouldn't go here.",
        "The plumber repaired the faucet in the apartment of a lonely housewife and was about to leave, but you can't trample against the script of a German film.",
        "I'm sitting working, I'm looking around the office, a man is walking, I'm looking at a puppy in my arms, I'm stretching my neck, I'm blurring into a snotty smile, I'm looking at a man, at a puppy, at a man, at a puppy. The guy reacts sooooo strangely to me. I look closely - and this is a fur HAT under my arm.",
        "- Why are there so many blank pages in the passport? It's just that you're living too boring!",
        "The difference is in mentality: the theme is a gang with superior forces, trying to rob a certain object, but meets an unexpected rebuff from a person who should not be in this place. In Hollywood, it turned out to be a 'Die Hard', and we have 'Operation S'.",
        "Did you know that drunk electricians see fixies?!",
        "The main thing that you need to learn well in this life is proteins, fats and carbohydrates.",
        "- I am an owl ... - I mean , can you turn your head 270 degrees ? - I mean, I can do it to a neighbor-a lark with a puncher ....",
        "One guy at the resort was chasing women so hard that his eye was knocked out. The hospital did not find a suitable one and they inserted a bull. Here he goes to the platform and thinks what he will tell his wife. His wife saw him and wailed: - Oh, Vanya, don't look at me like that! I'll tell you everything myself!",
        "The exam at the institute. The student doesn't know anything, but the humane professor got caught.— Well, answer at least the simplest question, name some kind of dielectric. Silence.— Imagine: spring, you and a girl in a dark room, alone ...— Ebony, Professor!— That's right, young man, but in our time there was celluloid.",
        "The tyrant of Syracuse, Dionysius, sent Philoxenus, who criticized his poems, to work at the quarries. After a while, he again demanded him to the palace to listen and appreciate his new poems. Philoxenus listened to him attentively, then silently got up and headed for the door. Where are you going?  tyrant asked. Sire, I'm going back to the quarry,he replied.",
        "On my way to work, I go to my favorite cafe-bakery, there are two people at the counter - the owner himself and the girl. I order khachapuri. Girl: - How much? Me: - One... one... How to say it correctly? Girl: - That's right “adyn))) The owner of the cafe: - That's right - two!",
        "The most favorite thing in cleaning an apartment is chasing a cat with a vacuum cleaner.",
        "Eight-year-old Yegorka was very surprised when on his birthday, a tipsy father wished him to live as long as he did.",
        "Vovochka called his grandmother *ukoy at lunch and got a slap on the head from my father. Not much, as agreed.",
        "Wife to husband:— Listen — your friend has been living with us for the third month... — And I thought it was yours...",
        "Not bad either!.. I thought, throwing a slipper at the cat, and hitting my mother—in-law in the forehead.",
        "I don't mind the irony, but the phrase Good morning is too much.",
        "- Did you go to take the exam? - I went... - And what ticket did you get? - Military...",
        "In the Middle Ages, people were not afraid to do evil to each other. The earth wasn't round.",
        "We are spending the Old Year, dogs! Happy New Year, pigs!",
        "— And why, the more you drink, the more beautiful the opposite sex is?— The body thinks that it is being poisoned and is trying to urgently continue its kind.",
        "The words 'don't be nervous' well help to bring a person into a normal state of rabies.",
        "A summer resident, having caught a neighbor's boy climbing an apple tree on his plot, threatens him: - Here I will talk to your father! The boy looks up and says: - Dad, Uncle Vanya wants to talk to you here.",
        "Dear, I don't know if I should go on a diet or not - it seems that the battery in our floor scales has died. - Honey, she didn't just die - you did crush her.",
        "A man comes to the doctor. He examined him, and said: — Well, well, my dear, one lung will have to be removed... The man is terrified:— What are you, Doctor! My lungs have always been fine...Well, your lungs are fine now, but your liver doesn't fit anymore.",
        "There is one dog in the parking lot, for some reason does not like me, barks constantly. The day before yesterday I was walking, I decided to treat her with a sausage to show that I am not her enemy. So this creature took and choked. And when she cleared her throat, she decided that I had almost killed her on purpose. Now she hates me even more.",
        "You've been training all year, untangling headphones, now I see that you're ready for the most important test. Here you go, it's a Christmas garland.",
        "A friend is someone who helps to throw a corpse into the river without asking questions!",
        "Pharmaceutical news: the naphthyzine production plant is kept on snot alone.",
        "- Who are you? - I am the man of your fantasies!- hm... Why alone?",
        "- Sara Moiseevna, how could you describe your life in two words? — For what?!",
        "- You lead the wrong way of life!— Oh... Don't be jealous of me...",
        "A very cheap plastic surgeon always says at the end of the operation: 'Well, so far...'",
        "I don't overeat at night, but just have breakfast in advance, because I will definitely be late in the morning and won't have time to eat.",
        "It doesn't matter which leg you got up from. The main thing is not on the cat.!",
        "Vovochka came to visit his grandmother.— What, are the parents fighting again?  his grandmother asks him.— Yes, Mom brought some kind of clap from the resort. I gave it to my dad, Uncle Seryozha and a neighbor from the apartment opposite. Now everyone is shouting, swearing. I just don't understand one thing: either I brought a little, or I didn't divide it equally.",
        "A woman comes to a fortune teller: - Do you remember, I was with you five years ago? You also gave me a rich husband and five children. - I remember... - I want to know - when will I have a husband?",
        "The neighbor's drill always cracks louder and nastier than its own.",
        "The announcement on the column: I am treating all diseases. A man passes by and says to himself: Fly, fly, you won't fly away from everyone.",
        "The New Year will come in half an hour. A couple with full purses hurries home through the deserted streets. They stumble upon a puking drunk. – You see, – the husband reproaches his wife, – people are already having fun! And you have everything at the last minute!",
        "Why didn't you give up your place in the trolleybus, grandma?— Money is not the main thing in life!",
        "Who do you love more, mom or dad?!— Mom and Dad! And more?!— And no one else!",
        "Yesterday I chased two hares. I caught both of them. The hares still can't believe it.",
        "Gena comes to Cheburashka. He opens the door and says:— Oh, hi Gena, and I was just thinking about you! And what did you think?— At least he didn't show up!",
        "A conversation between two young mothers:— God, how your son looks like his father! Yeah, I'm surprised myself.",
        "Our head of the customer service department is a terrible person. It's written on his door: 'Chief ORC'.",
        "Due to the transfer of the clock to winter time, the birds flying south had to wait an hour at the border.",
        "— Girl, how much do you weigh?— It's a secret...— Well, tell me at least the first two digits...",
        "- Mom, it seems to me that you love money more than us. - Don't be silly, Dengoslav!",
        "In one village, a boy was playing on the roof and fell into the vegetable garden. So to speak, I fell for fuck's sake.",
        "Russian faucets - one step from frostbite to burn!",
        "One girl was called a crocodile, but not because she was scary, but because she dragged a moose into the river and devoured it.",
        "Are you asking where I got my pockets full of money from? It's pretty simple - I have very small pockets.",
        " - Here is your salary...- Awesome! Give me two!",
        "My mother-in-law told me: - I can't see you! And I went to the optometrist.",
        "In private dentistry, it hurts only near the cash register. There is anesthesia for everything else.",
        "- Pour me some vodka, please. - You're crazy, we have a hospital! - Then alcohol.",
        "— Guys, figure it out, I gave my wife SCALES... and she gave me a RULER for my birthday. I didn't understand something...",
        "Vovochka joined the army to mow down from the institute.",
        "Where have I not been! Greece, Spain, Cuba, USA, Morocco... And I haven't been to the Maldives either...",
        "— My wife left me.— Did you look in the kitchen?",
        "A real vacation is when you buy shorts, a swimsuit and a panama hat, not new wallpaper, tiles and laminate.",
        "A suicidal loser rolled off the Leaning Tower of Pisa",
        "An announcement at the Georgian Institute: 'Entrance exams will not take place. All tickets are sold out.'",
        "- Dear, I want a fur coat! - Oh, you, my hostess! Now I'll run for herring and beetroot!",
        "70% of children do not believe in a sober Santa Claus.",
        "Every girl in the closet has tights, called 'well, you can't see under the pants anyway.",
        "Switzerland can fit seven times on the territory of the Tyumen region. But he doesn't want to.",
        "- Don't throw it away, we'll take you to the dacha. - There is still a purgatory in the form of a balcony in front of the dacha.",
        "We have such a tradition - to wipe the floor with a sponge for washing dishes on the sly.",
        "Do you remember, bread was sold without packages and you could touch all the loaves and choose which one you like best?",
        "It seems I got on the wrong bus and mistakenly came to hell. But no, that's right, I'm at work.",
        "After the holidays, there is a heaviness in my head and an incredible lightness in my wallet.",
        "Every morning there is a religious ritual. Grub sacrifice to the cat.",
        "— Hey, let's get acquainted.— No. - And what?— You're wearing sweatpants.— Well, what, and we'll buy you.",
        "I probably, when I die, then by inertia I'll get out of the coffin at 6:30, take a shower and go to work.",
        "A Russian language teacher, passing near the office of a laborer, stepped on a nail. The worker was shocked: he had never heard such adverbial phrases in the Russian language...",
        "With the current ecology, before eating fruits and vegetables, it is not enough to wash them. They need to be kept under water until they stop struggling.",
        "— They say that girls love with their ears...- what?— With their ears, I say, they love.- what?— Go home, frigid!",
        "I have such an old mobile phone that even the camera built into it is not digital, but film.",
        "Wife: — I'm like Cinderella - I wash, clean, cook... Husband in response: - I told you, if you marry me, you will live like in a fairy tale!",
        "Kangaroo jumps. Stops, scratches his belly, jumps on. He stops, scratches his belly, pulls a kangaroo out of the bag by the ears: - I've told you how many times - don't eat cookies in bed!",
        "From the rules of good form. Before you eat food that has fallen on the floor, you need to blow on it.",
        "- Where did the authorities go? - Quiet you! Maybe it read my thoughts!",
        "Corrupt officials are officials with reduced social responsibility",
        "Oh, this moment when you turn over to the other side with a stuffy nose, and both nostrils are breathing! God save gravity!",
        "Arguing with your wife is like hunting a bear, if you didn't kill with the first phrase, then run with all your might.",
        "A student of the medical institute, who is undergoing an internship in a hospital, turns to a doctor: - Could you give me another patient? - Why? - The one you gave me is already dead!",
        "Family quarrel: - It's not me that's important to you, it's my wallet! - I didn't care about your wallet, the content is important to me!",
        "- I'm Grandpa Lenin! - Is he crazy or something? - You're a psycho yourself, my granddaughter's name is Lena.",
        "By the time you realize that your parents were right, you will already have a son who will believe that you are wrong.",
        "The son quarrels with his parents: - I'm tired of being with you all the time, always coming on time! I want romance, freedom, beer, girls! I'm leaving, and don't try to hold me back! The son resolutely goes to the exit. His father catches up with him at the door. - Dad, I told you: don't try to stop me! - I'm not stopping you, son. I'm with you!",
        "The folklore ensemble requires lozhkari, tsokari, topari, I-i-ihari, u-u-uhari and egegeyschiki.",
        "I quit smoking almost 3 months ago. One of the advantages: The sense of smell has sharpened. Now I distinguish a good perfume from a cheap one, the food smells much tastier, it turns out, and all that ... :) Minus: We have to change socks more often!",
        "We had a photographer, grandfather. I haven't seen a single photo of him where people wouldn't laugh. As it turned out later, he did not pronounce the letters p and L. ",
        " - Are you sure that people are the smartest creatures on the planet? Aren't you? - Well, look, for example, cows don't consider the one with a bigger udder and longer legs an idol, do they?!",
        "How to determine whether it will rain or not? If a bird has pooped on your car, it won't rain in the next couple of hours.",
        "The announcement on the door of the store 'We work from 8.00 to 21.00 without lunch and weekends' I perceive every time as a complaint.",
        "Yesterday I glued ceiling tiles. Probably familiar to many. Now I understand why the glue is called 'Titanium'. You smear it on the tile and then you stupidly hold the ceiling for half an hour.",
        "A company of riot police liquidated a cannabis field with an area of 2 hectares. After that, she declared herself a division and went into space to fight Pokemon.",
        "At the bedside of a dying man:— Dear, what to do with the money that we have been saving up for a car all our lives?— Give it to your grandchildren! Let them buy a chocolate bar...",
        "Dad puts his daughter to bed. Half an hour later, Mom looks into the dark room:— Well, how? Sleeping?— Yes, Mom, sleeping!",
        "Hello, is this a pharmacy?- Not really.- What do you mean, not really?- There are a lot of fools here, but this is an office!",
        "A policeman walks past the sandbox and hears one boy say to another:- Do you know how a cop differs from a donkey?The cop grabs him by the ear:Well, what is it, brat?- Oh, uncle, nothing, nothing! ...That's it!",
        "Are you okay?- Yes, in a random ",
        "I have a brain. And I love him. But I don't like it when someone else loves my brain without my consent.",
        "It infuriates when you gain 30 kilograms for a role, and then you remember that you are not an actress at all!",
        "At first you say that you don't have burnout, and then you just stand in the shower under boiling water for an hour.",
        "— Chief, were you called?— Yes, I did. I'm raising your salary by 0.5 times.",
        " Sports commentator: - You will easily recognize our athletes by their yellow T-shirts and blue underpants. The rest of the skiers are dressed much warmer...",
        "Girls have their periods due to the fact that they drink the blood of men for a whole month, and then there is nowhere to put it.",
        "- In short, I decided to say no more often! - Are you going to drink? - And why, in fact, not?!",
        "I noticed that toilet paper began to disappear from the toilet. I began to observe. The daughter tears off a large piece, puts one end in the water, and lowers the other to the floor. It washes away. And it's all dragging in there. Punished. I try it myself in the evening. Cool.",
        "Studies have shown that if a woman sleeps for a long time, her blood pressure stabilizes, her mood improves and her husband's risk of cardiovascular diseases decreases.",
        " - Does your plan involve my participation? - Then what are we waiting for? Get to work!",
        "A child was screaming wildly on the plane, and I couldn't fall asleep. I ordered whiskey, I thought it would help, but the baby's parents forbade him to drink.",
        "- Listen, grandfather, your grandmother is constantly yelling at you, how do you tolerate? - Duck, I turn off the hearing aid and let him continue to yell.",
        "A professor of philology gives a lecture: - There are languages where double negation can mean a statement. But there is no language where a double statement means negation. From the audience: - Yeah, of course...",
        "If you run out of a pack of soda at home, then you're about 90 years old. ",
        "- Doctor! It was so inconvenient for me to call you in such a downpour! - Nothing, I have another patient in the next house, so I will immediately kill two birds with one stone.",
        "— Buy me a kinder surprise.— You're 27. — No, one is enough.",
        "My husband is returning from work. The wife is so happy:— Oooh! My husband is back! My husband has a stupor, glass eyes… After a few seconds he came to himself and how he would bark:— Fool! Think you're yelling! I almost jumped out of the window!",
        "There are no red-haired taxi drivers, because taxis are for the soul.",
        "Studies have proven that homeopathy helps those who sell it best.",
        "Tipping a doctor is a bribe. Tipping the waiter is a good tone. One saved a life, the other brought coffee.",
        "There are no useless things, there is a small balcony.",
        "One girl went on a diet several times. And every time by.",
        "She fell in love with him so much that she gave birth to his son within a couple of months after meeting.",
        "Happiness is fleeting. Therefore, always take a liter more.",
        "The father had three sons. And they rented their apartments.",
        "Is it a bad thing to litter the Russian language with foreign words, or is it just not comme il faut?",
        "Lyuba walked along the railway tracks with headphones on.",
        "The driver of the freight train went to make tea.",
        "Philologists have established that Sh is the male of the letter Sh.",
        "Feminists don't go to geometry lessons because they can't prove anything.",
        "A boy becomes a man when priests stop looking at him.",
        "When a seventh-grader confidently showed Bali, Ibiza and the Maldives on the map, the geography teacher realized that this juvenile trash had a good summer.",
        "A woman who took two turns everywhere, after her death got into two boilers.",
        "The teacher of the Russian language absolutely does not care whether her ex calls or calls. She both laid and puts on his calls.",
        "When Dahl ran out of dialect words, he broke a bottle of vodka in front of the village men and wrote it down, wrote it down, wrote it down.",
        "Hackers leaked the database of the Russian Post to the network. Finally, at least someone has translated it into electronic form.",
        "The group Beasts is 20 years old this year. In terms of human, this is about 100 years.",
        "If you are lonely, watch a horror movie at night, and it will seem to you that someone is at home...",
        "According to statistics, people who have recently visited the dentist are less likely to get into a fight and generally watch their words.",
        "A black stripe is always followed by a white one. If an evil dog bites you today, then a good dog will bite you tomorrow.",
        "In Novosibirsk, on the night from Saturday to Sunday, a sauna burned down. The deputy, the prosecutor and the police chief were the first on the scene.",
        "During disasters, women and children are evacuated first. To think about solving the problem in silence.",
        "Does anyone know how to understand that a piper plays well at all?",
        "Scientists have found out that Noah, while sailing on the ark, ate, as they are now called, extinct animals.",
        "A healthy diet is when you filter the tap water before brewing Doshirak.",
        "In India, the defendants are forbidden to answer the judge's questions with songs.",
        "When I was little, I dreamed that when I grew up, I would spend half my salary on sweets. Then I grew up and tried beer.",
        "After visiting an economy class plastic clinic, customers' faces look cheap but angry.",
        "Someone wrote in chalk on the asphalt under the windows of a high-rise building: Call me when yours leaves!. Many men stayed at home then. Shelves were nailed, irons were repaired, lessons were done with the children.",
        "At the graduation, Seryozha's dream and Katya's mother's fears came true at the same time.",
        "After vodka was recognized as doping, the Russian Sport Fishing Championship lost all meaning.",
        "Petya is tired of being called a sucker in the yard. He freaked out and signed up for a shooting club. Now they call him an oblique sucker.",
        "The participants of the boring championship did not come by cars and buses, but inside these vehicles.",
        "Having met a bear in the forest, start offering him banking products. He will pretend that he did not notice you and will pass by.",
        "Weak knowledge of Greek mythology has always been my Achilles' knee.",
        "A biker who rides without a helmet knows the taste of all the insects of his region.",
        "Dmitry Rogozin has a Twitter account. And Elon Musk has Twitter. But there is one nuance.",
        "There is a shortage of highly qualified low-paid personnel on the market.",
        "A girl who got lost in Peterhof was brought up by a pack of guides.",
        "A grandson who confused his pills with his grandmother's, blew up in the morning and went somewhere by tram.",
        "Red-haired taxi drivers do not exist, because a taxi is for the soul.",
        "Father Dmitry has been collecting money for the chapel for four years. But so far it was only enough for Audi.",
        "Nothing demoralizes the enemy more than Scottish parachutists.",
        "The boy was playing with matches and lost a three-room apartment.",
        "Grandma didn't have a smartphone, so she tied a QR code to herself.",
        "OOO Tro changes its name to OOO Wallpaper due to a decrease in the number of founders.",
        "In the Dagestan circus, the clown remembers everyone, who is laughing at him.",
        "An experienced sword swallower took out a whole sturgeon from the corporate party.",
        "You can't hide from life forever in TV shows and computer games. One day you'll have to start drinking like normal people.",
        "A competition has been announced in the housing and utilities sector for the best surprised face in connection with the arrival of winter.",
        "Grandma drank 10 bottles of Red Bull on a bet and milked a cow to death.",
        "Winter has come! In Moscow, summer curbs and tiles are being replaced with winter ones!",
        "In autumn, I especially want to sit at home, comfortably wrapped up with money.",
        "It is not politically correct to call the day of the sale Black Friday. It is necessary to say Afrolohotron.",
        "Gerasim caught a Goldfish once. And he had three cows.",
        "Dyslexic sectarians sacrificed larch to Astana.",
        "How many wonderful people are around. And you eat animal meat.",
        "Those who see an organized conspiracy in everything, clearly did not try to organize anything themselves.",
        "Seafood is very harmful. A friend of mine ate a crab and died of cancer.",
        "Ridiculous death: a traffic police officer was killed by a chipboard board.",
        "We want to draw special attention of novice aquarists to the fact that fish never sleep on their backs.",
        "A boss with thirty years of experience knows how to look at obscenities.",
        "My younger sister went to first grade today. And I tell her: Where did you go, we're flying in the economy.",
        "As recent events have shown, the penultimate ones were better.",
        "Olsha, though she missed in the dash, but no one interfered with her to take the bear.",
        "Fools do not need to be taught, they are untrained. They are solvent. This is the essence of the trainings.",
        "The government suggested that the incomes of Russians are falling perhaps because they whistle at home.",
        "In Texas, a man followed a girl into the shower, saying he identified himself as a girl. The girl's father knocked out his teeth, saying that he identifies himself as a Tooth Fairy.",
        "If you look at the Matrix on the contrary, you can see how Keanu Reeves gets off drugs and finds a stable job in the office.",
        "People who can roll their tongue into a tube have a special gene that makes they think that the ability to roll the tongue into a tube is a huge achievement, and you can brag about it.",
        "People who know how to make millions in Forex, but instead teach it for $ 300 — here they are, the real heroes!",
        "The statement that there are no more gentlemen is wrong! For example, I saw a man holding an umbrella over his wife while she was changing a tire at the car. So there's nothing to invent here.",
        "Today I found out that there are no canaries in the Canary Islands. It's the same with the island of Lesbos... There are no canaries there either.",
        "The most well-mannered and mutually polite people when meeting are mushroom pickers. Everyone understands: there is a forest around, the opponent has a knife!",
        "The day off is the hardest day of the week. We need to rest, and sleep, and clean up the apartment, and take a walk, and relax. And you don't know where to start.",
        "Wisdom is when you have a whiskey in you, but there is no desire to call exes.",
        "The unlucky sandwich falls down with butter, the lucky ones with caviar.",
        "Sometimes you look at a person and realize that he is an asshole. And it happens even worse: you look at a person and don't understand that he is an asshole.",
        "Fish contributes to the development of the cerebral cortex, so fools should sometimes be given bream.",
        "How to buy a good rope on Ali? Find the one with the least reviews.",
        "If you run in the park in the morning, and no one knows about it, then it doesn't count.",
        "When too much work gets into the body, it begins to produce antidelas.",
        "Russia contains up to 95% of the world's reserves of unsolicited advice.",
        "Modern radio is a set of 10 songs and steadily changing advertising from day to day.",
        "Make a two-digit number from 40 to 80. Multiply by 2. Subtract 14. Add 17. Divided into three. Close your eyes. Is it really dark?",
        "Rabinovich is walking down the street and very carefully carries two watermelons. Meet him Abram: - Yasha, give me one watermelon. - I can't do it. The mother-in-law said: Yasha, I will give half my life for one watermelon!...",
        "I remember filling my markers with my mother's French perfume as a child. Then I painted standing up for a week.",
        "Mom comes home from work. So, what did my good kids do useful today? The first: - I washed the dishes! - What a good fellow you are! Treats him to a chocolate bar. Second: - And I wiped the dishes! - Good girl! - gives him cookies. Third: ell, I swept up the pieces and took out the bucket.",
        "Children are quarreling. One, having exhausted all arguments, declares: - And you are a foster child! Your parents took you to the orphanage! Another: - My parents chose the best child, smart and beautiful, but yours had no choice: what they brought in the hospital, they had to take!",
        "A young girl says to a sitting man: - Oh, give way to a pregnant woman. He gives in, then looks closely - she has nothing. - Excuse me, but how long? - 30 minutes, but I'm so tired, so tired...",
        "- And my grandfather lived in the next apartment, moved? - Yeah, to the cloud storage.",
        "A man without a wife is like a fish without a bicycle.",
        "What do you do if you get a call in the middle of the night and the number is undecided?— I'm sending it right away!— And if the number is determined?— I am sending by name and patronymic!",
        "Advice of the day. If you are attacked by a vampire, bite him first. He, at least, will be offended.",
        "At the moments when I do school lessons with my child, I feel like a hardened politician... I don't understand anything, but the expression on my face is smart, smart.",
        "I decided not to swear anymore.Now I sit and say nothing.I have nothing more to say to this world.",
        "A girl is leafing through a family album. - Mommy, who is this curly-haired handsome man? - Don't you recognize it? It's your dad! - Yes?! And then who is this bald fat man who lives with us?",
        "In a school for mentally retarded children: - Masha, how much is 2X2? - Five thousand! - Wrong, but what will Petenka say? - Tuesday! - Wrong, and Vovochka? - Four.. - That's right, but how did you calculate it? - It's elementary, - five thousand minus Tuesday.",
        "At the philosophy test, the student proved to the teacher that there were no lectures, and there is no such science.",
        "I always sleep with a knife under my pillow — just in case. Suddenly someone will come with a cake.",
        "- Why does it take so long to study to be a pharmacist?- It takes three years there just to learn how to read prescriptions written by doctors.",
        "The neighbor from above screamed at her child so in the morning that I also cleaned the room and dressed warmly.",
        "If you feel bad - hug the cat tightly. That's all. Now it's bad not only for you, but also for the cat.",
        "They ask the groom:— When visiting your fiancee's house, what first caught your eye?— Mother-in-law! My face is still scratched!",
    )
}