name: Deploy to Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x
  
    - name: Set up Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew shadowJar

    - name: Authenticate with Google Cloud
      run: echo "$GCLOUD_SERVICE_KEY" | gcloud auth activate-service-account --key-file=-
      env:
        GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Deploy to Google Cloud
      run: ./gradlew appengineDeploy
      env:
        GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
        GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Send Telegram notification "New deploy for backend created"
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python Scripts/send_telegram.py "🕹️ New deploy for backend created! 🕹️
        Author: ${{ github.actor }}
        Branch: ${{ github.head_ref }}
        Pull Request URL: ${{ github.event.pull_request.html_url }}"